### ISSUE TITLE
Service queuing with JS on Espruino 

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#101]
@loklaan is going to flesh this talk description out. Essentially using JavaScript to notify the availability of a high demand service, with notifications over rest requests. Terribly great.

**Comment by loklaan** [comment]
Yes! This IS _terribly great_.

There are many high demand services in this world, but the one I'd like the be notified about... is availability of the men's bathroom, at work.

I think the following emoji train succinctly explains the project I will be basing this talk on.

:toilet: :door:   :arrow_backward: :computer: :arrow_forward:   :traffic_light:  

I'll be updating this talk with more details as I:
* implement this project
* test it in production environments

**Comment by xwipeoutx** [comment]
+1, Looking forward to this, for sure! Sounds fantastic.

**Comment by AshKyd** [comment]
@loklaan: I'm very excited about this talk. Can we queue it for February? :+1:

**Comment by loklaan** [comment]
@AshKyd Hey! I'd love to do it!

BUT, I am still in the implementation phase. My solid yes/no for the Feb meetup will have to wait until after next weekend (16th-17th) when I get a chance to work on it. So, leave me as candidate for the moment. :hand:

**Comment by AshKyd** [comment]
No problems, I'll ping you next weekend. :)

**Comment by AshKyd** [comment]
Consider this a ping next weekend @loklaan. :P How's the project going? Will you be able to talk at the next meetup?

Keeping in mind it doesn't have to be finished, you're welcome to share your learnings as a work-in-progress. So can I schedule you in? :)

**Comment by loklaan** [comment]
@AshKyd No bingo, I had other plans come up.

I would definitely like to finish the project before talking about it. :)

At this point I think it is best to leave me out of next meetup. Sorry!

I'll update this issue when I'm sure the talk is ready.

**Comment by iamkevinv** [comment]
Ping @loklaan - status?

**Comment by loklaan** [comment]
Hey Kev - this has gone into backlog for me, sorry. I don't know when I'll be able to get around to it.

So, as for status, _frozen_ for now.

**Comment by iamkevinv** [comment]
How is your _frozen_ status on this going? I hope you haven't _let it go_.

**Comment by garrows** [comment]
Wow @iamkevinv! that's a level 9 Dad pun right there. :clap:

**Comment by loklaan** [comment]
Hahaha brilliant @iamkevinv! But yeah, still frozen.

**Comment by iamkevinv** [comment]
Hi @loklaan - Are you at all able to show us what you started with? :)

**Comment by loklaan** [comment]
Hoi @iamkevinv

I've pretty much dropped this project. Or, left it for someone else at my workplace.

Let us clean away this issue.
