### ISSUE TITLE
Talk request: Vue.js

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#102]
Anyone got any experience. Hearing cool things around the place.

**Comment by kzima** [comment]
@garrows Yeah, I am in vue.js since v0.5 and I absolutelly love it. I was able to replicate all bootstrap4 components with plain Vue.js in no time: 
https://github.com/kzima/vuestrap-base-components

It is getting more popular now after 1.0 release.

**Comment by garrows** [comment]
@kzima cool. Do you think you could share your thoughts & experiences at BrisJS? I think the February meetup is full but how about March?

**Comment by kzima** [comment]
@garrows I am happy to share my experience at BrisJS. March is fine for me :)

**Comment by garrows** [comment]
Awesome @kzima. Looking forward to it.

**Comment by kzima** [comment]
Hey @garrows,what day in March did you have in mind for the vue.js presentation?

**Comment by Novex** [comment]
I think it's Monday, March 7 according to the meetup.com event

**Comment by AshKyd** [comment]
Yup, first monday of the month. I'll ping @iamkevinv to get you on the lineup if you're good to go. :)

**Comment by kzima** [comment]
@Novex , @AshKyd Ok, cool, thanks

**Comment by iamkevinv** [comment]
Hey @kzima - If you are ready to rock for monday, i really don't mind a surprise late entrant :) Always good to have more presentations. If you're wanting a bit more time than a usual standard 20min slot though, we could put you in April. Did you want to pop in for March 7th? I can add you to the description. Otherwise let me know. :)

**Comment by kzima** [comment]
Hey @iamkevinv, yeah Monday is fine for me. I will keep it very short though, 5 min max + Q&A. I was planning to introduce vue.js, compare it to Angular and React and explain why we use it for our projects. Also I was hoping to share my experience and problems I run into when developing large SPA.

If you need anything else just let me know :)

**Comment by iamkevinv** [comment]
You're on the list!

**Comment by fud** [comment]
@kzima Hey were you going to put the slides up. I just wanted to look at the further reading list.

**Comment by kzima** [comment]
@fud Slides attached :)
[Vue.js (1).pdf](https://github.com/BrisJS/meetups/files/162304/Vue.js.1.pdf)

**Comment by fud** [comment]
Cheers. :+1:

**Comment by AshKyd** [comment]
Thanks for the talk, really enjoyed it. Thinking I'll have to give Vue a try for my next project!
