### ISSUE TITLE
Talk request: Webpack

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#104]

**Comment by marklawlor** [comment]
:+1: Especially Webpack + Babel

**Comment by xwipeoutx** [comment]
+1

**Comment by AshKyd** [comment]
Good one. Is there anyone who'd like to pick this one up for next month?

**Comment by AshKyd** [comment]
@girvo has expressed interest in this one.

Next meetup is February 1st, and we have a 20 minute slot (though you can go longer if you need). Will that work?

**Comment by girvo** [comment]
Yep, that'd be great. Funnily enough, I've been meaning to put my hand up for BrisJS for a while now!

**Comment by AshKyd** [comment]
Thanks, that's good timing then. I'll schedule you in, let me know if there's anything you need. :)

**Comment by girvo** [comment]
Is there any particular focus you'd like the talk to have? There's a tonne of cool stuff to talk about with Webpack: Babel, Purescript, Sass/Less workflows, hell I even wrote a Lisp loader for it! https://www.npmjs.com/package/wisp-loader

**Comment by brotchie** [comment]
@girvo For a while, we were using webpack for transpiling only and weren't really aware of its ability to handle other assets (i.e. Sass / Less / Hot Loading, etc) so would be really helpful if you could cover some of its non-transpiling uses!

**Comment by tomtomau** [comment]
@girvo - any chance you could post your slides? Going to set it up for work :D

**Comment by AshKyd** [comment]
Thanks a bunch for this one @girvo. Could you pop any resources from your talk against the issue for anyone who'd like to go back and check them out? :)

**Comment by iamkevinv** [comment]
Ping for resources to add?
