### ISSUE TITLE
Senior Backend Developer (Node.JS & AWS) - Well-Funded Gold Coast Start-Up 

### ISSUE THREAD

**Issue by AdamGrabish** [BrisJS/meetups#106]
Hi JavaScripters

Senior Backend Developer (Node.JS & AWS)
•	Social App Startup
•	Video Messaging
•	Expanding Digital Studio
You will be an instrumental contributor to the backend engineering team, handling scale, load and real-time processing on both web and mobile platforms. Led by an experienced team and powered by a talented design and engineering team.
Your main responsibility will be to assist with the backend, wrangling data and keeping things performing well using Node.JS, Java and Amazon Web Services (AWS). As requirements grow, you will be helping to define tech direction and tooling and will be instrumental in ensuring delivery of maintainable code in a smart and efficient manner.
Requirements
•	5+ years backend Java developer
•	Amazon Web Services (AWS) stack an advantage
•	JavaScript expert - knowing how to leverage frameworks, libraries and APIs for a fast path to quality; express.js and loopback.io.
•	Video and audio experience an advantage.

To find out more, please email adam.grabish@ambition.com.au or call me directly on (07) 3020 0316 for a confidential chat

**Comment by davidmason** [comment]
Is the "5+ years backend Java developer" a typo and supposed to be "...JavaScript developer", or is this actually a position that requires both Java and Node?

**Comment by AdamGrabish** [comment]
Hi David,

Thanks for your enquiry. This is not a typo, the business is ideally looking for a developer with a background in Java who has commercial experience with Node and is happy to develop with it moving forward.
