### ISSUE TITLE
Data analysis project

### ISSUE THREAD

**Issue by desiguel** [BrisJS/meetups#107]
Does anyone know anyone who would like some free research conducted on a customer data-set? I'm doing a data analysis project/thesis at UQ in the first half of this year and I thought I'd help out someone in the community rather than just analyze some random data. Short brief below:

# Background

My name is Andre de San Miguel and I'm currently studying for a Masters in IT  at the University of Queensland. Previous to this I've worked for 18 odd years as an analyst, trader and consultant.

# Proposal

One of the prerequisites for graduating from the Masters course is the completion of a research thesis, and in my case the completion of some fairly detailed data analytics.

As my preferred research area (data mining & customer data analysis) requires data not typically available in the public domain, I would like to offer free research and analysis in exchange for access to a relatively large customer data-set, that could roughly be used to achieve the following research objective:

<b>Identify and analyze trends within a/the customer database and relevant external data to enable the development of strategies related to customer acquisition, engagement and retention.</b>

This objective isn't set in stone and is pretty broad, so if you've got some other analytical needs then let me know.

Essentially you'd be getting some free research and analysis on your data in exchange for access to your data.

# Confidentiality

I'd be happy to sign a confidentiality agreement/deed or for you to anonymise your data-set (recommended as my final findings will be in the public domain).

# Timing

I'll be conducting this research over five months with an end date in late June 2016.

# Deliverables

*   Insights into your data!
*   A circa 100 page thesis report.
*   Source code (under MIT or similar license).

# Research Tools

Tools: R or Matlab (probably R), D3.js.

# Contact Details

email: andre@otcd.com.au
phone: 0403 755 855

**Comment by csinge** [comment]
I've passed this onto our GM

**Comment by desiguel** [comment]
Cheers
