### ISSUE TITLE
Slackbot-powered internet radio from a @Raspberry_Pi with @nodejs!

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#108]
@tomtomau has offered to talk about his recent slackbot radio project.

**Comment by tomtomau** [comment]
That was quick

**Comment by AshKyd** [comment]
I've been practising. :p

Talk sounds amazing btw, you're scheduled in. Reckon you could do a 20 min slot with Q&A? The whole slackbot-IoT thing seems to be really popular right now, so this should be good. :)

**Comment by MauriceButler** [comment]
Very interested.
:+1:

**Comment by tomtomau** [comment]
Thanks for having me!

Slides are here:
http://slides.com/tomnewbyau/deck#/
Github Repo for the internet radio is here:
https://github.com/tomtomau/internet-radio-slackbot

Remember it's a weekend hack project!

**Comment by AshKyd** [comment]
Awesome talk, thanks for the links. :)
