### ISSUE TITLE
Automating the generation of XKCD style movie narrative charts using d3.js.

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#109]
@drzax has offered to deconstruct his attempt to automate the generation of XKCD style movie narrative charts using d3.js.

[![narrative chart](https://imgs.xkcd.com/comics/movie_narrative_charts.png)](https://xkcd.com/657/)

**Comment by AshKyd** [comment]
Thanks a bunch @drzax. Could you please add any slides/resources you might have to the issue?

**Comment by drzax** [comment]
Sure thing. Here's a rough outline of [what I intended to say](https://github.com/drzax/talk-brisjs-narrative-charts/blob/master/draft.md) (no guarantee that it's what I ended up saying).

And the code is here: https://github.com/abcnews/d3-layout-narrative

**Comment by AshKyd** [comment]
Awesome. Thanks again, really enjoyable talk. :)
