### ISSUE TITLE
Static websites still got it

### ISSUE THREAD

**Issue by dwightgunning** [BrisJS/meetups#110]
Hey there,

My name is Dwight and I have a proposal for a talk: Static Websites still got it.

Static Websites are often overlooked but offer a lot of advantages over complex web-app stacks or hosted service (Wordpress, Squarespace etc.). There are awesome possibilities for putting client-side javascript to work, Angular.js etc., plus all the functionality and integrations possible with 3rd Party APIs.

A bit about me: I grew up on the Gold Coast, bachelor of InfoTech from QUT, tech consultant at Accenture for 8 years, moved to Amsterdam in 2010 and have been working on startups and side-projects for the past 5 years. One of my side-projects is Knownly (http://www.knownly.net) makes deploying static websites super fast and simple by integrating with Dropbox. Hence my interest in the topic.

I gave the above talk at a DevOps meetup a couple weeks ago in Amsterdam. I'm back in Australia until 22nd April so was thinking I should get into the local scene while I'm here. With a few tweaks I think the talk would be great for a JS crowd.

Looking forward to meeting up while I'm here.

Dwight

**Comment by xwipeoutx** [comment]
ThoughtWorks have an interesting write-up about this approach, too - though it was Git, not DropBox.  If a company as large and agile as ThoughtWorks is doing it, it seems like there's plenty of merit to the idea.

https://www.thoughtworks.com/insights/blog/incremental-approach-content-management-using-git

Just in case people was some casual pre-meetup reading :)

**Comment by dwightgunning** [comment]
Indeed. There are a bunch of variations on the theme.

Git post-receives hooks work great if you're comfortable with Git and don't mind coupling your build-deploy flow with your VCS.

For large projects I prefer a clearer separation (e.g. use of a dedicated CI like Jenkins, Codeship). For simple sites I want zero setup and simple/fast deployments so Dropbox plus Knownly works perfectly (when the complexity grows I'll init a git repo in the Dropbox folder which works just fine).

**Comment by AshKyd** [comment]
Sounds really cool. Next meetup is March 7th, will you be around then to schedule you in?

**Comment by dwightgunning** [comment]
Sure I'll be around so count me in.

Since we've never met in person it might be nice to at least do a quick
skype call we get a bit of an idea of what we're in for?

Any details I should know about? What's the preferred length (incl. time
for questions)? I used a 30min slot last time. Any things the audience
particularly likes / doesn't like when it comes to their speakers, demos
etc.

Let me know if there's a twitter account/hashtag or any other ways to help
you guys with promo.

Looking forward to meet you all.

Best Regards,

Dwight
ᐧ

--
Dwight Gunning
Twitter me: @dwightgunning <https://www.twitter.com/dwightgunning>

**Comment by AshKyd** [comment]
Hey, sure. Might see if I can get @iamkevinv in on that too since he's the organiser for the March meetup. Are you free for a chat tomorrow by any chance, or otherwise sometime Monday?

It's a pretty casual atmosphere, so there's no strict rules. Otherwise details are as follows:

* It's a 20 minute slot with time for questions afterward.
* Format is entirely what suits you best. Some folks do slides, others more of a demo and show some code.
* We've got a 1080p display, with HDMI or Mini DisplayPort connectivity for you.
* No Internet, but I can hook you up to my phone if need be.
* Twitter account is [@brisjs](https://twitter.com/brisjs)

Anywho, let me know when you're around. You can contact me at ash@kyd.com.au if you'd like to take the logistics private. :)

**Comment by iamkevinv** [comment]
@AshKyd is right - and sorry we haven't been able to catch up yet.
We will have plenty of time, so 20-30mins and some question time is completely viable.
We have a very diverse skill and interest range in the audience, so feel free to take the lead on content - the creativity here is yours and you should feel free to flaunt it without restriction!
Looking forward to having you there too!

**Comment by dwightgunning** [comment]
That's great.

I'll try to get hold of you guys before the event... if not I'll just show
up early for a quick tech-check of my laptop/projector and we'll be good to
go.

See you Monday.

Dwight
ᐧ

--
Dwight Gunning
Twitter me: @dwightgunning <https://www.twitter.com/dwightgunning>

**Comment by kzima** [comment]
@dwightgunning Nice presentation. +1 for static websites!

**Comment by dwightgunning** [comment]
Thanks @kzima - it was a great crowd. Based on the conversations I had and the questions that were asked you've got some really smart folks and great developers in the community.

Keep up the good work and if I can ever support / help out - just let me know.

Dwight

**Comment by dwightgunning** [comment]
PS: my slides are here: http://www.slideshare.net/dwightgunning/static-website-still-got-it-brisbane-js-meetup

**Comment by AshKyd** [comment]
Awesome, thanks. :)
