### ISSUE TITLE
ES6 - The greatest thing to ever happen to the JavaScript

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#112]
$SUBJECT

**Comment by AshKyd** [comment]
Sounds awesome, I've scheduled you in. Hope @iamkevinv doesn't mind. After tonight's discussions, I'd personally love to hear more about the ins and outs of promises and async/await stuff.

**Comment by iamkevinv** [comment]
Perfect.

**Comment by AshKyd** [comment]
Thanks @jwulf, very amusing and informative. Loved it!

Links from your tweeter:

* Async/await code samples: https://thomashunter.name/blog/the-long-road-to-asyncawait-in-javascript/
* Twitter convo with Brendan Eich: https://twitter.com/sitapati/status/705971610423918593

Do you have any other resources to share or shall we close this one?
