### ISSUE TITLE
Consoleconnect.com - Node.js (API/Frontend/Fullstack) Developer Positions

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#114]
## Code in JS, Revolutionise the internet

UPDATED as of MARCH 2017: New positions open! 2 python roles, but also this incredible Node.JS API developer position: http://grnh.se/vg7tqf1 (all positions advertised on our greenhouse board)

~_UPDATED as of JAN 2017 all positions filled - but **_absolutely_** stay in touch!_~

~_UPDATED Friday 7th OCT: A new Node API Dev position is current and open! - http://grnh.se/r8tbaj1_~

Definitely one of the best opportunities around to join our great growing team, with a Silicon Valley & Brisbane based company, which retains its startup culture and passion for creating an incredible new internet service product - http://consoleconnect.com/

We'd especially like to hear from people who are interested in backend/API development with us, but we're always interested in all flavours of JS developers, whether you like developing with browserified node frontend JS, or all of the above, it would be great to see people with range.

We've been privileged to take on board some of our BrisJS members before ( older posts: #52 ), and are continually impressed with the skill and passion of Brisbane devs who are keen to make a great product together.

We're keen to find some more great team members, so please have a look at the official job posting http://grnh.se/vg7tqf1 and feel welcome to get in touch with me on this issue or at kvanderbeken@consoleconnect.com if you have any questions. 
That's the official public link, so we put a simple screening task on there to show you at least know JS, and stem the torrent of 1 click applicants from places like seek ;-). If you feel that's onerous you should let me know that too!

Look forward to fielding your questions!

**Comment by iamkevinv** [comment]
This position is temporarily no longer advertised, but we're still taking resumes and talking with talented people to get them onboard. Get in touch with me :)

**Comment by iamkevinv** [comment]
Still current folks! Also quite keen to find someone leaning more to backend node.js API on express

**Comment by jwulf** [comment]
@iamkevinv still open?

**Comment by iamkevinv** [comment]
Updated jwulf. Not at the moment... but there will be another round for sure!

**Comment by iamkevinv** [comment]
It's on again 👍 
Come join an awesome team doing great stuff in the JavaScript API

**Comment by iamkevinv** [comment]
Pinned out a new issue #197 for this instead, so closing this one :) The positions are still there... check out the links!
