### ISSUE TITLE
[BrisJS User  | Mentions   |  Leaderboard]

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#117]
After scanning https://github.com/BrisJS/meetups/issues for @ mentions... everyone mentioned gets a mention. So, hello beautiful people!! Even spelling mistakes, @import and @display get a mention or two.

```javascript
u={MauriceButler:12,kevdesign:18,Vheissu:3,eddieajau:4
,marklawlor:14,iamkevinv:11,rknell:14,ridget:7,AshKyd:16
,colingourlay:7,xwipeoutx:7,collypops:3,garrows:11
,DamonOehlman:1,korynunn:2,KoryNunn:5,tatey:1
,louisstow:6,swren:1,govpack:14,PandaWhisperer:1,spidie:6
,shotlom:11,timoxley:2,banterability:1,baterability:1,cobbweb:1
,csinge:2,marak:1,Fishrock123:1,elonmusk:1,chrsr:1,'import':1
,Sportsmed:2,Mauricebutler:1,davidmason:2,mauricebutler:1
,ljowen:1,streetkid:3,nigelr:1,anyone:2,ArtemGovorov:1,BrisJS:1
,chriswilsoon:3,drzax:4,annagerber:1,geoffreyd:5,AnnaGerber:1
,mathias:1,issacs:1,alexzhaosheng:2,fariazz:3,jbristowe:2
,andrewling89:5,display:2,jwulf:2,fud:1,shikhirsingh:2
,loklaan:2,kzima:1,butlermaurice:1,girvo:1,Raspberry_Pi:1
,nodejs:1,tomtomau:1,dwightgunning:1,brisjs:1}

A=[];for(p in u){A.push([p,u[p]])};
A.sort(function(a,b){return a[1]<b[1]?1:a[1]>b[1]?-1:0})

md='| BrisJS User        | Mentions           |  Leaderboard  |\n'
md+='| ------------- |:-------------:| -----|'
for(i=0;i<A.length;i++){uza=A[i][0];x=A[i][1]
md+='\n|@'+uza+'|    '+x+'      |'+(new Array(x+1)).join(' :trolleybus: ')+'|'
}

//display(md)
// font-family:Apple Color Emoji,Segoe UI Emoji;

```

[All github Emoji (Smiles)](https://gist.github.com/AliMD/3344523) and the results are...

**Comment by govpack** [comment]
| BrisJS User        | Mentions           |  Leaderboard  |
| ------------- |:-------------:| -----|
|@kevdesign|    18      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@AshKyd|    16      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@marklawlor|    14      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@rknell|    14      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@govpack|    14      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@MauriceButler|    12      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@iamkevinv|    11      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@garrows|    11      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@shotlom|    11      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@ridget|    7      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@colingourlay|    7      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@xwipeoutx|    7      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@louisstow|    6      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@spidie|    6      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@KoryNunn|    5      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@geoffreyd|    5      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@andrewling89|    5      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@eddieajau|    4      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@drzax|    4      | :trolleybus:  :trolleybus:  :trolleybus:  :trolleybus: |
|@Vheissu|    3      | :trolleybus:  :trolleybus:  :trolleybus: |
|@collypops|    3      | :trolleybus:  :trolleybus:  :trolleybus: |
|@streetkid|    3      | :trolleybus:  :trolleybus:  :trolleybus: |
|@chriswilsoon|    3      | :trolleybus:  :trolleybus:  :trolleybus: |
|@fariazz|    3      | :trolleybus:  :trolleybus:  :trolleybus: |
|@korynunn|    2      | :trolleybus:  :trolleybus: |
|@timoxley|    2      | :trolleybus:  :trolleybus: |
|@csinge|    2      | :trolleybus:  :trolleybus: |
|@Sportsmed|    2      | :trolleybus:  :trolleybus: |
|@davidmason|    2      | :trolleybus:  :trolleybus: |
|@anyone|    2      | :trolleybus:  :trolleybus: |
|@alexzhaosheng|    2      | :trolleybus:  :trolleybus: |
|@jbristowe|    2      | :trolleybus:  :trolleybus: |
|@display|    2      | :trolleybus:  :trolleybus: |
|@jwulf|    2      | :trolleybus:  :trolleybus: |
|@shikhirsingh|    2      | :trolleybus:  :trolleybus: |
|@loklaan|    2      | :trolleybus:  :trolleybus: |
|@DamonOehlman|    1      | :trolleybus: |
|@tatey|    1      | :trolleybus: |
|@swren|    1      | :trolleybus: |
|@PandaWhisperer|    1      | :trolleybus: |
|@banterability|    1      | :trolleybus: |
|@baterability|    1      | :trolleybus: |
|@cobbweb|    1      | :trolleybus: |
|@marak|    1      | :trolleybus: |
|@Fishrock123|    1      | :trolleybus: |
|@elonmusk|    1      | :trolleybus: |
|@chrsr|    1      | :trolleybus: |
|@import|    1      | :trolleybus: |
|@Mauricebutler|    1      | :trolleybus: |
|@mauricebutler|    1      | :trolleybus: |
|@ljowen|    1      | :trolleybus: |
|@nigelr|    1      | :trolleybus: |
|@ArtemGovorov|    1      | :trolleybus: |
|@BrisJS|    1      | :trolleybus: |
|@annagerber|    1      | :trolleybus: |
|@AnnaGerber|    1      | :trolleybus: |
|@mathias|    1      | :trolleybus: |
|@issacs|    1      | :trolleybus: |
|@fud|    1      | :trolleybus: |
|@kzima|    1      | :trolleybus: |
|@butlermaurice|    1      | :trolleybus: |
|@girvo|    1      | :trolleybus: |
|@Raspberry_Pi|    1      | :trolleybus: |
|@nodejs|    1      | :trolleybus: |
|@tomtomau|    1      | :trolleybus: |
|@dwightgunning|    1      | :trolleybus: |
|@brisjs|    1      | :trolleybus: |

**Comment by iamkevinv** [comment]
Hahah! I love it! Nice work @govpack :-)

**Comment by shotlom** [comment]
Hmmm, about that metric ... 

@MauriceButler	x12	:trolleybus: 
v
@shotlom	x11	:trolleybus:  

Maybe that should be 

@MauriceButler	x12	:ok_hand:
v 
@shotlom	x11	:grey_question:

**Comment by iamkevinv** [comment]
Having the heuristics to determine that you're asking questions, would be quite a feat @shotlom :)

**Comment by xwipeoutx** [comment]
Not really... Just look for a question mark.

**Comment by govpack** [comment]
@shotlom on second thoughts it ought to have been a case insensitive tally. I mean Maurice especially, is suffering from a bad case of "Multi Camel Case Capitalization Disorder" or MCCCD (or 1600 in Arabic numerals) and he'd be much higher and happier if we corrected for that, maybe.

@iamkevinv, funnily enough looking for @xyz was actually derived from a similar thing that listed out all questions from some range of issues (and issue titles) albeit NOT grey questions, or :question: | :grey_exclamation: | :grey_question: NOR any of these...

# ?¿;՞؟፧᥅⁇⁈⁉⍰❓❔⩻⩼⳺⳻⸮㉄꘏꛷︖﹖？𑅃󠀿

@xwipeoutx the problem with 'just' looking for question marks is they appear in search strings of urls, and in code and "where do the sentences begin?" and which module to choose for that. So 'just' is a cool thing to say until you try it, but 70 lines of code later it's done -- so what do i care. I didn't think it was simple or easy, but it's worth it!! to see it ticking away, extracting things from the comments, as if it knows what it's doing. 

at that point they are being taken out of context, so that can be a bit funny.

and yes `if(yi.indexOf('?')>0){...}` did appear in there, so @xwipeoutx you are :100:% right -- if only we were programming in English. Now it reads... 

```javascript
if(/[?¿;՞؟፧᥅⁇⁈⁉≟⍰❓❔⩻⩼⳺⳻⸮㉄꘏︖﹖？]|:question:|:grey_question:/.test(yi)){
```

it's nothing if not a minor amusement.

**Comment by govpack** [comment]
or similar
````javascript
/[ \u003F\u00BF\u037E\u055E\u061F\u1367\u1945\u2047\u2048\u2049\u225F\u2370\u2753\u2754\u2A7B\u2A7C\u2CFA\u2CFB\u2E2E\u3244\uA60F\uFE16\uFE56]|:question:|:grey_question:/.test('xxx')
```

**Comment by xwipeoutx** [comment]
@govpack I'm sure they appear in all these places, but one thing I've
learned about data analytics; near enough is good enough

God Bless
- Steve
