### ISSUE TITLE
Cross-thread data-replication with function-invoking (tbd)

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#118]
@korynunn has requested a slot at the next meetup to talk about his next project, tentatively titled “cross-thread data-replication with function-invoking”.

**Comment by KoryNunn** [comment]
Or maybe something completely different if it doesn't work out..

**Comment by AshKyd** [comment]
@KoryNunn: thanks for the talk, it's pretty impressive. Do you have any resources more than the repo at [/korynunn/lenze](/korynunn/lenze) you'd like to add here?

**Comment by KoryNunn** [comment]
Hmm not really, I might update the example for fastn to use it in the future.
