### ISSUE TITLE
ES6 modules - Babel, Rollup, JSPM, what is the future?

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#119]
So there's a lot of work being done on ES6 modules. What tools are people using? How does NPM support ES6 modules? What is Node going to do? OMG what's happening!

I'd like to propose a talk on ES6 modules. It's something I'm really interested in coming from the Node camp, since CommonJS has become the de facto ES5 module format and it's going to require a pretty large shift.

I'd like to discuss:

* Briefly, how ES6 modules work & differ from CommonJS.
* ES6 modules in the browser? :O
* Babel,
* Webpack/Browserify
* JSPM & Rollup,
* Node
* Other?

Keen to do this in May unless someone wants to jump in earlier.

**Comment by garrows** [comment]
Cool. Looking forward to it.

Not sure if your questions were retohrical or not but I started a es6 game
recently and used webpack with babel
https://www.npmjs.com/package/babel-loader which worked quite well.

**Comment by govpack** [comment]
@AshKyd @garrows 

cool, it's a fair enough topic, i'd be interested in hearing a summary of that lot. 

....it gets some coverage in the following talk: http://nodeup.com/ninetynine
"Rod Vagg is joined by Bradley Meck, Caridy Patiño and Forrest Norvell to talk about Node and ES Modules!"

...along the lines of "too long didn't listen" closely enough... they're all going to get along!!! and the future will be more of the same!! Yeah great, more stuff to learn. I'm happy **loading modules** is becoming a language feature, hopefully they will provide some more hooks & control over where modules are loaded from. 

There's some overlap there between what npm does, and what the language wants to do. Could it potentially allow for doing what npm does dynamically at runtime?

**Comment by iamkevinv** [comment]
Hi @AshKyd - are you able to still put together at least a subset of what you wanted to raise for May 9?

**Comment by AshKyd** [comment]
Sure, started some slides this weekend.

**Comment by iamkevinv** [comment]
Are you OK with standard 20 minutes, or would you like the 40 minute slot?

**Comment by AshKyd** [comment]
Nah, definitely stick with the 20. I don't have *that* much to talk about. :)

**Comment by iamkevinv** [comment]
Thanks again @AshKyd - if you have the talk resources... you know the drill ;-) links!

**Comment by AshKyd** [comment]
Slides are here: http://ashkyd.github.io/es-modules-2016/

Might write some words at some point.
