### ISSUE TITLE
Machine Learning with JavaScript

### ISSUE THREAD

**Issue by desiguel** [BrisJS/meetups#120]
Would anyone like a talk on this topic? I can do one in May if there is interest.

Andre

**Comment by demsey2** [comment]
+1

**Comment by garrows** [comment]
I would very much like this too!

**Comment by AshKyd** [comment]
Definitely, sounds good. Couldn't tempt you for April 4th @desiguel?

**Comment by desiguel** [comment]
No can do unfortunately... I won't be around in early April.

**Comment by AshKyd** [comment]
No probs. Let's put you on for May then. :)

**Comment by AshKyd** [comment]
Just wanted to confirm you're good for May 2 @desiguel, and I'll put you on the agenda. 20 minute timeslot sound good? :)

**Comment by desiguel** [comment]
Not sure about 20.. will see how much material I've got and let you know.

**Comment by AshKyd** [comment]
No pressure, but let me know so we know where to put you on the lineup. I'm sure people will have questions at the end too, so you might be surprised. :)

**Comment by desiguel** [comment]
Should be ok for 15min + 5min for questions.

**Comment by iamkevinv** [comment]
Hi @desiguel - All set for May 9?

**Comment by desiguel** [comment]
Yup.. all good.

**Comment by desiguel** [comment]
@iamkevinv What type of connector is available for video input? I can output to vga..

**Comment by iamkevinv** [comment]
Hi @desiguel - We export natively to HDMI, and i have Mini Displayport to HDMI adapters.
Can i grab your name for the Meetup Page?

**Comment by iamkevinv** [comment]
Are you OK with standard 20 minutes, or would you like the 40 minute slot?

**Comment by desiguel** [comment]
Andre de San Miguel

On 03/05/2016 11:58 PM, "Kevin Vanderbeken" <notifications@github.com>
wrote:
>
> Hi @desiguel - We export natively to HDMI, and i have Mini Displayport to
HDMI adapters.

**Comment by desiguel** [comment]
20 minutes is ok.. I don't have enough material to cover for 40.

A.

**Comment by iamkevinv** [comment]
Thanks for the talk @desiguel :) - if you have resources you can link to here, that would be great 👍

**Comment by iamkevinv** [comment]
@desiguel - got any of your links to materials to add here?
