### ISSUE TITLE
Aurelia 

### ISSUE THREAD

**Issue by tomtomau** [BrisJS/meetups#121]
Hey there!

I've been doing a work project in Aurelia now for about a month and a half and the poll at the last meetup on JS Frameworks suggested there wasn't many (or any?) other people who'd tried out Aurelia yet.

I'd be more than happy to do an intro + getting started + experiences thus far sort of talk sometime if people were interested.

**Comment by AshKyd** [comment]
Sounds cool, Can I schedule you for a 20 min slot on April 4?

**Comment by tomtomau** [comment]
I'm overseas without internet (gasp) for the next week, so I'm willing to bet I won't have time to prep for the April meetup :(

**Comment by AshKyd** [comment]
No probs. Let us know and we can make it the month after, maybe. :)

**Comment by tomtomau** [comment]
Can put me down for May!

**Comment by iamkevinv** [comment]
Hi @tomtomau - All set for May 9?

**Comment by tomtomau** [comment]
Yep all good @iamkevinv, when do you need a blurb?

**Comment by iamkevinv** [comment]
Always helps!

**Comment by iamkevinv** [comment]
Are you OK with standard 20 minutes, or would you like the 40 minute slot?

**Comment by tomtomau** [comment]
Hey @iamkevinv - didn't see this! I think it could easily be closer to 30-40 minute slot in the end with questions. Just let me know what would work better for the night :)

**Comment by iamkevinv** [comment]
The 40ish min slot is perfect to start the night with! Thanks mate.

**Comment by iamkevinv** [comment]
Thanks for the Talk @tomtomau - can you link the resources here?

**Comment by tomtomau** [comment]
No worries, slides are [here](http://slides.com/tomnewbyau/aurelia#/) and the repo ended up [here](https://github.com/tomtomau/brisjs-aurelia-demo).

Any chance of having the video on YouTube?

**Comment by iamkevinv** [comment]
Partially uploaded. Australian internet sucks. I promise it will be there.
