### ISSUE TITLE
What we learned building x-plat React Native app in 3 months

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#124]
@girvo has offered to share what his team learned building x-plat React Native app in 3 months.

**Comment by iamkevinv** [comment]
@girvo - How are you going? Poised to give us this talk monday? Would be great to hear about.

**Comment by iamkevinv** [comment]
@girvo - Any update? I'd love to put a date on this talk ;-)

**Comment by iamkevinv** [comment]
Hi @girvo - People are still keen to hear this one... do you have time for a sept presentation?

**Comment by iamkevinv** [comment]
Going to check in - monday is the november meetup @girvo - any chance to see this presentation? :)

**Comment by iamkevinv** [comment]
This was opened in march. If no responses from @girvo on a firm presentation for Feb next year, we'll close this @AshKyd . Cheers.

**Comment by jwulf** [comment]
Yo @girvo would love to hear this talk - you going to give it?

**Comment by iamkevinv** [comment]
Doesn't seem like it @jwulf - Closing it. Anyone can re-open if they want to present something similar. Thanks to all involved!
