### ISSUE TITLE
Angular Hack Day Brisbane

### ISSUE THREAD

**Issue by ChrisBriggsy** [BrisJS/meetups#126]
Hi there,

I’m running an Angular Hack Day in Brisbane on Saturday 14th May 2016, and was hoping this event would be something BrisJS would be interesting in partnering up on.   

> Angular Hack Days are free community events that are run to share the Angular love with fellow devs. 

The days are broken up into 2 parts: In the morning, attendees get to learn about the basics of Angular 2 through a few 15-minute talks by Angular experts. Once the presentations are done, the attendees then fire up their laptops and code an angular app. Mentors are on hand to help get people unstuck or answer any questions. 

We recently ran a highly successful event in Melbourne - we packed out the venue, completely sold out of tickets, and had nothing but positive feedback from the attendees. You can check out [my write-up of the event over on my blog] (http://blog.chrisbriggsy.com/First-Angular-Hack-Day-Melbourne/).

If you were interested in getting involved with the Brisbane Angular Hack Day, there are a few ways you could help out:

1.  Can we send someone to promote the event by making a brief announcement regarding the event to the BrisJS meetup group?
2. Help us find speakers & mentors with ninja Angular skills
3. You could help to organise the event, promote your meetup at the hack day and meet new people
4. Can you guys promote the event to your meetup group via emails or the meetup page? 

You can find out more at www.AngularHackDay.com. We also been running Xamarin Hack Days for a couple of years, which you can read about at www.XamarinHackDay.com   

Looking forward to hearing from you,

Chris Briggs
Angular Hack Day Organiser

**Comment by xwipeoutx** [comment]
Hi there,
(Full disclosure: I work for the same company as Chris)

I was hoping to be able to do the spiel at BrisJS, but I'll be away camping for the next BrisJS meetup :cry:.  

I'd like to emphasise that the hack day will include some pretty decent learnings about Angular2, and a good chance to dive in with mentoring support. I've just started using it on a client project myself, and I must say, it's very awesome and a big step up from Angular.  Certainly worth learning - you won't want to go back to vanilla Angular.

**Comment by iamkevinv** [comment]
Hey folks, yeah i'd love to have someone do a spot at the next meetup... if someone wants to do it... please let me know. Otherwise i'll just include it as part of upcoming events at the usual preamble.

**Comment by adamstephensen** [comment]
Hi Team. I'm free to come along and plug the event and see if I can round up a few more speakers and mentors.
