### ISSUE TITLE
Join the ABC News team to work on major events coverage

### ISSUE THREAD

**Issue by colingourlay** [BrisJS/meetups#127]
We're looking for a dev to join our team until November, to work on some of the major events we'll be covering this year, including the Federal Election, Olympics and US Election.

Details about this temporary contract role are in the [job ad](http://careers.abc.net.au/caw/en/job/495231/developer-websites-applications), but in short, you'd be working with the front-end team here in Brisbane, helping them build custom sections of our News websites & apps for our major events coverage.

Working in a newsroom alongside journalists and creatives, with the opportunity to share your work with the ABC's large, diverse audience is a pretty awesome and unique experience. I'd recommend it to anyone.

Applications close on Sunday, so get in there now!

[Apply](http://careers.abc.net.au/caw/en/job/495231/developer-websites-applications)

**Comment by colingourlay** [comment]
P.S. If you have any questions, let me know and I'll try to answer them :dancers:

**Comment by iamkevinv** [comment]
Closed @colingourlay ?
