### ISSUE TITLE
React front-end developer / cross-over to Node.js

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#130]
Pretty cool bimodal company with a solid revenue stream from a SaaS platform and a funded internal startup looking a frontend developer.

Here's a description of the tech stack:

- React | Flux | Redux
- Hot-loading
- Cross-platform JavaScript mobile development
- Test-driven Development
- Continuous Integration
- AWS CodeDeploy
- Linting (less time on style, more time on substance)
- AWS PaaS deployment 
- Node.js
- Golang
- LAMP Stack
- Microservices Architecture
- Containerization via Docker
- Redis
- ElasticSearch

Hit me up for more deets.

**Comment by iamkevinv** [comment]
Hey @jwulf - i routinely purge the older ones in here... if it's still "on" then let me know and i'll re-open the job posting.
