### ISSUE TITLE
Hiring an entire JavaScript team, wholesale

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#133]
https://www.youtube.com/watch?v=NlgDXpz6nEk

**Comment by jwulf** [comment]
Hiring an entire team of JS devs, wholesale - $720,000 in salaries. 

They're looking for six devs in total, and hiring any combination of two or more devs as a unit. "Molecules, not atoms" as they say at Stripe.

**Comment by iamkevinv** [comment]
Likewise with this one :) Let me know if it needs reopening.
