### ISSUE TITLE
Not living up to the promise? Righto.

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#135]
An alternative to promises. 

@korynunn has kindly volunteered a talk about his library - "Righto", which could help you in your call chain.

**Comment by iamkevinv** [comment]
@korynunn can you link applicable resources here please :)

**Comment by KoryNunn** [comment]
Sure!

The lib: https://github.com/KoryNunn/righto

A comparison of the two: https://github.com/KoryNunn/righto-v-promise

**Comment by iamkevinv** [comment]
Thanks man!
