### ISSUE TITLE
Talk Proposal - Hiring a JS Developer: A Client's Perspective

### ISSUE THREAD

**Issue by pdm55** [BrisJS/meetups#136]
**Hiring Javascript developers to code an online game**

_The product_
http://akqbridge.com/

_The journey_
6 developers have put different parts of the game together over a 3 year period.

_My proposed talk_
My motivation in having an online game. Where I looked to find my developers. How I saw my duties as the client. Key difficulties we have faced. Similarities and differences between the 6 developers. Where to now?   

Peter Munro (aka Peter Soupman on Facebook)

**Comment by iamkevinv** [comment]
Hi @pdm55 - I've added you to Monday's lineup - thanks for volunteering to give a talk :-)

**Comment by iamkevinv** [comment]
If you have further resources to share, you're welcome to link them here @pdm55 👍
