### ISSUE TITLE
Talk - Experiences with Firebase

### ISSUE THREAD

**Issue by LennyThompson** [BrisJS/meetups#138]
Provide some insight into implementing firebase as the datastore for a web app, in particular looking at the angular fire and javascript APIs, and security rules with the firebase-bolt compiler. With coding example.

This can be scheduled more or less whenever suits, just give me a couple of weeks notice.

**Comment by themikola** [comment]
I would be very interested in this. Have just gotten into the latest firebase release, and am struggling with the security rules.

**Comment by iamkevinv** [comment]
Hey @LennyThompson - thanks for volunteering at the meetup... great to see you posted the issue. Lets set you up for the July meetup date :) thanks!

**Comment by iamkevinv** [comment]
Looking forward to this on monday @LennyThompson :)

**Comment by LennyThompson** [comment]
The repo with the source for the demo firebase ap...

https://github.com/LennyThompson/firebase-demo

I can add the presentation as well if anyone is interested.

**Comment by mcnamee** [comment]
Great work @LennyThompson 
Thanks for the time you spent preparing and giving the talk

**Comment by LennyThompson** [comment]
[Firebase presentation.pdf](https://github.com/BrisJS/meetups/files/368339/Firebase.presentation.pdf)

**Comment by LennyThompson** [comment]
All done Kevin...

**Comment by iamkevinv** [comment]
THANKS! 👍
