### ISSUE TITLE
Talk: React Native, Common pitfalls, what you need to know (Formerly Cordova/PhoneGap)

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#14]
Someone mentioned this tonight. I can do a basic intro talk but I'm not an expert. Anyone else want to do a talk?

**Comment by rknell** [comment]
Hey,

This is what I deal with every day if you wan't me to have a chat?

- Ryan

**Comment by MauriceButler** [comment]
I was going to put my hand up but I also am no expert, just someone who gets stuck with it. 

@rknell looks like you are the resident expert. :+1:

**Comment by kevdesign** [comment]
Heheh... looks like @MauriceButler volunteered you @rknell ... let us know what you could give people a demo with

**Comment by iamkevinv** [comment]
Hi @rknell :) - are you able to give us a presentation for the next brisJS? 6th July.

**Comment by rknell** [comment]
Hi Kevin,

Sorry for not getting back to you next time, the meeting crept up on me,
Yep I can do it.

What level do you think the group is at regarding PhoneGap/Cordova? Do they
understand the concept around plugins etc or should I just start with a
really simple, entry level presentation?

Kind regards,

Ryan Knell
0452 323 234

On Tue, Jun 16, 2015 at 9:03 PM, Kevin Vanderbeken <notifications@github.com

**Comment by MauriceButler** [comment]
IMHO I believe intermediate level would be better.

I think "most" attendees have a basic understanding of PhoneGap and what it solves already but how to get the most out of it would be beneficial.

If someone needs the hello world example they can do that themselves easy enough, even before the meetup.

**Comment by iamkevinv** [comment]
If @MauriceButler gave you enough of a direction @rknell can i book you in? Next meetup is 6th July.

**Comment by rknell** [comment]
Yep I can do it

Kind regards,

Ryan Knell
0452 323 234

On Mon, Jun 29, 2015 at 9:38 PM, Kevin Vanderbeken <notifications@github.com

**Comment by iamkevinv** [comment]
Seems like you slipped through the cracks? Is this still a presentation you can give? @rknell

**Comment by rknell** [comment]
Hi mate,

It is and I want to, unfortunately just not this month, snowed under so
wont be able to attend either, still keen but I will let  you know when i
have me head above water again.

R

Kind regards,

Ryan Knell
0452 323 234

**Comment by iamkevinv** [comment]
no problem... i'll push back to October

**Comment by iamkevinv** [comment]
Assuming this goes to Nov

**Comment by iamkevinv** [comment]
@rknell Next BrisJS is nov 2 :) which is soon. Please confirm you're all good to go with this so i can send out the email. Thanks :)

**Comment by iamkevinv** [comment]
Ping @rknell :)

**Comment by rknell** [comment]
Oh hey mate,

Sorry not going to be able to make it - will be in NSW. Sorry!

Kind regards,

Ryan Knell
0452 323 234

**Comment by iamkevinv** [comment]
Another ping for @rknell  :) Any luck getting you on board for monday - last chance for the year!

**Comment by AshKyd** [comment]
@rknell: Would be keen to schedule this talk in for February 1, would that suit you?

**Comment by iamkevinv** [comment]
@rknell - Would you perchance be able to give us a talk soon?

**Comment by rknell** [comment]
Whens the next meeting?

<http://www.snappy-apps.com.au>

**Comment by iamkevinv** [comment]
It was Monday 13 June. If not that we'd have first Monday of July.

**Comment by iamkevinv** [comment]
How about it :) ?
July good for you @rknell ?

**Comment by iamkevinv** [comment]
pinging @rknell ?

**Comment by iamkevinv** [comment]
Since we had such a good response... Are you at all able to show this off in Sept @rknell ? :D

**Comment by rknell** [comment]
Bit under the pump at the moment, could we push it back to the October
meetup?

<http://www.snappy-apps.com.au>

On Sat, Aug 13, 2016 at 6:04 PM, Kevin Vanderbeken <notifications@github.com

**Comment by iamkevinv** [comment]
I'll hold you to it! (Actually not, but appreciate you stepping forward to
do it :-) )

**Comment by iamkevinv** [comment]
@rknell - Would you still be on for the Oct Meetup next monday?

**Comment by rknell** [comment]
Hi Kevin,

Sorry still flat out, wont be able to make it this time.

<http://www.snappy-apps.com.au>

**Comment by iamkevinv** [comment]
November it is.

**Comment by iamkevinv** [comment]
@rknell - I'm checking in again - would you be available for the talk for November meetup next monday? I think people would be keen.

**Comment by rknell** [comment]
Hi Kevin,

Been doing more with React Native and I think its a better way to go,
I could give a talk about my thoughts and the hurdles I needed to
overcome to get started if you like? I think I would generally advise
against making an app with Cordova these days.

What do you think?

R

**Comment by iamkevinv** [comment]
That also sounds good :)
And would be excellent for you to explain why people shouldn't be looking at cordova anymore in a slide somewhere too then.
Line up for dec? - assuming next monday would be rushing you to meet the Nov one.

**Comment by rknell** [comment]
Yep, lets do it, ill start working on the slides this month

**Comment by iamkevinv** [comment]
Hi @rknell - I remembered you said you were working on this - howd you go? Were you still keen for Mon Dec 12? I'm going to announce the lineup ASAP and need to juggle a few talks around as everyone's keen :)

**Comment by rknell** [comment]
Yep lets do it!

<http://www.snappy-apps.com.au>

On Sun, Dec 4, 2016 at 11:22 PM, Kevin Vanderbeken <notifications@github.com

**Comment by rknell** [comment]
It would be something like first steps with react native - common pitfalls
and what you need to know

<http://www.snappy-apps.com.au>

On Sun, Dec 4, 2016 at 11:22 PM, Kevin Vanderbeken <notifications@github.com

**Comment by iamkevinv** [comment]
I think that would be appreciated by all :)
Probably also explain why Cordova is kind of going the way of the dodo...

**Comment by rknell** [comment]
No worries, I will give some background about how I ended up here.

<http://www.snappy-apps.com.au>

On Mon, Dec 5, 2016 at 11:29 AM, Kevin Vanderbeken <notifications@github.com

**Comment by iamkevinv** [comment]
I'm doing the announcements today, there's been a lot of interest for dec speaking... was it for a 20 min or 40 min slot?

**Comment by rknell** [comment]
Just 20 is fine

<http://www.snappy-apps.com.au>

**Comment by iamkevinv** [comment]
If you have any links to share @rknell - please do! thanks again
