### ISSUE TITLE
Talk - Minimising CSS Complexity

### ISSUE THREAD

**Issue by lukebrooker** [BrisJS/meetups#140]
This would be the talk I gave at [CampJS](http://vii.campjs.com/schedule/), although slightly updated.

**Here was the excerpt:**

Many try to solve CSS complexity and long-term maintenance by using advanced methods of organisation like BEM, OOCSS, SUIT or more recently CSS modules or other forms of CSS in JS™. While these may be necessary, and choosing a strategy is important, there is a lot of complexity that can be removed regardless of organisational strategy.

There are many CSS techniques/solutions we use today that are overly complicated or simply extraneous, and we use these day in day out without really thinking about why.

This is what this talk is about. Using examples of complex CSS components and design systems, we will deconstruct what the intended outcome was, how it can be simplified and the methods/CSS techniques used to get there.

There will be many CSS tips and tricks included, but hopefully, we will also challenge some fundamental ideas of how to write complex CSS. You will walk away with a better understanding of CSS, and a stronger foundation for building complex design systems with CSS.

**Comment by iamkevinv** [comment]
hey @lukebrooker - when would you like to do this talk? Next week's July meet?

**Comment by iamkevinv** [comment]
Assuming a 20-25min slot?

**Comment by iamkevinv** [comment]
Can split the 40 and 20 into a 30 each for yourself and Eddie to give enough time if needed.

**Comment by lukebrooker** [comment]
It was originally 30 mins, but I could get it down to 25 if needed 😄

**Comment by iamkevinv** [comment]
Resources to share for your talk @lukebrooker ?

**Comment by iamkevinv** [comment]
If you find your resource links for the folks at home @lukebrooker - feel free to add. Closing for now. Thanks!
