### ISSUE TITLE
RedEye Apps - Front-end JS developer

### ISSUE THREAD

**Issue by tomtomau** [BrisJS/meetups#141]
Hi folks,

We're hiring a front-end JS developer here at RedEye to work on our Aurelia JS application. Don't worry if you haven't worked in Aurelia before - if you've worked in Angular, Knockout, etc. it will feel very familiar (and hopefully way better!)

RedEye is a software startup of ~30 awesome people here in the CBD creating software solutions for service providers and asset owners (think oil & gas pipelines, hydro dams, urban utilities).

If you're interested in finding out more, shoot me an email - tom @ redeye.co - or come say hello at Monday's meetup - I have a big red beard.

Cheers!

**Comment by iamkevinv** [comment]
Hi @tomtomau - Let me know if this should be reopened... i'm just doing a cleanup of some of our older postings :)

**Comment by tomtomau** [comment]
All good :)
