### ISSUE TITLE
Talk - Building Simpla on Web Components

### ISSUE THREAD

**Issue by bedeoverend** [BrisJS/meetups#142]
Would love to give a talk on how we've created [Simpla](https://simpla.io) - a library of Custom Elements built on Polymer that contain editable content and talk to a RESTful API.

Something of a background on what Simpla is, the problems we faced and how Web Components / Polymer has helped resolve them.

Be keen to give this one on August 1st if possible?

**Comment by iamkevinv** [comment]
Okay! Lets let the world know. Look forward to having you present!

**Comment by iamkevinv** [comment]
Are you cool to do about 15 minutes+Questions? We're compacting in 4 talks for Aug so i'd like to shave off some minutes and not having an opening 40min talk. Honestly you'll probably still get the whole 20 minute slot anyway, but i ask just in case.

**Comment by bedeoverend** [comment]
@iamkevinv nah that's fine. 15 minutes + Q/A works well. Looking foward to it!

**Comment by iamkevinv** [comment]
Thanks for the talk - i think people really got into it!! We'd be happy to see where this goes and have you back anytime. If you could share some links here it would be great.

**Comment by bedeoverend** [comment]
@iamkevinv thanks! It was great meeting everyone and seeing some fantastic talks. [Here are my slides](https://speakerdeck.com/bedeoverend/simpla-on-webcomponents-at-brisjs-august-2016).

Also for anyone who's interested, I'd highly recommend reading [this](https://developers.google.com/web/fundamentals/primers/customelements/) article on the new Custom Elements spec by Eric Bidelman. Well worth a read.

For anyone interested in learning a bit more about Simpla - take a look at https://simpla.io, our [Git Repo](https://github.com/simplaio/simpla) and for a chat check out our [Slack Channel](http://slack.simpla.io). Cheers!

**Comment by iamkevinv** [comment]
Awesome, thanks!
