### ISSUE TITLE
Talk - Houdini, write your own CSS magic 'natively' in JavaScript

### ISSUE THREAD

**Issue by azariah001** [BrisJS/meetups#144]
Are people interested in a talk on Houdini? I'd be willing to do a talk on it, although I'm no expert. At this stage I don't think anyone is really :stuck_out_tongue: but it's really cool and I'd like to share if others are interested. :smile:

For those not already aware. Houdini is the product of a joint task force between all of the major browser engineering teams plus some engineers from HP and Intel. The aim is to expose the CSS engine directly within the Javascript runtime to allow developers to create new CSS rules as well as simplifying direct interactions with an elements styling properties. The goal is to get Houdini to a point where they can go to W3C with a standards proposal.

At this stage, there's only a collection of incomplete drafts so it's super early days but there's already an early polyfill available which basically just does what we're already doing but through the syntax and commands that they're defining for the new... API? I guess you'd call it that, the polyfill is super inefficient. :stuck_out_tongue_closed_eyes: Anyway, there's a lot of cool stuff to go through. There was a presentation about it at Google I/O this year which is where I heard about it and I'd love to share my ideas with the group. :grinning:

**Comment by iamkevinv** [comment]
This sounds cool @azariah001 :) I'd be pretty happy to have you in the next BrisJS for August if you're keen?

**Comment by azariah001** [comment]
Yeah, I'm up for it. :smile:

**Comment by azariah001** [comment]
Cool! I've started prepping. :smile:

**Comment by iamkevinv** [comment]
Are you cool to do about 15 minutes+Questions? We're compacting in 4 talks for Aug so i'd like to shave off some minutes and not having an opening 40min talk.

**Comment by azariah001** [comment]
Yeah that's fine, no problem at all. :)

**Comment by azariah001** [comment]
Talk concluded. :smile: 

Will probably revisit this topic at some point in the future when there's actual stuff to demo. :grinning:
