### ISSUE TITLE
Web Application Developer required - JS Stack - Immediate start

### ISSUE THREAD

**Issue by cam861** [BrisJS/meetups#147]
Scooter Tutor is working tirelessly to drop the barriers and disrupt the home tuition space.  We've been working on it for years and now we're ready to start to build the team.  Let me know if you're interested in learning more about the position... 

We have a (token) Seek ad running at the moment, but feel free to contact me directly.

[Seek Ad](http://www.seek.com.au/job/31466484?pos=1&type=standout&engineConfig=&userqueryid=124779934007540583&tier=no_tier&whereid=)

Cheers,

Cam

**Comment by iamkevinv** [comment]
How is it going @cam861 ? - I've been closing some of the older postings... can this one be taken down too? Or have more info to entice people?
