### ISSUE TITLE
Talk - Automated browser testing with Nightwatch.js

### ISSUE THREAD

**Issue by VladimirAus** [BrisJS/meetups#148]
Can do short 15mins
- basics of automated browser testing
- nightwatchJS scripts 
- examples of writing tests for custom functionality

or can do extended 30mins talk with @jannakha with addition of
- real life production examples
- headless browser setup for Linux
- alternative browser testing framework

**Comment by iamkevinv** [comment]
Nice. We have added this to our stack at work too, so i'd really like to see someone talking about it. I don't mind if you want a group presentation that's a bit longer... Could have you both up first so we can have the 30-40 min slot :) Just let me know. Hows September looking?

**Comment by iamkevinv** [comment]
Hiya - just triple checking you'll be there to present for sept?

**Comment by VladimirAus** [comment]
Yep @iamkevinv, September is looking good. 30 minutes should be plenty of time.

**Comment by iamkevinv** [comment]
I feel you could attach any links to your presentation resources or things people should check out - please do

**Comment by iamkevinv** [comment]
Thanks again for the presentation @VladimirAus ... if you have some links to the talk or interesting things to check out... feel free to link them here :) - I'm cleaning up so i'll close this issue but you can still add to it.
