### ISSUE TITLE
Proposal: Chat Bots

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#149]
My team did a facebook messenger bot for GovHack and it was super easy and pretty powerful. 

Anyone interested in a simple talk on how to make them and what they can do?

I might even throw in slack bots too.

**Comment by iamkevinv** [comment]
I'm assuming you're good to go for this one…

**Comment by garrows** [comment]
Well I only got the 1 👍 so I thought it wasn't a very popular topic. Happy to drop it or do a really short talk.

**Comment by iamkevinv** [comment]
People generally don't upboat much here. You should do the things!

**Comment by iamkevinv** [comment]
Thanks dude - can you add links or resources for the talk here?

**Comment by iamkevinv** [comment]
@garrows if you have links for peoples... feel free to add. I have to close this issue now. Thanks!

**Comment by garrows** [comment]
My slides http://slides.com/glenarrowsmith/chat-bots#/
and the easy to follow facebook guide https://developers.facebook.com/docs/messenger-platform/guides/quick-start
