### ISSUE TITLE
Intro to ember and ember cli

### ISSUE THREAD

**Issue by ridget** [BrisJS/meetups#15]
I've been starting down this road recently and would love to give my first js talk on the subject.

**Comment by kevdesign** [comment]
If you have any cool resources you can link and share onto this issue @ridget - i'd be happy to add the right label so people can refer back to this :) thanks!

**Comment by ridget** [comment]
Sure thing:

* [Ember Guides](http://emberjs.com/guides/) honestly the documentation for Ember is pretty fantastic
* [Ember CLI - use this tool, do not pass go, do not collect 200 bugs](http://www.ember-cli.com)


Useful blogs:

* [Evil Trout has a bunch of posts and small ember screencasts](http://eviltrout.com)
* [Ember zone is a more in depth series of posts looking at ember internals](http://ember.zone)

**Comment by kevdesign** [comment]
Thanks man! So awesome.
