### ISSUE TITLE
Talk - Building React apps, components and libraries with a *little* bit of configuration

### ISSUE THREAD

**Issue by insin** [BrisJS/meetups#150]
I can give a talk about using [nwb](https://github.com/insin/nwb) to develop React apps, components and libraries.
---

For React apps, it starts out as a zero-config single `devDependency`, with a hot-reloading development server, default testing setup with Karma, Mocha and PhantomJS and production build with React-specific optimisations and deterministic filename hashing.

Command-line feature toggles and a single configuration file if you need more than what zero-config offers:
- Plugin modules which enable use of Sass, Less and Stylus preprocessors
- Tweaking commonly-used Webpack config like aliases, define expressions and `publicPath`
- Tweaking Webpack loader configuration to enable features like CSS Modules
- Configuring Karma to use your preferred testing framework and run in different browsers
- Escape hatches for merging any extra Webpack and Karma config in if you need them
- Handy development features
  - Automatic installation of modules from npm as you develop
  - Turning destructured imports into cherry-picked imports at transpile time

The features you can use in your apps without any config are compatible with [create-react-app](https://github.com/facebookincubator/create-react-app), so nwb is an alternative to ejecting out of create-react-app and having to manage all the configuration and devDependencies yourself because you want to make one little tweak.

You can run nwb's development build in your own Express server as middleware, which is how I use it for development at work.

You can also use its setup to run or build a React app without having to create a project for it, which is good for quick prototyping and playing about starting with a single `.js` file.
---

For React components/libraries, nwb implements a complete development, build and test setup extracted from having maintained multiple npm modules for React components and related npm modules (e.g. form utilities)

It supports:
- Developing against a live demo app
- Testing and code coverage
- Ready to run on Travis CI out of the box, with code coverage posted to coveralls and codecov
- ES5, ES6 modules and UMD builds for publishing to npm
- Wrapping of React component `propTypes` so they'll be stripped from the production build in apps which use them
- Preconfigured to publish only what's needed to npm

**Comment by iamkevinv** [comment]
Wow - impressive - you're in! Haha

**Comment by iamkevinv** [comment]
@insin Confirmed?

**Comment by insin** [comment]
@iamkevinv Yup!

**Comment by iamkevinv** [comment]
@insin Urgent: How long do you need for your talk session. Normally a slot is 20 mins, but we can give you around 35ish to 40ish if we put you on first. Please let me know asap. Thanks.

**Comment by insin** [comment]
20 minutes is fine.

**Comment by iamkevinv** [comment]
Was great! If you can share links and resources here for your presentation that would rock

**Comment by iamkevinv** [comment]
Hi again @insin - if you have anything like talk slides or extra resources you'd like to link, feel free to add it here. I'm just cleaning up so this issue will get closed. Welcome to add more even though i closed it.
