### ISSUE TITLE
JS13K overview

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#152]
There's a few folks here doing [JS13K](http://js13kgames.com), I reckon we could fill an October slot with some show & tell style talks.

Peeps I know are entering this year:
- @ashkyd (hey, it's me!)
- @garrows 
- @korynunn
- your name here?

Leave a mention in the comments if you're taking part and I'll add your name to the list.

**Comment by garrows** [comment]
I'm in. 
@korynunn should demo his game too as an honorary JS13k entrant.

**Comment by KoryNunn** [comment]
JS130k

**Comment by iamkevinv** [comment]
Lock you gents in with a 20 min session?

**Comment by KoryNunn** [comment]
Yep. Completely not js13k but still a game so..

**Comment by AshKyd** [comment]
Yeah, I ain't got much to show but I'll take 5 mins and show it.

**Comment by iamkevinv** [comment]
Well you each can talk for 6.6666 mins i'm sure.

**Comment by iamkevinv** [comment]
@AshKyd @KoryNunn @garrows - link your game things here :)

**Comment by KoryNunn** [comment]
Mine is unlinkable sorry, maybe one day.

**Comment by garrows** [comment]
https://github.com/garrows/js13k-2016
