### ISSUE TITLE
Talk - Serverless Architectures

### ISSUE THREAD

**Issue by johncmckim** [BrisJS/meetups#153]
I attended the September Meetup last night and really enjoyed it. A couple of people I chatted to suggested the fun project I've been working on recently might be a good topic for a talk.

I've been building a Serverless garden monitoring system. It uses React, GraphQL, Auth0, Firebase Hosting, AWS (IoT Hub, Lambda, DynamoDB + more) together to create a web dashboard and notification system for my garden.

The talk would be on Serverless Architectures in general. It would basically cover [this blog post of mine](https://serverless.zone/serverless-architectures-9e23af71097a) in more detail. Depending on time, I could then dive deeper into one area of the system i.e. the React + GraphQL dashboard on Lambda.

**Comment by tomtomau** [comment]
That's something I'd definitely be interested in seeing - I've recently started playing around with serverless (which I see you've contributed to), so would be keen to see some how you achieve certain things.

**Comment by johncmckim** [comment]
@tomtomau if you have specific things you want to know about let me know.

I was thinking that if I do a demo I'd look at the Serverless framework (version 1.0.0). I would go over the `serverless.yml` config and demo a deployment.

**Comment by iamkevinv** [comment]
This is great… lock you in for the next one? Do you want a 20 or 40 min slot? 5 min usually on top of each to deal with questions.

**Comment by johncmckim** [comment]
I can do the next one. The 3rd of October?

The 40 minute slot would be good. I'm doing a talk in Sydney on the same topic which is a 40 minute slot.

**Comment by johncmckim** [comment]
Noticed you changed the dates. I can do that date too.

**Comment by iamkevinv** [comment]
Keen eye! Thanks for the confirmation :) Looking forward to it.

**Comment by johncmckim** [comment]
@iamkevinv is there a way I can contact you about this presentation outside of Github? Email? Want to organise a few things for the presentation.

**Comment by iamkevinv** [comment]
Totally. me@kevinv.org

**Comment by johncmckim** [comment]
Thanks again for having me.

I have uploaded my slides to my website - [BrisJS Oct 2016](https://johncmckim.me/presentation/2016/10/10/brisjs-serverless-garden). You can view the slides at that URL or get a PDF copy.
