### ISSUE TITLE
Talk: IoT for slackers

### ISSUE THREAD

**Issue by unixbigot** [BrisJS/meetups#154]
Following on from the recent talk on Chat Bots, I have a presentation I'm preparing for a conference that I could preview at BrisJS - how to connect physical devices running NodeMCU (which is Not Javascript, but a Lua environment heavily influenced by NodeJS) to Slack teamware via the Node-RED javascript flow-based programming environment.

**Comment by iamkevinv** [comment]
Oh sounds like this would follow on from the node red talk well

**Comment by iamkevinv** [comment]
Hi @unixbigot - all ready to go to present your venerable part 2 of the IoT and node-red series? ;-) 
Would love to see this one for monday - 20 minutes or 40 minutes?

**Comment by unixbigot** [comment]
@iamkevinv the version I did at Yow Connected ran 45 mins, but had a lot of intro material (basically rationale for why I chose the platforms I did).   I'm sure I can trim it to 30 with space for questions.   20's not out of the question if I focus on just the JS parts.   But longer's easier.

**Comment by iamkevinv** [comment]
Okay cool. 20 mins + questions, usually becomes 30 minute per speaker anyway. Don't trim down too much - and yes, you're allowed to rely on the fact that a cross section of our audience will have seen your talk last month to cut down a bunch of intro. Sounds like everything will be great.

**Comment by iamkevinv** [comment]
Don't stress too hard... you can take a bit longer to ensure you present things properly! We're not going to cut you off at the knees!

**Comment by unixbigot** [comment]
Slides from my presentation are here: http://christopher.biggs.id.au/   (See also slides for the longer version presented at YOW Connected in Oct)

Info on where to get featured hardware here: http://blog.unixbigot.id.au/2016/09/iot-for-absolute-beginners.html

**Comment by iamkevinv** [comment]
Thanks again :) marking as done and shared
