### ISSUE TITLE
Talk - Javascript rules my life (intro to Node-RED)

### ISSUE THREAD

**Issue by unixbigot** [BrisJS/meetups#155]
I use the Node-RED system (which is a visual programming tool written in NodeJS) to pull together a lot of information at home and work.   With Node-RED, Javascript is the glue that can bring together a huge number of other systems into one information flow.

At home, I can unlock my front door using my phone, monitor the environment, and control lights and other stuff.

At work, I can pull system performance information from databases and logs, monitor status from a smartphone, and receive alerts if things are out of whack.

**Comment by demsey2** [comment]
just watched a video on Node-RED website, this looks awesome

**Comment by iamkevinv** [comment]
Happy to join the line up for oct? 20 mins with 5 min questions?
I see you have two talks volunteered (#154) - do you mind if we space them out over the two next monthly sessions?

**Comment by unixbigot** [comment]
Definitely prefer to space out the talks.   #154 is a cut down highlights of the presentation I'm doing at Yow Connected in oct.    This proposal (Javascript rules my life) is a wider survey of what you can do with Node-RED.   I'm fine to do this one in oct, and  the other whenever it fits.

**Comment by iamkevinv** [comment]
Fantastic. We've had to push it back a week because of a public holiday landing on the monday. Hope this is still okay. I'll add the confirmation label.

**Comment by unixbigot** [comment]
So this would be Oct 10th?  That's fine (better, even)

**Comment by iamkevinv** [comment]
YES! :D

**Comment by iamkevinv** [comment]
Hi @unixbigot - we'll close this one soon - if you have resources to give to the community from your talk, please feel free to link them here! Thanks

**Comment by unixbigot** [comment]
Slides are on my website http://christopher.biggs.id.au/
