### ISSUE TITLE
Wanted: Javascript Developer (() => experience.match(/node|angular[\d]/g))()

### ISSUE THREAD

**Issue by csinge** [BrisJS/meetups#157]
Sorry, got a little trigger happy with the save. 

DWS is looking for senior javascript/front end developers, pay is great and we get to work on some really cool projects, with a lot of bleeding edge technologies.  If your interested call me on 0468336808 or email me at cameron.singe@dws.com.au

Cheers
Cameron

**Comment by iamkevinv** [comment]
All sorted now @csinge ?

**Comment by csinge** [comment]
this.close();
