### ISSUE TITLE
Talk: Techniques and practices for testing Angular 2

### ISSUE THREAD

**Issue by duncanhunter** [BrisJS/meetups#159]
Writing frontend tests has always been hard, let us show you how to make testing easier in your Angular 2 applications.
From unit testing components and services to end-to-end testing your entire application, we will give you tips and techniques for testing in Angular 2.

**Comment by iamkevinv** [comment]
Would love to confirm you for this next meetup @duncanhunter - Are you free to do a 40 or 20 minute session next monday? Thanks!

**Comment by duncanhunter** [comment]
Hi

I'm free Monday to do a 20-40min talk on testing. Look forward to it.

**Comment by iamkevinv** [comment]
Which would you like... 20? or 40? :-) I divide the night into time slots for each person, and that determine the running order. Hence asking for specifics. After my usual intro, there's usually one 40 min up front, with a 20-30 min intermission for networking pizza and drinks, and two 20 min sessions following.

**Comment by duncanhunter** [comment]
lets go for 40min

**Comment by iamkevinv** [comment]
Thanks again :) Could you share your slides @duncanhunter ?

**Comment by duncanhunter** [comment]
Thanks for having me :)

here is a link to the slides https://docs.google.com/presentation/d/19tJt0UQY2fJ5URqrL6VLiT9eYVdO4uoUUNPG9Vh8SAw/edit#slide=id.p14
