### ISSUE TITLE
PM2 for node server

### ISSUE THREAD

**Issue by shotlom** [BrisJS/meetups#16]
I'd like to hear experience of using node server in production with PM2 or forever

PM2 [https://www.npmjs.org/package/pm2] 
Forever [https://www.npmjs.org/package/forever]

**Comment by iamkevinv** [comment]
Did anyone still feel keen for this?

**Comment by shotlom** [comment]
Would like to see what Glen does.



On Mon, Jun 29, 2015 at 10:07 PM, Kevin Vanderbeken <
notifications@github.com> wrote:

> Did anyone still feel keen for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/16#issuecomment-116629786>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by garrows** [comment]
@iamkevinv thought we've done this one. @MauriceButler talked about PM2 and I talked about noleg-stack https://github.com/garrows/noleg-stack

**Comment by iamkevinv** [comment]
@garrows I do remember that. Closed then. A new one can get opened for further questions.
