### ISSUE TITLE
Event: The Angular Superpowers Tour

### ISSUE THREAD

**Issue by duncanhunter** [BrisJS/meetups#161]
https://www.ssw.com.au/ssw/Events/Training/Angular-Superpowers-Tour.aspx
Brisbane
FRI, 18TH NOV
Price $49

This one-day workshop brings developers up-to-speed on the new features and benefits of using Angular 2 to build awesome web applications.

Everything has changed! Angular 2 and modern web best practices involve massive changes to how we build modern web applications.

At SSW we have already gone through the hard work of implementing these new and exciting technologies in our projects for everything from small start-ups to enterprises and government agencies.

Come watch our best Angular 2 devs build an Angular 2 application from scratch and take it all the way to an enterprise application using all the best tools and practices we use.

Don't waste weeks learning Angular 2, the Angular CLI, RxJS, TypeScript, ngrx, NPM, WebPack, end to end testing and unit testing. Get your head around all the core concepts and get jump started in just one day.

**Comment by iamkevinv** [comment]
We'll mention this at the meetup
