### ISSUE TITLE
Wanted: JavaScript dev (React, Redux, TypeScript, all the things)

### ISSUE THREAD

**Issue by AdamPD** [BrisJS/meetups#162]
Hey guys,

We're [PharmaData](http://pharmadata.io).  We're looking for a kickass full stack dev, with a focus on a thick front end client using React.  It's all an in-house product that is growing globally.  We focus a lot on building a great culture and making it a fun place to work.

Our front end stack is ...
- React, Redux, redux-thunk (now moving to redux-saga), gulp
- TypeScript (we really like it!)
- NW.js for desktop app
- Native iOS app written in Swift (Swift is awesome too)

Our back end stack is ...
- .NET - Nancy, Autofac
- SQL Server 2016 (we process a lot of data, but might consider a move to Hadoopy stuff)

Hit me up if you're interested!

**Comment by zhaoshengjun** [comment]
Hi @AdamPD , I am interested! How to proceed?

**Comment by lukekhamilton** [comment]
Hi @AdamPD, are you guys open to remote dev's? If so love to have a chat.

**Comment by AdamPD** [comment]
Hey @zhaoshengjun and @lukekhamilton - can you shoot me an email on adam@pharmadata.io and we can chat?

**Comment by lukekhamilton** [comment]
Hey @AdamPD, have emailed you. I'm currently o/s so I can either call you or we can skype?

**Comment by iamkevinv** [comment]
Hey @AdamPD - Still needed? Otherwise feel free to close :)

**Comment by lukekhamilton** [comment]
I don't think so as he never got back to me about it. #slack
