### ISSUE TITLE
Startup projects from a tech perspective

### ISSUE THREAD

**Issue by ChrisGrigg** [BrisJS/meetups#164]
Recently I built a simple food diary, web app where the user take pictures of their food. This was done with the tech in the title. I can present my journey. I'm aware that there are 2 talks relating to Angular 2 on Ionic for Nov so not sure this is going to be different enough.

**Comment by iamkevinv** [comment]
HI @ChrisGrigg... Would certainly still like you to present your talk... Okay for Mon Dec 12? I'm going to announce the lineup ASAP.

**Comment by iamkevinv** [comment]
We will have #165 on in dec too so it would probably complement that well.

**Comment by iamkevinv** [comment]
I'm doing the announcements today - is this confirmed? else i have someone waiting to jump in... was it for a 20 min or 40 min slot?

**Comment by iamkevinv** [comment]
Sorry to do this @ChrisGrigg but i couldn't confirm you for the announcement so i'll have to pop you into the next meetup instead. The project sounds great so i'd really encourage you to present it at the first BrisJS of the year... currently scheduled for first monday of Feb. I'll move the project milestone to suit.

**Comment by ChrisGrigg** [comment]
Hi @iamkevinv no problem sorry for my delayed reply. Feb is fine :) I may change the title to something like "My startup journey - from front end to full stack developer" as there are lots of pure tech talks on Angular 2 already.

**Comment by iamkevinv** [comment]
Hi @ChrisGrigg - Can i still confirm you for next monday's BrisJS? I'd like to put the announcement email out since we're really running late with it. Would you require a 40min or 20 min slot?

**Comment by ChrisGrigg** [comment]
Hi Kevin, yep happy to do it. Whilst doing the presentation I've thought
this title isn't suitable so have changed it quite alot to talk more just
about experiences of starting a startup in the ideation phase as a tech
person. A 20 min slot will be fine. I'll confirm the title tonight. Thanks

**Comment by ChrisGrigg** [comment]
Hi the title will now be "Startup projects from a tech perspective". Hope that's still suitable for BrisJS!

**Comment by iamkevinv** [comment]
Any resources you could link here would be appreciated :-)
