### ISSUE TITLE
Talk: Angular 2 Routing from 0 to Hero

### ISSUE THREAD

**Issue by thiagospassos** [BrisJS/meetups#165]
- setting up routing from scratch in an Angular 2 app
- navigating through routes
- child routes
- nested outlets
- parallel routes /  named outlets
- lazy loading routes
- securing routes

**Comment by iamkevinv** [comment]
Lets do it @thiagospassos! - We would certainly still like you to present your talk... Okay for Mon Dec 12? I'm going to announce the lineup ASAP.

**Comment by thiagospassos** [comment]
Hey @iamkevinv, I'm in.

**Comment by thiagospassos** [comment]
Hey @iamkevinv just so I can prepare for the talk, what's the length of it? cheers

**Comment by iamkevinv** [comment]
I'm doing the announcements today, there's been a lot of interest for dec speaking... I was actually going to ask you that question...was it for a 20 min or 40 min slot?

**Comment by thiagospassos** [comment]
I can do either, @iamkevinv, but to be able to deliver the whole thing it would need to be the 40min slot.

**Comment by iamkevinv** [comment]
Okay lets get you into almost 40 then... we're packing in the talks this monday, but by putting you up first before pizza and intermission, we should be able to give you about 30ish to speak, and breathing room for 10 mins of questions. Sound good?

**Comment by thiagospassos** [comment]
@iamkevinv sounds great, looking forward for it :)

**Comment by iamkevinv** [comment]
Hey @thiagospassos - if you have any links to share here... please do :)

**Comment by thiagospassos** [comment]
Here's the GitHub link with the source code of the demo: bit.ly/ng2-routing-brisjs

**Comment by iamkevinv** [comment]
Thanks!
