### ISSUE TITLE
Wanted: JS Developer

### ISSUE THREAD

**Issue by henrycjc** [BrisJS/meetups#167]
*Dr Rob’s Experimentary* are looking for a full-stack JS developer with good experience developing SPAs in HTML/CSS/JS and backend HTTP APIs who is interested in part time work (5-10 hours per week) or a short-term contract 1-2 months. This is basically a green-fields project where the front-end and back-end exist only as a prototype which will now be rewritten “for real” as a top-quality, maintainable solution for the medium to long term.

You will be working as the co-lead-developer with the developer who has produced the prototype and has been investigating the “production ready” version (that's me), so solid experience will full-stack is a must. While there are absolutely no preconceived ideas on the technical stack of either the back-end or the front-end (I am open to anything), I have experience with AngularJS 1.x and Python/Flask so going in that direction would work or the ability to set and explain another technical direction and mentor would be fine too.

The business domain is in the science / education / SaaS arena with a number of investors already on-board and a library of interactive content already prepared (100s of hours of footage) / being worked on so they are keen to get someone else on the team asap to work towards an MVP for a limited release in the new year.

If you're interested please drop me an email: henry.ponco@gmail.com

**Comment by jwulf** [comment]
@henrycjc is this still open?

**Comment by henrycjc** [comment]
@jwulf Closing off now.
