### ISSUE TITLE
Talk proposal: Control your home with HomeBridge and your iPhone

### ISSUE THREAD

**Issue by unixbigot** [BrisJS/meetups#168]
Given that you have

   * Existing IoT devices (that aren't directly supported by apple HomeKit, almost nothing is so far)
   * A computer that runs NodeJS (eg a Raspberry Pi)
   * An iPhone or apple TV

How do you get to "Hey Siri, turn down the damn television"?

Well, once you've done 'npm install -g homebridge' and then npm-ized the right plugins, it's not much harder than this:

```
	{
            "accessory": "TV",
            "name": "Damn Television",
            "description": "Panasonic Smart TV in Living Room",
            "ip": "192.168.1.103"
	},
```

In 15 minutes I can talk you through what you need to know and have.

**Comment by iamkevinv** [comment]
Nice. I did this recently and it was pretty easy. Would actually be good to know how to get into writing these plugins and getting new hardware controlled :)

**Comment by iamkevinv** [comment]
@unixbigot If you're happy to do this talk Mon Dec 12? I'm going to announce the lineup ASAP.

**Comment by unixbigot** [comment]
I'm up for it @iamkevinv

**Comment by iamkevinv** [comment]
I'm doing the announcements today, there's been a lot of interest for dec speaking... was it for a 20 min or 40 min slot?

**Comment by unixbigot** [comment]
20min please

**Comment by iamkevinv** [comment]
Hey @unixbigot - if you have any links to share here... please do :)

**Comment by unixbigot** [comment]
Slides are here:  http://christopher.biggs.id.au   and see also my recent presentation on IoT security
on the same page

Detailed links:
  *  slides http://christopher.biggs.id.au/presentations/homebridge/
  * iot security slides http://christopher.biggs.id.au/presentations/iot-scary/index.html
  * iot security video http://youtu.be/qKJz4aPubNI

Finally my IoT series on Medium will soon have a post about HomeBridge (any day now... honest)

  * https://medium.com/@unixbigot/latest

**Comment by iamkevinv** [comment]
Thanks!!
