### ISSUE TITLE
Talk: Machine Vision / AI in Electron

### ISSUE THREAD

**Issue by matt-way** [BrisJS/meetups#169]
Hey all,

So we've been using electron to do all our AI experiments this year (working on new machine vision algorithms). Would be keen to share a few little things, explain the state of machine vision, find out if anyone else is interested in the AI space.

**Comment by garrows** [comment]
@matt-way I'm very interested 💯

**Comment by iamkevinv** [comment]
This is very cool... but i think we might be booked solid for next monday... i'm doing the announcements today... was it for a 20 min or 40 min slot?

**Comment by matt-way** [comment]
I could do as short or as long as the space permits.

**Comment by iamkevinv** [comment]
okay i'm going to try and squeeze in 4 talks this month :)

**Comment by iamkevinv** [comment]
Lets get you our usual 15 talk + 5min of questions aka the 20 min slot - cool?

**Comment by matt-way** [comment]
Yeah, that's fine. Thanks.

**Comment by iamkevinv** [comment]
Hey @matt-way - if you have any links to share here... please do :)
