### ISSUE TITLE
Talk: Building an Alexa Skill with Node + Lambda

### ISSUE THREAD

**Issue by johncmckim** [BrisJS/meetups#171]
At AWS re:Invent this year we entered the re:Invent Alexa skill contest. We built a version of chaos monkey that allows you to start and stop servers on the Amazon Echo. It's all up on [hackseter.io](https://www.hackster.io/a-cloud-guru/alexa-chaos-monkey-280d79).

Building an Alexa skill is actually pretty easy to do. I was thinking I could walk through building a skill that allowed you to ask Alexa when the next BrisJS meetup was on using the [meetup.com api](https://secure.meetup.com/meetup_api/console/?path=/:urlname/events). This would include

* Configuring a skill on [developers.amazon.com](https://developer.amazon.com/)
* Creating a Lambda function with the Alexa skill boiler plate
* Coding an intent to that responds with the date for the next meetup

**Comment by iamkevinv** [comment]
This would be awesome @johncmckim!
Are you okay to present this at the meetup this coming monday? Please let me know if you need a 20min or a 40 min slot.

**Comment by johncmckim** [comment]
I'm going to be in Melbourne this Monday unfortunately. But I'd be happy to present at the following Meetup.

**Comment by iamkevinv** [comment]
Drat! Okay mate, thanks heaps for letting me know so quickly too. 👍 
Moving you to march.

**Comment by iamkevinv** [comment]
We're you still interested in presenting next week? Would this be a 20min or 40min slot?

**Comment by johncmckim** [comment]
Yep. Let's do it. Happy to do either 20 or 40 mins. If I've got 40 minutes I can go into some code and examples which would be good.

**Comment by iamkevinv** [comment]
Okay we can give you that slot since nobody claimed it :) 40 minutes, up first before pizza.

**Comment by johncmckim** [comment]
Perfect. Looking forward to it.

**Comment by fud** [comment]
@johncmckim what was that VS Code theme. I was also curious.

**Comment by johncmckim** [comment]
@fud @jwulf here you go. Don't ask me how to install them though I can't remember hahah.

```
"workbench.colorTheme": "Atom One Dark",
"workbench.iconTheme": "vscode-icons"
```

**Comment by iamkevinv** [comment]
Any links you can share @johncmckim would be great.
