### ISSUE TITLE
Building internationalized applications using React, Redux, TypeScript and Electron

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#172]
For the first week of January 2017 I didn't sleep, and did 267 commits to the new Magikcraft spellbook. 

In a whirlwind week we converted it from Webpack to Browserify, wrote a custom module loader for Microsoft's Monaco editor, and contributed four patches to upstream packages. 

In this talk I'll be sharing lessons from the journey, including how we had it localised into nine languages within half an hour by building it with internationalisation baked in and using IBM's Globalization Pipeline.

**Comment by iamkevinv** [comment]
LETS DO THIS @jwulf :-D 
Good for the next monday meetup?
Do you need a 20 min or 40 minute slot?

**Comment by iamkevinv** [comment]
@jwulf has let me know:

Magikcraft devs Tim Marwick and Ian Daniel (and possibly Chris Briggs as well) can tag team it. They can tell you more about exactly what they are going to cover, but it's going to be something along these lines:

An overview of our React / Redux / TypeScript / Websocket stack and lessons learned putting it together; some discussion around "To go Electron or not, what's involved, and when does it make sense?" aka "Why we did it and then undid it"; and the WORLD PREMIERE demo of the "Zombie Apocalypse Leaderboard". 

The Zombie Apocalypse Leaderboard uses a serverless backend, and has been built for Magikcraft's attempt at the highly-competitive Guinness World Record for "The most zombies killed by JavaScript lightning in a ten-minute period" - to be held at the opening of Microsoft Ignite on the Gold Coast on February 13.

**Comment by iamkevinv** [comment]
Any you links you have to share would be great
