### ISSUE TITLE
Talk: Design Patterns (OOP) and Scaling in JS

### ISSUE THREAD

**Issue by 99M8** [BrisJS/meetups#174]
* Flyweight Design Pattern (DP).
* Proxy DP.
* Other DPs. 
* Performance of different DPs.
* "Best" DP for scalability.

**Comment by iamkevinv** [comment]
Sounds interesting! Can you make it for the first Monday in march BrisJS? Would you need 20 min or 40 min to present?

**Comment by iamkevinv** [comment]
@ElizavetaKonovalova can you confirm for the next meetup? 20 min talk time okay?

**Comment by iamkevinv** [comment]
@ElizavetaKonovalova - We're desperately late to confirm the lineup of speakers to the audience so i need an answer ASAP, else will need to move you to next month. Thanks!

**Comment by iamkevinv** [comment]
Sorry @ElizavetaKonovalova since i can't get a confirm at this point - i need to bump this talk to next month so we can get others in and make the announcement. I look forward to your presentation then :)

**Comment by iamkevinv** [comment]
I just read your answer on the RSVP... i'm assuming now that this is a talk request, rather than volunteering a talk as i thought it was?

**Comment by iamkevinv** [comment]
If you're volunteering a talk @ElizavetaKonovalova - Just to get scheduling right, we need to know a few things...

1. Are you available for:
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by iamkevinv** [comment]
Hi! Kevin again - Just trying to get in touch to see if we can organise your talk for the meetups. Let me know if you get these messages? Thanks :)

**Comment by iamkevinv** [comment]
ping @ElizavetaKonovalova :)

**Comment by 99M8** [comment]
Hello, @iamkevinv. Very sorry for the 1-year late reply! ~_~
I will close the current issue and once I have time for the talk open a new one.
Sorry for the silence!

**Comment by iamkevinv** [comment]
No problem! Glad you got in touch. Happy to have you there sometime soon 😀
