### ISSUE TITLE
Scaffolding JS stacks using Yeoman, Cloud 66, Docker and push it to Cloud

### ISSUE THREAD

**Issue by samousavih** [BrisJS/meetups#175]
This is a talk about how fast we can build up most JS stacks using Yeoman, utilise Docker, choose the cloud provider we like and orchestrate our containers using Cloud 66.

**Comment by iamkevinv** [comment]
Cool talk idea, Can you make it for the first Monday in march BrisJS? Would you need 20 min or 40 min to present?

**Comment by samousavih** [comment]
Hey Kevin
It should be OK for a 20 minutes talk,
If you have some templates for the slides please send that through, or any content that might be helpful.

**Comment by iamkevinv** [comment]
@samousavih Can you confirm for the next meetup? 20 min okay?

**Comment by iamkevinv** [comment]
@samousavih - We're desperately late to confirm the lineup of speakers to the audience so i need an answer ASAP, else will need to move you to next month. Thanks!

**Comment by iamkevinv** [comment]
Sorry @samousavih since i can't get a confirm at this point - i need to bump this talk to next month so we can get others in and make the announcement. I look forward to your presentation then :-)

**Comment by iamkevinv** [comment]
We'd love to hear your talk! Just to get scheduling right, we need to know a few things...

1. Are you available to present at the May meetup?
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by iamkevinv** [comment]
Hi @samousavih - was trying to get your info about talk availability. If you're getting this... please let me know :-) - Kev.

**Comment by samousavih** [comment]
Hi @iamkevinv , sorry for my late response. I am being lazy these days, I changed the topic a little bit , and will prepare that for June 5th, I think 20 mins should be OK.
Thanks @iamkevinv and sorry again

**Comment by iamkevinv** [comment]
Sorry @samousavih looks like this time we didn't see your reply. June has obviously passed now. Are you still able to present this? I Feel like it's a bit late to try and rope you in for this so last minute, so can you do our August meetup?

**Comment by samousavih** [comment]
Hi @iamkevinv,
Yes I can do the August meetup, if there is still a free room.

**Comment by AshKyd** [comment]
That's great news @samousavih. Just to confirm, this is a 20 minute timeslot on on August 14th (the date was changed due to CampJS).

One more question, I was hoping you could provide your Twitter handle (if available) so we can link from the meetup, website etc. Thanks!

Also FYI [information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by samousavih** [comment]
That is alright, I am @samousavih on Twitter.
Thanks

**Comment by AshKyd** [comment]
Thanks a bunch for the talk, was good to go through and get a handle of. I know you didn't have too many slides, but do you have any resources you'd like to share with the meetup?

**Comment by samousavih** [comment]
Hey @AshKyd ,
Not much actually, but here are the links to a few websites and stuff to read.
Hope that helps.

https://www.cloud66.com/
http://yeoman.io/
https://dzone.com/articles/getting-started-with-microservices-on-docker-and-c

Oh wait, here is the Dijkstra's quote I referred to during the talk ;)

https://effectivesoftwaredesign.com/2015/10/22/on-the-real-danger-of-quick-and-dirty-programming/

Cheers,
Amin
