### ISSUE TITLE
Talk: Introduction to Angular 2

### ISSUE THREAD

**Issue by Blizzard7** [BrisJS/meetups#176]
This is a talk about introducing people to Angular 2. The core concepts of Angular 2 ( module, component, service, router and dependency injection) will be introduced and demonstrated via a simple demo app.

**Comment by iamkevinv** [comment]
Sounds good, but we might be closed for the March Event... have popped you into April. Would you be available for either depending on cancellations?

**Comment by Blizzard7** [comment]
Hi Kevin,
April sounds good to me.  Sorry, I won't be able to fill in March in case of cancellations.

**Comment by iamkevinv** [comment]
Are you still confirmed for the April 3rd Event?
Are you OK with one of the two 20 minute presentation blocks?

Let me know anything else that might be required. Need this confirmed ASAP

Thanks!

**Comment by Blizzard7** [comment]
Sorry Kevin. I can't make it this month.

**Comment by iamkevinv** [comment]
No problem... i'll move you over to May for re-scheduling.

**Comment by iamkevinv** [comment]
Can you confirm talk length in advance?

**Comment by Blizzard7** [comment]
I will be able to do that in 20 minutes.

**Comment by Blizzard7** [comment]
Too busy with life at the moment. Not sure when I will be able to do that.
