### ISSUE TITLE
Talk: 'Serverless' Express

### ISSUE THREAD

**Issue by AnnaGerber** [BrisJS/meetups#177]
The aws-serverless-express library enables you to build web services with Node.js and Express and run them as AWS Lambda functions delivered through the Amazon API Gateway. This talk will step through how to use this library to develop a simple API backed by DyamoDB, and how to deploy it to AWS via CloudFormation.

**Comment by samousavih** [comment]
Ah cool, would be interested in that topic

**Comment by iamkevinv** [comment]
20 Mins @AnnaGerber ?

**Comment by AnnaGerber** [comment]
Yep, 20 mins is fine

**Comment by iamkevinv** [comment]
You're locked in.

**Comment by iamkevinv** [comment]
Any links you can share @AnnaGerber would be great.

**Comment by AnnaGerber** [comment]
Slides are here: https://www.slideshare.net/annagerber/serverless-express
