### ISSUE TITLE
Talk: Less is more. Writing software the unpopular way.

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#178]
I'd like to talk about the other way to write software, the one where you don't use frameworks, build processes, or install a million libraries.

There are pro's n' con's to both, and I think they would be good to discuss.

**Comment by iamkevinv** [comment]
Target month? Time length?

**Comment by iamkevinv** [comment]
Kory said March or following, and standard 20min block.

**Comment by iamkevinv** [comment]
You're locked in.

**Comment by iamkevinv** [comment]
Any links you can share @KoryNunn would be great.

**Comment by KoryNunn** [comment]
Sure.

"Slides": korynunn.github.io/jfwc
We side-tracked into Promises: https://github.com/korynunn/righto-v-promise
