### ISSUE TITLE
Talk: Promises for beginners

### ISSUE THREAD

**Issue by liammclennan** [BrisJS/meetups#179]
People are using promises, mostly successfully, which is good, but sometimes we may not entirely understand what they are, how they work, or how we should use them. 

I'd like to explore promises in detail from first principles, focusing on how to use them successfully and some anti-patterns to avoid.

**Comment by iamkevinv** [comment]
Sounds great :) Thanks for volunteering.

**Comment by iamkevinv** [comment]
Is this a 20 minute long or 40 minute long session?

**Comment by jwulf** [comment]
Can the talk also cover the intersection of Promises and righto [0]?

[0] https://github.com/KoryNunn/righto

**Comment by iamkevinv** [comment]
Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) April 3rd
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by iamkevinv** [comment]
Oops! the 40 min April slot is now gone. Okay with a 20?

**Comment by iamkevinv** [comment]
We're pretty swamped with volunteer (which is SO great!), so i have to move you over to the May meetup.

**Comment by liammclennan** [comment]
Could only do this one in May. 20 mins is cool.

**Comment by liammclennan** [comment]
@iamkevinv can you please take me off the schedule for May? Seems like there is plenty of content around.

**Comment by iamkevinv** [comment]
Sure @liammclennan...
Since the date moved to May 8th... are you available for June 5th? Would you like to be locked in for that? - Thanks!

**Comment by liammclennan** [comment]
No thanks. I'm going to take a break for a bit.

**Comment by iamkevinv** [comment]
Hello... this is my usual follow up before announcing on meetup. Above you were saying no to the June 5th meetup.... is that still the case? I'll pre-emptively move you to july but feel free to correct me.

**Comment by iamkevinv** [comment]
Hey @liammclennan - you keen to give this talk next week? I'm sure everyone else would be keen to hear it.

**Comment by liammclennan** [comment]
No thanks. Bit busy atm.

**Comment by AshKyd** [comment]
@liammclennan: hope things calm down for you at some point. :) Would the August meetup suit better?

**Comment by AshKyd** [comment]
@liammclennan Just putting together the September meetup and figured I'd touch base.

Will you available any time soon, or would you prefer if we tried to get someone else to do this one :)

**Comment by liammclennan** [comment]
Hi @AshKyd . Happy for someone else to do it.
