### ISSUE TITLE
Talk: State Mutation considered harmful: Pure Function Master Race (Functional Programming)

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#181]

**Comment by jwulf** [comment]
I could give this talk, but it would be titled: "State Mutation considered harmful: Functionally Pure Master Race."

**Comment by jwulf** [comment]
April 3?

**Comment by jwulf** [comment]
I can talk about Functional Programming versus Imperative and Objective. Benefits of Functional Programming, some patterns of functional programming in JavaScript, and drawbacks - with some examples of when to use functional and when to not use it.

**Comment by iamkevinv** [comment]
Hey @jwulf - yes i'm trying to work out who is most ready for April so if that's the one you're keen for i'll throw you into the hat. The synopsis sounds cool, but i'll probably have to shorten your title for the email hehe.

**Comment by jwulf** [comment]
Awesome, cool. Look forward to it.

**Comment by jwulf** [comment]
Functional programming is the One True Way(tm) to code - except when it's not. In this talk we'll look at functional programming in JavaScript, with some use cases and considerations. We're not going to do Monads and Endofunctors, grow a beard, and write a parser, but we will cover some practical use cases in JavaScript.

**Comment by iamkevinv** [comment]
Okay we already have seen you be very active here so we'll make sure to include you for April.

Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Thanks!

**Comment by jwulf** [comment]
Looks like Ash is doing the 40 min slot, so I'll take a 20 min slot

**Comment by AshKyd** [comment]
Thanks for the talk @jwulf, you do know how to please the crowd! I realise you don't have any slides, but do you have a link to any resources you wanted to share?

**Comment by iamkevinv** [comment]
@ping @jwulf - if you have slides/resources... please link them here and we'll add the label

**Comment by jwulf** [comment]
Me on Twitter: https://twitter.com/sitapati

Magikcraft: http://magikcraft.io/

JavaScript and FP: https://bethallchurch.github.io/JavaScript-and-Functional-Programming/

Immutable.js: https://facebook.github.io/immutable-js/

Ramda: http://ramdajs.com/

Array.forEach performance: https://jsperf.com/fast-array-foreach

Array.map performance: https://jsperf.com/for-versus-map

Brisbane Functional Programming Group: https://www.meetup.com/Brisbane-Functional-Programming-Group/?chapter_analytics_code=UA-24376892-1

Great book on Functional Programming in JavaScript: https://www.manning.com/books/functional-programming-in-javascript
