### ISSUE TITLE
Talk: Graphql with Relay.js

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#182]

**Comment by joshduck** [comment]
I worked with the Relay.js team for a while. I'd be happy to talk about that framework.

**Comment by iamkevinv** [comment]
@joshduck That would be cool mate... i see that it's not purely GraphQL (specifies a react ecosystem) but i think that would still help out a lot. Keep the focus on what GraphQL is about, but the added bonus of a library meshing well with react is handy for people using that indeed.

**Comment by iamkevinv** [comment]
We'd love to hear your talk! Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) April 3rd
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by iamkevinv** [comment]
We're pretty swamped with volunteer (which is SO great!), so i have to move you over to the May meetup.

**Comment by joshduck** [comment]
I'd like a 40 minute slot; I can give a good overview of GraphQL and how local storage of data works in Relay/other GraphQL frameworks. 

May 1st is a public holiday. Are you planning on bumping the meetup?

**Comment by iamkevinv** [comment]
Good catch! Yes the following Monday - I'll update everything to reflect that tomorrow

**Comment by iamkevinv** [comment]
Hey @joshduck,

Since the date moved now... are you available for either or both of:
- [ ] (a) May 8th
- [ ] (b) June 5th

Can i confirm you for either one if you're ready?

Thanks!

**Comment by joshduck** [comment]
Hi Kevin,

Yep, I'm ready. May 8th would work best for me.

Josh

**Comment by AshKyd** [comment]
Awesome talk, we appreciate the effort you put in to this one. You already shared your slides via Twitter so I'll close this one off as done. Thanks again!

https://www.dropbox.com/s/h78qzyibu6up0af/Exploring%20Relay%20-%20PDF.pdf?dl=0
