### ISSUE TITLE
Talk: Redux

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#184]

**Comment by liammclennan** [comment]
I can do this one as long as it is the same day as the promises one.

**Comment by deecewan** [comment]
I can do this one. Probably don't need promises to do it either, if you like.

**Comment by iamkevinv** [comment]
Well, if Liam is taken up with another one, we can spread it out a bit and give David a chance.
Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) April 3rd
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by deecewan** [comment]
i guess it depends on how much depth you want, and in what context.

I could probably get it done in twenty minutes.  May 1st would be better, i think.  Not much time left before the April 3rd event.

**Comment by iamkevinv** [comment]
Whatever you'd like :-) lets go with 20 min then, and re-schedule you with the rest in May. Thanks!

**Comment by iamkevinv** [comment]
Hey @deecewan,

Since the date moved... are you available for either or both of:
- [ ] (a) May 8th
- [ ] (b) June 5th

Thanks!

**Comment by deecewan** [comment]
June 5th would be much more preferable.

**Comment by iamkevinv** [comment]
Hello... this is my usual follow up before announcing on meetup. Are you okay to do this one for this next june 5th meetup ?

**Comment by iamkevinv** [comment]
Ha... i'll take those emoji as a yes. :)

**Comment by iamkevinv** [comment]
@deecewan - Resources to share? Thanks :)

**Comment by deecewan** [comment]
[Slides](https://docs.google.com/presentation/d/1udWdzKMu_Y2YI9_b8YfrZKlxmYdr_zgDpNMkNz0LdXY/edit?usp=sharing) are here. Warning, tho, for anyone looking at these later. I gave up toward the end and did a live code demo.

[The Redux Docs](http://redux.js.org/) are a *super* good place to look. Nice examples, and they dig a bit deeper.
[This video series](https://egghead.io/series/getting-started-with-redux)(free) is by the creator, and I found it pretty useful to wrap my head around things.
