### ISSUE TITLE
Talk: Introduction to React Native

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#185]

**Comment by MrCeleryman** [comment]
I did an introduction to React Native talk for the ReactJS meetup the other day, happy to update it or do another similar talk about React Native

**Comment by iamkevinv** [comment]
We'd love to hear your talk! Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) April 3rd
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by MrCeleryman** [comment]
Free both nights but would prefer the 1st of May if that is ok.
And I will only need a 20 min presentation block

**Comment by iamkevinv** [comment]
Great. I'll update the month milestone.

**Comment by MrCeleryman** [comment]
Just had a look at the Milestones and April looks pretty bare compared to May. If you are desperate fro speakers for the next meetup I can do it then If it is convenient

**Comment by AshKyd** [comment]
Hey @MrCeleryman, just wanted to confirm you're good to go for the 20 min talk on May 8th (the 1st is a public holiday so the meetup falls on the next Monday) :)

**Comment by MrCeleryman** [comment]
@AshKyd  Yep happy too if there is still a slot available (should only need a small one)

**Comment by iamkevinv** [comment]
HDMI :)

**Comment by iamkevinv** [comment]
Hey @MrCeleryman - What's you're name? :) i only see you here as 'Daniel' - need it for the BrisJS entry

**Comment by MrCeleryman** [comment]
Daniel Mitchell

**Comment by iamkevinv** [comment]
Awesome. I can't fix the email already sent but the Meetup page is up to date :)

**Comment by AshKyd** [comment]
Thanks @MrCeleryman. Really appreciate your talk, it was a fun intro to React Native. Couple of questions before we close this off:

1. Do you have your slides/code uploaded somewhere we could share
2. I'm guessing you don't, but to be sure do you have a Twitter handle we could link from the site?

**Comment by MrCeleryman** [comment]
Sure the presentation is https://prezi.com/view/jy37kuwouw9lNoNSE4UQ/
And the code i showed is from https://github.com/MrCeleryman/ParmyayMobile

And yea no twitter

**Comment by AshKyd** [comment]
Awesome, thanks for that. Will aim to let you know when the video is posted.
