### ISSUE TITLE
Talk: publishthis.email - The fastest way to create a website...by email

### ISSUE THREAD

**Issue by matt-way** [BrisJS/meetups#189]
We just released a really simple product that people seem interested in, and figured the stack might warrant a talk. We use SES->S3->Lambda->Dynamo to convert any email sent to a particular address into a webpage.

You can check it out [here](http://publishthis.email).

**Comment by iamkevinv** [comment]
We'd love to hear your talk! Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) April 3rd
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by iamkevinv** [comment]
We're pretty swamped with volunteers (which is SO great!), so i have to move you over to the May meetup.

**Comment by matt-way** [comment]
Cool, May is fine. I'm sure 20mins would be plenty (don't want to bore people).

**Comment by iamkevinv** [comment]
Hey @matt-way,

Since the date moved... are you available for either or both of:
- [ ] (a) May 8th
- [ ] (b) June 5th

Thanks!

**Comment by matt-way** [comment]
I might be interstate next week (I'll know over the next day or so), so let's just say June 5th to be safe. Thanks.

**Comment by iamkevinv** [comment]
Hello... this is my usual follow up before announcing on meetup. Are you okay to do this one for this next june 5th meetup ?

**Comment by matt-way** [comment]
Yeah, for sure. Count me in :)

**Comment by iamkevinv** [comment]
@matt-way - Resources to share? Thanks :)
