### ISSUE TITLE
WebAssembly 101

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#190]
A new toy, woohoo!

WebAssembly has landed in Firefox and Chrome behind flags with Edge to follow shortly, so let's get started by learning what is it, why we need it, how it works, and how to get a head start coding today.

**Comment by AshKyd** [comment]
Can do a 40 min slot

**Comment by jwulf** [comment]
Awesome! Totes looking forward to this.

**Comment by maraisr** [comment]
If you give examples using Rust - I'll attend!

**Comment by AshKyd** [comment]
@maraisr Done! I've got a bit of Rust and a bit of C, though I'm not super advanced with either so be warned the talk will reflect that. :)

**Comment by maraisr** [comment]
@AshKyd maybe this could be some use maybe - its cpp but could quite easily be done with Rust. https://github.com/maraisr/webasm-test and maybe even https://mbebenita.github.io/WasmExplorer/

**Comment by AshKyd** [comment]
Hey folks, my slides from WebAssembly 101 are here:

https://wasm-brisjs.talks.ash.ms/

I don't have the demos available because I foolishly didn't push them up and my PC is out of commission.

Some useful links from the presentation include:

* The webassembly site - http://webassembly.org/
* A cartoon intro to webassembly - https://hacks.mozilla.org/2017/02/a-cartoon-intro-to-webassembly/
* Wasm explorer - https://mbebenita.github.io/WasmExplorer/

Thanks everyone for coming along, this was a fun talk and I hope you enjoyed it too.

**Comment by maraisr** [comment]
@AshKyd thanks for delivering! Lets be honest @idooo - wasm isn't that bad...
