### ISSUE TITLE
Talk: Blocking JS, the Event Loop, and Async

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#191]
More of a beginner/intermediate topic about how JS does async if it cant do async.

Only if people think it's a worthwile talk.

**Comment by iamkevinv** [comment]
We'd love to hear your talk! Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) April 3rd
- [ ] (b) May 1st

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by KoryNunn** [comment]
2017-4-3 or 2017-5-1 are fine, but I'll need to be not-first, so that Em can come grab Hnery from me.

I'd think 20 mins should be enough.

**Comment by iamkevinv** [comment]
The 20 min presentations start after the networking and food break so sounds good.

**Comment by iamkevinv** [comment]
We're pretty swamped with volunteer (which is SO great!), so i have to move you over to the May meetup.

**Comment by KoryNunn** [comment]
ok np

**Comment by iamkevinv** [comment]
Yo @KoryNunn,

1. Since the date moved... are you available for either or both of:
- [ ] (a) May 8th
- [ ] (b) June 5th

Thanks!

**Comment by KoryNunn** [comment]
Can do 8th not sure on 5th

**Comment by KoryNunn** [comment]
Also Henry's daycare situation has changed and I can do any time slot now.

**Comment by iamkevinv** [comment]
Hello... this is my usual follow up before announcing on meetup. Are you okay to do this one for this next june 5th meetup ?

**Comment by KoryNunn** [comment]
Yep that should be fine.

**Comment by iamkevinv** [comment]
@KoryNunn links to share? Thanks.
