### ISSUE TITLE
Talk: Internet of Javascript Things - Automate your life with MongooseOS and mJS

### ISSUE THREAD

**Issue by unixbigot** [BrisJS/meetups#192]
# What's the problem?

The Internet of Things (IoT) is the third computing revolution, the story so far being

1. Personal computing
1. Cloud computing
1. and now Ubiquitous computing (IoT)

The **most annoying** challenges in the Internet of Things (IoT) are connecting Things to the cloud safely, managing your Things, and updating them.

# What's the solution?

Mongoose-OS is the new hotness that solves all these problems for you out of the box, and lets you skip ahead to the cool stuff.

Mongoose OS gives you

* Painless installation of an OS core on your devices, up and running in two minutes
* Coding in Javascript (or C if you're kinky like that)
* A nice web IDE
* Remote management
* Over-the-air updates

and for a bonus you get ludicrously easy enrolment in Amazon's IoT framework, 
giving your Things access to all the features of AWS IoT, Lambda and the whole cloud enchilada.

# What will I talk about?

* Livedemo of getting to Hello World for five bucks in two minutes
* Tour of the Mongoose OS Javascript environment
* The 5 minute summary of AWS IoT framework
* Voice control with Siri or Alexa
* Using AWS Rules to create complex multi-device behaviours

**Comment by iamkevinv** [comment]
I always love these.... can't wait to see it. Require 40 or 20 mins?
We have a massively packed schedule now... so i can't guarantee if it's May or June meetup. Going to have to look into doing more of these, more actively now that we have more talk submissions. :)

**Comment by iamkevinv** [comment]
Just to get scheduling right, we need to know a few things...

1. Are you available for:
- [ ] (a) May 8th
- [ ] (b) June 5th

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by unixbigot** [comment]
Hi Kevin, 
   I can do 20min on May, but I may not have one of my planned demos ready by then (could still do the talk but not as cool)
   20min in  June is totally do-able.

Cheers —chris

— 
Christopher Biggs      <christopher@biggs.id.au <mailto:christopher@biggs.id.au>>
Brisbane, Australia.   +61-407-722-799  @unixbigot

**Comment by iamkevinv** [comment]
Okay - i don't want to rush you, and i love cool demos... so if you're okay with it maybe June. We're pretty full there too but should still be good :)

**Comment by unixbigot** [comment]
June is ok, later if overfull.

**Comment by iamkevinv** [comment]
Hello... this is my usual follow up before announcing on meetup. Are you okay to do this one for this next june 5th meetup if we can fit it in... waiting to hear from the ones who registered in before you first before locking it down. Happy to take such a cool talk if we can though :)

**Comment by unixbigot** [comment]
Yep, happy to do it.   Haven't actually written it yet though, so if you have folks with ready talks in the pipeline, by all means tap those guys.

I see you joined IOT, Kevin.  After running my first meetup yesterday I have even greater respect for the BrisJS team.

**Comment by iamkevinv** [comment]
Cool @unixbigot!... yeah i think it's good to have you on standby... waiting on 1 more confirmation and you are off the hook haha. 

RE: IoT meetup - Yeah i look forward to coming to the IoT meetups... i was disappointed to miss the first one but i'm so very flat out at the moment. Hopefully catch you folks soon. :)
Re Effort: Hehe yeah it's tough. I'm glad to get a little help from some kind people sometimes like Ash but it's still a lot of time spent - which i'm happy to do if people keep liking it.

**Comment by iamkevinv** [comment]
It's your month @unixbigot - you ready to rock it?

**Comment by unixbigot** [comment]
Let’s do it.   I heard china post had to order new planes to carry all the shinies I’ve been buying.

It’ll be a 20min quickie - Internet all the things with Mongoose-OS and Espressif.    Two open-source projects
come together to bring JavaScript and Amazon IoT to a number of popular sub-$10 miniature computers.

(20 mins plus dicking with HDMI time, that is :)

—chris

— 
Christopher Biggs      <christopher@biggs.id.au <mailto:christopher@biggs.id.au>>
Brisbane, Australia.   +61-407-722-799  @unixbigot

**Comment by AshKyd** [comment]
Hah, thanks @unixbigot. Shame about the gremlins, but I think things worked out well anyway. Do you have your slides/presentation up somewhere we could link to?

**Comment by unixbigot** [comment]
Thanks, Ash.  I’ll get them up as soon as i can, probably not before tonight.



—chris

— 
Christopher Biggs      <christopher@biggs.id.au <mailto:christopher@biggs.id.au>>
Brisbane, Australia.   +61-407-722-799  @unixbigot

**Comment by unixbigot** [comment]
Slides are up

http://christopher.biggs.id.au/talk/2017-07-02-iot-in-two-minutes/ <http://christopher.biggs.id.au/talk/2017-07-02-iot-in-two-minutes/>


— 
Christopher Biggs      <christopher@biggs.id.au <mailto:christopher@biggs.id.au>>
Brisbane, Australia.   +61-407-722-799  @unixbigot

**Comment by AshKyd** [comment]
Cool, added it to the talk page. The video is up too. https://bris.js.org/#talk-187
