### ISSUE TITLE
Could you create a prototype solution in 54 hours?

### ISSUE THREAD

**Issue by eunicehoxl** [BrisJS/meetups#195]
Hi! Just like to let you know of an upcoming hackathon at River City Labs this 21-23 April, [Unearthed Brisbane](http://unearthed.link/UEBRIS_17). The event needs people like you to come up with tech prototypes! It will feature challenges from Origin Energy and is a fully catered event. Enter code "UnearthedCommunity" at checkout to get $10 off your ticket. Hope to see you then! 

Cheers,
Eunice

**Comment by AshKyd** [comment]
Thanks @eunicehoxl, how was the event? Got anything to show off?

**Comment by eunicehoxl** [comment]
Hi Ash, 

The event went well - thanks! You can check out the prototype solutions here. <https://portal.unearthed.solutions/competitions/unearthed-brisbane-2017/submissions>

Cheers,
Eunice 

Eunice Ho  |  Event Coordinator  |  Unearthed
+61 404 449 491 |  eunice@unearthed.solutions
