### ISSUE TITLE
Talk: Building an ExpressJS + GraphQL Server

### ISSUE THREAD

**Issue by triyuga** [BrisJS/meetups#198]
_Don't worry, it's an elegant idea, for a more civilised age_  -- [@rbzhu](https://twitter.com/rbzhu) [#graphql](https://twitter.com/hashtag/GraphQL?src=hash)

What is [GraphQL](http://graphql.org/) & why is it cool?

Getting started quickly with **Express + GraphQL ([express-graphql](https://github.com/graphql/express-graphql))**. 

Example: **Schema + Resolver + [pluggable] Provider** architecture for GraphQL.

Example: Simple authentication setup using **JSONWebTokens ([jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken)) / ExpressJWT ([express-jwt](https://github.com/auth0/express-jwt)) + [pluggable] User backend**. Granular access control to query fragments based on user roles/permissions. Getting started quickly with [Auth0](https://auth0.com/).

_If you do Apps that use multiple API(s!) and micro services and you don't use GraphQL, be kind to yourself and start using GraphQL :)_  -- [@TimMarwick](https://twitter.com/TimMarwick)

**Comment by triyuga** [comment]
<img width="1152" alt="screen shot 2017-04-25 at 3 48 58 pm" src="https://cloud.githubusercontent.com/assets/2193454/25370535/c909c77a-29ce-11e7-888f-51d1d2043769.png">

http://graphql.org page provides good overview inc informative animations,

**Comment by iamkevinv** [comment]
@triyuga - We'd love to hear your talk! Just to get scheduling right, we need to know a few things...

1. Dates you're available to present, in case one of the nights is full. (If both, please let me know that too):
- [ ] (a) May 8th
- [ ] (b) June 5th

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by iamkevinv** [comment]
Just so we can plan, we have two GraphQL submissions... https://github.com/BrisJS/meetups/issues/182 which has been previously been volunteered by Josh. If @joshduck is doing May, then having you on in June would be excellent. Otherwise if Josh passes for now, we definitely have an opening for May.

**Comment by triyuga** [comment]
Hi @iamkevinv 

I can do either date.
20mins is fine.

Cheers!

**Comment by joshduck** [comment]
@triyuga i'm intending to give an introduction to GraphQL (under 10 minutes) in my talk Where I'll talk about the idea of requests describing the data and show GraphiQL via graphql.org/swapi-graphql/. If you'd like to know the specific points I'll be hitting on let me know.

**Comment by triyuga** [comment]
@joshduck sounds good. 

I see you are speaking next week, which I believe means I'll be speaking next month. @iamkevinv can you confirm?

In the comments here:
https://github.com/BrisJS/meetups/issues/182
You mentioned you'd be doing 40mins slot, but above you said 10mins.
There may end up being some overlap in our talks, but I'm not sure it matters, especially if they are a month apart...

GraphQL is great so I think we'll all be hearing a lot more about it going forward. 
Matt Way presented on GraphQL server-side last night at LocalhostBNE.
And I've also submitted a talk about GraphiQL React component for the Bris React meetup.

:)

**Comment by joshduck** [comment]
I'll be speaking for 40 minutes all up -- 10 minutes on GraphQL and 30 minutes on Relay.

**Comment by iamkevinv** [comment]
@triyuga i think having you on in June will be great; having a series of a topic has proven to have lots of interest and benefits...

**Comment by triyuga** [comment]
Great thanks @iamkevinv !

Looking forward to your talk @joshduck . We're using Apollo for now, so keen to learn more about Relay!

**Comment by iamkevinv** [comment]
Hello... this is my usual follow up before announcing on meetup. Are you okay to do this one for this next june 5th meetup ?

**Comment by iamkevinv** [comment]
@triyuga Ping? Keen to give this talk?

**Comment by iamkevinv** [comment]
@triyuga - I've included this on the lineup... if there's something stopping this talk, i have someone who can be a backup in the wings. Let me know early though...

**Comment by triyuga** [comment]
@iamkevinv yes can do. Sorry for late response. I missed the notifications.

**Comment by iamkevinv** [comment]
Hey @triyuga - if you have some resources to share - drop them here :)
