### ISSUE TITLE
async and await in Javascript VS promises VS callback

### ISSUE THREAD

**Issue by ohiaia** [BrisJS/meetups#199]
When to use one or the other... and why ...

**Comment by iamkevinv** [comment]
@ohiaia - Just to get scheduling right, we need to know a few things...

1. Are you available for either or both of:
- [ ] (a) May 8th
- [ ] (b) June 5th

2. Do you require the 40min presentation block, or one of the other two 20 minute presentation blocks?
- [ ] (a) 40min
- [ ] (b) 20min

Let me know anything else that might be required. Confirming the above will make sure we put you into one of the upcoming nights.

Thanks!

**Comment by ohiaia** [comment]
Sadly I will be not able to do the talk the 8th of May nor the 5th of June... The first one is too soon. The last one is to near to the due date of the birth of my daughter ... :) 

A quick presentation of 20 minutes will be more than sufficient ... 
 
But if you find someone else that can do the talk No Problem... 
It's a "hot" interesting change with a not to many side aspects.

Actually it could be better for you as my foreign accent is still a bit too strong... :P
Thanks you 
...and see you in Toowong soon?! ;)

**Comment by iamkevinv** [comment]
Well I guess we can always put you in for July ;-)
If someone volunteers before then we could get them in. Thanks for letting
me know :-)

**Comment by iamkevinv** [comment]
@ohiaia are you available to do this talk next week if we have capacity? Thanks :)

**Comment by ohiaia** [comment]
Actually Yes. I should be able to prepare the slide to cover a 5/10 minutes talk... Probably adding a little sample of use cases of the mixed way too... Would that be okay for you?!

**Comment by iamkevinv** [comment]
Would be great... lets do it

**Comment by AshKyd** [comment]
Thanks for your talk @ohiaia, reallly enjoyed it. Do you have your slides up somewhere we could link to?

**Comment by iamkevinv** [comment]
Any resources to share @ohiaia ? - Thanks.
