### ISSUE TITLE
Magikcraft's "JavaScript Über Alles" Tour of Europe

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#200]
Fresh from speaking at NDC Oslo, setting a new JavaScript world record, and launching the Magikcraft Open Source Platform at CoderDojo's Coolest Projects in Dublin, Ireland, the legendary Josh Wulf presents a wrap-up of the trials, the triumphs, the revolutionary technology, and the life-changing movement that is Magikcraft: introducing a new generation of coders to the power of JavaScript through Minecraft.

You will laugh, you will cry, you will be deeply moved by this touching story of the human impact of the world's one true full-stack language: JavaScript.

**Comment by iamkevinv** [comment]
@jwulf - if we have capacity is this still a go? It's getting really tight - 5 talks already so i'm trying to work out who is confirmed or not. Cheers.

**Comment by jwulf** [comment]
I'm back and I'm in. I went to the Elm workshop in Oslo and will talk about he Maybe Monad as well

**Comment by AshKyd** [comment]
Resources shared on Meetup: https://medium.com/@sitapati/magikcraft-in-europe-140-characters-or-less-at-a-time-4a0b2b647af3

Stay tuned for videos here: https://bris.js.org/#talk-188

(And a non-broken avatar. Not sure what's going on there.)

**Comment by AshKyd** [comment]
Thanks to you and Prahlad for a great talk, entertaining as always!
