### ISSUE TITLE
D3.js

### ISSUE THREAD

**Issue by shotlom** [BrisJS/meetups#21]
Anyone else interested in the D3 vis n charting library ?

**Comment by markgandolfo** [comment]
extending this to http://dimplejs.org/ or http://c3js.org/ would be great.

**Comment by MauriceButler** [comment]
My kingdom for someone to show me how to dynamicly scale a date rand of x-axis on a D3 line graph...

**Comment by AshKyd** [comment]
I know nothing! Totally nominating @colingourlay for this one.

**Comment by xwipeoutx** [comment]
I've had a fair bit of experience in d3, basically written a whole charting library with dynamic data for a BI application at work, including time/categorical/numeric axes, GIS and heaps of interaction.  Am happy to do a talk on it if people are interested.

Question is, what kind of specifics? Some ideas
* Rendering Geo data using Leaflet, d3.js, OpenStreetMap and geojson
* Simple primer data binding/entering/leaving/transitioning
* Generation and application of scales (Thinking of you here @MauriceButler - though more specifics would help. Also, I hope your kingdom is nice)

Thoughts?

**Comment by MauriceButler** [comment]
For me, I would love to hear about doing what I would refer to as simple.

I have a data set and I would like to draw a chart please.

In my experience that is not actually simple however...

Especially when you start working with either dates, or scalable axis.

And should you need to combine the 2....

I am sure the more complex stuff would be interesting however. :)

**Comment by kevdesign** [comment]
@xwipeoutx - Tag, you're it! Would you be able to prepare this for April BrisJS?

**Comment by xwipeoutx** [comment]
Can do. How long have I got? In minutes, that is , not days.

**Comment by kevdesign** [comment]
We usually put in 20 mins or so per person but if it's big then we just put two presentations on instead of 3. It all works out so just let me know.

**Comment by AshKyd** [comment]
Can't wait. @xwipeoutx Can I grab a brief description of your talk so I can tweet it out?

**Comment by xwipeoutx** [comment]
I'll do a quick refresh on the fundamentals of D3 (binding and transitions), and then explain how to take full advantage of `d3.scale` to draw a chart and effectively transitioning between slices of data.

**Comment by AshKyd** [comment]
Cool, thanks. :+1:

**Comment by kevdesign** [comment]
Ah i got your synopsis wrong then on the announcement - @xwipeoutx - i can update that too.

**Comment by ghiculescu** [comment]
Won't be able to make it, but @xwipeoutx would love to see anything you can share afterwards (slides etc)

**Comment by AshKyd** [comment]
I think @kevdesign is recording this one so we can hopefully expect it on YouTube at some point.

**Comment by kaffeebrauer** [comment]
sounds great, would like to see the talk shared, as I had to cancel at the very last minute.

**Comment by garrows** [comment]
@xwipeoutx really enjoyed your talk. Looking forward to getting a copy of your slides if you could share.

**Comment by xwipeoutx** [comment]
Hi All, glad you enjoyed it.  Felt I rushed the whole thing, wasn't sure how well received it was.

Anyway, here are [the slides](http://stevesspace.com/BrisJS-D3/), and the [github repo](https://github.com/xwipeoutx/BrisJS-D3/tree/gh-pages) is the best place to get the source I imagine.

The [javascript source](https://github.com/xwipeoutx/BrisJS-D3/blob/gh-pages/js/d3-demo.js) is probably the most relevant. You'll want to look for the `setupDemo` functions

**Comment by kevdesign** [comment]
I got some great comments about your talk after - I think you opened up an aspect of d3 so people could really see how to get into it - and not just pretty examples - well done!

**Comment by KoryNunn** [comment]
This was a really good talk. The basics were presented in a non-confusing way because you obviously know how D3 works.

**Comment by kevdesign** [comment]
Thankyou!
