### ISSUE TITLE
Building a chatbot with AWS Lambda and Lex

### ISSUE THREAD

**Issue by johncmckim** [BrisJS/meetups#215]
I built a chatbot using AWS Lambda (Nodejs of course) and AWS Lex for the AWS Chatbot Challenge - see [our entry](https://devpost.com/software/a-cloud-guru-bot-ryfwn3).

![acg-slackbot](https://user-images.githubusercontent.com/1297227/28243938-d6ef1e0e-6a1e-11e7-8a43-d4dba579a868.gif)

I could walk through building a Slack bot and using AWS Lex to add intelligence to the bot. I would touch on AWS Lambda & the Serverless framework. But since I've spoken about that before I would not make it the focus of the talk.

**Comment by AshKyd** [comment]
Sweet, that sounds fun

1. I think we've already got a 40 min talk, do you reckon a 20 min block sounds good?
    - [ ] (a) ~40min~
    - [ ] (b) 20min
1. Are you available for:
    - [ ] (a) August 14

As a FYI [information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by johncmckim** [comment]
Yep @AshKyd  August 14th for a 20 minute slot works great.

**Comment by AshKyd** [comment]
Thanks for the talk, and the good answer on the random curveball question! Do you have slides/resources posted somewhere we could share with the meetup?

**Comment by johncmckim** [comment]
@AshKyd the slides are available at [http://slides.com/johnmckim/serverless-slack-bots](http://slides.com/johnmckim/serverless-slack-bots).

The bot is on the Slack app store at [https://slack.com/apps/A68R1BXL4-a-cloud-guru-bot](https://slack.com/apps/A68R1BXL4-a-cloud-guru-bot)

**Comment by AshKyd** [comment]
Sweet, added 'em to the talk page. Will get video up when it happens https://brisjs.org/#talk-190
