### ISSUE TITLE
Themeable email templates with MJML

### ISSUE THREAD

**Issue by benoneal** [BrisJS/meetups#218]
Talk title: Themeable emails
Talk length: 20 min
Talk synopsis: How to build a complete brandable email templating solution that doesn't suck.
Available month(s): October

**Comment by AshKyd** [comment]
Sounds great, let's lock it in for October!

Could you please provide your Twitter handle (if available) so we can link from the meetup, website etc.

FYI [Information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by benoneal** [comment]
Cool. I can do that. 9th October yeah? My twitter handle is @BenONealUX but it's extremely inactive.

**Comment by AshKyd** [comment]
No probs, the Twitter integration is just to populate a pic & bio on the site. :)

Yeah, 9th October. Here's the placeholder event if you wanted to RSVP for a reminder: https://www.meetup.com/BrisJS/events/241140125/

**Comment by AshKyd** [comment]
So we've pretty much finalised the next meetup. I haven't sent out an announcement, will wait until closer to the date.

Just wanted to confirm you're good, and see if you wanted to tweet out some kinda promo so we can schedule some retweets from @brisjs through the month.

Also, event is here: https://www.meetup.com/BrisJS/events/241140125/

**Comment by benoneal** [comment]
@AshKyd Yup 👍 still good to go with this one.

**Comment by iamkevinv** [comment]
Any resources to share @benoneal ? Then we can close the issue :)

**Comment by benoneal** [comment]
@iamkevinv Sure! Code examples (and a link to the slides) can be found here: https://github.com/benoneal/brisjs-email-theming

Thanks!

**Comment by AshKyd** [comment]
Cool, thanks. I've added that to the site. https://brisjs.org/#talk-200
