### ISSUE TITLE
Lead Front End Position available 

### ISSUE THREAD

**Issue by mikerubio720** [BrisJS/meetups#219]
Hey guys we have a position for a Lead Front End Dev.
The role is for an award winning e-learning company, is an innovation trail blazer! With a passion for learning and education, they bring a fresh perspective and high tech approach that makes people want to learn. They have an amazing work culture that's not accidental. They value people and love to see individuals thrive in their unique skills. 

The role of Lead Front End Developer is one that has a strong hands on coding element, with a degree of team leadership and management. This means, not only are you a front end wiz with HTML3, CSS3, JavaScript/jQuery, but you are also able to communicate complex issues into understandable terms for non-experts. You take pride in your work and ensure that UI/UX designs work with technical requirements. Your web coding is naturally responsive and performs great on any device or browser. 

We’re looking for someone who has around 4 years working commercially as a front end developer. The right person has skill working in an Agile/Scrum environment and thrives under pressure. You need have previous experience designing system architecture, developing software solutions and automations. You need to love seeing your team win, regardless if you get the glory. 

Essential 
HTML3, CSS3, JavaScript/ jQuery
Bootstrap
SASS
Agile/ Scrum 

Handy skills
Angular.js
Ember.js
Node.js
E-Learning experience 
UX/UI experience 

If you're interested shoot me an email on mike@seventwenty.com.au

**Comment by AshKyd** [comment]
Hi @mikerubio720, can you clarify if this is a position with you at seventwenty.com.au, or are you recruiting for another company? If so, please include the company in the job description. :)

**Comment by mikerubio720** [comment]
Hey Ash,

Yes, we are recruiting for the company we are representing. Unfortunately, the companies name is confidential until applicants apply for the role. Sorry about any inconvenience.
Regards,



Mike Rubio
Career Advisor
M 0433 011 409<tel:0433011409>
W seventwenty.com.au<http://www.seventwenty.com.au><https://seventwenty.com.au> [Seven Twenty] <https://seventwenty.com.au>

[twitter]<https://twitter.com/SevenTweety>      [linkedin] <https://www.linkedin.com/company/seventwenty>

email disclaimer<https://www.seventwenty.com.au/email-disclaimer>



________________________________

**Comment by AshKyd** [comment]
No probs, we might have to close this one in that case. If you have any roles you can advertise directly please feel free to post those. :)

**Comment by mikerubio720** [comment]
Hey Ash,
No worries. Thanks for your help anyway.
Mike

Mike Rubio
Career Advisor
M 0433 011 409
W seventwenty.com
________________________________
