### ISSUE TITLE
Production Node

### ISSUE THREAD

**Issue by shotlom** [BrisJS/meetups#22]
How about a BrisJS session focusing on Node for Production?

- [ ] Node server in prod (PM2 etc) - #16 
- [ ] Prototypes in prod - #17 
- [ ] Production npm - #13 
- [ ] Testing in a production environment - (e.g. Travis)[https://travis-ci.com]
- [ ] Versioning

**Comment by MauriceButler** [comment]
I can run through what we do at work if it helps?

**Comment by shotlom** [comment]
That would be awesomeballs

On Tue, Jan 20, 2015 at 11:28 AM, Maurice Butler <notifications@github.com>
wrote:

> I can run through what we do at work if it helps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/22#issuecomment-70590234>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com

**Comment by kevdesign** [comment]
Maurice - are you confirmed for this talk?

**Comment by MauriceButler** [comment]
Umm sure. I have nothing prepared but I can just talk through what our infrastructure is an how we deploy and npm etc.

**Comment by shotlom** [comment]
I noticed strongloop are pushing their production node products quite
strongly on Twitter. And there are a couple of interesting articles
appearing.

I don't have any production node but am looking to roll something out this
year.

In the absence of a strongloop vendor in Brisbane I wonder whether effort
might be well spent turning this into a formal fee for service training
package for brisjs/sydjs/melbjs node users. Perhaps delivered at campjs.

Ideas ideas.

**Comment by MauriceButler** [comment]
Hi All,

Links to things.

**Process Managers**
pm2: https://www.npmjs.com/package/pm2
forever: https://www.npmjs.com/package/forever
upstart: http://upstart.ubuntu.com/

**Private npm servers / tools**
bearded-protagonist: https://www.npmjs.com/package/bearded-protagonist
bearded-nemesis: https://www.npmjs.com/package/bearded-nemesis
sinopia: https://www.npmjs.com/package/sinopia

**Break promises**
abbott: https://www.npmjs.com/package/abbott

**Flow control**
kgo: https://www.npmjs.com/package/kgo

**Comment by garrows** [comment]
Some extra things to complement Maurice's talk....

I recommend running nginx in front of node and running node with upstart. 

An example upstart config file (replace the %APPLICATION% %PATH% and %NODEPORT%)
https://github.com/garrows/noleg-stack/blob/master/upstart.conf

And an example nginx config file (again replace the %DOMAIN% and %NODEPORT%)
https://github.com/garrows/noleg-stack/blob/master/nginx.conf

I can do a lightning talk on my ideal stack next month if requested.

**Comment by shotlom** [comment]
This link talks about "Ansible" and using systemd on Fedora.

"systemd offers some significant advantages over Upstart including
advanced, centralized logging support, simpler configuration, speed, and
way more features."

http://blog.carbonfive.com/2014/06/02/node-js-in-production/



On Mon, Feb 2, 2015 at 10:07 PM, Glen Arrowsmith <notifications@github.com>
wrote:

> Some extra things to complement Maurice's talk....
>
> I recommend running nginx in front of node and running node with upstart.
>
> An example upstart config file (replace the %APPLICATION% %PATH% and
> %NODEPORT%)
> https://github.com/garrows/noleg-stack/blob/master/upstart.conf
>
> And an example nginx config file (again replace the %DOMAIN% and
> %NODEPORT%)
> https://github.com/garrows/noleg-stack/blob/master/nginx.conf
>
> I can do a lightning talk on my ideal stack next month if requested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/22#issuecomment-72446847>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by iamkevinv** [comment]
Going to call this done until we can get someone with a specific new request. Thanks folks!
