### ISSUE TITLE
Full Stack Dev/DevOps (AWS, Node.js/JavaScript, PHP) Fortitude Valley, $80-$110k+Super

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#220]
# Full Stack Dev/DevOps (AWS, Node.js/JavaScript, PHP) Fortitude Valley, $80-$110k+Super
![FunCaptcha Logo](http://i.imgur.com/h2H54eo.png)

At FunCaptcha we fight an epic battle against cyber crime, spammers, scalpers and trolls. Our internationally praised Brisbane based company replaces the much-hated method that makes users "prove their humanity" by deciphering blurry letters and photos. Instead, FunCaptcha poses a clever 3D visual puzzle that is highly usable for humans, but very hard for abusive programs that crawl the internet, imitating legitimate users. FunCaptcha protects thousands of websites and apps worldwide, gaining testimonials by globally recognised companies. See more by searching for "FunCaptcha" on the web.

To support more high value clients, we are building our software development team. We will be adding features and maintaining our existing service, building tooling for our analysts/producers and building an awesome customer portal.

We are a modern software development team utilising test driven development practices, agile methodology, continuous integration & deployment and are supported by a talented quality assurance team.  

### Skills & experience:

* Real world experience delivering web services or applications
* Strong HTML, CSS & JavaScript experience
* DevOps experience
* Strong AWS experience
* Experience building APIs with Node.js
* PHP experience
* Git experience
* Strong problem solving & diagnostic skills
* Attention to detail

### Bonus point awarded if you have experience or an interest in:

* Serverless/Lambda
* Machine learning
* Web security
* Scaling services under super high load
* DynamoDB (or similar)
* Canvas
* Test driven development
* React/Redux
* Enjoying your job

### Key responsibilities:

* Full stack development
* Smooth deployment of product builds
* Evaluate and direct improvements of AWS infrastructure
* Respond to attacks and interruptions of service
* Ensure top security against legions of determined hackers
* Ensure top usability for everyday consumers
* Ensure cross-browser compatibility

### What we offer:

* A diverse, friendly & dynamic work environment
* Enjoy a healthy balance between the excitement of hard work and the rejuvenation of happy living
* Work directly with the founders of the company, who respect the value of high-quality, high-integrity software development
* Get in on the ground floor of a profitable company that major newspaper The Age placed in the Top 5 Start-Ups to Watch
* An awesome office in the new Startup Precinct in Fortitude Valley

Email your CV or any questions to g.arrowsmith@funcaptcha.com

**Comment by jonny2k9** [comment]
You have an excellent 404 page! Might apply 😄

**Comment by garrows** [comment]
Still looking for people. 
We are looking at hiring two people for this role so if you're skilled in some of the above areas, get in contact anyway.
