### ISSUE TITLE
BrisJS Open Hack Day Event/s

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#222]
Hey, what about a "BrisJS Hack Day" as a thing? We could have a "BYO project and get help / give help" track, and also a "Getting Started" track for absolute beginners.

**Comment by iamkevinv** [comment]
This is absolutely on the cards :-)
Workshops will get kicked off at BrisJS and informal hack days would come
along with them. JS101 and Node for Noobs will probably be some of the
first series - as those have been requested. I'll open a new BrisJS issue
to start getting feedback on that separate to this discussion.

Was going to start work on both in OCT after my wedding is done. Good to
start thinking about where and when and who stuff now.

Kevin

**Comment by AshKyd** [comment]
We should totally reach out and see if we can team up with [Brisbane Tech Newbies](https://www.meetup.com/Brisbane-Tech-Newbies/) for the 101 type events considering Caitlin has already made a start on it.

**Comment by MauriceButler** [comment]
I heard great things about the node girls that happened on the weekend too so there is a great opportunity to reach out and include them.

@jwulf You might be able to assist with introductions there etc?

**Comment by iamkevinv** [comment]
Of course 👍 have a few contacts already, but asking again never hurts.

It's early days but any feedback or interesting tips and ideas for us to
focus on are a benefit.

**Comment by iamkevinv** [comment]
Ash - yeah the idea would be to broadcast pretty far and wide, and as soon
as something even remotely more organised (than right now) eventuates as
per aforementioned dates I'll be super keen to pull in everyone in this
space :-)

**Comment by AshKyd** [comment]
My suggestion was more about reaching out to help make Brisbane Tech Newbies a great meetup rather than pulling them into ours. That feels a bit like a steamroll which is the last thing we should be doing 😆

**Comment by anchat1990** [comment]
Hello everyone 👋 Love the idea for a hack day! would love to get involved. I have a mailing list for the existing attendees and those interested in fitire nodegirls events. Would be awesome to team up.

**Comment by iamkevinv** [comment]
Cool @anchat1990! Look forward to starting to work on this later on!

@AshKyd - You do still make a totally relevant point, we'll have to be conscious that if we do want to run a hack day aren't steamrolling BNE tech newbies. It's certainly not intentional. I think we could probably collaborate with them to make sure everyone's still happy and there isn't a huge overlap, or join up with them for a special event.
There's a lot in the air right now. Appreciate the inputs from everyone though!
