### ISSUE TITLE
Talk: Node and .NET in-process interop

### ISSUE THREAD

**Issue by KimBurgess** [BrisJS/meetups#224]
Yep, you read correctly. That's a thing.

Recently we had a project where we needed to integrate some of our front-end components (written in js) with another product. Tiny problem - the only integration option for this other product was a .NET SDK. Faced with the option of having to completely re-implement one side of this, the thought occurred:
![Why not both?](https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif)

Happy to do a shorter talk on how this was done, why it was done and some tools if others face a similar situation. For our implementation I ended up popping together tooling in Typescript (because lack of type safety scares me), but happy to do the talk in both vanilla JS and TS in parallel as our tool is a simple wrapper over an untyped library.

**Comment by jwulf** [comment]
Did you use Edge.js?

**Comment by KimBurgess** [comment]
Certainly did! I built [edge-ts](https://github.com/acaprojects/edge-ts) around it to then provide types and a few little niceties to the API (such as the option for promises for async invocation etc).

**Comment by AshKyd** [comment]
Definitely sounds interesting. Reckon you could do a 15-20 min talk on this one?

Also:
1. Are you available for:
    - [ ] (a) September 4th
1. Please provide your Twitter handle (if available) so we can link from the meetup, website etc.

[Information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by KimBurgess** [comment]
Tops. The 4th works well. You can find on Twitter via [_______kim](https://twitter.com/_______kim), or more widely at [simple.industries](https://simple.industries/)

**Comment by AshKyd** [comment]
Awesome, see you there.

**Comment by iamkevinv** [comment]
Any resources to share here @KimBurgess ? Then we can close this issue :)

**Comment by KimBurgess** [comment]
Sure!

[Slides](http://slides.com/kimburgess/edge-js) from the talk.

The [edge-ts repo](https://github.com/acaprojects/edge-ts) I mentioned, and [an example of it in use](https://github.com/acaprojects/skype-native).

But most importantly, the (real) [edge repo](https://github.com/tjanczuk/edge) that does the... ![magic](https://i.imgur.com/YsbKHg1.gif)
