### ISSUE TITLE
Sept Meetup - React.js patent panel discussion

### ISSUE THREAD

**Issue by developersteve** [BrisJS/meetups#225]
This actually came about during a convo with @iamkevinv 

Ive got an awesome patent lawyer from Brisbane keen to be on the panel from Hopgood Ganim to talk on the legal side of things (he knows his shiz when it comes to tech patents). Will just need a few more panel people to talk on the code side. 

As this is a topic that covers a much wider issue around open source IP ownership and things that growing projects may not always be aware of i think we can some interesting views from  both the legal side and the development side.

**Comment by iamkevinv** [comment]
Referenced article: https://medium.com/@dwalsh.sdlr/react-facebook-and-the-revokable-patent-license-why-its-a-paper-25c40c50b562

**Comment by AshKyd** [comment]
This sounds very cool, it's become somewhat of a hot topic of late.

What do you need to make this happen?

**Comment by developersteve** [comment]
@AshKyd just some more panelists, 2 or 3 more.

**Comment by iamkevinv** [comment]
Any resources to share here @developersteve ?
