### ISSUE TITLE
Talk: Service Workers: Annoying or Helpful?

### ISSUE THREAD

**Issue by thiagospassos** [BrisJS/meetups#226]
Talk title: **Service Workers: Annoying or Helpful?**
Talk length: 20 min
Talk synopsis:
A service worker is a script that your browser runs in the background, separate from a web page. This opens the door to features that don't need a web page or user interaction. 
Now, with a little bit of imagination, you can see how annoying or how useful service workers can be. 
Let's take a tour of some of the features and annoyances of this piece of technology.

Available month(s): October onwards.
Optional: @thiagospassos

**Comment by AshKyd** [comment]
Sounds like a great talk, thanks for getting in touch. We might already have enough talks for October but Kev will get in touch and let you know closer to the date :)

**Comment by thiagospassos** [comment]
Hey @AshKyd, November would actually work better for me. Cheers

**Comment by AshKyd** [comment]
Nice, thanks. I've put you on the November lineup, looking forward to hearing how not to be annoying with Service Workers :D

[Information for speakers](https://bris.js.org/#present) is available on the website. Talks will be recorded for the website & YouTube channel, if you wish to opt out of this please let us know. Internet is not available at the venue, but if you need access to a 4G hotspot please let us know on the night.

**Comment by iamkevinv** [comment]
Hey @thiagospassos - can you confirm you're speaking at our Nov 6 meetup? Looking forward to this talk!

**Comment by thiagospassos** [comment]
Hi @iamkevinv, yes, it's confirmed. Cheers

**Comment by iamkevinv** [comment]
Hey @thiagospassos - if you have links and resources to share here from your talk... please do! I'll update the label and close the issue then.

**Comment by thiagospassos** [comment]
Hi @iamkevinv, 

Here's the slide deck https://1drv.ms/v/s!Auyj8a8D7jzShtQZP2FweF7dYqdqfA 
Here's the source code for the demos: https://github.com/thiagospassos/service-workers 

Thanks

**Comment by iamkevinv** [comment]
Thanks heaps!
