### ISSUE TITLE
How I learned to stop worrying and love charting North Korean missile ranges in D3.js

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#227]
Sez Josh Bryd:
> I would love to do a longer one at a later date too with more preparation time :)
https://twitter.com/phocks/status/904859651652567044

So here's a placeholder.

**Comment by iamkevinv** [comment]
Hey @phocks - are you keen to do your follow up in Dec? Otherwise it may be Feb. Trying to work out what we will have in the coming months :) No pressure or anything - just gambling on content ;-)

**Comment by phocks** [comment]
Hmmmmm @iamkevinv I will be just flying back from our honeymoon early December... Perhaps Feb would be good I could follow up with a walk through of the North Korea Missile piece we did that made it to the front page of Reddit http://www.abc.net.au/news/2017-10-16/north-korea-missile-range-map/8880894

**Comment by iamkevinv** [comment]
Okay mate... thats all good, i know it gets hectic and you need some recovery time too - congrats btw!

**Comment by phocks** [comment]
Congrats to you too!

**Comment by AshKyd** [comment]
Confirmed with Josh, he's going to go for a 20 minute slot 👍

**Comment by AshKyd** [comment]
New title: `How I learned to stop worrying and love charting North Korean missile ranges in D3.js`

Synopsis:
> Josh joined the ABC's Digital Storytelling Team a little over 6 months ago as his first proper programming gig. Since then he's learned a bunch of stuff, and published one of last year's most impressive stories, drawing acclaim from Reddit and around the world.
>
> In this talk he'll take us on his learning journey and go through how to get off the ground with D3.```

**Comment by iamkevinv** [comment]
hey @phocks - if you have any resources you want to link to, please do before we close this :)

**Comment by phocks** [comment]
Yep, here's the source code for the ABC News Interactive https://github.com/abcnews/north-korea-missile-map/

And here's the standalone code on Glitch from the BrisJS talk https://glitch.com/edit/#!/nk
