### ISSUE TITLE
The theme is CSS in JS

### ISSUE THREAD

**Issue by loklaan** [BrisJS/meetups#228]
Hey folks,

I've done some talks at the lovely [Brisbane React Meetup](https://github.com/Brisbane-React-JS/meetups) on CSS-in-JS.

- **State of CSS-in-JS**
  _Goes over all the ways we go about writing styles in JS, for React, React Native, and beyond_
- **Writing Themeable Components**
  _Emphasis on React Components examples, but it is applicable to other view libs/frameworks_

I was wondering if these kinda topics would be good for BrisJS?

I've previously approached these talks from the assumption/starting point where audience is already comfortable with writing UI components (with libraries _like_ React). And also familiarity with the general concept of CSS-in-JS.

Let me know if these would be welcome submissions (20 min each?) (or a single big submission 40 min? could also squeeze into 20min...). I'm passionate and can talk about these things in length, but fairly new to public speaking, so any help on that front would be appreciated 🙏  if these goes forward.

> P.S. The phrasing "css-in-js" is pretty funny because it does also refer to styling in react-native, which uses a _css-like_ system... I'll likely keep it the talk/discussion to web css-in-js because thats where almost all the dragons lie.

**Comment by AshKyd** [comment]
We're still looking for a 40 min talk at the next BrisJS if you reckon you could pull something together for October 9? That would be awesome. :D

That might make it a good opportunity to start with the basics, as we're a more generalist meetup and I'm sure there's people who aren't super familiar with React (myself included!) But yeah, that's a totally appropriate topic and we'd love to hear from you.

**Comment by loklaan** [comment]
Exciting! Thanks for the big spot!

Talk title:
"**The theme is CSS in JS**"
😂 

Talk length:
**40 min**

Talk synopsis:

> _Nowadays we write our css in .js files. Howdathunkit?_
> 
> _Lets explore the future of writing reusable ui components for our web apps, by stopping to take a look at the history of css-in-js. Its not a very long history... but it's crammed full of hacks & innovation from all corners of our web community!_
> 
> _Also, since theming is often vital to successful styling, we'll jump into some code to discover patterns to enable the overriding of styles used inside of ui components._
> 
> _The talk is being given by the unknown web lurker & js fanboy, Lochlan Bunn. Lochy has been writing reusable components, with various levels of failure, at the local product house Rex Labs._

---

_In some more detail, for posterity (mostly myself hah)._

I'll pull the two prev talks together and start em' off without any expectation from the audience.

By the end of the talk & demos I'll (hopefully) accomplish:

* Making the case for css-in-js in functional ui components
* Breaking apart the "state of css-in-js" in terms of available technical choices, and the ecosystem that employs them
* Coming to terms with a caveat: theming becomes ambiguous and hard to accomplish
  * Differentiate systems of "theming" & "design rules"
  * Going through some code to explain how to write themeable functional ui components

The content and conclusions are in no way ground breaking, but the final points about theming are often the hardest to come by in the community/industry (from my experience). I'm eager to get those across, but starting from the start. Well, I'm also nervous, but mostly eager.

**Comment by iamkevinv** [comment]
Any resources to share @loklaan ?

**Comment by loklaan** [comment]
@iamkevinv Yep!

@loklaan
https://theme-is-cssinjs.surge.sh/
https://glitch.com/edit/#!/writing-themeable-components

Thanks for chasing 🙌
