### ISSUE TITLE
Full Stack Developer (Heroku, Node.js, Rails) based in Toowong - 16 hours a week.

### ISSUE THREAD

**Issue by Marknel** [BrisJS/meetups#230]
Hi BrisJS community,

I'm Mark Cracknell from NGU Group. We do a bunch of different things such as real estate, property development, software development, law, finance and more.

I've got some contract work that needs to be addressed over the next few months and I'm looking for an enthusiastic full stack dev who's keen to work on some unique projects.

**Key Tasks**
- Maintenance & development of new features for an existing client Node.js/React platform.
- Minor design works for some existing platforms in RoR and Node.js
- Maintenance for two existing Node.js platforms for NGU Real Estate

**Required Skills**

- Experience deploying production applications
- Experience with Heroku, Pipelines, CI and test-driven development
- Experience working with and developing APIs
- Node.js, React and Rails experience

**What we Offer**

- Work from our brand new Toowong office (directly opposite Toowong Villag).
- Parking available on-site
- Great team with a diverse range of talents
- Quiet working space
- Potential to grow into a full time role as needed.

Shoot through your resume to mark@ngutechnology.com.au

**Comment by AshKyd** [comment]
Closing this one because it's been a while. Feel free to reopen it if you need.
