### ISSUE TITLE
Health Hack wants you! 3-5 Nov 2017

### ISSUE THREAD

**Issue by andrewsaul** [BrisJS/meetups#231]
We want you to come to Health Hack this year! I promise it'll be great. https://www.slideshare.net/AndrewSaul1/come-to-health-hack-brisbane-2017

Health Hack is national event that helps medical researchers, health professionals and students find solutions to their important problems. 
Work with medical researchers and healthcare professionals on real problems in important areas like drug research, genomics, health care service delivery and many more. Get stuff working NOT sell an idea to investors.

Health Hack is happening 3-5 November in Brisbane at the ThoughtWorks offices (near Central Station). Sign up and learn more at the website: https://www.healthhack.com.au/ 

Follow us on Twitter @HealthHackAu if you like.

**Comment by slimlime** [comment]
oo sounds interesting.

**Comment by garrows** [comment]
This is an awesome event. Highly recommended.

**Comment by andrewsaul** [comment]
We’ve got our first problems up for Brisbane and I’m excited about them and I hope you will be too. https://www.healthhack.com.au/brisbane-problems/

We’ve got data visualisation & analysis, image processing, web dev, databases, apps, robots ( I repeat: ROBOTS!) and more. All of it in aid of the greater good.

- Nicole Robinson from the Queensland University of Technology wants to improve the ability of social robots to interact with humans so that they can support people taking part in healthcare programs.
- Professor Kathy Andrews from the Griffith Institute for Drug Discovery, Griffith University is bringing a problem about the development of an e-mentoring tool for biomedical HDR students.
- The Maternity Consumer Network is bringing a problem about the presentation of perinatal data in the maternity sector.
- Prof Naomi Wray is bringing a problem about Motor Neuron Disease.
- Steffen Bollmann from Centre For Advanced Imaging, The University of Queensland is bringing a problem about medical imaging.
 
And there’s more to come for Brisbane still not to mention Sydney.
It’s going to be a great weekend. We’ve got free childcare in Brisbane too!
