### ISSUE TITLE
Using Github as a CMS Backend

### ISSUE THREAD

**Issue by triyuga** [BrisJS/meetups#232]
Talk title: **Github as a CMS Backend**
Talk length: **20 min**

### Talk synopsis: 
Github has a fairly decent CRUD GUI, and a great API. Together
* Avoid building your own CRUD UI!
* Enables server-less CMS! But works well if you have a server too.  
* Use Markdown!
* Revisions via Git!
* Local IDE support
* Static asset uploads supported 

**Tips and Tricks**
* Caching for performance
* Working Github API rate-limits
* more as I think of them! :p

Available month(s): **Nov, Dec, Jan**
Optional: **@TimMarwick**

![mmj-creation](https://user-images.githubusercontent.com/2193454/31331257-fb18a28e-ad24-11e7-8cbf-ec142b1d53c3.gif)

**Comment by iamkevinv** [comment]
Very cool mate... but we'd be hard pressed to get it all squeezed into Nov. Lets have you on the next one if possible :) Thanks!

**Comment by iamkevinv** [comment]
Hey @triyuga - We have an opening for Nov after all... are you interested?

**Comment by triyuga** [comment]
@iamkevinv Sure can do Nov!

**Comment by iamkevinv** [comment]
@triyuga - You're so special, we're discussing when would be the best time to have this talk 👍 
Are you also available Monday, December 4 for the Dec BrisJS? Sorry for any muckaround this could cause. If you prefer this month because you're not sure about the other, then we'll have you on this month for sure.

**Comment by iamkevinv** [comment]
Hey @triyuga - since you confirmed Nov so kindly and to avoid any further complications - let’s stick with Nov. looking forward to next week! Will update the meetup page in the morning from the train.
