### ISSUE TITLE
Software Developer – Web and Mobile - Virgin Australia

### ISSUE THREAD

**Issue by kenwu27** [BrisJS/meetups#235]
**About The Role**

When you think Virgin, you automatically think innovation. Joining our Digital and Emerging Technology’s team will see you at the forefront of innovation, delivering innovative projects from ideation through to full development. You will be integral to the development of the digital strategy across all aspects of the Virgin Australia business.

The role of Software Developer (JavaScript) will see you developing precision-engineered software solutions for the Virgin Australia Group. Utilising best practices and leading edge technologies, you will interact with leaders, specialists, internal stakeholders and other developers to create applications in any given software development approach.

**In Your Role You Will**

designing and developing scalable and extensible web solutions 
actively engaging with customers to ensure solutions continue to deliver great travel experiences 
Regularly reviewing industry best practice to identify new opportunities for innovative solutions. 

**About You**

We are looking for a candidate who can take initiative and pursue the role with a passion for challenging the status quo. You will have a strong understanding in responsive web design and software development with RESTful API.

Other Technical Knowledge That Would Be Useful Includes

- JavaScript libraries and frameworks not limited to: React.js, Redux, Node.js, Gulp, Webpack 
- HTML5, CSS/SASS 
- WCAG 2.0 Accessibility standards 
- Gitlab CI, Jenkins, Bamboo or equivalent tools for Continuous Integration/Delivery 
- Atlassian Jira and Confluence for agile development 
- Apache or Express server configurations 
- GIT and SVN version control 
- Test automation 

Strong written and verbal communication skills is a must for this role as you will be required to work with a variety of stakeholders at all levels of the business.

**What You’ll Get From Us**

Other than the opportunity to work for an award-winning airline, you will have the opportunity to directly impact the travel experience of over 20 million travellers every year. You will also have the opportunity to work with alliance and technology partners around the world and use leading edge technologies to help design and deliver leading edge solutions.

And as a Virgin Australia team member, you will also receive fantastic employee benefits including discounted flights for you, your family and friends (across domestic and international) and global accommodation options.

**Interested? Apply at LinkedIn at https://www.linkedin.com/jobs/view/445350605/**

**Comment by AshKyd** [comment]
Closing this one because it's been a while. Feel free to reopen it if you need.
