### ISSUE TITLE
6 ways to an Awesome API

### ISSUE THREAD

**Issue by AnnaGerber** [BrisJS/meetups#236]
Lightning talk

**Comment by iamkevinv** [comment]
Due to https://github.com/BrisJS/meetups/issues/240 you may be off the hook ;-) 
Moving to Feb.

**Comment by AnnaGerber** [comment]
Still thinking of including this in the Feb meetup? I can stretch it out to 20 minutes if wanted

**Comment by AnnaGerber** [comment]
Slides are here: http://slides.com/annagerber/6-ways-to-an-awesome-api
