### ISSUE TITLE
Lightning talk: Adventure & Discovery at Fronteers Conf

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#241]
Talk title: Adventure & Discovery at Fronteers Conference, Amsterdam
Talk length: 10 min lightning talk

Talk synopsis: 
The venerable @AshKyd was at https://fronteers.nl/congres/2017/speakers#ash-kyd and had a great time, immersed in tech and the Amsterdam nexus of the web interested minds. He'll be along to tell us about the cool things he learned/saw while there and tell you what's hip and new in EUR.

Available month(s): Dec
Optional: https://twitter.com/AshKyd

**Comment by AshKyd** [comment]
Polished the talk into a blog post you can read here:
https://ash.ms/2017-12-09/diversity-brisbane-tech/
