### ISSUE TITLE
Contract EmberJS Developer ASAP Start

### ISSUE THREAD

**Issue by jamesatgbst** [BrisJS/meetups#242]
GBST have a position for an experienced JS dev to join our Brisbane (Ann St CBD) team building an investment management portal for a large client in the UK. You'll be working with the https://www.emudesign.com.au/ team, the internal digital department of https://www.gbst.com/ a publicly listed fintech.

We understand that EmberJS skills aren't common, so Ember isn't a hard prerequisite if you're otherwise strong on frontend stacks and you're interested in learning it.  We pay top market rates and there are perm opportunities for the right people. 

Please introduce yourself to @jamesatgbst on GitHub and Twitter, or via james.radvan at gbst.com if you're interested.

**Comment by srsgores** [comment]
@jamesatgbst, has the role been filled?  If not, please feel free to reach out.

**Comment by jamesatgbst** [comment]
@srsgores we are still looking. I understand you're in Calgary, do you have plans to come to Brisbane? If so drop me a CV at my email above. Cheers

**Comment by srsgores** [comment]
Thanks, @jamesatgbst.  Check my e-mail for my resume.  Cheers
