### ISSUE TITLE
Can someone talk about Web Components?

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#246]
https://www.webcomponents.org

Good topic to do a little research and put together a presentation. What are they? How do they work? Why would we use these over other frameworks?

**Comment by AshKyd** [comment]
Armagan originally asked for this talk, but will _also_ be in a position to give the talk in a couple of months. So let's say this one could be a maybe-tentative for May or so.

**Comment by broccolinisoup** [comment]
Hey @AshKyd , yes that's 100% true :) I'm aiming April meetup now. Will update here about how I'm progressing on. Cheers!

**Comment by iamkevinv** [comment]
Hey @broccolinisoup - were you still interested in giving the talk on web components? I've actually been doing a lot of work in this area and would love to see someone talk about it. :)

**Comment by broccolinisoup** [comment]
Hey @iamkevinv unfortunately I won't be able talk, I have 2 overseas trip in the next 2 months and I will be back in August. Let's talk about it after winter :)

**Comment by iamkevinv** [comment]
@rapelt is a possibility for presenting this too and has https://github.com/BrisJS/meetups/issues/279 open for it.

I will also present related work at CampJS this year.

**Comment by iamkevinv** [comment]
@broccolinisoup, @rapelt or...i guess me @iamkevinv ... could all give some general background on web components specs. Would either of you be keen to volunteer?

**Comment by iamkevinv** [comment]
Not keen @broccolinisoup, @rapelt ?

**Comment by rapelt** [comment]
Hey Kevin, I have so much on at the moment I am not in a position to do this talk justice.

**Comment by Komalbandi** [comment]
Hi,

I am keen on doing a talk on component driven development using Atomic design patterns.
Just curious has anyone done this talk?

**Comment by iamkevinv** [comment]
@Komalbandi - Sounds like a good talk - can you create a new github issue for it?  -> https://github.com/BrisJS/meetups/issues/new?body=Talk%20title:+My+Talk%0ATalk%20length:+20+min/30+min%0ATalk%20synopsis:%0AAvailable+month(s):%0AAlso:+your+Twitter+account+and+full+name+so+we+can+promote+your+talk

**Comment by adam-9001** [comment]
Hi all, saw this talk request is still open. I'd like to do a talk on how to build UI frameworks (eg. alternatives to React/Vue) using Web Components. I've opened an issue for it here: https://github.com/BrisJS/meetups/issues/477
