### ISSUE TITLE
Quiz show: 👍 or 👎

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#247]
It would be good to have a roundup of the latest language features and how/why you might use them.

**Comment by AnnaGerber** [comment]
How about this (inspired by a talk from CrikeyCon)?

Latest ES features - hot or not? 

Format: Game show
Participants: Host plus 3 or 4 volunteers to be contestants.

For each ES features:
1. The host presents a slide or two, briefly describes what it is, how to use it.
2. Contestants have signs with hot on one side and not on the other. They hold up signs to indicate whether they would use the language feature.
3. Host reveals their answer and why (contestants can chip in with their opinion if they disagree)
(For bonus points the answers could reflect the zeitgeist - based on result of polls or a survey sent out on Twitter or to the meetup participants)

Repeat for half a dozen features
Tally up the scores and announce the winner

**Comment by jwulf** [comment]
Love it!

**Comment by iamkevinv** [comment]
Let’s start wrangling people for this… I’m sure a lot of people follow newly released specs

**Comment by AnnaGerber** [comment]
After discussion with others I think this will be better in two teams of two (so we'll need 4 contestants plus one host) so that if team members disagree with each other they can banter for a bit to reach team consensus.

Ping @KoryNunn to help come up with list of features for the zeitgeist survey

**Comment by jwulf** [comment]
Async iterators: for-await-of - omg, how did we even program before that?

Optional chaining operator? You might as well be coding in COBOL without that.

**Comment by AshKyd** [comment]
Things we need:

- [ ] Suitable topics (including some newbie friendly)
- [ ] a survey to send out prior to the event (google doc?)
- [ ] Contestant one (Kory)
- [ ] Contestant two
- [ ] Contestant three
- [ ] Contestant four
- [ ] Moderator/host

Anyone keen on taking part or putting this together?

**Comment by KoryNunn** [comment]
Happy to handle survey and help gather the list of features

**Comment by AnnaGerber** [comment]
Survey results are here: https://www.surveymonkey.com/results/SM-GXBQGHG9L/
