### ISSUE TITLE
Hello Brisbane JS !! 

### ISSUE THREAD

**Issue by incessantmeraki** [BrisJS/meetups#249]
Hello everyone. My name is Ashwin.  I am from Kathmandu and have recently arrived in Brisbane. It's great that there is a vibrant JavaScript community here in Brisbane. I am super excited about attending the March's session and looking forward to meet cool people and learn new things.

**Comment by AshKyd** [comment]
Hey Ashwin.

The next meetup is here, we haven't finalised it but you can RSVP in advance: https://www.meetup.com/BrisJS/events/qwkzxnyxfbhb/

Hope to see you around!
