### ISSUE TITLE
Vector maps

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#25]
I've been playing with [vector maps](http://ash.ms/vector-slippymap/) lately. Might be fun to talk about [Leaflet](http://leafletjs.com), [geo](geojson.io)/[topojson](https://github.com/mbostock/topojson), and making things pretty.

**Comment by kevdesign** [comment]
If you have any of those related resources/slides @AshKyd and could still link them here... please do...  cheers.
