### ISSUE TITLE
Live code: Flappy Bird under 5 minutes

### ISSUE THREAD

**Issue by loklaan** [BrisJS/meetups#250]
Hey folks!

Lightning talk proposal.

Flappy Bird will save you from boredom for about **5 minutes** at a time.  
_Instead of playing it_, **let's build it**!  
With a text editor & browser!  
In vanilla JS!

---

```
1. Here is a gif of the real flappy bird.
2. Ok here we go, let's code it.
3. ????
3. Oh wow nice we did it; an ASCII Bird.
```

---

PS. Might need to revise the 5minute thing, I haven't speed-run this yet... 💁  

Inspired by a [talk at CampJS](https://www.youtube.com/watch?v=krj_TQOrS5g) by Ed Robinson a couple years ago ❤️

**Comment by loklaan** [comment]
Resources:

Source on Github
https://github.com/loklaan/talks/tree/master/2018-ascii-bird

Live Demo ([and Source](https://glitch.com/edit/#!/ascii-bird)) on Glitch
https://ascii-bird.glitch.me/

**Comment by iamkevinv** [comment]
Legendary
