### ISSUE TITLE
CSP: Can See Purpose

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#252]
Here's some docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Some questions you could cover:

* what is CSP and what problems does it solve?
* how could you use it to make your site more secure
* are there any gotchas to be aware of?
* etc, etc.

Might be a good one for someone to research :)

**Comment by AshKyd** [comment]
To the person who came and spoke to me about this, I'm super sorry but I don't remember who you were. Can you please leave a comment here with your availability? :D

**Comment by iamkevinv** [comment]
That's great @ndench :) - Are you available for the 8th october meetup?
Could you provide the following too please:

Presenter name: 
Talk title: 
Talk length: 10 min/20 min/30 min
Talk synopsis:
Available month(s):
Optional: your Twitter account so we can promote your talk

**Comment by ndench** [comment]
Yep 8th October works for me.

Presenter name: Nathan Dench
Talk title: CSP: Can See Purpose
Talk length: 20 min
Talk synopsis:
  - What is a Content Security Policy and why should I have one?
  - How can I implement it without breaking everything?
Available month(s): October (preferred), November
Twitter: https://twitter.com/nathandench

**Comment by iamkevinv** [comment]
Bring a laptop and hook it up is almost everyone's standard way of doing things. 👍 

From Brisjs.org/#present 

> The Auto & General venue is fitted out with 1080p displays mirrored throughout the venue. These support HDMI & mini DP, however audio from the laptop is not yet supported.
> There is room wide amplification for your presentation, with a lapel & hand-held mic.
> Internet is generally not available at this time. If required, you may request access to a tethered phone connection from organisers but please ensure your presentation will work offline should the worst happen.
> If you have special requirements on the night (either technical or personal), please let us know.

**Comment by iamkevinv** [comment]
Looking forward to having you there!

**Comment by joemudryk** [comment]
@ndench Hey, went to the talk last night which was quite good. Now I am looking at implementing CSP at my place of work. Did you have a copy of the slides that you used? I'm trying to find the reporting tools that you mentioned for when an XSS attack is attempted. 

Thank you

**Comment by ndench** [comment]
Thanks @joemudryk! Here's a [link to my slides](https://slides.com/ndench/csp-can-see-purpose), the reporting tool I mentioned was [report-uri.com](https://report-uri.com/) which keeps track of all your CSP violations.

**Comment by joemudryk** [comment]
Champion, thank you

> Thanks @joemudryk! Here's a [link to my slides](https://slides.com/ndench/csp-can-see-purpose), the reporting tool I mentioned was [report-uri.com](https://report-uri.com/) which keeps track of all your CSP violations.
> 
> Also, here is the [blog post](https://ndench.github.io/security/csp-can-see-purpose) that goes along with the talk, it has a bit more info than the slides.

**Comment by iamkevinv** [comment]
Hi! I presume this went well and Kory made you feel welcome when he hosted Oct. Thanks for sharing @ndench :)

**Comment by ndench** [comment]
Yes it went great, thanks @iamkevinv :smile:
