### ISSUE TITLE
Javascript: You Might Not Need It

### ISSUE THREAD

**Issue by srsgores** [BrisJS/meetups#253]
I propose a rather controversial talk about the excessive "need" for javascript tools in today's modern dev environments.  [Similar to the aptly-named website](http://youmightnotneedjs.com/), or [this post on slack](https://slack-files.com/T03JT4FC2-F151AAF7A-13fe6f98da), I propose a look at the following subtopics:

* Why we used frameworks to begin with: how the rise of jQuery introduced the "need" for _YAFS_ (yet another framework syndrome)
* Difference between framework vs. tool
* Pure HTML and CSS replacements for JS: `<details>`, `<meter>`, `<progress>`, `<dialog>`,  `<input type="checkbox">` menu "hack"
* Vanilla JS code structuring techniques: `Proxy` (`Object.observe`), structuring code with ES2015 `class`, `import`, polyfilling browser support
* Vanilla JS performance and benchmarking

Background: I am from Canada originally, but will be working and living in Brisbane for a year from May 2018.  Thus, I could only potentially deliver this talk on June or July.

**Comment by iamkevinv** [comment]
Looking forward to having you in Brisbane @srsgores :-)

**Comment by srsgores** [comment]
Can we bump the time up to 30-40 mins?  I want time to take questions

**Comment by iamkevinv** [comment]
We definitely have time for questions after every 20 min talk - so consider it included :-)

**Comment by srsgores** [comment]
Ok, but I **do** want 30 mins for the presentation, so I have room for extra material.  Please let me know if you can accommodate this request.   The presentation may not take quite that, but having the extra flexibility will help to give me peace of mind while I prepare the material.

**Comment by iamkevinv** [comment]
Yep, that shouldn't be an issue. We can give you the 30. Let me know how you go with your material and if you need any info :)

if you're curious... We stopped regularly offering the 40 min headline spot as people's attention tends to drift after 20, and it allows more diversity in topics through the night which the community was craving. So now we do 20's, and 10-15's. Short snappy topics have also meant that networking time with the audience means you can further the conversation personally over pizza with people for another 25 min. :-)

**Comment by srsgores** [comment]
I totally understand, and this is more of a peace of mind thing.  I want to allow for questions as I go, or to have the ability to do so.  I will update once I settle in to Brisbane and have a better idea of the duration of my material.

**Comment by iamkevinv** [comment]
Hey @srsgores - I'm checking in to see if you're still keen to present this month? Just lining up confirmations to announce the lineup for the night. Thanks!

**Comment by srsgores** [comment]
Thanks for following up.  Unfortunately, my travel has taken me to North QLD, so I will not be able to present until July.  Sorry for any inconvenience.  July should be no problem, though, and I'm currently planning to be in Brisbane for that time.

**Comment by srsgores** [comment]
Slides about half-done, and will finish in the next week or so: [view slides here](https://docs.google.com/presentation/d/1jGkXldJ-W2b388EAtJwjwQc81EXJWdvNFzpJbSOpC-Y/edit?usp=sharing)

**Comment by iamkevinv** [comment]
Sounds good @srsgores
