### ISSUE TITLE
Cross domain communication: I created a new design pattern!

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#258]
I'm excited about this one, I know literally nothing about it.

> Armagan is currently works at Red Hat as a software engineer and enjoys developing web-based systems with Javascript. She is also organiser of NodeGirls Brisbane.
> In this talk, we will learn the ins and outs of cross-domain communication in Javascript.

https://mobile.twitter.com/broccolinisoup

**Comment by iamkevinv** [comment]
@broccolinisoup - Some folks have asked for your slides if possible at #297, so perhaps we can link them here? :) Hope you can present again this year!
