### ISSUE TITLE
Intro to TensorFlow JS

### ISSUE THREAD

**Issue by sarah-j-smith** [BrisJS/meetups#261]
Talk title: *What is TensorFlow JS?*
Talk length: 20 min
Talk synopsis: Google has just released [TensorFlow JS](https://github.com/tensorflow/tfjs) and yes, its an AI thing for Javascript.  But what does it mean, what's it good for, and how can I get started doing something with it?
Available month(s): April
Optional: [@sarah_j_smith](http://twitter.com/sarah_j_smith)

**Comment by AshKyd** [comment]
Too cool, I'm very excited to hear this one. Thanks @sarah-j-smith!

**Comment by iamkevinv** [comment]
Hi @sarah-j-smith - Could you link any resources here for folks? Slides? Examples for more reading? THANKS!

**Comment by iamkevinv** [comment]
Hi @sarah-j-smith - just a reminder that i'm closing this issue off, but if you add anything to provide some resources i'll add the resources shared label. Thanks!
