### ISSUE TITLE
Fixed Mindset vs Growth Mindset

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#263]
Jordan has offered his talk “Fixed Mindset vs Growth Mindset” at the May meetup.

https://mobile.twitter.com/JawdinMorris

**Comment by jawdinmorris** [comment]
Duration: 10 Minutes
A short presentation on the damaging effects of a fixed mindset and how you can foster a growth mindset in development and other areas of life.

**Comment by AshKyd** [comment]
Love it, thanks.

**Comment by AshKyd** [comment]
@jawdinmorris just wanted to confirm you're good for the next meetup?

**Comment by AshKyd** [comment]
Correct! And thanks so much. You're locked in ^_^

**Comment by iamkevinv** [comment]
Thanks folks! Appreciate volunteering @jawdinmorris

**Comment by iamkevinv** [comment]
Thanks heaps for your talk @jawdinmorris - could you please pop up a link to your slides here? Thanks :)
