### ISSUE TITLE
How to build a software product, and an entire developer career by cutting and pasting code

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#265]
"Good artists borrow, great artists steal." - Pablo Picasso

In this thrilling BrisJS live event, I will build an application based on audience requests, live, on-stage, purely by cutting and pasting code from the internet.

The purpose of this talk is to demonstrate the power of cut-and-paste coding, give an overview of the vast amount of resources that are available to you on the internet, and subtly educate on the meta-skills involved in code research.

Also: entertainment.

**Comment by AshKyd** [comment]
Love it. Also love that it's validating something everyone does, but that may have a stigma for newbies. How long do you need?

**Comment by iamkevinv** [comment]
Sounds good @jwulf - i'd also love a blurb about how you go about selecting good code vs bad code

**Comment by iamkevinv** [comment]
Which month would you like to attempt this @jwulf :)

**Comment by iamkevinv** [comment]
@jwulf - Keen on this talk? We have Oct 8 coming up.

**Comment by iamkevinv** [comment]
Just a friendly re-ping @jwulf :)

**Comment by jwulf** [comment]
Yo, I won't reliably make it to BrisJS this month. Param and I are competing in the ICN QLD State Titles on Saturday and Sunday. I don't know how I will be on Monday, so I won't commit to the talk this month!

**Comment by iamkevinv** [comment]
Thanks for the info mate - will move this to next month.

**Comment by iamkevinv** [comment]
Have we lost you mr @jwulf? Thoughts on Dec or Feb targets?

**Comment by jwulf** [comment]
When is the December Meetup?

**Comment by iamkevinv** [comment]
December 3rd

**Comment by iamkevinv** [comment]
@jwulf are you wanting this closed or want to still do it sometime?

**Comment by iamkevinv** [comment]
Re-open if you want to do this one @jwulf - closing for now to keep things neat
