### ISSUE TITLE
Top5.JS - "Top 5 JS Blog Posts/ things This Month - You Won't Believe #7!!!"

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#266]
A regular slot each month, maximum 8 minutes in length, with a rapid-fire overview of the top ten blog posts of the month. The list then gets released on Twitter for people to follow along.

During the month, peeps can submit cool and interesting blog posts that they find as comments on that month's blogosphere issue. Then, on the night - "counting down this month's top ten!"

I'd be happy to present this, and to find others to present it.

**Comment by AshKyd** [comment]
This sounds awesome, I'm onboard!

That said if it's gonna be a regular thing I'd suggest:
1. It's gotta be short. Maybe make it the top 5 to keep it achievable/varied
1. Reckon you could do it on slides.com or something so you can jump right in after Kev's intro without needing to set up?

Are you thinking of setting up a “submit ur tips” google form or something? How do you see that working?

**Comment by jwulf** [comment]
Yeah, exactly - people can submit during the month. They could do it via a Google Form, or maybe by tagging BrisJS in tweets?

Top 5 & slides.com sounds great.

**Comment by iamkevinv** [comment]
@jwulf Could you pop up the link to your slides please?

**Comment by iamkevinv** [comment]
Rolling this one over for the next month

**Comment by iamkevinv** [comment]
Rolling this one over for next month again!

**Comment by iamkevinv** [comment]
I've edited this for Top5.js instead as you mentioned above and last session.

**Comment by iamkevinv** [comment]
@jwulf - ready to reprise your role on Aug 6th?

**Comment by jwulf** [comment]
Yes. Can I go just before the pizza break please?

**Comment by iamkevinv** [comment]
@jwulf - Reprising this one next week in Sept? 👍 
I'll add you to the list if you confirm. Thanks :)

**Comment by jwulf** [comment]
Yep, I'm down. I'm competing in the Coffs Harbour Classic on September 8, so I'll be right in the middle of my burndown. Can you please put me before the break so I can slip out early if I need to?

**Comment by iamkevinv** [comment]
Sure mate, happy to oblige :) Thanks for helping out yet again!

**Comment by iamkevinv** [comment]
Moving to next month for the perpetual JS fest!

**Comment by iamkevinv** [comment]
If we get https://github.com/BrisJS/meetups/issues/265 in for oct... you'd be off the hook for this

**Comment by iamkevinv** [comment]
Please let me know if you want to revive this at any point in 2019. Cheers
