### ISSUE TITLE
Fast functional frontends in Elm and Javascript

### ISSUE THREAD

**Issue by unixbigot** [BrisJS/meetups#272]
Talk title: Fast functional frontends in Elm and Javascript
Talk length: 20
Talk synopsis:  Elm is a lightweight functional language for the browser that compiles to javascript.  Most elm tutorials show you a hello world or a small single page app and leave you at that.  This presentation gives a brief introduction to elm and then dives in to how to integrate with existing
"heavyweight javascript" code such as Oauth providers, and mapping engines.

These techniques will help you meld elm and off-the-shelf libraries, or even gradually port your
JS app to Elm.

Available month(s): jun
Optional: @unixbigot

**Comment by iamkevinv** [comment]
@unixbigot - i found this oldie in our issues... looks like it could benefit from linking some resources if you still have them!? Otherwise we'll just hit close :) Thanks!

**Comment by unixbigot** [comment]
I’ll link slides and videos of another delivery

**Comment by unixbigot** [comment]
Video and slides for this talk are [here](http://christopher.biggs.id.au/talk/2018-05-23-functional-frontends-with-elm/)

**Comment by unixbigot** [comment]
@iamkevinv slides+video now linked.

**Comment by iamkevinv** [comment]
Wonderful! thanks :)
