### ISSUE TITLE
The Widget Machine - Angular, Web Components, Forms

### ISSUE THREAD

**Issue by rapelt** [BrisJS/meetups#273]
Talk title: The Widget Machine
Talk length: 15 minutes
Talk synopsis:
"The Widget Machine" is a cool product I developed for a client using Angular that allows non-developers to rapid prototype "Widgets" with in minutes through configuration files.

Available month(s): Not October

**Comment by iamkevinv** [comment]
Hi @rapelt - are you still interested in presenting at our coming July meetup in a few weeks?

**Comment by iamkevinv** [comment]
Hi @rapelt - can i get your full name for the meetup description and slides? I'll go with Rebekah for now until i hear back. Thanks :)

**Comment by rapelt** [comment]
Rebekah Higgins is my last name (got married but haven't change my email yet).

**Comment by rapelt** [comment]
I have my talk on Angular Forms but I am just finishing off one on Micro Front ends and Web Components that could be a better fit for Bris JS. So here are my Angular Forms slides but how would you feel if I did my micro front ends talk?
[widget-machine.pdf](https://github.com/BrisJS/meetups/files/2139415/widget-machine.pdf)

**Comment by iamkevinv** [comment]
Thanks for the info @rapelt ...
I didn't realise these were actually separate talk proposals!? How exciting. 👍 
More than happy for you to present whatever you feel is best - depending on what you were aiming for you may actually be able to pull together two talks into the one slot?

To help clarify for myself...  "Widget Machine" is for Angular forms predominantly? This would still be totally fine to present - you'll have plenty of interested folks. Slides look great btw. This could easily be a 20min standard talk length.
Then there's a Microfrontends+WC talk also upcoming? ... I actually put up my own talk about this just this morning before i noticed your comment!! How funny is that! Everything happens in pairs.
This isn't a problem at all though; there's plenty of opportunity to cover these topics more than once, and considering i haven't really 'written' mine yet you totally beat me to it. I can re-visit some months after or something too.

If you can clarify for me the separation or combination of the talks that would be great... we can actually put up separate github issues for it too that way for scheduling.

Thanks!
- Kev

**Comment by iamkevinv** [comment]
They sound very complementary which is awesome. Since we already put Widget machine on the meetup announcement, i'm slightly favouring that, so people know what they are getting and have already RSVP'd to. Very happy to have you back to present the follow up so to speak.
Sound good?

**Comment by rapelt** [comment]
Okeydokey. Thanks.

I look forward to seeing your Micro Front end talk.

**Comment by slimlime** [comment]
Cool! Sounds like interesting talk topics. 🎉

**Comment by iamkevinv** [comment]
Sounds like you might beat me to it 🥇 
Hopefully we can compare notes on the content on Monday. 👍

**Comment by iamkevinv** [comment]
PS: If you're keen @rapelt - please feel free to put up another github issue here to have your microfrontend talk available too if you can 👍 

Maybe a proforma here to save you time below... feel free to edit however you'd like of course:
---
Talk title: Microfrontends with Web Components
Presenter name: Rebekah Higgins
Talk length: 20min
Talk synopsis: "Discussing why micro front ends are necessary and how we can build them with Web Components."
Available month(s): Not October

**Comment by iamkevinv** [comment]
Thanks for your talk @rapelt - are the links to the slides here still correct ( https://github.com/BrisJS/meetups/files/2139415/widget-machine.pdf ?? ). If so i'd appreciate a link so we can attach it to the video when we upload and process that.
Cheers!

**Comment by rapelt** [comment]
Yes, they are correct.

On Tue, Jul 3, 2018 at 12:14 PM, Kevin Vanderbeken <notifications@github.com
