### ISSUE TITLE
Front-End Engineer Job in Brisbane at Communic8

### ISSUE THREAD

**Issue by ljhdut** [BrisJS/meetups#275]
## Description
Do you love working with a highly-skilled, fast-paced team in a start-up environment?
We’re redefining organisational communication through an innovative and unique
solution that enables large companies and small businesses to better communicate,
discover, and engage with their employees and customers.

In support of this vision, we maintain a relentless focus on product innovation and
great user experience, with the objective of providing a communication platform that
is convenient, simple, efficient, and fun to use that supports millions of users.
To help support this vision, we're looking for a front-end developer who can bring
more than just technical depth, we’re looking for a team member who can make an
impact as an individual by bringing fresh ideas and further innovation to our product
offering. This person needs to be versatile and enthusiastic to take on new problems
as we continue to push our technology forward.

If you’re looking for an opportunity to be a part something bigger than yourself,
playing a key role in shaping an innovative and new product, and want the fun and
feel of a start-up company, we’d love to chat!

If you are holding out for an opportunity to:
• Make a huge impact as an individual
• Be part of a team of smart and passionate professionals who will challenge
you to grow every day
• Solve difficult challenges using your expertise in coding elegant and practical
solutions
• Create an application at a large scale

And you are experienced with…
• Writing highly efficient, testable, quality code written with modern web
development technologies
• Obsessing over creating world class user experiences
• Succeeding as a key contributor to technical projects
• Taking ownership and doing whatever it takes to get the job done

And you constantly look for opportunities to…
• Innovate, simplify, reduce waste, and increase efficiencies
• Use data to make decisions and validate assumptions
• Learn from others and help grow those around you

Then this is your opportunity.

### Minimum qualifications:
• Relevant tertiary education/degree or related technical field or equivalent
practical experience
• Demonstrated experience working with web development fundamentals
(JavaScript, HTML5, CSS3)
• Demonstrated experience with at least some current frameworks (React,
VueJS, AngularJS) and technologies (SCSS/SASS/LESS, Gulp, TypeScript)
• Comes from a development background developing user-facing software with
strong problem-solving, communication and analytical skills
• Has previous development experience with cross-browser compatibility and
responsive website design
• Demonstrated experience with at least some current style frameworks (e.g.
Material Design)
### Preferred qualifications:
• Communicating with users, other technical teams, and management to collect
requirements, describe software product features, technical designs, and
product strategy
• Knowledge of software engineering best practices for the full software
development life cycle, including Agile methodologies, coding standards, code
reviews, source control management, build processes, testing, and operations
• The ability to work quickly toward tight deadlines, and make smart trade-offs
between speed, accuracy, and maintainability
• Experience with the latest web standards, including HTML5 and CSS3.
• Strong sense of web design and attuned to the fundamentals of user
experience
• RESTful web app development
• Git-based workflow experience (e.g. GitFlow)
• Package and task manager experience (e.g. npm / bower / Gulp / Grunt)
## Job Details
• Title: Front-End Engineer
• Location: Brisbane, Queensland Australia (Brisbane CBD & Inner Suburbs)
• Employment Type: Full time
• Apply: Email careers@communic8group.com with an accurate and up to date
CV.

**Comment by AshKyd** [comment]
Thanks @ljhdut. Which company is this for?

**Comment by ljhdut** [comment]
@AshKyd , it is a startup company "Communic8 Group Pty Ltd"

**Comment by iamkevinv** [comment]
How's it going @ljhdut - is this still current?
