### ISSUE TITLE
Data Analysis in JavaScript - yes it can be done!

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#276]
Talk title: Data Analysis in JavaScript - yes it can be done!
Talk length: 30 min - 40 min
Talk synopsis:
Why are we always told that we need to do our data analysis in Python? What's wrong with JavaScript that we can't use it for data analysis? Well, nothing really - you probably aren't surprised to hear that that JavaScript is an extremely capable language and it's tools and ecosystem for data analysis is growing every day.

Join Ashley Davis, local developer and author of Data Wrangling with JavaScript, for a discussion of data analysis in JavaScript. There'll be a live demonstration and you'll learn practical and easy data analysis and visualization techniques that you can apply now in JavaScript. You'll be able to take these techniques away with you and start applying them to your own real world scenarios.

Available month(s): August or September.
Twitter: ashleydavis75
Email: ashley@codecapers.com.au

**Comment by iamkevinv** [comment]
Thanks @ashleydavis :)

**Comment by AshKyd** [comment]
Nice one, can't wait to see this.

Probably best to shoot for 30 mins with this one fyi. The longer they go, the more folks tune out so we've been trying to keep 'em short & sweet :)

**Comment by ashleydavis** [comment]
30 mins is good.

I've got two early access copies of the ebook to give away on the night.

I've also got a 40% discount code for everyone else.

I was thinking we give one a way at random to anyone that turns up on the night and another one at random to anyone who has asked a question.

What do you think?

Do you guys have anyway to draw a competition like this?

Ultimately I just need the two email addresses of the winners.

**Comment by ashleydavis** [comment]
Am I good to go for this talk on the 6th August?

**Comment by iamkevinv** [comment]
Absolutely... happy to have you there :)

**Comment by ashleydavis** [comment]
Great. I'd like to do a random giveaway of the e-version of my book.

I have two vouchers to give away. One I'd like to giveaway at random to anyone that turns up.

The other I'd like to giveaway at random to anyone who has asked a question.

Are you able to organise a random draw?

**Comment by iamkevinv** [comment]
That sounds great - not sure how to randomise it... i'll have to come up with a way!
I'm thinking two capped numbers generated... one a row, another a seat number from the left.

**Comment by ashleydavis** [comment]
That sounds good.

What about just for people who answer a question? Or should I keep it simple and just give away two copies to whomever is there?

**Comment by iamkevinv** [comment]
No you can definitely do both... we'll take questions after your talk :) 
Surprise people and don't tell them in advance... whoever asks a question will be very genuinely rewarded!

**Comment by ashleydavis** [comment]
Hey @iamkevinv, did you figure out a way to give away some copies of my book at random?

**Comment by iamkevinv** [comment]
/**
 * Returns a random integer between min (inclusive) and max (inclusive)
 * Using Math.round() will give you a non-uniform distribution!
 */
function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
console.log(`We have a winner at:`,`row ${getRandomInt(1, 10)}`, `seat ${getRandomInt(1, 10)}`);

**Comment by ashleydavis** [comment]
Hah cool

**Comment by iamkevinv** [comment]
Thanks again for your talk! Any resources you can share here on this thread would be great. Did you manage to catch up with the winners of your book?

**Comment by ashleydavis** [comment]
My pleasure. I gave the codes to the winners and told them to email if they have any problems getting it.

Slides: https://www.slideshare.net/AshleyDavis33/data-analysis-in-javascript

GitHub repo: https://github.com/ashleydavis/brisjs-data-analysis-talk

**Comment by iamkevinv** [comment]
Cheers!
