### ISSUE TITLE
Micro-frontends with Web Components

### ISSUE THREAD

**Issue by rapelt** [BrisJS/meetups#279]
Talk title: Micro-frontends with Web Components
Presenter name: Rebekah Higgins
Talk length: 20min
Talk synopsis: "Discussing why micro front ends are necessary and how we can build them with Web Components."
Available month(s): Not November

**Comment by iamkevinv** [comment]
@rapelt - My talk on this topic will happen at CampJS this year instead, so if you're keen - you could always present yours at the upcoming BrisJS which is the monday before the camp. It's late notice but maybe you'd be keen to show this on August 6th?

**Comment by iamkevinv** [comment]
Are you keen on getting this one into a brisjs presentation @rapelt ? We have next week Monday, September 3, 2018, or i can pop it in for oct?

**Comment by iamkevinv** [comment]
We're down to the wire for confirming the talks, so i'll just give you some more breathing room and maybe you're keen for Oct? :)

**Comment by iamkevinv** [comment]
Ping again @rapelt :)

**Comment by iamkevinv** [comment]
Much appreciate the information @rapelt - appreciate your involvement at any time in the future :)
