### ISSUE TITLE
Filling the holes in google's analytics

### ISSUE THREAD

**Issue by benoneal** [BrisJS/meetups#280]
I've recently implemented a solution to reliably and accurately track and chart Time On Page, which is something google's analytics platform is _woefully_ inaccurate about. I could give a short (15-20mins) talk on the unexpected challenges and pitfalls I had to overcome to give visibility to this metric, which, for our business, was a critical blind spot. 

The talk would also be more generally applicable to other data gathering and analysis problems, and would showcase how to rapidly prototype and give meaningful visibility to data without implementing a full-blown integrated admin dashboard.

**Comment by iamkevinv** [comment]
That sounds pretty neat @benoneal - always happy to have you there
Can you give me some potential talk details?

Full name: Ben O'Neal
Talk title: 
Talk length: 20 min/40 min
Talk synopsis:
Available month(s):
Optional: your Twitter account so we can promote your talk

Thanks!

**Comment by benoneal** [comment]
Full name: Ben O'Neal
Talk title: Filling the holes in Google's Analytics
Talk length: 20 min
Talk synopsis: Reliably tracking user engagement is essentially impossible using Google's Analytics. To track this data yourself, you'll need to overcome a variety of frustrating challenges. Once you have the data, you'll need to make it useful, and we'll cover how to do all this in an MVP fashion.
Available month(s): September/October

**Comment by iamkevinv** [comment]
Thanks again @benoneal - can i confirm you for next week's lineup (It's on Monday, September 3, 2018)? I've slipped getting the announcement out due to various health issues, i do apologise! I'd like to send that out ASAP. Thanks....

**Comment by benoneal** [comment]
@iamkevinv Sorry to hear that. Hope you're feeling better. The more I think about this talk the more I think it's not really worth a full slot. Probably best dealt with as a lightning talk, otherwise the rest would just be my waxing poetic about my life story leading up to solving that problem.

**Comment by iamkevinv** [comment]
Haha that's totally fine too @benoneal :) Nobody minds if you wax-lyrical about the life and times of @benoneal! But up to you. You thinking like 10-15min? A normal slot is only 20mins.
If this is okay, i'll confirm you for monday?

**Comment by benoneal** [comment]
I can probably push it out to 15mins. Sure, let's lock it in.

**Comment by iamkevinv** [comment]
Are you on twitter @benoneal ?

**Comment by benoneal** [comment]
Technically yes: https://twitter.com/BenONealUX

**Comment by iamkevinv** [comment]
Thanks for this @benoneal - if you have some resources to share... please feel free to add them here.

**Comment by benoneal** [comment]
Sure. Slides: https://docs.google.com/presentation/d/1lBpOkzjT70LHbTVp8XuMZP9lG8fNR68P5Vp2dEj5zmA/edit?usp=sharing

Can't share source code this time.

(Also I think next time, just book me out for the whole night... _especially_ if I volunteer for a "lightning" talk) 😆
