### ISSUE TITLE
CampJS + Ludum Dare + making games

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#281]
Feat. Lilly & Nathan.

15 minutes at the August meetup to tie in with CampJS.

**Comment by iamkevinv** [comment]
What will be sent:

> Join us for some information on the tools and process around making JavaScript powered games. Nathan & Lilly have years of experience making games at hackathons and can let you in on a sneak peak of their CampJS presentation for working with Phaser.js and other handy tools for creating graphics, levels, and sound effects.

**Comment by iamkevinv** [comment]
Any more resources we could share here would be good :) Thanks again Nathan and Lilly!

**Comment by nathanhoad** [comment]
Check out the [Ludum Dare](https://ldjam.com) site for info on the competition.

The tools that we talked about (and more!)

* Engine: [Phaser](https://phaser.io)
  * Check out [Lilly's Phaser example](https://github.com/lillypiri/CampJS-LudumDare)
  * Also, have a look through [the source code to Pixel Beach](https://github.com/nathanhoad/pixelbeach), a full JavaScript/Electron powered game. It's a more fleshed out version of something we made for Node Knockout last year
* Pixel editor: [Aseprite](https://www.aseprite.org)
  * There's a free version that was forked before the license change called [LibreSprite](https://github.com/LibreSprite/LibreSprite) (I haven't tried it so I'm not sure what features are missing)
  * [Piskel](https://www.piskelapp.com/) is a free online pixel editor with a downloadable version
* Level editor: [Tiled](https://www.mapeditor.org/)
* Sound effects: [Bfxr](https://www.bfxr.net/)
