### ISSUE TITLE
Full Stack React / Node.js Developer at Askable

### ISSUE THREAD

**Issue by xicovarisco** [BrisJS/meetups#282]
![dark](https://user-images.githubusercontent.com/2739233/42983132-57641d6a-8c28-11e8-98d0-92eaabcde256.png)

### About us
We're a small team in Brissy of 11 people who are building software to take on the $3 billion dollar Australian market research industry. 

Askable started in July 2017 as a side project for us at Orange Digital, a digital agency. It was a simple way for UX designers to find participants for their usability tests. Since then we've grown to $100k / month in revenue and become the preferred choice for companies like Woolies, Qantas, News.com.au and more.

### About the role
You will be using modern technologies like React / React Native / Node.js and GraphQL on a daily basis. Askable have been growing exponentially and we're hiring new developers for the first time, so there's a very high chance you're gonna get involved in most of our decisions from now onwards. 

### Get to know more and Apply
Get more information and apply through [https://au.askable.com/jobs](https://au.askable.com/jobs)

**Comment by iamkevinv** [comment]
@xicovarisco - Is this position still current? Should it be closed? Thanks!

**Comment by xicovarisco** [comment]
It should be closed mate!
