### ISSUE TITLE
Programmer's Health: A Space Time Odyssey

### ISSUE THREAD

**Issue by srsgores** [BrisJS/meetups#283]
*You are what you eat*: words, coupled with increasing studies released in the past decade which convinced me to really take a look at my dietary choices as a programmer. __I propose a talk to go over my journey to plant-based nutrition__: a story about a programmer's perspective on health, how to understand nutrition, what to look for in foods, and strategies to maintain a healthy lifestyle as a programmer.  It's a catalogue of my trials and tribulations on finding plant-based lifestyle helped me to lose 20 kgs in 6 weeks.  It's not a talk of "this is the one-size diet that fits all"; rather, it's a talk about strategies to adapting a healthier lifestyle, how to overcome nutrition obstacles during a lifestyle transition, and how to be more social along the way (having a social life is really important!).

## Today's Workplaces are Unhealthy
Today's workplaces promote a largely sedentary work lifestyle where we might be lucky to get outside on a daily basis.  We spend 6-8 hours at a minimum staring at screens, often never to speak to anyone else outside of IM (Slack, Mattermost, etc.).  By the end of the day, we just want to relax on the couch, watch some Netflix.  Working out is seldom an option for our busy lives; we have families, obligations, and sometimes even second jobs to maintain enough income to support any combination thereof.

But what if we could feel good *and* still have time for our loved ones?

## Let's Debunk Programmer Health Myths
I want to clear the air, and debunk myths about health and nutrition -- to set the record straight based on years of scientific research.  I think nutrition can be fun and not a boring topic:

* Standing desks: it probably doesn't matter
* Why you should stop eating meat to avoid cancer (WHO class 1 carcinogen)
* Psychological health: open office plans are not the answer
* Building workplaces to foster creativity through communal cooking
* Walking meetings: a newer healthy way to meet
* Vitamins in tablets: probably a scam, and unregulated
* Sleep: stop setting alarms
* Blue light filters: not the answer... how to start reading or listening to audiobooks
* Maintaining a social life: reward yourself with a sense of exploration and meeting new people
* Food shopping: make it simple by eating whole foods only.  Examples of how I shop at the supermarket
* Reducing workload and commitments: treat your life like an agile project, and reduce scope to live a happier life
* Pedometers: steps aren't everything; how much walking is enough, and how long we need to sustain it to get a benefit.  A review of the scientific data on this, which indicates 45 minutes of *brisk* walking, uninterrupted
* Recipes for life: what recipes worked for my transition to a whole food, plant-based lifestyle: smoothies, curries, and pastas.  Rough recipes explained in ratios and not instructions
* Understanding and reading scientific studies.  What to look for in studies and how to sift out the cruft
* How to enjoy cooking: making food a part of your life

## How to Take Action Today
Seeing is believing.  A look at some of the staples I've eaten over the years, how long each of those meals took to prepare, and the nutrients each provides.

You can make the transition by keeping yourself up to date on the scientific research and healthy foods to include in your diet:

* Online resources for tips on preparing and motivating yourself to eat healthy
* Unpaid, trusted, online scientific journals
* YouTube channels to follow for meal inspiration
* Documentaries and movies you can watch for motivation and reference on this whole-food, plant-based lifestyle
* Strategies to ease into a plant-based diet

## Let's Change the Programmer Nutrition Landscape
The talk will likely take a 30-minute slot.  I think this talk would largely benefit the programming community to encourage better, healthier workplaces.

**Comment by ichpuchtli** [comment]
I'm super interested in this talk. I've trying to find ways to make my work life balance healthier for a while too. 

I recently adopted several of the recommendations in this book by Dr Rangan Chatterjee (A leading function / lifestyle medicine practitioner) 

https://www.amazon.com.au/Pillar-Plan-Relax-Longer-Healthier/dp/0241303559.

Including:
 - [x] No screen time 90mins before bed
 - [x] No Caffeine before noon
 - [x] A daily stillness practice (meditation, relaxation, mindfulness) 
 - [x] A dynamic movement regime (strength, cardio, body weight stuff)
 - [x] Turning off app notifications (easy and immediate win) (reducing any stressors really)
 - [x] Reducing processed carbs and sugars and introducing good fats (LCHF) (ie eat wholefoods)
 - [x] Waking up at the same time everyday to maintain normal circadian rhythm
 - [x] 20 minutes of sun exposure in the morning (again helps circadian rhythm)
 - [x] Compressed eating window (I only eat between ~11am <-> ~5pm)

I also highly recommend P Mathew Walker's Book "Why we sleep" 
https://www.amazon.com.au/Why-We-Sleep-Unlocking-Dreams/dp/1501144316 

Gut Microbiome / Gut-Brain Connection is another really interesting space.
https://www.amazon.com.au/Gut-inside-story-bodys-under-rated-ebook/dp/B00VGJMAHA/ref=sr_1_1?s=books&ie=UTF8&qid=1533605852&sr=1-1&keywords=gut

Mitochondrial health is also super interesting. I'm looking for other good books on Mitochondria atm but this is one.
https://www.amazon.com.au/Head-Strong-Bulletproof-Activate-Faster-ebook/dp/B01I9BQBEU/ref=pd_sim_351_2?_encoding=UTF8&pd_rd_i=B01I9BQBEU&pd_rd_r=9158e219-99e2-11e8-aa87-c717d3c8781b&pd_rd_w=nXdZK&pd_rd_wg=2AumH&pf_rd_i=desktop-dp-sims&pf_rd_m=ANEGB3WVEVKZB&pf_rd_p=6390869983034446746&pf_rd_r=SB89W0J4SQVYHP0K2AZ3&pf_rd_s=desktop-dp-sims&pf_rd_t=40701&psc=1&refRID=SB89W0J4SQVYHP0K2AZ3

Really look forward to this talk I don't know why its not talked about more often.

**Comment by iamkevinv** [comment]
Hi @srsgores - Thanks for your contribution again - can i confirm you for next week's lineup (It's on Monday, September 3, 2018)? I've slipped getting the announcement out due to various health issues (ironically)!
I'd like to send that out ASAP. Thanks....

**Comment by srsgores** [comment]
Actually, **no**, I will not be able to deliver the talk until **December** at the earliest.  I think that will be better for everyone, as they set New Year's resolutions.

**Comment by srsgores** [comment]
So as we move towards the December meetup, what date will it fall on?  I need to determine whether I would still be able to deliver the talk because I may not be in the Brisbane area

**Comment by iamkevinv** [comment]
@srsgores - Meetup.com says Dec 3rd. Hope you can make it :)

**Comment by srsgores** [comment]
Hey @iamkevinv

Sorry to say that with the timing of my return to Australia, I **won't*** be able to present this December.

Perhaps this talk will better suit a January, with everyone setting New Year's resolutions.

Let me know what you think.

**Comment by iamkevinv** [comment]
We’re back in Feb - so we can target that one ☝️

**Comment by srsgores** [comment]
I've got the slides [up here](https://docs.google.com/presentation/d/1xdSl3_oG9pVJ-choI0Ve83-aw21vr3oifTme5KbMWVM/edit?usp=sharing)

Get ready for more memes!

**Comment by iamkevinv** [comment]
Hi @srsgores - Can i confirm you for next week please?

**Comment by srsgores** [comment]
Yes, I'll be good to go 👍
