### ISSUE TITLE
Web scraping with JavaScript

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#284]
Web scraping is the worst way to retrieve data. Scripts that do web scraping are tedious to write, inherently fragile, dependent on the structure the HTML and prone to breaking. 

So why would you ever want to do web scraping? Normally we'd acquire data from a data file (CSV or JSON), a REST API or a database. Sometimes though data isn't so readily accessible and we might find that the only way to get the data we need is to harvest it from web pages. This can be simple enough for simple web pages, we just do HTTP requests to get the HTML and use Cheerio (from npm) to extract the data from the page.

What happens though when things get more complicated? Say we need to authenticate before we can access a web page. Or maybe we have to wait until browser-based JavaScript has evaluated and populated the page before we can harvest the data. For situations like this we need to bring out the big guns and use a headless browser to load the web page before we extract the data. 

Join Ashley Davis, local developer and author of the book Data Wrangling with JavaScript, for a deep dive into web scraping. We'll tackle simple web scraping with request-promise and Cheerio from npm. For the more serious scraping we'll have to pull the Nightmare headless browser API from a toolkit.  We'll have some live coding and figure out how to extract data from real web site.

I could fit this talk into a 10-20 minute time slot. There's probably enough here to do a 30 min talk if necessary.

**Comment by iamkevinv** [comment]
Thanks again @ashleydavis for the multiple submissions (i love that!) - can i confirm any of these for you for next week's lineup (It's on Monday, September 3, 2018)? I've slipped getting the announcement out due to various health issues, i do apologise! I'd like to send that out ASAP.
I figure since one of them you said you'd need several months of prep... that leaves us with, [this one](https://github.com/BrisJS/meetups/issues/284), https://github.com/BrisJS/meetups/issues/286, or https://github.com/BrisJS/meetups/issues/286 ?

**Comment by ashleydavis** [comment]
Yeah sounds cool. This talk on web scraping is the quickest to put together.

I can make it fit 10-15 mins. Should be mostly live coding.

For the finance related talks... Kory and I were thinking of doing combined lightning talks on the topic at some point.

For the react  flow chart editor talk... I need to finish the code for it and I've been too busy in recent months to go back to it. It would be nice to talk about it early in the new year though.

**Comment by iamkevinv** [comment]
Awesome... sounds like a GO with this talk then! I'll add it up! Thanks!

**Comment by ashleydavis** [comment]
Slides: https://www.slideshare.net/AshleyDavis33/web-scraping-112846350

Code: https://github.com/ashleydavis/brisjs-web-scraping-talk

**Comment by iamkevinv** [comment]
Thanks so much for sharing!

**Comment by ashleydavis** [comment]
Was a good night!
