### ISSUE TITLE
Experimenting with fully algorthimic trading in JavaScript

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#286]
Alternate humorous title: How to automate losing money

Talk time: 10-15 mins.

Join Ashley Davis, local developer and author of Data Wrangling with JavaScript for overview of his experiments in algorithmic trading using the IG REST API. After successful stock trading in the Australia market on a longer term basis, Ash was keen to get into some fully automated short-term algorithmic trading. Unfortunately it's not as easy as you would think... the technical aspects actually turn out to be fairly straightforward, but coming up with trading strategy that works is the hard part.

**Comment by shotlom** [comment]
Did this talk happen?

**Comment by ashleydavis** [comment]
Not yet! Although I'm currently preparing slides for a different but similar talk **Backtesting trading strategies with JavaScript**.

Not sure yet when the talk will happen though!
