### ISSUE TITLE
Backtesting trading strategies with JavaScript

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#287]
Talk time: 10-15 minutes (could do a longer talk later if anyone is interested).

Join Ashley Davis, local developer and author of Data Wrangling with JavaScript, with a talk about how he approaches backtesting his stock trading strategies in JavaScript. Systematic trading often starts by scanning the entire stock market for companies that are consider to be worthy of buying.  When you consider that there are 2500 companies on the Australian Stock Exchange and that each has many years of financial data to consider you can start to appreciate that we are dealing with a lot of data here. And how do we determine the criteria that we are searching for? Backtesting is the answer, that's the simulation of trading strategies on historical data to see how they would have performed. Ash will give you a taste for how he does backtesting in JavaScript and we'll work through a simple example.

**Comment by iamkevinv** [comment]
OR.... if https://github.com/BrisJS/meetups/issues/290 and https://github.com/BrisJS/meetups/issues/294 are out... we could do a double talk with @korynunn and make it trading night

**Comment by KoryNunn** [comment]
Wooo trading night!

**Comment by ashleydavis** [comment]
Before we schedule this we should put out the word and see if anyone else want's to a trading or fintech-related lightning talk!

**Comment by shotlom** [comment]
Request from Overseas ... could you put this talk up on YouTube please? I'd be interested in it whilst I'm travelling.

**Comment by ashleydavis** [comment]
This talk is basically ready to go. I've got most of the slides, code, etc prepared - it just needs some clean up work.

Currently this is a 10-20 minute talk, but I could expand out some of the more advanced work and scale it up to 30-40 minutes if I'm given a few weeks notice.

**Comment by shotlom** [comment]
scale it up, scale it up!

**Comment by iamkevinv** [comment]
So @ashleydavis - this is the chosen one for Dec? I'll lock it in.

**Comment by iamkevinv** [comment]
Can we compromise on 30? :) Sorry to constrain your intellectual expression my friend :)

**Comment by ashleydavis** [comment]
Thanks again BrisJS for letting me talk!

Slides for my talk are online:
https://www.slideshare.net/AshleyDavis33/testing-trading-strategies-in-javascript

Example code is here:
https://github.com/ashleydavis/grademark-first-example

Last night I demonstrated coding using Data-Forge Notebook. If you are interested please go here:
http://www.data-forge-notebook.com/

Please keep any on my Twitter. In the coming weeks I'll be letting you know about videos and a blog post relating to the topic of testing trading strategies.

@ashleydavis75

I'm also adding new features to Grademark and I'll be Tweeting about that as I go!

**Comment by iamkevinv** [comment]
Thanks for your talk and the links!
