### ISSUE TITLE
Data-Forge Notebook demo and building desktop apps in JavaScript with Electron

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#290]
== New abstract ==

Join author and local developer Ashley Davis for a demo of his new product and a talk about how it was constructed. 

Data-Forge Notebook is a desktop application for doing data transformation, analysis and visualisation in JavaScript. The app itself is coded in TypeScript, using React for the UI and is built on the Electron platform. In this talk Ash overviews the myriad of technical problems overcome to to bring it to market across multiple platforms. You'll also learn some business tips on how to bring your own product to market.

Although Data-Forge Notebook has not even reached version 1 it is already proving popular and has been delivered to numerous customers on Windows, MacOS and Linux.

== Old abstract ==

Data-Forge Notebook is a new product that I'm working on for data analysis, transformation and visualization in JavaScript.

I'm currently collecting interest from the community and I'm keen to do a demo of it for BrisJS and try to drum up some support. The demo would be around 10 minutes and include some live coding.

It's a notebook-style desktop app for Windows, MacOS and Linux for doing JavaScript prototyping and exploratory data analysis ala Jupyter Notebook.

Landing page is here if you want more details: [http://www.data-forge-notebook.com/](http://www.data-forge-notebook.com/)

I could also do an extended talk and talk about the implementation of the app. Data-Forge Notebook is a Electron-based desktop application that is built using React and TypeScript. It also contains an embedded (but distinctly separate) Node.js installation that runs the code evaluation engine. The Electron app communicates with the code evaluation engine using interprocess communication.  

npm modules are installed automatically the first time they are seen by the evaluation engine. So I can talk about procedural interaction with npm.

I have some interesting tips I can share for making such an app be tolerant and resilient in the face of running the user's arbitrary code. This was a bit of a challenge given that a users code can do nasty things like aborting the Node.js process or putting itself into an infinite loop.

I've also had some challenges with the cross platform development. The app has been delivered on multiple platforms so I can talk about how that was achieved with Electron, how to create the installer, etc and where platform specific code was necessary.

If you are interested in this talk please let me know if you want the short version (10 minutes) or the extended version (30 minutes) or I could even do them on separate nights.

**Comment by iamkevinv** [comment]
Hey @ashleydavis - are you okay to do this for Oct 8?

**Comment by ashleydavis** [comment]
Unfortunately I'm out of town on holiday on the 8th! 

I'd be happy to do it the month after!

**Comment by ashleydavis** [comment]
I haven't prepared this talk yet, but I can put it together reasonably quickly if needed.

**Comment by iamkevinv** [comment]
hey @ashleydavis ... it's too last minute for april but do you want to headline for May with this one?

**Comment by ashleydavis** [comment]
Yeah that would be great! The best timing as well because Data-Forge Notebook is due to hit version 1 in the next few months.

Thanks for giving me plenty of time to prepare ;)

I'll also give away some more copies of my book (still have half a box of them!).

**Comment by ashleydavis** [comment]
I'm updating the title and abstract of this talk to reflect a longer 30 min talk.

**Comment by ashleydavis** [comment]
Just made a small update to the abstract. I'm planning to spend a slide talking about some business stuff - how a developer can get people to buy their product.

**Comment by ashleydavis** [comment]
@iamkevinv am I still good to do with this talk on the 13th of May?

**Comment by iamkevinv** [comment]
Sure are! You are confirmed.

**Comment by ashleydavis** [comment]
The slides for my talk:

https://www.slideshare.net/AshleyDavis33/building-desktop-apps-in-java-script-with-electron

**Comment by iamkevinv** [comment]
Thanks mate!
