### ISSUE TITLE
Destyle - decouple your styling from your components - Discussion & Feedback

### ISSUE THREAD

**Issue by matt-way** [BrisJS/meetups#293]
So I just built [destyle](https://github.com/syntropy-ai/destyle) as a trial for a project we are working on, after getting annoyed by all the available styling options in react. Wouldn't mind doing a short talk on it, to start a conversation, get feedback, etc. It's react specific, so not sure if it fits the meetup perfectly though.

**Comment by matt-way** [comment]
Sorry about the late reply.

Title: destyle - decouple your styling from your components
Length: 20min
Synopsis: Styling in react is fragmented. Is this because everyone is focusing on the wrong problem? destyle was built to see what we could do if we were able to separate styling logic from component logic, and build purely style-less themable components.
Available: October
Twitter: @_mattway

**Comment by iamkevinv** [comment]
Perfect matt - can i confirm you for this month?

**Comment by matt-way** [comment]
Definitely :)

**Comment by iamkevinv** [comment]
Oh and i just noticed @matt-way - you mentioned futsal at 6:30pm, but i'm afraid that's when we start BrisJS... Are you still good to talk?

**Comment by matt-way** [comment]
Yeah, talk takes priority. Was just wondering if my talk was a later one I could possibly do both.

**Comment by iamkevinv** [comment]
Hmm yeah, we could pop you up last speaker position, but getting you into the building after start would require a phone call or such - what time would you need?

**Comment by matt-way** [comment]
If I did both, I could get to the meetup by 7:30. Would that be too late?

**Comment by matt-way** [comment]
How about (if it is ok), I talk after pizza/drinks, but i'll try be there as early as possible. May even just skip soccer after all.

**Comment by iamkevinv** [comment]
Sure mate! @korynunn - Please note that one of the organisers will potentially show up a little late - we'll need to establish a sure fire way of contact. I'll rope in a phone number of the venue organiser for the night too.

**Comment by cartant** [comment]
@matt-way Thanks for your talk, Matt. destyle looks really interesting.

**Comment by matt-way** [comment]
@cartant Thanks for listening. 

Heres another repo link too if anyone ends up here. https://github.com/syntropy-ai/destyle

**Comment by cartant** [comment]
@matt-way Thanks. I will *definitely*  be checking it out.

**Comment by iamkevinv** [comment]
Hi! I presume this went well and Kory made you feel welcome when he hosted Oct. If you have some resources to share like slides, please post them here :) @matt-way

**Comment by iamkevinv** [comment]
@matt-way - If you can post up any links to the content here that would be awesome. Thanks!
