### ISSUE TITLE
Short talk: pushing the limits of memory in Node.js

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#294]
Talk time: 10-20 minutes.

Abstract: Node.js has memory limitations that you can hit quite easily in production. You'll know this if you ever tried to load a large data file into your Node.js application.

But where exactly are the limits of memory in Node.js? In this short talk we'll push Node.js to it's limits and find out where those limits are. We'll also cover some practical techniques you can use to work around the memory limitations and get your data to fit into memory.

**Comment by iamkevinv** [comment]
Or if https://github.com/BrisJS/meetups/issues/290 is too much... maybe this one?

**Comment by ashleydavis** [comment]
I can do this one almost anytime, but unfortunately I'm out of town on the 8th October.

**Comment by iamkevinv** [comment]
Hey mate... there's a slight opportunity to squeeze this in for the Nov brisjs meeting - but its quite full. Are you available? Just so i can work out if we can add this too. 
Would still like to get one of your larger talks in for Dec if that's possible?

**Comment by ashleydavis** [comment]
Yeah I could talk for 5-10 minutes on this topic if that's what you want.

My talk "Backtesting in JavaScript" (#287) is actually almost ready to go, but it can wait until December. My talk "Data-Forge Notebook demo" (#290) could also be put together quite quickly.

**Comment by iamkevinv** [comment]
I can't squeeze more than a lightning length talk in for Oct unfortunately, so target whichever big talk you prefer for dec 👍

**Comment by ashleydavis** [comment]
Ok, happy to do this one in November and #287 in December. @KoryNunn you should do a trading talk in December as well!

**Comment by ashleydavis** [comment]
I've put my slides online: https://www.slideshare.net/AshleyDavis33/nodejs-memory-limitations

**Comment by ashleydavis** [comment]
Code is here: https://github.com/Data-Wrangling-with-JavaScript/nodejs-memory-test

**Comment by iamkevinv** [comment]
Thanks for sharing the resources @ashleydavis :)
