### ISSUE TITLE
Talk about Jest - custom runners and watch plugins

### ISSUE THREAD

**Issue by SimenB** [BrisJS/meetups#295]
Hiya 👋

I'll be visiting Brisbane in early November, and was wondering if you'd be interested in having me give a talk at your meetup? The talk is called "Jest Beyond Tests" and is about what you can do with custom runners and watch plugins in Jest. Lasts about 30 minutes. (EDIT, I see you request 20 or 40 - I can do either)

Jest, in case you don't know what it is: https://github.com/facebook/jest

I'm a core team member on Jest, and would be willing to do some sort of q&a if you want that as well? I'm not sure about how you organise your meetup :) (found this through Google)

**Comment by SimenB** [comment]
I came over https://brisjs.org/#present now, do tell me if you want me to vhange to that format.

I can only do November, btw (I live in Norway, but will be in Brisbane for vacation)

**Comment by iamkevinv** [comment]
Sounds great @SimenB - would love to have you speak at BrisJS, thanks for volunteering. 

I've filled out the following in the format just so we can capture the info.

Presenter name: Simen Bekkhus
Talk title: Jest Beyond Tests
Talk length: 30 min
Available month(s)/date: November 5

Can you give me the following blurbs please?:

Your twitter account so we can promote:
Talk synopsis:

**Comment by SimenB** [comment]
Thanks!

Blurb: More and more people are using Jest to run their JavaScript tests, but did you know it can also be used to run your linter and your compiler? Jest can even be used to run your tests written with Mocha or Python! This talk will explore how you can use Jest, or its individual parts, for more than just running your tests.
Twitter (I'm super active, I know!): https://twitter.com/SBekkhus

**Comment by iamkevinv** [comment]
Great. Closer to the date i'll ping this thread and confirm your attendance for the event again :)

**Comment by iamkevinv** [comment]
Hi @SimenB - just confirming if you're still okay to take about 20 mins for this talk this coming month? Thanks :)

**Comment by SimenB** [comment]
Hey. Yeah, still on from my side 🙂

**Comment by iamkevinv** [comment]
Thanks again @SimenB - great to have you. If you have more resources to share, please add them here :)

**Comment by SimenB** [comment]
Thanks for having me!

Nothing much to share beyond the slides: https://github.com/SimenB/jest-beyond-tests
