### ISSUE TITLE
Contributing to Open-Source Software

### ISSUE THREAD

**Issue by cartant** [BrisJS/meetups#296]
Talk title: Contributing to Open-Source Software
Talk length: 20 min
Talk synopsis:

I've been a maintainer and contributor for the last two years and I'm currently a member of the RxJS core team. The talk would cover the following:

* Why you might want to consider contributing.
* The different ways in which you can contribute.
* Some things that maintainers really appreciate.
* Some things to avoid - i.e. maintainers' pet peeves.
* How to start contributing.

I presented the talk at ReactBris earlier this week - the ReactBris issue is [here](https://github.com/reactbris/meetup/issues/52) - so some of your audience will have already seen it. However, if you are in need of a talk, I'd be happy to present this anytime.

Available month(s): Anytime, with pretty much no notice required
Optional: @ncjamieson

**Comment by iamkevinv** [comment]
Sounds very cool @cartant - would love to have you in Oct... can i confirm you for next week?

**Comment by cartant** [comment]
Yeah, I can do it next week, but if others volunteer talks in the interim, I'm cool with this being bumped to sometime in the future.

**Comment by iamkevinv** [comment]
You're in!

**Comment by iamkevinv** [comment]
Hi! I presume this went well and Kory made you feel welcome when he hosted Oct. If you have some resources to share like links or slides, please post them here :) @cartant

**Comment by cartant** [comment]
If anyone is interested, the slides from the presentation are [here](http://cdn.s3.cartant.com/reactbris-2018-09-24/index.html).

There is more information on contributing to open-source software here:

* [How to Contribute to Open Source](https://opensource.guide/how-to-contribute/)
* [Guide to Idiomatic Contributing](https://github.com/jonschlinkert/idiomatic-contributing)

There are some examples of what not to do here:

* [Dear GitHub](https://github.com/dear-github/dear-github/blob/master/README.md)

Also, I can heartily recommend [`mdx-deck`](https://github.com/jxnblk/mdx-deck) for authoring slides.

**Comment by iamkevinv** [comment]
Thanks for sharing resources!
