### ISSUE TITLE
Slides on talk "🚸 Cross origin communication in Javascript- Armagan Ersoz"

### ISSUE THREAD

**Issue by liamzebedee** [BrisJS/meetups#297]
G'day guys, writing in here from Rotto' in The Netherlands. Love how the Brissy tech scene is evolving, congratulations! I wanted to see if I could get the slides of the talk mentioned above, from Armagan Ersoz, on Cross-Origin JS communication. Cheers in advance - Liam.

**Comment by iamkevinv** [comment]
I think this one was originally listed here as https://github.com/BrisJS/meetups/issues/258 - Armagan is presenting this month too, so i'll follow up!
