### ISSUE TITLE
Talk Proposals: "Ram-da Functional into your JavaScript" or "Squeaky Clean Scripts with Maid"

### ISSUE THREAD

**Issue by Lukejkw** [BrisJS/meetups#298]
I have 2 talk proposals, both of which I have done a few times in Johannesburg, South Africa. 

I will be in Brisbane for December and would love to come and speak for you guys.

## Talk 1: Ram-da Functional into your JavaScript

In the talk, I cover the basics of FP in JavaScript and introduce a functional JS library called ramda to help you on your way.

I usually do this talk with a friend of mine but would be doing it alone. We have done the walk at an internal company user group, the Joburg Ruby User Group and the Joburg JavaScript User Group.

**Video recording of the talk at Jozi.JS:** http://lukewarrendev.co.za/blog/talk-how-to-ram-da-functional-into-your-javascript/

## Talk 2: Squeaky Clean Scripts with Maid

A short talk about literate programming using an awesome little CLI tool called maid.

I have done this talk at an internal company user group and at the Joburg JavaScript User Group.

**Video recording of the talk at Jozi.JS:** http://lukewarrendev.co.za/blog/squeaky-clean-scripts-with-maid/

**Comment by iamkevinv** [comment]
Sounds excellent @Lukejkw :)
Which would you prefer to present? The group would be pretty open to either, i'm sure.

**Comment by Lukejkw** [comment]
I'll do the functional one. It is a bit meatier.

When would you like me to talk?

**Comment by iamkevinv** [comment]
Thanks for that! The next BrisJS event is December 3 :)
https://www.meetup.com/BrisJS/events/nlmxrpyxqbfb/

**Comment by iamkevinv** [comment]
Got a twitter handle i can quote?

**Comment by Lukejkw** [comment]
That's the day I land :rofl: I will have to just come through jetlagged

My twitter handle is 'lukejkwarren'

**Comment by iamkevinv** [comment]
Yikes! I'm so sorry but also thank you very much. At least we'll give you pizza and beer 👍

**Comment by Lukejkw** [comment]
No worries! Super duper excited.

See you there

**Comment by iamkevinv** [comment]
Thanks for your talk @Lukejkw - if you have resources to link, please pop them here.
