### ISSUE TITLE
Sandra: AI in JS

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#299]
Full name: 
Talk title: AI in JS
Talk length: 20 min
Talk synopsis for the mailouts etc:
Available month(s): November
Optional: your Twitter account so we can promote your talk

**Comment by sandra-arato** [comment]
hi @iamkevinv ,
Please see details below:
Full name: Sandra Arato
Talk title: AI in JS
Talk length: 20 min
Talk synopsis for the mailouts etc:
If you ever wondered about what neural networks and learning agents might do, and how they will solve the biggest problems humanity face, then you probably will need more than 20 minutes to fully appreciate the depth of data science. But each large project starts with a prototype, and for each big problem there is a scaled solution. In this talk, we take the baby steps to incorporate AI into your projects, and those steps are written in Javascript. 
twitter handler: @SandraArato

thank you 😄

**Comment by iamkevinv** [comment]
Wonderful! Thanks and see you there!

**Comment by iamkevinv** [comment]
@sandra-arato - If you have some resources you'd like to share with the audience, please feel free to share them here! Thanks again!
