### ISSUE TITLE
Armagan Ersoz: How did the community help me find my next home? 

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#300]
Hi @broccolinisoup - Can you please fill in some details about your upcoming talk? Also... thanks for volunteering! 

Full name: Armagan Ersoz
Talk title: How did the community help me find my next home?
Talk length: 20 min
Talk synopsis for the mailouts etc:
Available month(s): November
Optional: your Twitter account to promote the talk - @broccolinisoup

**Comment by broccolinisoup** [comment]
Hey hey @iamkevinv my pleasure :) Looking forward to it!

**The talk synopsis:**
Armagan currently works at RedEye Apps as a Front End Developer and enjoys developing web-based systems with JS. She is also an organiser of Muses CodeJS (ex NodeGirls) Brisbane. In this talk, Armagan will talk about the importance of communities and how communities help her find her next home (RedEye Apps) ❤️

**Twitter handle:** @broccolinisoup

Let me know if you need anything else.

**Comment by iamkevinv** [comment]
Brilliant, thanks! See you there!

**Comment by iamkevinv** [comment]
@broccolinisoup - If you have some resources you'd like to share with the audience, please feel free to share them here! Thanks again!
