### ISSUE TITLE
Short talk: Fooling the V8 garbage collector

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#302]
Duration: 10-15 minutes

Abstract: Following on from his talk on memory limits in Node.js, Ashley Davis talks about garbage collection in the V8 engine. 

You can do what you want in a garbage collected language and it's going to clean up after you right? 

Most of the time yes, although it's also pretty easy to fool the garbage collector into not cleaning up after you - this causes a dreaded memory leak (if you don't dread this it hasn't caught you out yet).

We'll discuss the data structures and algorithms used by the V8 garbage collector.  We'll figure out how to play nicely with it and also how we can break it.

**Comment by iamkevinv** [comment]
Available for dec @ashleydavis? Lightning talk length?

**Comment by ashleydavis** [comment]
I'm already doing a 30-40 min talk on backtesting for the dec meetup. I think that's enough ;)

**Comment by iamkevinv** [comment]
haha okay great!

**Comment by ashleydavis** [comment]
I'm going to withdraw this talk for now, but planning to submit some other talk ideas.
