### ISSUE TITLE
Syntropy Studio

### ISSUE THREAD

**Issue by matt-way** [BrisJS/meetups#304]
I would really love to talk about this new software we've been building for a good chunk of this year. I was using it to demo code during the destyle talk, and think it could benefit a lot of js devs. I'm still working on a good synopsis, but currently am calling it a CCE (creative coding environment). It has some similarities to an IDE, a data science notebook, and reactive programming software like lighttable. We've built it personally to help our AI research, but it would be useful for things like generative art, data science, algorithm design, visualisation, component experimentation, etc.

It's not quite ready for release yet, but the meetup would be a great place to introduce it, and create a discussion.

**Comment by matt-way** [comment]
Yeah definitely. I just have a really busy day, but i'll get the talk details to you as soon as I can. Also I think 20 should be ok (havent figured the talk out fully yet), but might go over a little.

**Comment by iamkevinv** [comment]
Cool mate - we should be able to work it out. I'll confirm you for the night :)

**Comment by iamkevinv** [comment]
Got a twitter handle i can quote?

**Comment by matt-way** [comment]
Yeah twitter handle is correct.

**Comment by iamkevinv** [comment]
@matt-way Sorry matt - they are recorded, but they're trapped on my drive still. I'll remedy this in 2019.
