### ISSUE TITLE
A short introduction to ReasonML

### ISSUE THREAD

**Issue by anisjonischkeit** [BrisJS/meetups#305]
Talk title: A short introduction to ReasonML
Talk length: ~10 mins
Talk synopsis: ReasonML is a new syntax and toolchain on top of OCaml. It compiles to Javascript adding some nice features including 100% sound typing, native compilation, preprocessing extensions, and more. The talk will give a brief introduction to ReasonML and show some of the cool things that it gives you.
Available month(s): If there are still slots available, I'd be keen to slot in as a lightning talk during the December meetup.
Twitter: https://twitter.com/_anisj

**Comment by iamkevinv** [comment]
@anisjonischkeit - Happy to have you present in Dec if you're available. Otherwise Feb :)

**Comment by iamkevinv** [comment]
it's on tonight :) Come find me if you want to present :)

**Comment by anisjonischkeit** [comment]
Here are the slides: https://talks.anis.com.au/intro-to-reasonml/

**Comment by iamkevinv** [comment]
Thanks so much @anisjonischkeit! Let's get you on again for an in depth explanation sometime soon with maybe a sample app? That would be amazing. Please share any links you like here for resources which could help others :)
