### ISSUE TITLE
Short talk: Deploying Node.js microservices to Kubernetes using Terraform

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#306]
Duration: 10-15 mins

Abstract: Need to deploy your Node.js app to Kubernetes but having trouble getting your head around it? In this talk we'll look at using Terraform to create *infrastructure as code* and simplify the job of creating a Kubernetes cluster and deploying a Node.js application. This will be a whirlwind tour of Terraform and demonstration of how to bring online a simple Node.js microsevices application.

I have example code already for this talk, so it's not far off being ready.

**Comment by ashleydavis** [comment]
I still have to do some prep, but I have code ready to demo.

**Comment by ashleydavis** [comment]
Note that I've just adjusted the name of this talk.

**Comment by iamkevinv** [comment]
Cool @ashleydavis 👍 
Is this one you'd like next week for the Feb Meetup? I'm still working out scheduling as we have a bunch of confirmations in already. If you're holding out till march that's cool too.

**Comment by ashleydavis** [comment]
This point is good to go for Feb.

**Comment by iamkevinv** [comment]
Awesome sauce
