### ISSUE TITLE
Books to give away

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#310]
My book Data Wrangling with JavaScript is printed!

I have 4 physical copies put aside to give away at BrisJS.

We can give them all away one night or spread it out over multiple nights. @iamkevinv let me know what you think.

![img_20181214_100614](https://user-images.githubusercontent.com/625126/51003325-024c5700-1582-11e9-84a9-3eb2ea14724a.jpg)

**Comment by iamkevinv** [comment]
Love it! How do they earn such goodies? :)
I think let's spread them out and give you maximum exposure for your kindness.

**Comment by ashleydavis** [comment]
I'm happy to give them away at random ;)

**Comment by iamkevinv** [comment]
Maaaaybe you could give them your fave speaker of the night as a reward for speaking? And one to someone who asks a good question?

**Comment by ashleydavis** [comment]
How about we do a random draw again?

At the end of the night we give away two books at random to audience members.

I can do a quick announcement at the beginning that anyone who stays until the end will go in the random draw.

**Comment by iamkevinv** [comment]
Noice - works for me. I’ll have to rewrite my row/column random chair selector haha
