### ISSUE TITLE
How to use a full potential of service worker with your App

### ISSUE THREAD

**Issue by alexandre-combemorel** [BrisJS/meetups#313]
Hi folk,

I got the chance to develop a project using full potential of the service worker API. Tough challenge tho, the target was to create an offline map using the Esri API.
We faced a lot of: device size limit, divergence of service worker implementation, number of request, how to store and save massive amount of data and so on.

I'm happy to share about our experiences and how implementing an efficient service worker for scaled App.

I can provide a structure of what I could talk about. I think it is a good 15 min talk and from experience quite a few questions are usually asked on this topic which is getting really popular.

Cheers,
Alex

**Comment by iamkevinv** [comment]
I would freakin love this to be presented! Are you available next week? I'm locking down scheduling.

**Comment by alexandre-combemorel** [comment]
Next Monday should be fine yes :) need to prepare a little bit. When do you need the slides for?

**Comment by iamkevinv** [comment]
I don’t need them in advance :-) You present them live and unedited! Heheh

**Comment by iamkevinv** [comment]
If you have the resources from your talk you can link, please do :)

**Comment by alexandre-combemorel** [comment]
[Brisbane-JS-presentation-04-02-18-Service-worker.pptx](https://github.com/BrisJS/meetups/files/3544291/Brisbane-JS-presentation-04-02-18-Service-worker.pptx)
Sorry for the very late reply. The ppt is pretty small but enough to get through some important info.
