### ISSUE TITLE
Talk offer: Gitlab for JS developers.

### ISSUE THREAD

**Issue by VladimirAus** [BrisJS/meetups#316]
Gitlab is not only code management service and the only open source platform out of big 3 (Bitbucket and Gitlab). It is also `A full DevOps tool` as stated on their home page.

In this talk we are going to see what are the features available in GitLab free version and why is it more than just source control tool.

**Comment by iamkevinv** [comment]
@VladimirAus - perhaps this is a good talk to schedule for the April meetup?

**Comment by VladimirAus** [comment]
Mon 1st Apr? Soinds like a good day @iamkevinv

**Comment by iamkevinv** [comment]
Can i confirm you @VladimirAus? I've already prepped the email to the group :)

**Comment by VladimirAus** [comment]
Double confirmed @iamkevinv

**Comment by iamkevinv** [comment]
Got any cool links for people @VladimirAus ??
