### ISSUE TITLE
Short talk: Automated testing of Node.js applications with Cypress

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#318]
This talk follows will follow on from https://github.com/BrisJS/meetups/issues/317, so please schedule that one first.

Duration: 10-15 minutes

Abstract: After previously talking about development, packaging and deployment of Node.js applications, Ash now addresses another key area of the application development pipeline: running automated tests against a Node.js application. 

In this talk Ash gives an overview and demonstration of using Cypress for testing web pages and REST APIs. He also shows how we can sneak a dev-focused REST API into the dev version of our application to allow our tests to load database fixtures and query the database to make sure that the right data is ending up where it was intended.

**Comment by iamkevinv** [comment]
At the risk of wearing you out - what’s your availability like for this talk in case we can get it in for June as a backup…

**Comment by ashleydavis** [comment]
Hey @iamkevinv, I'm too maxed out at the moment. I have multiple product launches on at the moment plus I have two talks already planned for the next couple of months. Feel free to ask me again in a couple of months time.

**Comment by ashleydavis** [comment]
I'm happy to do this talk when you need it. Please just give 2 weeks notice, I don't have anything specially prepared for it yet.

**Comment by ashleydavis** [comment]
I'm happy to do this talk in 2020. Just want a couple weeks notice to make sure I have enough time prep an example.

**Comment by ashleydavis** [comment]
I already gave this talk.
