### ISSUE TITLE
Talk on JS and Security

### ISSUE THREAD

**Issue by gupta-kartik** [BrisJS/meetups#319]
Requested by Ash here - https://github.com/BrisJS/meetups/issues/259

**Comment by iamkevinv** [comment]
@gupta-kartik were you still set for next week?

**Comment by gupta-kartik** [comment]
@iamkevinv sorry will have to postpone this to May. I am not prepared for Monday.

**Comment by iamkevinv** [comment]
@gupta-kartik - you keen?

**Comment by iamkevinv** [comment]
Please post a new issue when you're avail :)
