### ISSUE TITLE
ABC News are looking for devs to join them for the next few months

### ISSUE THREAD

**Issue by kevdesign** [BrisJS/meetups#32]
By way of @colingourlay:

> The ABC's News Online team are looking to bring on a couple of extra front-end developers to help us out over the next few months while our project load is high.
> 
> This would be ideal for a freelancer that's looking for a few months of steady work. We'd be looking to get you in as soon as possible. You'd be helping us out with a range of tasks – building new sections of the website, working with journalists to create content, general site maintenance, etc.
> 
> I spent a year in this team before moving into our new interactives unit, and they're all awesome people. I'd definitely recommend it to any of you. Our office is just behind the Wheel of Brisbane in Southbank.
> 
> If you're keen, send your CV / Resume / whatever you think shows your ability to me at:  gourlay.colin@abc.net.au
> 
> Cheers!

**Comment by kevdesign** [comment]
@collypops - This position been filled i take it? Can the issue be closed?

**Comment by AshKyd** [comment]
Yup, close it down! We've got a pair of the raddest ninja rockstar 10xers around. :P cc @louisstow @lylep-abc
