### ISSUE TITLE
Lead Full-stack Software Engineer at RapidAIM

### ISSUE THREAD

**Issue by dcmoore14** [BrisJS/meetups#321]
![logo-charcoal](https://user-images.githubusercontent.com/47553236/52619197-c6900e80-2eec-11e9-9ea1-199bdd724692.png)

RapidAIM is a new Brisbane-based, venture-backed AgTech startup with the potential to revolutionise global farming and biosecurity.

**About the role**

We’re hiring our lead Full Stack Software Engineer to lead the design and building of our back-end cloud systems and applications. We have a demonstrator tech stack (mobile web app / AWS back-end)  currently deployed in nationwide trials of our beta product. The mobile web app has been developed using Elm. Our AWS backend is Python, with a ‘serverless’ architecture deployed using CloudFormation and the Chalice framework. We use a number of AWS technologies including Lambda, API Gateway, IoT and ElasticSearch.

As a senior member of our team, you’ll be responsible for building a team of software developers around you as we grow, and for making the key architecture and technology decisions that set the foundations to rapidly scale and seamlessly bring our pipeline of new products to the market. As you first familiarise yourself with our existing tech stack you’ll be supported by CSIRO Data61 software engineers who helped build our demonstrator tech stack.

**Apply**

Get more information and apply on LinkedIn [here](https://www.linkedin.com/jobs/view/1072964898/)

**Comment by dcmoore14** [comment]
This position has been filled. Thanks!

**Comment by iamkevinv** [comment]
Great!
