### ISSUE TITLE
Short Talk offer: 10 simple tips for maintainable code (examples in React but generally applicable)

### ISSUE THREAD

**Issue by gschema** [BrisJS/meetups#322]
Hi guys,
I am kin to share 10 tips on maintainable, readable code (including tests) that I generally tend to recommend first to developers I work with because it pretty much fits 20/80 rule well.

It would be 10 tips + examples within ~15 minutes.

Let me know if that is interesting and worth the time. I am happy to prepare that for the next meeting in March (April is an option too).

Let me know what do you think.

Thanks,
Dusan

**Comment by iamkevinv** [comment]
Sounds good - lets get you in for April @gschema :D

**Comment by iamkevinv** [comment]
Hey @gschema - just checking if you're able to be confirmed for monday? Is 10min plus some question time enough?

**Comment by gschema** [comment]
Hey man, yeah Monday is sweet. Yeah, 10-15 min will be fine. Ta

**Comment by iamkevinv** [comment]
Thanks again- if you have some links or writings to share feel free to post them here @gschema 👍
