### ISSUE TITLE
Tips for Mentoring a Junior Dev

### ISSUE THREAD

**Issue by allyeastman** [BrisJS/meetups#323]
Talk title: Tips for Mentoring a Junior Dev
Talk length: 10 min
Talk synopsis: 
Over the past 3 years, Ally has had her fair share of mentoring from devs with different skill levels and personalities.
In this talk, she will share tips around how to guide mentors, paired programming and helping juniors grow in their careers.
Available month(s): March (preferred) otherwise any other month afterwards
Optional: @allyeastman_

**Comment by iamkevinv** [comment]
Thanks for contributing @allyeastman! Keen to make it happen for our international women's day themed event in march to highlight our brissy talent :) Really appreciate it!

**Comment by iamkevinv** [comment]
Thanks for telling the group all your mentoring tips @allyeastman! If you have any resources like your slides you can share with the group, please pop some links here 👍

**Comment by allyeastman** [comment]
Thanks Kevin! I really appreciate you organising last night, it means a lot to the local women in tech.
Here are my slides: https://docs.google.com/presentation/d/10MPyVxGtFt2h0FrsNlXTF1C78r8sUm2keOx2CdcSTIc/edit?usp=sharing

**Comment by iamkevinv** [comment]
My pleasure! Thanks for the link to slides 😀 Please tell everybody they’re welcome to volunteer more talks for any month 👍
I always want a balanced panel of speakers but volunteers can be scarce - would love for that to change for the better! All the Brisbane tech queens contributions have been great examples of what a meetup night should be like 👏🏻
