### ISSUE TITLE
The language of adoption

### ISSUE THREAD

**Issue by vanessalove** [BrisJS/meetups#324]
Talk title: the Language of Adoption
Talk length: 20 min
Talk synopsis: You have just heard about a new tool and just know that it would advance your team and improve processes. But when you talk to your boss about purchasing, their eyes have glazed over, and the answer is no. It's hard to understand why they are so out of touch with technology! Your desk-pod-mates are totally on-board! The folks at the other pod next to you are  not really so sure, and aren't helping your case. 

When wanting buy-in (and funding) from different levels of a business, your language has to change. You need to know what are the pain points in each area, and what benefits they would gain. I have examples of how this does work, and how, by listening, you can get the outcome that you want. Getting what you want is hard if you do not listen and learn to speak the same language as your audience.
Available month(s): This coming (4th March)
Optional: @fly401

**Comment by iamkevinv** [comment]
Thanks so much for contributing! Would love to hear about this Monday. 👍👍
