### ISSUE TITLE
The Journey to React...

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#326]
Speaker: Jacquie Hardy - Development Manager at Youfoodz. 
Talk title  - The Journey to React...
Short Description - TBA
Length: 20m
Linkedin: https://www.linkedin.com/in/jacqueline-hardy-87642469/
Github: @j4cq

**Comment by iamkevinv** [comment]
Hi @j4cq - Just put this issue on your behalf after chatting with sammy. See you monday!

**Comment by iamkevinv** [comment]
Really appreciate you coming out to speak with BrisJS @j4cq! If you have any resources like your slides you can share with the group, please pop some links here 👍

**Comment by j4cq** [comment]
Thanks for having me! My slides can be viewed here: https://docs.google.com/presentation/d/1mxWc0fnKjK4mxsk4wSkSNv4qsZx6ek3C34Ijg7XUPaM/edit?usp=sharing
