### ISSUE TITLE
SSL Certificates with NodeJS 

### ISSUE THREAD

**Issue by ahaw021** [BrisJS/meetups#329]
Talk title: SSL Certificates with NodeJS 
Talk length: 40 min
Talk synopsis:  In the past security via SSL was optional. Today it's a must have and often developers may struggle understanding key concepts of SSL. 
This talk is a mixture of theory and hands on demonstrations (sample code)

- Why SSL is important
- Key components of SSL
- Obtaining a SSL Certificate from Let's Encrypt (live demo)
- Using an SSL Certificate with Common NodeJS libraries (Restify, Mosca, TCP)
- Good practices for SSL 
- Tools and Further Readings
- Available month(s): April / May

Optional: your Twitter account so we can promote your talk

**Comment by jwulf** [comment]
Dockerised nginx reverse proxy with lets encrypt sidecar. Then you just ignore SSL in your Node code. https://github.com/jwilder/nginx-proxy

**Comment by ahaw021** [comment]
this works for woking with HTTP protocols but nginx doesn't proxy other protocols well

**Comment by jwulf** [comment]
^ True story.

I haven't got websockets working since I switched to this method. 

One of its significant benefits (and why I switched to it) is the auto-renewal of certs.

**Comment by iamkevinv** [comment]
@ahaw021 You available for the next talk night next week? I’d like to confirm this

**Comment by ahaw021** [comment]
Hi @iamkevinv 

Happy to do this for the monday 

Andrei

**Comment by iamkevinv** [comment]
Thanks @ahaw021 - if you have links to share please do post here 👍

**Comment by ahaw021** [comment]
[BrisJS Certificates.pptx](https://github.com/BrisJS/meetups/files/3154912/BrisJS.Certificates.pptx)

PowerPoint attached
