### ISSUE TITLE
DRY (Don't Repeat Yourself) in the Wild

### ISSUE THREAD

**Issue by ahaw021** [BrisJS/meetups#330]
Talk title: DRY (Don't Repeat Yourself) in the Wild
Talk length: 10 Minutes
Talk synopsis: 

DRY in Principle
Sample Company (4x Teams with NodeJS/Angular)
Time savings with DRY
Reality of DRY - Probably DRYish

Available month(s):
Optional: your Twitter account so we can promote your talk

**Comment by iamkevinv** [comment]
If you can’t do the other one - we could this lightning talk? @ahaw021

**Comment by iamkevinv** [comment]
we'll get you in with https://github.com/BrisJS/meetups/issues/329 first :) Thanks

**Comment by iamkevinv** [comment]
Hey @ahaw021 Andrei! Are you available to present at the next BrisJS? I’m locking down speakers to announce. I wasn’t sure it was going to happen as I am in Belgium but I have some last minute saviours ;-)

**Comment by ahaw021** [comment]
Hi @iamkevinv  

Sure no problems. This should be a 10 minutes talk only 

Lock me in

Andrei

**Comment by iamkevinv** [comment]
You're more than welcome to make it 20! We are still hunting a 3rd speaker.

**Comment by ahaw021** [comment]
Ok book me in for 20 :D 

Will add a bit more background on how DRY came about and keeping processes DRY

Will update the Agenda

**Comment by iamkevinv** [comment]
10 or 20 or somewhere between... i don't want you to feel pressured :) 
We do have another speaker who's just come in. So you're welcome to still keep it short if you like :)

**Comment by ahaw021** [comment]
Hi @iamkevinv  - i am good for 15 minutes

**Comment by ahaw021** [comment]
PowerPoint attached 👍 
[DRYinTheWild.pptx](https://github.com/BrisJS/meetups/files/3176989/DRYinTheWild.pptx)

**Comment by iamkevinv** [comment]
Thanks for adding your notes!
