### ISSUE TITLE
Contract - Angular Work - Project Managment Platform

### ISSUE THREAD

**Issue by Lexvancooten** [BrisJS/meetups#332]
**About The Role**
We are looking for a freelance Angular developer to work on updating a current project. The project is a Project Management Platform which has been built using Angular 1.0. Happy for you to work remote (we are based in Brisbane), a portfolio demonstrating examples of your previous work as a freelancer is required and it is preferable that you have had at least 2 years experience. If any further information is required please let me know, happy to clarify any further details you may need. You can email me directly at Lex@ImmerseEnterprise.com

**Comment by iamkevinv** [comment]
Oh... found someone @Lexvancooten ?

**Comment by Lexvancooten** [comment]
No havn't found someone yet! I wasn't sure if I posted in the correct
location. How do I add labels?

Kind Regards,

*Lex Van Cooten* | Managing Director

m: 0456 389 212

l: Linkedin.com/in/lexvancooten/ <https://www.linkedin.com/in/lexvancooten/>

e: Lex@ImmerseEnterprise.com

w: ImmerseEnterprise.com <http://www.immerseenterprise.com/>

<http://www.immerseenterprise.com/>

DISCLAIMER: This e-mail and any attachments are intended only for the
individual or company to which it is addressed and may contain information
which is privileged, confidential and prohibited from disclosure or
unauthorised use under applicable law. If you are not the intended
recipient of this e-mail, you are hereby notified that any use,
dissemination, or copying of this e-mail or the information contained in
this e-mail is strictly prohibited by the sender. If you have received this
transmission in error, please return the material received to the sender
and delete all copies from your system.

**Comment by iamkevinv** [comment]
I already have. That's my task :) I've re-opened this for you.
