### ISSUE TITLE
Talk: Cross-platform component library with Svelte

### ISSUE THREAD

**Issue by cam-stitt** [BrisJS/meetups#335]
**Duration:** 15 minutes

**Overview**
With the continued rise of component libraries, we walk through a real-world scenario describing the need for a cross-platform (non-framework specific) component library. Then, we walk through how we can achieve this using Svelte, including example components in multiple frameworks.

**Comment by cam-stitt** [comment]
I've prepared the talk, ready to go!

**Comment by iamkevinv** [comment]
Sounds great - thanks for contributing! Let’s get you on with the next meetup in June.

**Comment by iamkevinv** [comment]
Marking as confirmed for the next talk night @cam-stitt 👍👍

**Comment by iamkevinv** [comment]
If you have the resources from your talk you can link, please do :)

**Comment by cam-stitt** [comment]
Slides are found [here](https://speakerdeck.com/cam_stitt/cross-platform-components-with-svelte)
