### ISSUE TITLE
How to lose money in realtime

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#339]
**Presenter:** Kory Nunn
**Twitter:** @KoryNunn
**Title:** How to lose money in realtime
**Talk description:**
Using an interpreted custom language to trade cryptocurrency, and watching its AST evaluate in real-time.

**Comment by iamkevinv** [comment]
Meetup page updated too. Thanks man

**Comment by KoryNunn** [comment]
Slides: https://docs.google.com/presentation/d/1IbxjYkSCT8We_24-zJ5b6HY7uVf25Pbd0KXnTswUQ8Y/edit?usp=sharing
