### ISSUE TITLE
Job: Front-end Web Developer

### ISSUE THREAD

**Issue by Jam-Per** [BrisJS/meetups#341]
**Hi BrisJS'ers, we are looking for two Senior Software Engineers with strong React experience coupled with .NET API knowledge. These are permanent roles for a large organisation, based in the Brisbane CBD in brand new facilities!**

You will join a team that focuses on improving the Customer Experience, taking cues from the business and building out appropriate solutions.

Working with modern technologies in a mature Agile environment, with weekly releases and 1 click deploy, you will use your strong problem solving skills to move towards React from an older JavaScript framework over the course of the next 2 years.

This organisation is a dominant force in the industry in which they play, working to build world class solutions on a daily basis.

**Your role will include the following responsibilities:**

- Provide expert advice and consultancy to delivery teams
- Assist teams to troubleshoot challenging technical problems
- Proactively analyse incidents and trends to reduce the overall number of incidents 
- Plan and participate in workshops, stand ups, product demonstrations and retrospectives
- Assist in the decision-making process around hosting of the products and services to be used for build, deploy, and configuration
- Manage / resolve incidents and requests assigned to the Software Installations queue
- Influence and operate as a genuine trusted advisor throughout technology
- Mentor, support and regularly engage delivery teams
- Maintain up to date knowledge, provide examples of contemporary approaches, techniques, and technologies used in the building, deployment, and configuration of software and systems

**You should have the following skills and experience:**

- Solid experience as a Software Engineer working with React and .NET API
- Agile Methodology experience
- Continuous Delivery and Continuous Integration experience (ideally TeamCity, Octopus Deploy, Git)
- Ability to build strong relationships with both business and technology teams
- Exposure to Cloud (AWS) and Native Cloud Patterns is desirable
- Experience with Kubernetes and Rancher is also desirable

Please call me to discuss this in more detail on 07 3339 5611.

Thanks,
James!
Paxus Australia Pty Ltd

**Comment by iamkevinv** [comment]
Hi @Jam-Per - Could you please provide the name of the organisation in the description before i add the label which makes it viewable from BrisJS.org ?

**Comment by Jam-Per** [comment]
Hi Kevin,

Full disclosure; I work for a recruitment agency engaged directly by the client to find them 2 highly skilled React Developers.

My preference would be to not put the client name in an open forum, but instead to have discussions with your members as they show interest.

Please let me know if this is acceptable.

Thanks,

James

**Comment by iamkevinv** [comment]
Thanks for your candour James,
To avoid BrisJS.org's #jobs page descending into "just another recruiter board" so to speak, we have to maintain a policy of people disclosing the company this is for. We therefore encourage this board to be for developers seeking, and for companies listing directly. If that's incompatible with your pitch, i'm afraid i can't tag this post to appear on the website. Sorry about that!

**Comment by Jam-Per** [comment]
Hi Kevin,

I appreciate the sentiment behind your decision. I believe the method in which one has to post to your job board, plus the level of scrutiny that goes before a position is posted to your website, is very likely sufficient enough to ensure that your #jobs page will not descend into “just another recruiter board”, even without the disclosure of my end client.

I can share the name of the organisation, but in doing so I believe I may be circumvented in the process. Can we reach some sort of compromise to at least test how opening your job board to some Recruiters might actually add benefit to your community? For example, I am happy to disclose my company and give a bit of background about the organisation I am recruiting for without giving the name away.

Thanks,

James
