### ISSUE TITLE
Talk on Usability Testing 

### ISSUE THREAD

**Issue by gupta-kartik** [BrisJS/meetups#343]
Ready to go for next one Kev.

**Comment by iamkevinv** [comment]
Confirming you for July @gupta-kartik :)

**Comment by iamkevinv** [comment]
Can you give a description for this talk please @gupta-kartik so i can put it in the announce?

**Comment by iamkevinv** [comment]
@gupta-kartik ???

**Comment by gupta-kartik** [comment]
Title: Build without regrets: a primer on usability

Description: Too often we build products only to find that they don’t work and then spend time rewriting them. Kartik Gupta takes us through the importance of regular usability analysis so you end with a product your customers can use.

**Comment by iamkevinv** [comment]
Want to share any resources @gupta-kartik ?

**Comment by gupta-kartik** [comment]
Yes! You'll have to allow me till this weekend to finalise the resources. Life is a bit too rich at the moment.

**Comment by iamkevinv** [comment]
Feel free to add any resources here when you can :)
