### ISSUE TITLE
Lightning talk: Using ink to write the ABC amazon game

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#345]
Who: Nathan Hoad (@nathanhoad)
Using ink to write interactive narratives like the Amazon race - an interactive news game about what it’s like to work in an Amazon warehouse.
https://www.abc.net.au/news/2019-02-27/amazon-warehouse-workers-game-race/10803346

**Comment by iamkevinv** [comment]
Did you have any slides / links to share @nathanhoad ?

**Comment by nathanhoad** [comment]
Inky tool: https://www.inklestudios.com/ink

Inky parser: https://github.com/y-lohse/inkjs

Game source: https://github.com/abcnews/amazon-race-game
