### ISSUE TITLE
Preventing Cross-site scripting (XSS) attacks in Angular and React

### ISSUE THREAD

**Issue by AKlaus** [BrisJS/meetups#349]
I'd like to talk about CSP and Cross-site scripting (XSS) attacks with a short run on the state of affairs in the modern SPA frameworks (Angular, React). 

Would people be still interested in the topic? I know it was [covered to some degree in October 2018](https://github.com/BrisJS/meetups/issues/252).

Have a blog post on the subject [here](https://alex-klaus.com/protecting-angular-from-xss-attacks-with-csp/).

**Comment by iamkevinv** [comment]
Hi @AKlaus - That sounds awesome - could you present this coming monday? 20 mins sufficient?

**Comment by iamkevinv** [comment]
I've popped it on the meetup page and holding off on the email until you can confirm :) 
https://www.meetup.com/BrisJS/events/mhnwzqyzlbhb/

**Comment by AKlaus** [comment]
@iamkevinv, I'll fit it in the 20 min talk. See you on Monday

**Comment by AKlaus** [comment]
Here's my slides:
https://www.slideshare.net/AlexanderKlaus2/preventing-crosssite-scripting-xss-attacks-react-angular

**Comment by iamkevinv** [comment]
Thanks!
