### ISSUE TITLE
Bullion Capital Looking for Javascript and Nodejs Engineer

### ISSUE THREAD

**Issue by swren** [BrisJS/meetups#35]
As a developer, you will be responsible for the ongoing development of our online trading system and supporting services. We are developing new technology that has been released in Australia and we are now looking to expand into overseas markets. This is an excellent opportunity to get involved in global financial markets, help grow the business at the ground level and become an integral part of our IT Team.

BullionCapital offers a physical bullion market, with an online trading platform for precious metal traders and investors. You will be directly working on our trading engine and supporting systems. The dynamic nature of this large project provides the opportunity to work on many different systems and technologies - from front-end client interaction to backend processes and monitoring. You will be self-motivated, willing to learn and can work well within a team environment.
 
The following are requirements for the position:
Minimum 2-5 years experience in software application development - Node.js, PHP and MySQL specifically
Very good JavaScript skills with Angular experience
jQuery, HTML and CSS experience
GIT
Understanding of service-driven architecture
Strong verbal and written communication skills
 
The following would be highly desirable:
An understanding of Node.js platform andJavaScript Frameworks
Experience in application design, especially in the financial markets area

A remuneration package commensurate with skills and experience will be negotiated.

**Comment by AshKyd** [comment]
This one went to @marklawlor, yeah? Is it okay to close off now?

**Comment by swren** [comment]
Hey Ash

Yes, we were lucky enough to get Mark onboard, but are still looking for more :)

**Comment by kevdesign** [comment]
Awesome.

**Comment by alexzhaosheng** [comment]
Hi, I'm interesting with this position, could you tell me how to apply? 
I have quite good experience, here is a JavaScript framework I've created: http://www.knotjs.com
I'm going to attend the Meetup this Thursday, or you can reach me at Woodheadz@Gmail.com

**Comment by iamkevinv** [comment]
@marklawlor and @swren can field this one :-)

**Comment by iamkevinv** [comment]
@swren - I'm assuming this can be closed? Been open some time.
