### ISSUE TITLE
Lightning Talk on CampJS

### ISSUE THREAD

**Issue by gupta-kartik** [BrisJS/meetups#350]

**Comment by iamkevinv** [comment]
Really trying to sneak in there aren't you? :P 
I guess if you're going to do this, it has to be this month. Otherwise will be too late. We have a pretty packed schedule though so we'll have to be quick.

**Comment by iamkevinv** [comment]
Did you just wanted to talk about it during my mention of upcoming events? or is this actually a lightning talk? Normally i put up a slide and let folks talk for a few as you remember. Just trying to work out if i'm listing this as an actual talk or i it's an advertisement hahaha...

**Comment by gupta-kartik** [comment]
It is going to be a call for action. @garrows is going to present tonight so a step up from boring old me :) 
We would appreciate 5-10 minutes at the beginning if you can manage it @iamkevinv. It won't be longer than that
