### ISSUE TITLE
BrisJS Social Booked for 20 people at 6pm Buffalo Bar 12th August

### ISSUE THREAD

**Issue by gupta-kartik** [BrisJS/meetups#351]

**Comment by gupta-kartik** [comment]
For your attention @iamkevinv I'll set up the meetup event shortly

**Comment by iamkevinv** [comment]
Thanks @gupta-kartik - appreciate you volunteering to help put that together :)

**Comment by gupta-kartik** [comment]
You're welcome @iamkevinv. I will try to be more consistent this month onwards.

**Comment by iamkevinv** [comment]
lol so we never made the meetup event... so it never happened. :) Oops.

**Comment by gupta-kartik** [comment]
That was my bad. Sorry. CampJS is a time sink at the moment.
