### ISSUE TITLE
Node.js and Docker

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#352]
This talk happened on the 5/8/2019.

Here's my slides: 
https://www.slideshare.net/AshleyDavis33/nodejs-and-docker-at-brisjs-5th-august-2019

Here's the example code on GitHub: 
https://github.com/ashleydavis/docker-nodejs-examples

I also have a bunch of other similar examples on GitHub: 
https://github.com/ashleydavis?tab=repositories&q=docker

**Comment by iamkevinv** [comment]
Thanks mate!
