### ISSUE TITLE
Talk on security

### ISSUE THREAD

**Issue by bendechrai** [BrisJS/meetups#353]
Hi there! I just heard that your next meetup is the 2nd Sept, and I have been looking for an excuse to come to Brissy. If you're still looking for a presenter that evening, I'm happy to talk about one of various security topics in JS...

1. History of JWTs, auth, etc...
1. How OAuth and OpenID Connect work in single page apps
1. Secure communications to keep your customer's data safe

Do any of these sound interesting?

**Comment by iamkevinv** [comment]
Sure is! Would love to have you. Sorry it took so long to respond :)
Would be great to hear any of those topics as honestly we don't get enough of them. Would be great to actually get a few of them over time. Which would you prefer for Monday @bendechrai? :)

**Comment by bendechrai** [comment]
Hi Kevin! No worries. I'm happy to give all three over time :)

The history of JWTs/Auth/... is probably a good general one to get started with. That usually takes 20-30 minutes (although last time I gave it Q&A pushed the topic out to 50!) Maybe we call it a 30-minute talk including questions, and if there are still questions I'll take people out for a beer or something :D

If you're happy with that, here's the info you need:

*Abstract*

>We've all written a login page, but is that still best practice?
>
>Come learn about OAuth, OpenID Connect, and JSON Web Tokens; how they work, and how they can simplify your projects, from single-page apps to the APIs that drive them, and everything in between.

*Longer description*

>It's unusual to develop applications that have no identity requirements nowadays. Whether it's securing access to resources, synchronising data between devices, or providing a customised experience, any new project will soon need that login form.
>
>While you might start out with a simple login form and a backend user directory, these soon grow into their own beasts, when requirements call for multi-factor authentication, or machine-to-machine authorisation functionality.
>
>These requirements and associated maintenance costs are often at odds with the desire to focus on building new features that actually bring your users value, or fixing bugs that currently bring them pain.
>
>In this talk, you will learn about OAuth, OpenID Connect, and JSON Web Tokens; where they came from, how they work, and how they can simplify your projects, from single-page apps to the APIs that drive them, and everything in between.

If you want a bio:

>Ben Dechrai is a technologist with a staunch focus on security and privacy. This started at the age of 11, when he wrote software to stop his parents from breaking the family PC, and resulted in his working as a developer advocate for Auth0. He enjoys helping developers find the joy of experimentation, from ethical skulduggery to subversive automation, and can be found on Twitter and Instagram at @bendechrai.

**Comment by iamkevinv** [comment]
Fantastic mate - going to send out the details tonight. Let's keep an eye on time. I'll get you up first after my intros, and give you about 30 mins and then we'll break for pizza and networking. 👍

**Comment by iamkevinv** [comment]
This was excellent! Come back anytime! Much appreciated. 
Just cleaning up issues on github now... so going to close this. Looking forward to more submissions soon :)
