### ISSUE TITLE
Talk : Deployment Of Web Application on AWS (20 mins)

### ISSUE THREAD

**Issue by Shreykhanna** [BrisJS/meetups#354]

**Comment by iamkevinv** [comment]
Sounds cool @Shreykhanna - can you give a bit more info?
Are you happy to present on 2 Sept?
How long? 10m (lightning) / 20m (standard) / 30m (headline)?
Also a few-sentence description of the talk for my use on the email/meetup page :-)

**Comment by Shreykhanna** [comment]
Date : 2 September 2019
Duration : 20 minutes
Description :  
1. Introduction on AWS.
2. AWS Resources to be used for deployment.
3. Live Demo of the whole process.
4. AWS Security general best practices.

Sir, Is the description well enough?

**Comment by iamkevinv** [comment]
Perfect mate... much appreciate it! See you monday!

**Comment by iamkevinv** [comment]
Thanks for doing this talk Shrey! Hope to see a another new talk from you this year. ;-)
