### ISSUE TITLE
"Just in Time" serverless rendering with Lambda

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#355]
Speaker: 
Maurice Butler - https://twitter.com/ButlerMaurice

Description:
When it comes to optimal SEO and pages shareable to social media, there is no option your first html payload needs to be informative. To do so you can use server-side rendering or build-time static rendering, but these methods all fall apart when doing anything more complex than a TODO app or you add dynamic data and authentication into the mix. So this is how I tricked AWS Lambda into doing a hybrid "Just in Time" render of our public-facing, dynamic data-driven, heavily SEO and social sharing reliant pages.

**Comment by MauriceButler** [comment]
Slides are here https://docs.google.com/presentation/d/1vbjrk4N3lFjzEOX7YmIpt0NXunI0Dk1cTns40S6w_Bo

**Comment by iamkevinv** [comment]
Thanks again for doing this talk last year @MauriceButler - i'm cleaning up and going to close this one now. Appreciate you sharing the resources :)
