### ISSUE TITLE
Short talk: Crafting a multi-stage build pipeline with Docker

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#358]
Talk title: Crafting a multi-stage build pipeline with Docker
Talk length: 10-15 mins
Talk synopsis:
This short talk continues from Ash's previous talk on using Docker with Node.js. Our application is more advanced now and we've decided we need a build process. We might be wanting to using Babel, TypeScript, React or something else. How do we create a build process without adding unnecessary bloat to our Docker image? In this talk we learn how a Docker multi-stage build allows us to separate the debris from our production application.

Available month(s): I can put this talk together with 1 week notice.
Twitter: ashleydavis75

**Comment by iamkevinv** [comment]
Thanks for the submission! In the lead-up to the Oct BrisJS event, i'll check in again to see if you're ready and will mark this issue as confirmed when you do :)

**Comment by iamkevinv** [comment]
Confirming for Oct 14?

**Comment by ashleydavis** [comment]
Yep all good. 

Will be 10-15 minutes based on my recent blog post: 

https://blog.logrocket.com/crafting-build-pipelines-with-docker/

**Comment by iamkevinv** [comment]
15 is a 20 slot then :) 
Thanks! See you then!

**Comment by ashleydavis** [comment]
Here are my slides: https://www.slideshare.net/AshleyDavis33/crafting-build-pipelines-with-docker

Examples and resources:

GitHub
https://github.com/ashleydavis/docker-nodejs-examples

Blog post
http://www.the-data-wrangler.com/crafting-build-pipelines-with-docker/

Docs
https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by iamkevinv** [comment]
Thanks for sharing all these resources! Looking forward to more from you in 2020 ;-)
