### ISSUE TITLE
Talk: "Adapting a component library for better adoption"

### ISSUE THREAD

**Issue by astrotim** [BrisJS/meetups#359]
**Talk title** 
_Adapting a component library for better adoption_

**Talk length** 
20 min regular talk

**Talk synopsis** 
Tim Holt, web developer at the ABC, explains how we have adapted our component library to address growing pains since launching products on our new React infrastructure. 

**Proposed date**
14th October 2019

Note: I will be [presenting this topic at Web Directions Summit](https://www.webdirections.org/wds/speakers/tim-holt.php) in Sydney. 

**Conference synopsis:**

Developing a UI component library for a large organisation with many different products is a challenging endeavour. A good system will strike the right balance between consistency and flexibility and will afford developers efficiency and quality. These are characteristics difficult to get right up front.

At the ABC, we are continually iterating our component library to improve a key measure of success: adoption. We want teams to want to use it! This talk will discuss some of the challenges we’ve faced, how we approach trying to find the right level of component granularity and cover some illustrative examples of the changes we’ve made to get more developers of ABC digital products on board.

**Comment by iamkevinv** [comment]
Thanks for the submission! In the lead-up to the Oct BrisJS event, i'll check in again to see if you're ready and will mark this issue as confirmed when you do :)

**Comment by astrotim** [comment]
Awesome!

**Comment by astrotim** [comment]
Looks like the date for the next meetup is Monday 14/10/19 - I've updated my proposal above.

**Comment by iamkevinv** [comment]
Yes! Public holidays mean we delay. Confirming for Oct 14?

**Comment by astrotim** [comment]
Confirmed ✅

**Comment by zorfling** [comment]
Did you ever share the slides @astrotim ? Been mentioning your talk to a few people and it'd be cool to send a link.

**Comment by astrotim** [comment]
@zorfling here's the deck
https://speakerdeck.com/astrotim/adapting-a-component-library-for-better-adoption

I tried posting it as a comment on the Meetup page, but "something went wrong"

**Comment by zorfling** [comment]
Thanks @astrotim

**Comment by iamkevinv** [comment]
Thanks @astrotim - hope to see you or your colleagues present something soon at BrisJS in 2020 - love seeing some ABC representation!
