### ISSUE TITLE
Understanding ES6 Generators

### ISSUE THREAD

**Issue by marklawlor** [BrisJS/meetups#36]
Hey guys,

I've prepared a talk on ES6 generators. It covers the basics of what they are and some quick examples of code patterns they can be used in.

I'm happy to present at the Jan / Feb meetup

**Comment by kevdesign** [comment]
Lets do this in Feb. Thanks for jumping in though - i really appreciate it.
If there are more things to come though - please don't slow down the enthusiasm.

**Comment by marklawlor** [comment]
Thats cool, Feb meet up it is :+1:

**Comment by kevdesign** [comment]
Thanks again for presenting @marklawlor - If you could post the slides link here too that would be really handy. Cheers.
