### ISSUE TITLE
The Angular Light Touch

### ISSUE THREAD

**Issue by adriandavidbrand** [BrisJS/meetups#360]
Talk title: The Angular Light Touch
Talk length: 20 min
Talk synopsis: How to rapidly build forms application using ngx-rxcache for state management and ngx-ez for templates with barely any boilerplate and hardly any code. I am the Angular specialist for the Department of Human Services Aged Care and we have been using this pattern for over a year now and it has greatly increased our velocity, reduced cost and new devs get up to speed very quickly. I recently gave this talk to the Brisbane Angular Meetup and though I would like to share it with the wider JS community.
Available month(s): Any
Optional: your Twitter account so we can promote your talk

**Comment by iamkevinv** [comment]
Thanks for the submission! In the lead-up to the Oct BrisJS event, i'll check in again to see if you're ready and will mark this issue as confirmed when you do :)

**Comment by iamkevinv** [comment]
Confirming for Oct 14?

**Comment by adriandavidbrand** [comment]
All good for next Monday.

**Comment by adriandavidbrand** [comment]
Where and when? I will have a way to plug my laptop in via HDMI?

**Comment by iamkevinv** [comment]
Yes, HDMI is the input for the mirroring of picture (sound is not transferred through hdmi at the venue). The output should be set to 1080i output (not 1080p) but if you're lost i can help on the night. I start my introduction from 6:30 and we begin with talks once it's over. We're at Toowong tower, level 6. You get there by being collected by security on Gallery level (that's GL) in the corporate tower lift area. https://brisjs.org/#findus

**Comment by iamkevinv** [comment]
@adriandavidbrand For the talk info, is your full name Adrian Brand?

**Comment by iamkevinv** [comment]
Thanks again @adriandavidbrand - Hope you can present something in 2020 too :)
