### ISSUE TITLE
Using GraphQL Subscriptions to play Sounds 🔈

### ISSUE THREAD

**Issue by xicovarisco** [BrisJS/meetups#361]
**Summary of talk**
How to architect a platform to play sounds in Real Time with GraphQL Subscriptions.

**Details**
Using GraphQL Subscriptions to play Sounds
How can we empower and excite teams using sounds on custom triggers.

**Description of the Talk**
The idea is to explain why it's important to keep the team momentum high (specially in startups). After that I'll demonstrate how we (Askable) use a sound system to make us aware of what's going on with our clients (E.g we hooked our booking system to trigger a loud sound to us every time a client purchases something)
Lastly we do a live demo in-house :)

My Info
@xicovarisco

**Comment by iamkevinv** [comment]
Thanks so much for volunteering to present this one at BrisJS. Are you available for the November meetup on Nov 4 ?

**Comment by iamkevinv** [comment]
Can i confirm you for November 4 @xicovarisco ?

**Comment by iamkevinv** [comment]
I've also got 20 minutes set aside for this talk - please feel free to explore the details of graphQL's applicable features and how the audience can leverage them for anything :)

**Comment by xicovarisco** [comment]
Hey mate,
I've just seen your messages. Sorry for not answering that before.
I'll be there. :)

Thanks

**Comment by iamkevinv** [comment]
Thanks heaps for your talk mate... looking forward to more brisjs presentations featuring you in 2020 :)
