### ISSUE TITLE
Prosemirror rich text editor

### ISSUE THREAD

**Issue by ghedwards** [BrisJS/meetups#362]
I'd love to see a presentation on the prosemirror rich text editor

**Comment by iamkevinv** [comment]
This one has been on our board a long time @dallasclark - since your company is in the space of text editor solutions, perhaps it's an interesting opportunity to review and present some other types of solutions in the space in a compare and contrast fashion?

**Comment by dallasclark** [comment]
Hey @iamkevinv,

Thanks for the ping!

Definitely, I will see if I can persuade one of the editor gurus for this talk.

DC
