### ISSUE TITLE
Genie Solutions is hiring Senior Developers!

### ISSUE THREAD

**Issue by nootn** [BrisJS/meetups#363]
We are in search of developers who are motivated to help us achieve our purpose of helping medical professionals deliver better health outcomes!

Our team's are cross functional and we know developers generally have a preference to either front or back end style work.  In this case we need one of each!  So we do have a back-end data-heavy type person needed, but also a React guru!  If that sounds like you have a read of the [job ad](https://www.linkedin.com/jobs/view/1502241247/) and hit me up on [LinkedIn](https://www.linkedin.com/in/andrewnewton/) or [Twitter](https://twitter.com/nootn) if you would like to know more!

**Comment by thebinarysearchtree** [comment]
I want to do the backend one :)

**Comment by iamkevinv** [comment]
@nootn - Is this position still current? Should it be closed? Thanks!
