### ISSUE TITLE
How live coding on Twitch made me a better developer

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#364]
After streaming for some time on YouTube, I took the plunge, and I'm now professionally live coding on Twitch.tv: https://www.twitch.tv/thelegendaryjoshwulf

I share my experience and the surprising discovery I made live coding; my hardware and software setup; and the tools that I've written in JavaScript to automate my workflow.

**Comment by iamkevinv** [comment]
Sweet! Okay to do November BrisJS? 20m?

**Comment by jwulf** [comment]
What's the date?

**Comment by iamkevinv** [comment]
4 Nov

**Comment by iamkevinv** [comment]
This one, or #366 ?

**Comment by jwulf** [comment]
Let's do Twitch this time.

**Comment by iamkevinv** [comment]
Hey mate... is this around 10min+Q&A or 20min+Q&A?

**Comment by jwulf** [comment]
I can do either.

**Comment by iamkevinv** [comment]
Can i confirm you for this talk 2nd Dec @jwulf?

**Comment by jwulf** [comment]
20 mins ready to rock

**Comment by iamkevinv** [comment]
Thanks for the presentation again mate :)
