### ISSUE TITLE
Lightning Talk: ES2020 features you can use now

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#365]
New ES2020 features available NOW in TypeScript 3.7-beta: optional chaining and nullish coalescing. Program like it's the future NOW!!!

**Comment by jwulf** [comment]
Prettier support for optional chaining: https://github.com/prettier/prettier/issues/6595

**Comment by iamkevinv** [comment]
When you keen for this one @jwulf ?

**Comment by jwulf** [comment]
I can't make it this month.

**Comment by iamkevinv** [comment]
@jwulf there's also this one you could pick for April if you're keen?

**Comment by jwulf** [comment]
YesBlog | Bio | Books | Talks: www.joshwulf.com---- On Fri, 27 Mar 2020 11:27:28 +1000  Kevin Vanderbeken<notifications@github.com> wrote ---- 
@jwulf there's also this one you could pick for April if you're keen?

**Comment by iamkevinv** [comment]
I'm operating on the FIFO principle and selected this one for presenting at BrisJS :) Hope that's cool @jwulf :)

**Comment by jwulf** [comment]
Yep, that’s good.

**Comment by iamkevinv** [comment]
Thanks @jwulf - I've set up the talks via Zoom conferencing.

The speakers will join the zoom conf directly, everyone else watches on youtube streaming.
Please aim to join and test with us at 6:20pm.
You can download and install the Zoom client if you follow the zoom meeting url below too, and use the following details:

> Join Zoom Meeting:
> https://zoom.us/j/169245706
> 
> Meeting ID: 169 245 706
> 
> Backup voice telephone line options for audio:
> One tap mobile:
> +61871501149,,169245706# Australia
> +61280156011,,169245706# Australia
> 
> Dial by your location
>         +61 8 7150 1149 Australia
>         +61 2 8015 6011 Australia
>         +61 3 7018 2005 Australia
> Meeting ID: 169 245 706

**Comment by jwulf** [comment]
Here is the demo repo: https://github.com/jwulf/es2020-ts

**Comment by iamkevinv** [comment]
Thanks mate!
