### ISSUE TITLE
NestJS: a modern backend framework

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#366]
NestJS is a backend framework that provides you with plumbing and opinionated structure for building services using REST, GraphQL, WebSockets and gRPC.

"Inspired by Angular", it is TypeScript native and uses decorators and dependency injection to wire things up.

In this talk I will give you an overview of NestJS, some of the backstory, and demonstrate how easy it is to build a working, well-structured server in minutes.

**Comment by iamkevinv** [comment]
Excellent! Are you wanting to do this one or the https://github.com/BrisJS/meetups/issues/364 talk proposed earlier?

**Comment by iamkevinv** [comment]
My vote is on this one :)

**Comment by iamkevinv** [comment]
Thanks again mate... closing the issue now that this is long done :)
