### ISSUE TITLE
Voice AI technology, use cases and demos

### ISSUE THREAD

**Issue by shreyasnivas** [BrisJS/meetups#367]
G'day,

My name is Shreyas - I'm the CEO of Brisbane based Replica Studios.

We're an AI voice company, and recently returned from a trip to LA where we attended Techstars Music, and we also just secured a round of funding from US based investors.

Here's a 60 second demo of what we created using our Voice AI - https://www.youtube.com/watch?v=f4DgHI9J3U8&feature=youtu.be

I'd love to present a talk about the use cases we're working on, and I have a bunch of demo's to show.

I'm hoping to showcase what we do to the Brisbane Js scene, and we're looking to recruit a couple of devs this year. Happy to sponsor beers and pizzas at the next event.

Feel free to email me - shreyas@replicastudios.com

Here's a couple of relevant links about us :

www.replicastudios.com

https://www.smartcompany.com.au/startupsmart/news/replica-studios-raise/

Cheers,
Shreyas

**Comment by iamkevinv** [comment]
Hey Shreyas, Congratulations on your startup!
If you could focus your submission a bit more around a use case, and do a dive into the tech and solution driving it, along with demos, i think a lot of people will be interested.
Please feel welcome to post comments here and we can refine it together :-) 
Lets get a title, talk description with what people will learn from it, and we'll get your talk in! 👍

**Comment by iamkevinv** [comment]
Actually if we can refine the topic quickly, we can get you in for the Nov 4 event next week.

**Comment by shreyasnivas** [comment]
Hey Kevin,

Sounds great!

I did a similar talk before - I'm the second speaker (Replica Studios)

https://m.facebook.com/story.php?story_fbid=415387982709749&id=208108746608800&_rdr

I could omit the technical slides and maybe add some slides that are more
product oriented. Let me know what you think.

Best,
Shreyas

**Comment by shreyasnivas** [comment]
Hi Kevin,

Let me know if you've had a moment to run through that talk, I've got some
ideas around product oriented slides that I can add - essentially talking
more about the Frontend stack that might support the heavy text<>audio
capabilities that our users demand..

For example we are facing a few issues already since our app is browser
based, and the browser is caching an hour's worth of .wav files to be
played back to the user.. Our solution is to try and implement a
crossplatform app (Mac app, Windows app) for each OS that can utilise the
computing power of the device itself to provide users with lightning fast
workflows.

I could spend a moment talking about similar AI products and how we're
seeing them also choose this sort of cross platform stack.

And of course I will include all the slides from my talk which delve more
deeply into the use cases around podcasting, advertising, gaming,
integrating out API with 3rd party apps that need voice, etc.

I'd like to try and make the Nov 4th meetup. Let please try to align so we
can hit that deadline?

Let me know what I need to provide.
Best,
Shreyas


Shreyas Nivas
+61 0427 207 370
http://au.linkedin.com/in/snivas

**Comment by shreyasnivas** [comment]
Hey Kevin,

Im not sure whether we are working towards aligning for Nov the 4th or not.

I had initially offered to sponsor beers / pizzas for the event as well,
again not sure where we stand as I have not heard from you / your team.

I am traveling over the next 24 hrs and will have my keynote ready
regardless and look forward to an email from you confirming the plan.

Cheers mate
Shreyas

**Comment by iamkevinv** [comment]
So so so sorry mate... Github totally failed me and i didn't get notified of updates to this thread. 🤦‍♂ 
If you're married to the Nov 4th date i can drop the lightning talks and move them to dec 2nd. Otherwise, we can use the time ahead to make sure we properly advertise your talk for Dec 2, and ensure that everyone knows you're coming and what topics you'll cover - getting in some of the brisjs data science and ai enthusiasts who are out there too - right now we only have the weekend left and i don't want to short change you :) 
What are your thoughts?

**Comment by iamkevinv** [comment]
In terms of content, it's a technical audience so definitely don't omit that technology - feature that heavily and see where our javascripters could take that

**Comment by iamkevinv** [comment]
Appreciate the sponsorship offer but that's completely covered already. 👍

**Comment by iamkevinv** [comment]
If you have the opportunity, please do come to our event and enjoy the hospitality as some slight compensation for my lack of earlier reply. Would be excellent to meet.

**Comment by iamkevinv** [comment]
Yes! Definitely bring folks along, it's an open group :) Just some RSVP's on our meetup page is appreciated for numbers for catering :)

**Comment by shreyasnivas** [comment]
sounds good!

Shreyas Nivas
+61 0427 207 370
http://au.linkedin.com/in/snivas

**Comment by iamkevinv** [comment]
Confirmed for dec 2 @shreyasnivas?

**Comment by shreyasnivas** [comment]
Sure thing
