### ISSUE TITLE
Postman: How to test and monitor your APIs with no hassle

### ISSUE THREAD

**Issue by jernejk** [BrisJS/meetups#368]
Talk title: Postman: How to test and monitor your APIs with no hassle
Talk length: 40 min (can be 20 min as well)
Talk synopsis:
Testing and monitoring APIs is a hard and time-consuming process.
In this talk, I'll show you how to simplify debugging and integration testing with Postman. We'll import requests from Open API (Swagger), switch between different environments, manipulate environment variables with scripts, monitor the health of our application and much more.

Available month(s): December onwards
Optional: your Twitter account so we can promote your talk
jernej_kavka

**Comment by iamkevinv** [comment]
Thanks! Dec would be good. We only start back up in Feb.

**Comment by iamkevinv** [comment]
Hey again - if we have enough open time in the lineup - we can make it 30 min... for now we'll likely get a rush in Dec so i'm preserving options. You'll still get some time for questions on top of this regardless.

**Comment by jernejk** [comment]
Yeah, I'm happy to do any length as long as I get enough heads up to shave off content. :)

**Comment by iamkevinv** [comment]
Confirmed for dec 2 @jernejk ?

**Comment by jernejk** [comment]
Yes, I'm doing a practice run on Friday at my company. :)

**Comment by jernejk** [comment]
Thanks for having me at BrisJS. :)

@iamkevinv I noticed I was recorded and I'm happy to be published.

It would be great if the key would be censored if possible.
Most of the keys should have been replaced by now but I might have missed one.

**Comment by iamkevinv** [comment]
@jernejk - That will be no problem at all :)

**Comment by iamkevinv** [comment]
Thank you for supporting brisjs in dec :)
