### ISSUE TITLE
SheCodes workshop

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#369]
Hi all,

The SheCodes workshop is on for the first time in Brisbane this Saturday. https://shecodes.com.au/

Unfortunately there is a waitlist however they are looking for more *mentors* (men or women) which I'm sure this group is more than capable of providing. If you have some free time to donate to a good cause, register via eventbrite. 

https://www.eventbrite.com.au/e/1-day-coding-workshop-for-women-powered-by-she-codes-australia-registration-72355215397

:)

**Comment by iamkevinv** [comment]
https://twitter.com/BrisJS/status/1189892536002727941
