### ISSUE TITLE
#1gam & web-based gamedev stuff

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#37]
Last year I spoke (perhaps a little too late) about #js13k, which there seemed to be a bit of interest in. So in the interest of keeping everyone in the loop, here's some things you might want to keep an eye on in 2014:

* #1gam - [One game a month](onegameamonth.com) - Informal challenge, new theme every month!
* [Global Game Jam](http://globalgamejam.org/) - January 23 - 25 - There isn't a site in Brisbane yet, is there enough interest in trying to get one happening?
* Anything else?

**Comment by kevdesign** [comment]
Good luck with it all :) Please schedule some time to show us the results if you can :)
