### ISSUE TITLE
Fun with node.js REPL

### ISSUE THREAD

**Issue by tomquirk** [BrisJS/meetups#370]
Talk title: Fun with node.js REPL
Talk length: Lightning talk
Talk synopsis: "lightning" intro to the [node.js REPL module](https://nodejs.org/api/repl.html) and how [Messer](https://github.com/mjkaufer/Messer) uses it to implement Facebook Messenger in the terminal
Available month(s): November
Twitter: [@tom__quirk](https://twitter.com/tom__quirk)

If you guys still need a lightning talk, I'd love to put this together :)

**Comment by iamkevinv** [comment]
Yes please! Sounds cool!

**Comment by iamkevinv** [comment]
I'll confirm you for monday

**Comment by tomquirk** [comment]
Sounds great, thanks @iamkevinv 🎉

**Comment by iamkevinv** [comment]
Really appreciated your talk in 2019 @tomquirk - please feel free to come back any time for a 2020 encore!
