### ISSUE TITLE
When to TDD

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#372]
TDD is awesome | TDD is stupid
Pick a side, maybe both are wrong.

🧪When to TDD - Kory Nunn (@KoryNunn) - 20min:
When it comes to test driven development, there are some vocal camps that will tell you TDD is awesome in their flow, but there's certainly others that don't see the benefit of placing these up front conditions in their situation. Kory will explore some of these merits, but even if you picked a side already, as he says; maybe both sides could be wrong?

**Comment by iamkevinv** [comment]
Confirmed for dec 2 @KoryNunn ?

**Comment by KoryNunn** [comment]
Yep can do.

**Comment by KoryNunn** [comment]
Yep I'll probably be ready.

**Comment by iamkevinv** [comment]
@KoryNunn cannot make it anymore and this talk has been cancelled for now.

**Comment by KoryNunn** [comment]
Sorry about that. I'm still very interested in doing this, but I can't lock in a date yet.

**Comment by KoryNunn** [comment]
I can but I think I want to change the topic :S ive been making up another talk over the last few weeks that I need to get out of my head before the TDD one: "Maybe you shouldn't - Why scrutinizing the norm is a must"

**Comment by iamkevinv** [comment]
Sure mate - I'm seeing that as a larger pattern to the whole series :)

**Comment by iamkevinv** [comment]
Pop up a new github issue?

**Comment by KoryNunn** [comment]
Can we make this for next month?

**Comment by iamkevinv** [comment]
@KoryNunn - You keen for this one on march 2nd?

**Comment by KoryNunn** [comment]
Yep I'll be there

**Comment by iamkevinv** [comment]
Thanks again mate! I'll give you a better intro next time :)
