### ISSUE TITLE
Component driven development using atomic design pattern

### ISSUE THREAD

**Issue by Komalbandi** [BrisJS/meetups#373]
Talk title:Component driven development using atomic design pattern

Talk length: 20 min

Talk synopsis:
If you are using Angular, React, Vue or any of the modern frameworks, you are already familiar with component driven development.
I have worked across various industries and there seems to one common problem;
programmers acknowledge component based platform can help them reuse front end code, it helps with a user experience consistency.
But the questions has always been how?
The talk will be focused on using Atomic design pattern to better organise your front end component

Available month(s):
December or February

Full name: Komal Krishna Bandi

Twitter: komalbandi

**Comment by iamkevinv** [comment]
@Komalbandi We've had a last minute cancellation - if you're keen to fill in this spot for 2nd Dec, let me know - otherwise we'll see you in Feb. :-)

**Comment by Komalbandi** [comment]
@iamkevinv Sorry just saw your mail, I can present for the next one.

**Comment by iamkevinv** [comment]
Hi @Komalbandi - i hope your start to 2020 has been great!
Can you still present for our feb BrisJS?

**Comment by iamkevinv** [comment]
Thanks so much for presenting at brisjs... don't hesitate to share any of your talk resources here...

**Comment by Komalbandi** [comment]
Thank you Kevin, it was a pleasure and hope to do it again.

Kind Regards,
Komal Bandi
