### ISSUE TITLE
Metamodules: Importing the banana without the forest

### ISSUE THREAD

**Issue by BrighTide** [BrisJS/meetups#374]
Talk length: 5min
Talk synopsis: Often we encapsulate and deploy microservices as a node module. This is great, but when you want to re-use something from that service then your other services have to import an entire service just to use it. Using typescript and some npm scripts though you can create a "meta-module" build step, that packages what you need and publishes it as a separate module to be imported by other services.
Available month(s):
Also: No twitter, Jarred Filmer

**Comment by iamkevinv** [comment]
If you had any resources to share here @BrighTide please feel free to add them :)

**Comment by BrighTide** [comment]
Just the slides :) https://docs.google.com/presentation/d/1YgPk03eJ1u-W8mlwN0Gz9kP1dmewFwhrgWeByp_o96Q/edit?usp=sharing
