### ISSUE TITLE
Short talk: Lerna

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#375]
Time: 5-10 mins.

Lerna is tool I'm using with one of my npm packages to help structure a multi-package solution. Lerna makes it easy to manage multiple npm plugins you are building and publishing from a single code repository.

I can do this talk at short notice.

If anyone else wants to take this talk that's perfectly ok (I don't want to hog all the topics!)

**Comment by iamkevinv** [comment]
I love all the little talk suggestions mate! These will be great

**Comment by ashleydavis** [comment]
I'm not going to do this talk because I've stopped using Lerna, might good for someone else to do though!

**Comment by demsey2** [comment]
@ashleydavis what do you use now?

**Comment by ashleydavis** [comment]
I tend to use mono repos or meta repos with no additional tooling.

At work we have just started using [Turborepo](https://turborepo.org/), but it's to early to comment on that yet.

**Comment by demsey2** [comment]
I did read this https://monorepo.tools/#what-is-a-monorepo and also decided to try Turborepo

**Comment by ashleydavis** [comment]
The State of JS 2022 has a whole new section on mono repo tooling:

https://2021.stateofjs.com/en-US/libraries/monorepo-tools

I've tried npm workspaces in one small project and it's a great new builtin feature for managing a mono repo that contains multiple separate npm packages.

**Comment by ashleydavis** [comment]
If you are looking to share TypeScript code between projects I have a [blog post](https://www.codecapers.com.au/sharing-typescript-code-between-projects/) and [video](https://youtu.be/y76n6Ow83YQ) on that.

**Comment by demsey2** [comment]
thanks I will have a look
