### ISSUE TITLE
Short talk: REST Client

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#378]
Talk time: 5-10 minutes.

REST Client is a plugin to Visual Studio Code that allows you to define and make REST API request directly from VSCode. This is such a useful tool. It's like Postman (but not as sophisticated) except with the convenience of not  having to leave VSCode and you can also easily version control your request files and store them in your VSCode project.

I can do this talk at short notice.

If anyone else wants to take this talk that's perfectly ok (I don't want to hog all the topics!)

**Comment by iamkevinv** [comment]
Hey @ashleydavis - Are you interested in doing some of these existing submissions in 2021? Please let me know what months and things you'd like to Jump onto :)

**Comment by ashleydavis** [comment]
I can definitely do this talk. It's a real quick one.

**Comment by iamkevinv** [comment]
Awesome! Lets get you in for Feb 8th if that's okay @ashleydavis :)

**Comment by ashleydavis** [comment]
Yep all good.

**Comment by iamkevinv** [comment]
We'll do the presenting side over Zoom, and it will be automatically streamed to our youtube channel. If we hop on a few mins early we can test audio, video and sharing for everyone.
The link is https://us02web.zoom.us/j/169245706

Topic: BrisJS Meetup
Time: Feb 8, 2021 06:25 PM Brisbane
        Feb 8, 2021 06:25 PM

Join Zoom Meeting
https://us02web.zoom.us/j/169245706

Meeting ID: 169 245 706
One tap mobile audio dial in
+61871501149,,169245706# Australia
+61280156011,,169245706# Australia

Dial in audio by your location
        +61 8 7150 1149 Australia
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
Meeting ID: 169 245 706
Find your local number: https://us02web.zoom.us/u/kcd66mBOf

**Comment by iamkevinv** [comment]
Thanks for the talk, if you've got any resources you'd like to add, please do!

**Comment by ashleydavis** [comment]
Only the web page:

https://marketplace.visualstudio.com/items?itemName=humao.rest-client
