### ISSUE TITLE
ttsc: Politely intruding on the typescript compiler for fun and profit

### ISSUE THREAD

**Issue by BrighTide** [BrisJS/meetups#379]
Talk title: ttsc: Politely intruding on the typescript compiler for fun and profit
Talk length: 20 min
Talk synopsis:
- Sometimes it can be useful to apply code to your code
- Build steps, compilers, transpilers, linters, IDE's
- Since the typescript compiler is already creating an AST and getting all up in your code, why not add some plugins of your own to do stuff like
  - Take stuff from the type system so you don't have to repeat yourself
  - Parsing your comments
  - Adding your own linting / validation steps
- Warning: 95% of times you want to do this in a professional context you shouldn't
Available month(s): Feb, March

**Comment by iamkevinv** [comment]
Hi @BrighTide - Would you be happy to do this for the next BrisJS? Sounds great!

**Comment by BrighTide** [comment]
Sure!

**Comment by iamkevinv** [comment]
Awesome, see you on Feb 3 :)

**Comment by BrighTide** [comment]
- Repo: https://github.com/BrighTide/ttsc-demo
- Slides: https://docs.google.com/presentation/d/1fTt8R6RtXrvaVb6YBLINBq8hp-SaGfw8egl1GRSX_M0/edit?usp=sharing

**Comment by iamkevinv** [comment]
Brilliant! Thanks for the talk, everyone clearly appreciated it! Thanks for sharing the resources too!
