### ISSUE TITLE
Talk Volunteered -- "Fetching stuff with JS"

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#38]
I've had some success "Fetching stuff with JS"
if i make it to the jan5 meetup i would love to outline some 
thoughts/learnings gained after...
+ getting code analysis/metrics for a large JS codebase
+ getting the locations of every regular expression or unused functions within a set of files
+ getting local versions of 100k single page apps on codepen io
+ getting sets of github user repo outlines
+ getting img and linked images at some url
+ getting github activity logs

josh

**Comment by kevdesign** [comment]
Josh - Did you want to approach this one in the next BrisJS or did you want to wait for the March event in which we shall have lots of fast and furious talks ...aka Demo Night / Lightning Talk night. If it was for the next upcoming i could only give you 15min.

**Comment by kevdesign** [comment]
Due to the sudden surge of talking points for generators and promise related stuff - i'd like to relegate the bulk of blank page / lightning talks / Show BrisJS stuff for a full march event. Hopefully it will lead to lots of new talks too. I hope i can count on you too for that month @govpack! :)

**Comment by govpack** [comment]
Kevin, I'm happy with 5 minutes. I can present a chrome extension word game called WordFish that i made for the recent globalgamejam.org that everyone with chrome can play along with (it's in the google webstore [+FREE] -- i figure it would be the best way to go, before some of these things become ancient history. I'm happy to give another short talk in march as well :-)

**Comment by kevdesign** [comment]
Hi @govpack - Can i include your time for the next BrisJS in march? I'll add the correct label to this issue to pre-emptively confirm it.

**Comment by kevdesign** [comment]
You still happy to cover this tomorrow @govpack ? Sorry for the late reminder...

**Comment by kevdesign** [comment]
Thanks for your presentation @govpack :)
