### ISSUE TITLE
micro solutions to annoying problems.

### ISSUE THREAD

**Issue by aspiringguru** [BrisJS/meetups#381]
Long time lurker, first post here :)  

NYE resolution > to blog more. 

Browser caching has annoyed me . thought I was smart creating this.
https://medium.com/@GuruAtWork/html5-escape-js-css-cache-hell-7f88cf646018

If I think of enough useful things I'll do a lightning talk. maybe. hit me with requests :)

**Comment by iamkevinv** [comment]
Sounds great @aspiringguru - please do feel free to suggest some parts of a lightning talk :) I'm sure everyone would be happy to hear it 👍

**Comment by iamkevinv** [comment]
What upcoming brisjs events are you potentially available for this year? https://www.meetup.com/BrisJS/events/

**Comment by iamkevinv** [comment]
Hey @aspiringguru - You keen for march, april or may? Would love to get this talk out there for everyone :)

**Comment by iamkevinv** [comment]
How are you going @aspiringguru - Talk coming along?
I'm lining up talks for the next few months and just want to check in :) Let me know if you have questions or need a hand. 👍

**Comment by iamkevinv** [comment]
Hey @aspiringguru - Checking in for an April short talk... keen?

**Comment by iamkevinv** [comment]
@aspiringguru are you interested in getting into the dec BrisJS? Dec 7. Last chance to present until Feb 2021

**Comment by iamkevinv** [comment]
Hi @aspiringguru - Just checking in to see what upcoming dates you might be available for presenting this Talk?

**Comment by iamkevinv** [comment]
Just checking in @aspiringguru :)

**Comment by iamkevinv** [comment]
Hi @aspiringguru - Are you potentially able to present this on 4/July or 1/Aug?

**Comment by iamkevinv** [comment]
Hi @aspiringguru - Are you interested in an upcoming talk at brisjs again sometime?

**Comment by iamkevinv** [comment]
Closing due to length of time open. Please let me know if it should be re-opened.
