### ISSUE TITLE
Maybe you shouldn't - Why scrutinizing the norm is a must

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#382]
The word "Should" gets thrown around a lot in the software world.

"You should write your apps like this", "Everything should be unit tested", "Code should have comments"

But why should you? Who says? Maybe you shouldn't.

**Comment by KoryNunn** [comment]
slides! https://docs.google.com/presentation/d/1x3p_SjsfJwrYQvYYzAwhGsRJr_M0o17VorHrfsZm6cM/edit#slide=id.g7c2bb4417f_0_63
poems! https://poets.org/poem/calf-path
wikis! https://en.wikipedia.org/wiki/Path_dependence
horses! http://www.astrodigital.org/space/stshorse.html
cults! https://en.wikipedia.org/wiki/Cargo_cult

**Comment by KoryNunn** [comment]
Nathan sent me a Men In Black quote:

"A person is smart. People are dumb, panicky dangerous animals and you know it. Fifteen hundred years ago everybody knew the Earth was the center of the universe. Five hundred years ago, everybody knew the Earth was flat, and fifteen minutes ago, you knew that humans were alone on this planet. Imagine what you'll know tomorrow."

**Comment by iamkevinv** [comment]
Thanks for updating mate!
