### ISSUE TITLE
Automated Testing - Beyond End to End Testing

### ISSUE THREAD

**Issue by dallasclark** [BrisJS/meetups#384]
Think you've nailed your end to end strategies, or need some inspiration on what's on the horizon? This session will cover other automated testing strategies to minimise efforts in your teams, find issues sooner, and deliver high-quality products.

Including automatic visual testing, automatic accessibility testing, and creating code quality gates.

**Comment by iamkevinv** [comment]
Heya @dallasclark :) 
Very pleased to see this here! - Can you give me an idea on length, when you're ready to present (Feb 3 event, or March 2, etc)?

**Comment by dallasclark** [comment]
Hey @iamkevinv,

40-45 minute talk on March 2 please :)

**Comment by iamkevinv** [comment]
Confirmed to do your 30 minute headliner for BrisJS 2nd march?

**Comment by dallasclark** [comment]
Planned and ready ....

With merchandise too 💯

**Comment by iamkevinv** [comment]
Thanks again!
