### ISSUE TITLE
CloudGo - Associate Consultants wanted! - Permanent

### ISSUE THREAD

**Issue by beretta83** [BrisJS/meetups#385]
Hi everyone, 

CloudGo are an **exciting** and rapidly expanding ServiceNow partner with 40+ people across Asia Pacific. We're looking to help JavaScripters get into the industry and get first class training and mentoring around the enterprise platform in **ServiceNow**. 

**Brisbane** or **Sydney** based with opportunity to travel when travelling resumes. We are looking for strong coders with an appetite to expand their knowledge and skill sets into a market leading tool. In turn, we'll train you in the ServiceNow platform with the opportunity to become certified in different application streams depending on your interest. 

If you are **enthusiastic** and a **self starter** looking for a challenge, reach out for your chance to work with a strong team and flexible working conditions. Your next opportunity awaits!

[Technical Associate Consultant.pdf](https://github.com/BrisJS/meetups/files/4216334/Technical.Associate.Consultant.pdf)

**Comment by beretta83** [comment]
Hi Kevin,

Why has this been closed? I've been waiting for it to be promoted to your official website and I can see it's not there?

Thanks,

Brett
________________________________

**Comment by iamkevinv** [comment]
Sorry Brett, It was inadvertently cleaned up with some things and spam posts we've been hit lately. Thanks for bringing it up. I've added the jobs label now :)

**Comment by iamkevinv** [comment]
This position still current @beretta83 ?

**Comment by beretta83** [comment]
Hi Kevin,

It is though I haven't had any success advertising here. I don't mind if you want to bump up or close.

Best Regards,

Brett
________________________________

**Comment by beretta83** [comment]
> This position still current @beretta83 ?

I've appending the position slightly, hoping to be able to catch someones attention. We do pay for job advertising on Seek and other platforms as well but, I'm a big believer in returning to the ecosystem and I don't think I'd have a lot of reach to coders without ServiceNow experience through that channel.

**Comment by zombies808myneighbors** [comment]
@beretta83

I'm interested in learning more about this position. How can I contact you?

**Comment by beretta83** [comment]
> @beretta83
> 
> I'm interested in learning more about this position. How can I contact you?

Hey Aubrey,

Flick me an email at brett.azzopardi@cloudgo.asia.

Cheers,

Brett

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
