### ISSUE TITLE
Five Lessons from refactoring StackOverflow code that will make your JS journey 253% easier

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#386]
I logged on to StackOverflow the other day, and was shocked to discover that I had dropped to the top 25% of contributors. So I went on a burn, and raised my ranking to the top 0.11% for the month.

As I did that, I noticed several patterns emerge from the problems that people were grappling with in the javascript and node.js tags on SO. After a while, I noticed I was fixing the same things over and over again in people's code. And I started to understand the underlying problems that were causing people to throw up their hands and turn to StackOverflow with their b0rked code. Spoiler alert: it was never the problem that they were looking at.

I've distilled them down to 5 things that will improve your JavaScript coding life, especially if you are getting started. These five things, if you adopt them, will make you JS coding journey 253% easier.

**Comment by iamkevinv** [comment]
@jwulf - Lightning length? Which event are you free?

**Comment by iamkevinv** [comment]
We’ll be doing our BrisJS events over video conf for the next few months or more due to covid-19. 
Please let me know when you’re willing to present!

**Comment by jwulf** [comment]
April, const's do it!

**Comment by iamkevinv** [comment]
@jwulf ....is that... you can do it, or you can't do it? Genuine question. :-D

**Comment by jwulf** [comment]
Can doBlog | Bio | Books | Talks: www.joshwulf.com---- On Fri, 27 Mar 2020 11:25:07 +1000  Kevin Vanderbeken<notifications@github.com> wrote ---- 
@jwulf ....is that... you can do it, or you can't do it? Genuine question. :-D

**Comment by iamkevinv** [comment]
@jwulf did you want to jump in with this lightning talk next monday?

**Comment by jwulf** [comment]
Yes sir

**Comment by jwulf** [comment]
How long do I have?

**Comment by iamkevinv** [comment]
@jwulf 10m lightning or 20m regular- your choice

**Comment by jwulf** [comment]
Here is the repo: https://github.com/jwulf/five-things-from-stackoverflow-brisjs

**Comment by iamkevinv** [comment]
Thanks mate!
