### ISSUE TITLE
Functions as a Service (FaaS) -- What's the Appeal

### ISSUE THREAD

**Issue by ahaw021** [BrisJS/meetups#387]
Talk title: Functions as a Service (FaaS) -- What's the Appeal
Presenter name: Andrei Hawke
Talk length: 10 min
Talk synopsis: Why FaaS may be the preferred approach in the future. What is it and how can you start now. I will talk about this more from a DevOps and focus on Ops. I will also tie in how Dev can help Ops with use cases based on Microsoft Azure stack. 
Available month(s): March and April

**Comment by iamkevinv** [comment]
Sounds good!

**Comment by iamkevinv** [comment]
Hi @ahaw021 - Can i confirm you for next week, march 2nd?

**Comment by ahaw021** [comment]
yes i can @iamkevinv

**Comment by iamkevinv** [comment]
I didn't get the reply before i sent the announce email... but i'll add you on the page now :)

**Comment by iamkevinv** [comment]
Thanks so much for presenting! Love to hear a follow up sometime!
