### ISSUE TITLE
Lightning talk: "Intro to testing with cypress"

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#388]
Lightning talk: "Intro to testing with cypress"
Presenter: @ashleydavis
Length: 10min

In this talk Ash gives an overview and demonstration of using Cypress for testing web pages and REST APIs.

**Comment by ashleydavis** [comment]
My slides from the talk last night: https://www.slideshare.net/AshleyDavis33/intro-to-cypress

**Comment by iamkevinv** [comment]
Thanks again!
