### ISSUE TITLE
DevOps - How We're Rolling Out DevOps is Dead Wrong

### ISSUE THREAD

**Issue by dallasclark** [BrisJS/meetups#389]
Throwing this topic up here for the interim whilst I prepare for this presentation.

I've seen a number of organisations/teams rollout "DevOps" and miss the main necessary characteristics of the movement. The talk will discuss what problems existed in the past, *cough* and presently, and how DevOps resolves these issues.

Will cover the common pitfalls of rolling out DevOps.

At this point of time:
* Not sure how long this talk will be
* Not sure when I can present (it's a work in progress)

Would love to receive and answer questions in the interim.

**Comment by iamkevinv** [comment]
Sounds great title wise!
We’ll be doing our BrisJS events over video conf for the next few months or more due to covid-19. 
Just let me know when you’re thinking of presenting 👍

**Comment by iamkevinv** [comment]
How you going with this one mr @dallasclark ? :)

**Comment by dallasclark** [comment]
Little progress at this point, but I've received a number of enquiries of interest. I will get onto this band wagon, it won't be ready for next month's BrisJS though.

Maybe the next.

**Comment by iamkevinv** [comment]
@dallasclark - Can i confirm you for this next July BrisJS?

**Comment by dallasclark** [comment]
Not yet mate, my apologies :(

**Comment by iamkevinv** [comment]
I am sad. Bumping to next month :)

**Comment by iamkevinv** [comment]
This month or next month @dallasclark? Just trying to get the shortlist together :)

**Comment by dallasclark** [comment]
Push to next month please :)

**Comment by iamkevinv** [comment]
@dallasclark Any luck? We're still without a speaker, even after postponing. Let me know if you can ;-)

**Comment by dallasclark** [comment]
@iamkevinv Part of the presentation I'm working on needs some insights. I'm keen to hear what people think DevOps is and what have they done to roll out DevOps at their workplace?

What's the best strategy to ask the BrisJS community? Here?

**Comment by iamkevinv** [comment]
I can retweet your question from BrisJS account if that helps? Just let folks know this in prep of your upcoming talk 👍

**Comment by iamkevinv** [comment]
@dallasclark just following up on this one - can i confirm you for Next week?

**Comment by dallasclark** [comment]
Guess who is finally working on this presentation?

**Comment by iamkevinv** [comment]
Thanks so much for rounding out last year with this talk. If you have links to share please do!
