### ISSUE TITLE
Promise to yield: with generators to the "promised land"

### ISSUE THREAD

**Issue by PandaWhisperer** [BrisJS/meetups#39]
Hi BrisJS, 

I recently learned some cool tricks using promises and generators that make writing asynchronous code really, REALLY simple. Would like to share those insights in a lightning talk this Tuesday if you're interested. 

##### Who am I?

I'm currently visiting from California, and I like to check out local meetups whenever I'm in a new town. I work at a company called [PandaStrike](https://www.pandastrike.com), we do software consulting (we specialize in Node.js).

**Comment by AshKyd** [comment]
That sounds awesome. Our next meetup is on Monday 2nd of Feb if that suits. :)

**Comment by kevdesign** [comment]
Yeah we could do a very promise/generator driven meetup then! If you'd like to confirm @PandaWhisperer - i'll get you on the bill and we will spend less time to have lightning talks - defer these to some other time.

**Comment by PandaWhisperer** [comment]
Would love to. No need to skip anything, this won't be super long. Maybe 10 minutes.

@marklawlor does your talk include any examples of using generators with promises?

**Comment by marklawlor** [comment]
@PandaWhisperer The aim of my talk isn't to show you how to use Generators, but to help you understand what they are and why there were introduced to Javascript. I'll be ending my talking with a quick intro to promises and why they work well with Generators, but I won't be explaining the sample code in the slides.

A great lightning talk could be a use case analysis of where Generators/Promises helped you in a production environment and a run though of a code example.

I'll upload my slides to github either today or tomorrow and you can have a look at what I'm covering.

**Comment by kevdesign** [comment]
Going to be great - all good to go for the night :)

**Comment by PandaWhisperer** [comment]
Sounds good @marklawlor.

**Comment by PandaWhisperer** [comment]
Slides to the talk: http://pandawhisperer.github.io/BrisJS-Promised-Land/

**Comment by kevdesign** [comment]
Thanks for coming and giving us the presentation. :)

**Comment by PandaWhisperer** [comment]
My pleasure! Anytime.
