### ISSUE TITLE
How to create a minimal design system with limited resources

### ISSUE THREAD

**Issue by broccolinisoup** [BrisJS/meetups#390]
Presenter Name: Armağan Ersöz & Raouf Araji
Talk title: How to create a minimal design system with limited resources
Talk length: 30 min?
Talk synopsis: Design systems are an essential part of building consistent digital products, but it's sometimes treated as a side priority that doesn't get the attention it deserves.
Maybe you want to start building one but are a bit lost. Maybe you do not have enough buy-in from the business. Maybe there aren't enough resources for the design system to reach maturity. In this talk, Raouf and Armagan will talk about what the design systems are and how to build and maintain one from a designer and a developer perspective. They will share their first hand experiences of building one and give some actionable tips and tricks, especially when you don't have a dedicated team.

Available month(s): April and onwards
Twitter: @broccolinisoup &

**Comment by iamkevinv** [comment]
Thanks so much! I'll tag it :)

**Comment by iamkevinv** [comment]
Confirming this one for this night - let me know if there’s any issues!

**Comment by iamkevinv** [comment]
Thanks @broccolinisoup - I've set up the talks via Zoom conferencing.

The speakers will join the zoom conf directly, everyone else watches on youtube streaming.
Please aim to join and test with us at 6:20pm.
You can download and install the Zoom client if you follow the zoom meeting url below too, and use the following details:

> Join Zoom Meeting:
> https://zoom.us/j/169245706
> 
> Meeting ID: 169 245 706
> 
> Backup voice telephone line options for audio:
> One tap mobile:
> +61871501149,,169245706# Australia
> +61280156011,,169245706# Australia
> 
> Dial by your location
>         +61 8 7150 1149 Australia
>         +61 2 8015 6011 Australia
>         +61 3 7018 2005 Australia
> Meeting ID: 169 245 706

**Comment by broccolinisoup** [comment]
Thanks again so much Kev, for setting up the zoom and live stream us on youtube :) It was a great experience! Here is our slides: 
https://docs.google.com/presentation/d/1JeacKR-x_NBvGIl2elf_TIMiNjiPx2fJ/edit#slide=id.p1

Feel free to reach out to us if you have any questions.

**Comment by iamkevinv** [comment]
Thanks for sharing folks!
