### ISSUE TITLE
3 x Senior JavaScript Developers @ Tiny

### ISSUE THREAD

**Issue by dallasclark** [BrisJS/meetups#391]
Tiny is seeking 3 Senior JavaScript Software Developers to join our Editor Platform development team. In this role you will have the opportunity to influence the way hundreds of millions of people create content on the web. You will be a key member of the team responsible for editor technology used by well-known applications such as Wordpress, Confluence and Blackboard.

As a Software Developer, you will work with a team who develops and maintains our editor technology along with integrations into popular systems and frameworks. You'll work with the latest JavaScript and web technologies ensuring our products work in the latest web applications on modern browsers including mobile devices. As part of the role you will collaborate closely with engineering, UX, QA and product management across Brisbane, Umeå (Sweden) and Silicon Valley to successfully deliver products to market.

More information: http://jobs.tiny.cloud/apply/axdoDosXFv/Senior-JavaScript-Software-Engineer?referrer=20200316040713UMSWODW7QBD422TJ

**Comment by dallasclark** [comment]
2 positions have been fulfilled, we have 1 vacancy available.

DC

**Comment by iamkevinv** [comment]
Is this still open @dallasclark?
Thanks.

**Comment by dallasclark** [comment]
This particular one, yes. New jobs to be posted :)
