### ISSUE TITLE
ABC News Web - Senior Developer

### ISSUE THREAD

**Issue by louisstow** [BrisJS/meetups#392]
Bring your skills to a high performing team that powers Australia's number 1 News website – ABC News. News Web is a cross functional team of Developers, Designers, Content and Product people, collaborating to build the platform that impacts audiences that number in the millions. Each day, Australians rely on ABC News, as an online service to keep informed and updated. We are working with cutting edge technologies such as Node, React, Webpack – ensuring we keep at the forefront of industry trends to deliver quality at scale.

Read more: https://careers.abc.net.au/caw/en/job/500988/senior-developer

**Comment by iamkevinv** [comment]
Is this still open @louisstow? Otherwise looking to close and clean up these GH issues ;-) OK to keep open if still advertising!

**Comment by louisstow** [comment]
Oh sorry yes that's done. Thanks so much!

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
