### ISSUE TITLE
Fun with Babel and ASTs in JavaScript

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#393]
Talk: Fun with Babel and ASTs in JavaScript
Duration: 15-25 mins
Abstract:

Babel is a great way to make use of the latest JavaScript features and compile your code to an older version of JavaScript that runs everywhere. 

You probably know about Babel and may have even used it in your JavaScript projects. But did you know that it's not very difficult to create your own custom Babel plugins? You can use this to automatically manipulate and augment your code in really robust and reliable ways. You can even go as far as to add your own custom language features!

In this talk we'll look at some of the background you need to approach this and we'll learn step by step how to create a simple Babel plugin.

**Comment by ashleydavis** [comment]
Here's some resources for anyone who wants to follow up on my talk about Babel and ASTs:
- Babel web page: https://babeljs.io/
- Babel plugin handbook: https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md
- Abstract syntax trees on Wikipedia: https://en.wikipedia.org/wiki/Abstract_syntax_tree
- Babel plugin playground:  https://www.mattzeunert.com/babel-plugin-playground/
- How to create a Babel plugin without publishing it on npm: https://stackoverflow.com/questions/36368788/create-and-use-babel-plugin-without-making-it-a-npm-module
- Babel AST explorer: https://astexplorer.net/
- TypeScript AST viewer: https://ts-ast-viewer.com/
- Pattern matching JavaScript ASTs using JSPath: https://blog.scottlogic.com/2016/06/22/xslt-inspired-ast-transforms.html


Some examples of creating Babel plugins:
- https://shuheikagawa.com/blog/2015/09/13/lets-create-a-babel-plugin/
- https://itnext.io/introduction-to-custom-babel-plugins-98a62dad16ee
- https://dev.to/mfco/build-your-own-babel-plugin-from-scratch-fk3

**Comment by iamkevinv** [comment]
Many thanks mate!
