### ISSUE TITLE
ABC News Senior Product Manager

### ISSUE THREAD

**Issue by astrotim** [BrisJS/meetups#394]
Lead and oversee the product development of one of ABC’s most iconic brands ABC NEWS.

Bring your skills to high performing teams that power Australia's number 1 News website – news.abc.net.au - and Australia’s number 1 News app - ABC News. You will be leading cross functional teams of developers, designers, content and product people, collaborating to build the platform that impacts audiences that number in the millions.

Learn more: https://careers.abc.net.au/caw/en/job/501017/senior-product-manager-abc-news

**Comment by iamkevinv** [comment]
Is this still open @astrotim? Otherwise looking to close and clean up these GH issues ;-) OK to keep open if still advertising!

**Comment by astrotim** [comment]
Hey @iamkevinv this one has been filled now ✅
