### ISSUE TITLE
Best JS course online for an absolute beginner?

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#395]
I'm looking for recommendations for an online course for my son to do. It doesn't look like he is going to complete Year 12 this year (he might redo it next year) - so I want him to do 3-6 months of coding education remotely.

I looked at https://www.cleverprogrammer.com/, which I like because it focuses on the business of coding as well as the tech of it. I'm interested in recommendations for online JS coding courses.

**Comment by pejantantangguh** [comment]
Hi, WesBos JavaScript 30 is a good start.
https://javascript30.com/

You can check his youtube as well.
https://www.youtube.com/playlist?list=PLu8EoSxDXHP6CGK4YVJhL_VWetA865GOH

Frontend masters is great as well for basic
https://frontendmasters.com/courses/getting-started-javascript-v2/ 
He's the author of You Don't know JS book. It's good to learn JavaScript.

**Comment by cryptoroo** [comment]
General Assembly and Code Academy do good jobs. 

If he's a self learner then ReactJS courses by Maximilian Schwarzmüller are considered one of the "bibles" in the subject  https://www.udemy.com/course/react-the-complete-guide-incl-redux/

**Comment by jwulf** [comment]
Thanks @cryptoroo
