### ISSUE TITLE
Frontend Application Bundles

### ISSUE THREAD

**Issue by evanderkoogh** [BrisJS/meetups#396]
**Presenter Name:** Erwin van der Koogh
**Talk title:** Introducing Frontend Application Bundles - Docker for Frontend
**Talk length:** 30 min
**Talk description:** Glen Maddern and myself have been working on a thing called Frontend Application Bundles. (https://fab.dev). It is a way to package up any time of frontend application and deploy it seamlessly to anywhere such as Cloudflare workers, Lambda@Edge, Vercel (was Zeit) or your own infrastructure. Not only does it support static sites, but also fully server-side rendered applications and anything in between. So it is easy to sprinkle in a little bit of server-side logic in your otherwise static app.
**Available month(s):** Whenever.. 
**Optional:** Personal Twitter: @evanderkoogh, company Twitter: @linc_bot

**Comment by evanderkoogh** [comment]
Hey @iamkevinv. This is for the meetup next week right? 8th? More than happy to do a 20 min version as well if that makes it easier on you.

**Comment by iamkevinv** [comment]
Yes it is :) 
Sure 20min is good too, totally up to you... 25min is good as an upper limit. 20-25 is already confirmed by another talk on the night too - just trying to ensure everyone gets equal spotlight this month as we have 3 big talks (which is great 👍 )... and I also want to have some time for Question responses at the end.

**Comment by iamkevinv** [comment]
Hi @evanderkoogh - If you have any resources or links to share from your talk, please do share!
