### ISSUE TITLE
Our path to a static site

### ISSUE THREAD

**Issue by camposcristian** [BrisJS/meetups#397]
**Presenter Name:** Cristian Campos
**Talk title:** Our path to a static site
**Talk length:** 20-25 min
**Talk description:** We've gone through 4 iterations of aimementoring.com since 2017, having 2 different CMS's, 4 code bases, and at least 3 different architectures with some hybrids in the middle. It'll be mainly a stack talk, with some insights in terms of efficiency and learnings.
**Available month(s):** June 8 or July
**Twitter:** @criscampos10

Still need to work on the slides but could do it for either June/July

**Comment by iamkevinv** [comment]
Thanks for your submission! It's greatly appreciated. We'll schedule this for the event next week, June 8.

**Comment by iamkevinv** [comment]
Hi @camposcristian - If you have any resources or links to share from your talk, please do share!
