### ISSUE TITLE
Say Goodbye to Passwords and Hello to WebAuthn

### ISSUE THREAD

**Issue by bendechrai** [BrisJS/meetups#398]
Presenter Name:

>Ben Dechrai

Talk title:

>Say Goodbye to Passwords and Hello to WebAuthn

Talk length:

>30 min

Talk description:

>Identifying ourself to access social media, banking details, and every aspect of our online life is something we do potentially dozens of times a day.
>
>But as the nearly ten billion leaked account details documented by "';--have i been pwned?" attest, this process has a fatal weakness–passwords.
>
>The Web Authentication API (or WebAuthn) is a standard from the W3C and FIDO that "allows servers to register and authenticate users using public key cryptography instead of a password". WebAuthn is part of a set of standards that enable passwordless authentication between servers, browsers, and authenticators. It's supported in all modern browsers.
>
>In this presentation Ben Dechrai will outline how the technologies work, and how you can take advantage of them today to create a far more secure experience for your users.

Available month(s):

>June 8th

Optional: list any preferred social accounts so we can promote you and your talk

>https://twitter.com/bendechrai
>https://www.youtube.com/c/bendechrai
>https://www.linkedin.com/in/bendechrai/
>https://www.instagram.com/bendechrai/

**Comment by iamkevinv** [comment]
Thanks so much for the submission! It's greatly appreciated.
As we have two submissions for 30 minutes... could i please ask if you could target 25min instead? I'll ask the same of the other speaker. This ensures an even time for all speakers this month and a smoother running event. Sorry if that's a hassle - please feel free to let me know your thoughts.

**Comment by bendechrai** [comment]
Sure! 25 minutes it is 👍

**Comment by iamkevinv** [comment]
Hi @bendechrai - If you have any resources or links to share from your talk, please do share!
