### ISSUE TITLE
Talk Volunteered - Writing Node CLI Tools

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#40]
I've written a handful of node CLI tools now and I'm happy to share my experiences. 

Should be < 10min as I only have to cover:
* Manual argument parsing
* Using a helper library (commander)
* Reading input
* NPM tools

**Comment by shotlom** [comment]
:+1:

**Comment by davidmason** [comment]
:+1:  :star2:

**Comment by kevdesign** [comment]
You still happy to cover this tomorrow @garrows ? Sorry for the late reminder...

**Comment by garrows** [comment]
All good @kevdesign

**Comment by kevdesign** [comment]
:+1:

**Comment by kevdesign** [comment]
If you could share your slides that would be great - i really want to read it all myself, as i was off getting beers for the group lol. The pitfalls of being an organiser.

**Comment by garrows** [comment]
Of course.
https://slides.com/glenarrowsmith/writing-node-js-command-line-tools
Hope you enjoyed it.

**Comment by garrows** [comment]
And since it was last minute and doesn't have a thread, here is how I setup a production quality node server in 1 command.
https://github.com/garrows/noleg-stack
