### ISSUE TITLE
NodeJS freelancer - short term, WFH, full-time or part-time

### ISSUE THREAD

**Issue by nermaljcat** [BrisJS/meetups#400]
We're looking for freelance JavaScript developers out there interested in short contracts, with the potential for recurring/ongoing work? Junction AI is a US-based start-up with a dev team in Brisbane - junction.ai

Our stack is NodeJS back-end (express/lambda) with a Vue.js front-end - deployed in AWS (runs locally too for development).

We're especially interested in anyone with NodeJS marketing API experience:
- Facebook Graph
- Google API
- Google Ads
- Instagram
- Shopify etc.

Also interesting in any ML experience using the NodeJS TensorFlow bindings.

**Comment by iamkevinv** [comment]
Is this still open @nermaljcat? Otherwise looking to close and clean up these GH issues ;-) OK to keep open if still advertising!

**Comment by nermaljcat** [comment]
Hi Kevin, yeah we've found someone. Please feel free to close this one.
Thanks, Rob
