### ISSUE TITLE
Gatsby & Typescript: blazingly static

### ISSUE THREAD

**Issue by sarah-j-smith** [BrisJS/meetups#401]
Presenter Name: Sarah Smith
Talk title: Gatsby & Typescript: blazingly static 
Talk length: 30 min
Talk description: adventures in learning Gatsby&TS
Available month(s): July
Optional: LinkedIn sarahsmithdev Twitter sarah_j_smith

**Comment by iamkevinv** [comment]
Oh awesome! Hi @sarah-j-smith 👋  Thanks so much for volunteering. 
We have a similar but different proposal for this month too: https://github.com/BrisJS/meetups/issues/399
...Since you're covering the TS support also, i see no reason to avoid doing both this month. 👍

**Comment by sarah-j-smith** [comment]
Good contact for me is Sarah - at - smithsoft dot com for au. I’ve actually just deactivated my Twitter account so avoid using that. The LinkedIn or GitHub is good.

**Comment by iamkevinv** [comment]
@sarah-j-smith Hi Sarah - Can i confirm you for this next July BrisJS?

**Comment by sarah-j-smith** [comment]
> @sarah-j-smith Hi Sarah - Can i confirm you for this next July BrisJS, Monday 6th July? - (Online event)

Yep, I’m in!  See you then.

**Comment by sarah-j-smith** [comment]
Hey Kevin. Just been looking at Youtube Live.  I need the stream key if I'm going to stream on that URL that's linked off the event page.  Send it to me via DM (obv's not here in public).

**Comment by iamkevinv** [comment]
Hi @sarah-j-smith - If you have any resources or links to share from your talk, please do share!
