### ISSUE TITLE
WebAssembly, your browsers sandbox.

### ISSUE THREAD

**Issue by aaronpowell** [BrisJS/meetups#402]
Presenter Name: Aaron Powell
Talk title: WebAssembly, your browsers sandbox.
Talk length: 30 min?
Talk description: 
> We've been doing web development for 30+ years and in all that time have you ever stopped to think, “This SPA needs more C++”? Well thanks to the power of WebAssembly you can finally bring C, C++, Rust, Go and other high level languages to the browser.

> So does this mean that we can replace our JavaScript with these other languages? Probably not, so what is the role that WebAssembly can play in building web applications? And most importantly, what does it look like as a web developer to try and incorporate these platforms that have traditionally been on the server?

> For this talk, we'll look at some of the fundamentals of WebAssembly, how to incorporate it into our development process and ultimately what it looks like to build an application that uses a mixed development stack.

Available month(s): whenever
Optional: https://twitter.com/slace https://www.aaron-powell.com https://www.twitch.tv/NumberOneAaron

**Comment by iamkevinv** [comment]
Hi @aaronpowell - are you keen on giving this presentation this month?

**Comment by aaronpowell** [comment]
Yep, I should be able to. I'll confirm tonight

**Comment by aaronpowell** [comment]
Lock it in @iamkevinv 😁

**Comment by aaronpowell** [comment]
Code sample from the talk can be found here: https://github.com/aaronpowell/oz-dev-events

**Comment by iamkevinv** [comment]
@aaronpowell - If you have any additional slides or resources to share, please feel free to add another comment with them here :) Thanks for the presentation and the github code already linked :)
