### ISSUE TITLE
TypeScript + GraphQL

### ISSUE THREAD

**Issue by aaronpowell** [BrisJS/meetups#403]
Presenter Name: Aaron Powell
Talk title: TypeScript + GraphQL
Talk length: 20 min
Talk description:
> When building with GraphQL you define the schema up front and this can be really handy go use when it comes to writing the queries, resolvers, etc., especially if it's in TypeScript.

> So, how do you go about doing the type generation? We'll take a look at a tool that can generate you the TypeScript types, then implement our backend using them before looking at how they can plug into the front end with React Hooks.

> We'll cap off by learning how to model our storage platform effectively using its own types and combine them with the GraphQL schema types.

Available month(s): whenever
Optional: https://twitter.com/slace https://www.aaron-powell.com https://www.twitch.tv/NumberOneAaron

**Comment by iamkevinv** [comment]
Hi @aaronpowell - If you have any resources or links to share from your talk, please do share!
