### ISSUE TITLE
Positions available at PCCW

### ISSUE THREAD

**Issue by rodrigo398** [BrisJS/meetups#404]
Hi guys!.

I am trying to contact to ConsoleConnect by PCCW Global company as I would like to apply for an available position, because I saw in the last meetup that they have available positions, but I can't find a JD, or something similar.

In fact, there is an address on the slide https://youtu.be/5skrq64ECI0?list=FLXCIdiJ4sDa9Gqq3LaQeclA&t=402  (http://tiny.cc/globaljobs) but it didn't work. 

I have sent an email to @iamkevinv  but have not received a reply yet.

Do you guys know how I could contact them?.

I don't know if this is the right place to ask this question, and if it is not please let me know.

Thank you.

**Comment by iamkevinv** [comment]
Oh my! I'm so sorry I've missed your messages 😱
I'd be happy to help!
