### ISSUE TITLE
Building your own query language in TypeScript

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#405]
Presenter Name: Ashley Davis
Talk title: When to reinvent the wheel? Building your own query language in TypeScript
Talk length: 10-15 min
Talk description:

Were you ever unsatisfied enough with an existing framework that you took the completely crazy step of rewriting it?

Well, that just happened to Ashley Davis. He's just finished rebuilding GraphQL in TypeScript.

We'll talk about "reinventing the wheel". Why is it considered bad? When is it a good time to reinvent things? 

We'll look at how the new query language was developed and see a demo of it in action!

Available month(s): Now
Twitter: @ashleydavis75

**Comment by iamkevinv** [comment]
I'll consider you available for this one mr @ashleydavis ? :)

**Comment by iamkevinv** [comment]
Still waiting on replies from the others too

**Comment by ashleydavis** [comment]
Here's the slides from my talk last night:
https://www.slideshare.net/AshleyDavis33/when-to-reinvent-the-wheel-building-a-query-language-in-typescript

I demonstrated the MiniQL interactive example, which you can find here: 
https://github.com/miniql/miniql-interactive-example

Here is MiniQL's page on GitHub:
https://github.com/miniql/miniql

**Comment by iamkevinv** [comment]
@ashleydavis - Thanks for the presentation and linked resources!
