### ISSUE TITLE
Lead Front-end Developer at Compono

### ISSUE THREAD

**Issue by dp-lewis** [BrisJS/meetups#406]
Imagine having a satisfying and rewarding career from the moment you enter the workforce to the day you retire. This is what we’re building at Compono! 🥰

We’re currently looking for a Lead Front-end Developer to create a new Design System focused team, could it be you or someone you know?

Our tech stack is a modern marvel with all the things we know you’re going to love ❤️ (TypeScript, React, GraphQL). 

Learn more: https://app.shortlyster.com/listing/9326b619-6c7e-40cb-ba17-1ebdcf1e43bb

**Comment by iamkevinv** [comment]
Is this still open @dp-lewis? Otherwise looking to close and clean up these GH issues ;-) OK to keep open if still advertising!
