### ISSUE TITLE
The value of building with a community

### ISSUE THREAD

**Issue by dnorton94** [BrisJS/meetups#407]
Presenter Name: Dominic Norton
Talk title: The value of building with a community
Talk length: 20 min
Talk description: Hackathons have been an integral part of the developer community for almost 20 years. They have been used as a fun way to bring technical people together in a non-pressured environment to create innovative solutions. 20 years later Hackathons are so much more. Thousands of developers and non-developers are coming together to solve the world's toughest problems. In this talk, I share the secret to maximizing value from your next hackathon.
Available month(s): Sep 7th
Optional: list any preferred social accounts so we can promote you and your talk
https://anchor.fm/thehackathonpodcast
https://medium.com/hackathon-entertainment
https://www.linkedin.com/in/dominiconorton

**Comment by iamkevinv** [comment]
Thanks @dnorton94 :) - sounds good!
Still trying to arrange for a one or two more speakers, but after that i'll try and get everyone including yourself locked in for next week 👍

**Comment by dnorton94** [comment]
If you need help let me know and I'll reach out to my network.

**Comment by iamkevinv** [comment]
Yes absolutely a good idea. At this stage we might just delay by 1 week to get more speakers in. Hope this doesn't inconvenience you.

**Comment by iamkevinv** [comment]
Hi @dnorton94 - Can i confirm this for next week Monday 14th Sept?

**Comment by iamkevinv** [comment]
@dnorton94 - Hi! can I announce? We're super overdue at this point 🙃 I'll do the write up now anyway, just hoping for your confirmation again since we moved it by a week. You will be the only presenter this month so you have as long as you like! (Incredibly rare that this happens)

**Comment by iamkevinv** [comment]
https://www.meetup.com/BrisJS/events/fxdfkrybcmbkb/ <--- The talk is up! Please confirm you can make it 👍

**Comment by dnorton94** [comment]
Yes, still available looking forward to it!

**Comment by iamkevinv** [comment]
Meetup: https://www.meetup.com/BrisJS/events/fxdfkrybcmbkb/
Twitter: https://twitter.com/BrisJS/status/1304750387077869568
Facebook: https://www.facebook.com/events/236980201073834/ & https://www.facebook.com/BrisJSMeetup/posts/2534305106859727

**Comment by iamkevinv** [comment]
@dnorton94 - For tonight, we have you join our zoom conference, and that will automatically livestream to youtube. It will really help to install the zoom client on your computer, and we'll try out audio/video/screenshare before starting at 6:30pm brisbane time. Zoom details below:

> Topic: BrisJS Sept 14 Meetup
> Time: Sep 14, 2020 06:25 PM Brisbane
> 
> Join Zoom Meeting
> https://us02web.zoom.us/j/81151756053
> 
> Meeting ID: 811 5175 6053
> One tap mobile
> +61731853730,,81151756053# Australia
> +61861193900,,81151756053# Australia
> 
> Dial by your location
>         +61 731 853 730 Australia
>         +61 861 193 900 Australia
>         +61 8 7150 1149 Australia
>         +61 2 8015 6011 Australia
>         +61 3 7018 2005 Australia
> Meeting ID: 811 5175 6053
> Find your local number: https://us02web.zoom.us/u/kd7KFTkhAI

**Comment by iamkevinv** [comment]
@dnorton94 - Hope you got the zoom link and we'll see you soon :)

**Comment by iamkevinv** [comment]
Hi @dnorton94

**Comment by iamkevinv** [comment]
Thanks again for your talk @dnorton94 :)
