### ISSUE TITLE
Software Engineer at The University of Queensland

### ISSUE THREAD

**Issue by mreillyorg** [BrisJS/meetups#409]
The Division of Information Technology Services (ITS) at The University of Queensland provides an information environment that supports the teaching, learning, research and engagement objectives of the University and contributes positively to the student experience and the University’s reputation.

This is an excellent position for a Software Engineer to provide a high level of development and support for computing and network installations in ITS, client departments and organisations. This role is very fitting for someone who has strong interpersonal skills as this role will be a major link between ITS and the client.

This position is located at our Toowong office location on High street, just minutes from the CBD & walking distance from public transport.

# Our Ideal Candidate

  - Qualifications and training equivalent to an undergraduate degree in IT or related field and significant relevant experience; or an equivalent combination of relevant experience and/or education/training.
  - Skills and experience in analysis, design, development, systems management and maintenance of multi-user systems or applications.
  - Detailed knowledge in the following areas, with significant experience in:
    - 5 + years’ experience in programming with NodeJS and PHP
    - Frontend JS frameworks e.g. React, Angular or Ember.
    - Strong knowledge of PHP web frameworks such as Symfony or Laravel.
    - Database development (relational and NoSQL)
    - Docker, Amazon Web Services and Git.
    - Knowledge of Agile software development methods, especially Kanban
  - Self-motivated and keen to learn new technologies based on UQ’s technical landscape
  - Ability to work under tight timelines and on multiple concurrent initiatives, and prioritise work based on urgency

# Desirable
  - Experience in .NET Core
  - Web servers and web proxy servers such as Nginx and Apache

We value diversity and inclusion, and actively encourage applications from those who bring diversity to the University.

More detail can be found at https://www.seek.com.au/job/50603266.

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
