### ISSUE TITLE
Talk Volunteered: Arduino -> ESP8266 -> MQTT -> Mosca on NodeJS

### ISSUE THREAD

**Issue by spidie** [BrisJS/meetups#41]
I'm only a beginner but I'd be happy to do a short talk on what we have been up to with node on the backend of our IoT startyup, We are doing gate, trap and environmental monitoring using Arduinio, the ESP8266, nodemcu (a LUA based firmware for the 8266 with some nice features) and a Mosca/NodeJS backend. All tied together with MQTT.

**Comment by garrows** [comment]
+1

**Comment by MauriceButler** [comment]
Sounds cool.

**Comment by shotlom** [comment]
:+1:

**Comment by kevdesign** [comment]
Definitely cool - can you advise how long the presentation would be? Once i have an idea around that i can schedule. Thanks!

**Comment by spidie** [comment]
It's not written yet - probably just quite short. What are the options?
I like questions - how is 15 mins + 15 mins questions?
Might not be ready for March - have quite a bit on at the moment.

On 22 February 2015 at 18:59, Kevin Vanderbeken <notifications@github.com>
wrote:

> Definitely cool - can you advise how long the presentation would be? Once
> i have an idea around that i can schedule. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/41#issuecomment-75426375>.
>



-- 
Refactor. Engage | Succeed | Repeat
tel: +61 (0)7 5668 3424
mob: +61 (0)414 464564
web: refactor.com.au

**Comment by kevdesign** [comment]
Sounds fine - talks are normally 20mins, but we don't have any fixed limits. Just trying to make sure we don't have to rush or cut off anyone. Let me know when you're ready and we can get you on the bill :)

**Comment by fud** [comment]
+1 esp8266

**Comment by peterretief** [comment]
i would like to see this ?

**Comment by kevdesign** [comment]
@spidie 15 mins and then questions is perfectly fine. Let me know if you're ready.

**Comment by iamkevinv** [comment]
Hi @spidie - how did you go? Would like to have you present at the next brisJS :)

**Comment by spidie** [comment]
Hi Kevin
Would love to but I am pretty smashed at the moment.
What date?
Steve

On 16 June 2015 at 20:59, Kevin Vanderbeken <notifications@github.com>
wrote:

> Hi @spidie <https://github.com/spidie> - how did you go? Would like to
> have you present at the next brisJS :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/41#issuecomment-112385342>.
>



-- 
Refactor. Engage | Succeed | Repeat
tel: +61 (0)7 5668 3424
mob: +61 (0)414 464564
web: refactor.com.au

**Comment by iamkevinv** [comment]
6th July. First Monday of each month :)

**Comment by spidie** [comment]
I'm off to Sydney early the next morning after that date so not good one.
How about we aim for August?

On 16 June 2015 at 23:00, Kevin Vanderbeken <notifications@github.com>
wrote:

> 6th July. First Monday of each month :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/41#issuecomment-112419257>.
>



-- 
Refactor. Engage | Succeed | Repeat
tel: +61 (0)7 5668 3424
mob: +61 (0)414 464564
web: refactor.com.au

**Comment by iamkevinv** [comment]
I can put the August milestone against this issue. Thanks @spidie.

**Comment by iamkevinv** [comment]
Locking you in @spidie - let me know if there are issues with this.

**Comment by spidie** [comment]
Great - this is August 3rd right? I'd better step to it.
Am I still ok for 30m slot? 15m talk + 15m questions.

**Comment by iamkevinv** [comment]
If you have any links or a shareable link to the slides / notes - please add them here if you could. I'll close it with the Resources Shared label so it wont get lost.

**Comment by iamkevinv** [comment]
ping @spidie
