### ISSUE TITLE
Getting a Junior Role as a React Developer

### ISSUE THREAD

**Issue by ahaw022** [BrisJS/meetups#410]
Talk title: Hiring Junior React Engineers 
Talk length: 20 Minutes
Talk synopsis: 

The First Job can be the hardest to secure. 

I would like to talk a little about our experience hiring juniors. 

Starting with why we choice juniors, some tips from the hiring process, and some things I think would help those looking for a career in development. 

Speaker: Andrei Hawke - Head of System Engineering at Search365

Available month(s): October November
Optional: https://www.linkedin.com/in/andrei-hawke-b9140a14/

**Comment by iamkevinv** [comment]
Thanks @ahaw022 - Added you to the upcoming talks list :) Thanks for volunteering!

**Comment by iamkevinv** [comment]
Thanks @ahaw022 - can you share any links to resources here like your slides? Then i can put the label on appropriately :)
