### ISSUE TITLE
Talk proposal: Futuristic state management with GraphQL, Apollo and magic

### ISSUE THREAD

**Issue by tomquirk** [BrisJS/meetups#413]
Presenter Name: Tom Quirk
Talk title: Futuristic state management with GraphQL, Apollo and magic
Talk length: 20 min
Talk description: Heard of Redux, Vuex, or Mobx? Yeah, _so_ 2019. Learn how GitLab leverages Apollo (and a bit of magic) to manage and interact with client-side state using GraphQL queries.
Available month(s): Nov, Dec
Optional: @tom__quirk on Twitter

---

Hey folks, I'm not local in Brisbane, but if the coming events are running online, I'd be keen to give a talk!

**Comment by iamkevinv** [comment]
Awesome sauce! I'll add it to the list!

**Comment by iamkevinv** [comment]
Following up - Can i confirm you for a presentation next week for our online live-streamed BrisJS?

**Comment by tomquirk** [comment]
@iamkevinv yep, can do! Let me know if I need to give anything to you (slides etc.). Cheers

**Comment by iamkevinv** [comment]
Nope we can share slides here once the talk is done on Monday :-)

**Comment by iamkevinv** [comment]
For tonight: 

Join Zoom Meeting
https://us02web.zoom.us/j/169245706

Meeting ID: 169 245 706
One tap mobile
+61871501149,,169245706# Australia
+61280156011,,169245706# Australia

Dial by your location
        +61 8 7150 1149 Australia
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
Meeting ID: 169 245 706
Find your local number: https://us02web.zoom.us/u/kdhUAdM35n

**Comment by iamkevinv** [comment]
Once again, appreciate your talk! If you have resources to share, please feel free to add them on here :)
