### ISSUE TITLE
Senior/Lead Front End Developer @ Picklebet

### ISSUE THREAD

**Issue by jgh** [BrisJS/meetups#414]
We are looking for a senior front end developer, ready to take the lead on web and mobile development, at a fast growing esports scaleup, Picklebet. The Picklebet front end has to processes streams of constantly changing data and render it quickly and accurately to the user, experience building these types of applications is highly regarded.

You’ll work closely with our CTO, as well as designers and other stakeholders in a highly collaborative and technical environment. You’ll also play a key role in building out the engineering team, culture, and ways of working.

We’re looking for people with:
 - strong communication skills
 - the ability to collaborate remotely (since COVID we have been default remote)
 - the ability to work autonomously
 - willingness to work in the gambling industry
 - interest in online games and/or esports
 - the ability to deliver features / get the job done

Who have experience with:
 - Typescript
 - React
 - Redux
 - RxJS
 - Object-orientated programming
 - Javascript / HTML / CSS

And some of the following attributes:
 - Familiarity with CMS software like Contentful
 - UX/UI design experience and/or enthusiasm
 - Experience with React Gatsby and/or GraphQL
 - Experience with mobile app development/deployment
 - Experience with Firebase
 - Experience with Agile development
 - Knowledge and background in gambling
 - Passion for esports

**Comment by jgh** [comment]
Email: jeremy@puntaa.co

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
