### ISSUE TITLE
Senior JavaScript Developer @ Airteam (remote - anywhere in Australia)

### ISSUE THREAD

**Issue by atkinson** [BrisJS/meetups#415]
Times have changed. We've moved to a hybrid model of working. That means we’re now open to applicants from anywhere in Australia! You can work from our office or work remotely - your choice.

[Senior JavaScript Developer (remote)](https://www.airteam.com.au/careers/)

**Benefits**

- Highly skilled, senior and friendly team;
- Great clients + interesting work;
- Learning Budget of $2,000 plus two days of personal development every year;
- We’ll also chip in for your Internet and phone with our Communications Allowance and contribute towards keeping your laptop up to date!
- Employee Stock Ownership Plan. That’s right, everyone that works for Airteam has the opportunity to own part of the company!

**Essential skills for this role**

- 5+ years of solid JavaScript experience; you must be comfortable with React and modern JavaScript.
- Experience with AWS (we do _full-stack serverless JS_) - AWS certifications highly regarded!
- You are a self-starter and can work within a team to ship high-quality code
- You are an excellent communicator, written and verbal
- You have experience communicating with clients

**This role is right for you if**

You love to code; you’re the kind of person who loves to learn new things. You enjoy solving problems and crafting elegant solutions. You like to work autonomously, but as part of a team. You can choose the best methods to get things done with a focus on maintainable code. Your experience includes other languages or tech stacks. You enjoy working somewhere that gives you respect and fosters good relationships with clients and colleagues.

**Our hiring process**

1. Fill in the application form and include your CV. We are looking for examples of how you meet the essential skills we have outlined for the role. We love getting cover letters introducing yourself!
2. We review all applications. If we see a skills/experience match, we'll give you a call.
3. Then we'll move onto an interview stage to talk about what you can bring to the team. You'll get a chance to ask us lots of questions too!

**About Airteam**

We're a small team of experienced developers and designers creating brand new software for the world to use. We are makers and problem solvers, we are known for our ability to ship high-quality digital products. Our clients include fintech, financial services, insurance, education, healthcare and government.

We're looking for people who love what they do, enjoy a challenge, are happy to jump in and get things done and strive for better outcomes for our clients.

**Important information**

We are an equal opportunity employer and consider all applicants including people of different ages, gender, ethnicity, physical ability, sexual orientation, religious belief, work experience, educational background. We prefer not to work with recruiters.

Unfortunately, we cannot offer sponsorship for this position. Applicants must be in Australia and eligible to work.

We are not responsible for any fees related to unsolicited resumes sent from recruiters. Thanks!

[Apply on our website](https://www.airteam.com.au/careers/)

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
