### ISSUE TITLE
Intermediate / Senior Full-stack Developer @ Compono (Brisbane office + remote friendly within Aus)

### ISSUE THREAD

**Issue by dp-lewis** [BrisJS/meetups#416]
# Intermediate / Senior Full-stack Developer @ Compono

## Your Role and Your Impact

We are a rapidly growing startup in terms of our people, our Talent Optimisation products and our client base.

Our engineering team are a team of developers from different backgrounds and with diverse skills. We are currently looking for additional like-minded, talented developers to become part of our cross-functional teams. 

This Intermediate or Senior Full Stack Developer role can be either located in our Sydney or Brisbane Office with flexible working from home conditions (note: currently fully remote whilst we navigate COVID-19). You will become part of our work family, where on any given day you could:   

- Build and maintain product features throughout the entire applications stack      
- Provide documentation and technical support for operational carriers, service provider integrations and to other business units within the organisation      
- Uphold quality standards including reliability, efficiency, security, maintainability and usability by applying best practice processes, methodologies and tools      
- Integrate approved frameworks and technologies to improve existing services and to help fulfil business needs      
- Perform code reviews and test
And in everything you do, you will be part of our internal learning culture - where you both provide expertise and mentorship as well as take part in continuous learning within our team.

## About You

We're not focused on you having a Computer Science degree; instead, we focus on a combination of your skills and your capabilities. 

You will have a strong understanding, knowledge and experience in the following:       

JavaScript / Typescript programming languages (approximately 5+ years).
- Skillset consisting of React, Redux, noSQL databases, Express.js, TDD, AWS (bonus) and GraphQL     
- Both front-end and server-side development in the context of JavaScript / Typescript ecosystem       
- Production experience with AWS/Serverless     
Comfortable with databases and best practices around interacting with them       
- Writing tests and knowing how to write testable code.       
- Comfortable with version control, e.g. GIT       
- Ability to debug problems unassisted in most of the situations       
- Part of delivery of multiple products or systems       
- Understanding of software development and design principles      
- Knowledge of container environments, E.g. Docker       
- Demonstrated involvement in an Open Source project/s (favourable)

As an intermediate / Senior Developer in a fast-paced and growing startup, you will:          

- Manage deadlines and escalate where required          
- Articulate technical problems, concepts and ideas  
- Have strong abstract reasoning skills and ability to think conceptually and problem solve          
- Ability to deal with unknowns and help build better processes and practices          
- Possess understanding, passion and belief of our bigger business vision          
- Perseverance and Grit          
- Make evidence-based decisions          
- Ability to receive and act on feedback          
- Make well-guided estimates and forecasting.          
- Tenacious with an ability to drive their work through to conclusion
More about Compono

Imagine having a satisfying and rewarding career from the moment you enter the workforce to the day you retire. This is what we’re building!

Compono seeks to transform and power the work ecosystem for both employees and companies. Our suite of products delivers intelligent systems of employee engagement and talent optimization across 3 HR key pillars - talent acquisition, talent development, and talent retention. Our software improves organisational competitive advantage and helps a person’s working life become more fulfilling and productive in whatever company they work for.

We are a tech scale-up, and we know what it takes to build a successful business. We are supported by high profile investors who underpin our rapid growth. We’ve built our technology and products from the ground up using best practice approaches.

Want a more detailed look at our products, please visit Compono.com.

## Why join Compono? 

This is your unique opportunity to join a company at a pivotal growth stage. More importantly, be part of an environment where everyone is valued and where you are encouraged to generate your own ideas and have an impact on decisions. We are passionate about what we do but always with a close eye on work-life balance. Join a team that is inclusive of all differences and celebrates successes and always continuously learns!               

Flexible working with the ability to work from home 3 days per week pre-covid (currently full-time remote during COVID-19)             
Ability to be based in Sydney or Brisbane                    
A competitive salary package                      
A culture built on trust and empowerment  
How to Apply

We would love to hear from you! Don’t miss out on this opportunity and apply now by creating your Shortlyster profile. 

Please contact David Lewis on david.lewis@compono.com if you require further details. 

## Our recruitment process

The next part of our process is for you to create your online profile. This profile will help us to understand better who you are; the types of skills and work experience you have, the qualifications you hold and the work preferences and expectations you have. Ultimately, we want to make sure there is a good fit between you and our company.

Please note: Compono are continuing to recruit and onboard remotely due to COVID-19. All employees can be work remotely full-time until it's safe to return to our offices.

Unfortunately, we cannot offer sponsorship for this position. Applicants must be in Australia and eligible to work.

Apply using the following URL: https://candidate.shortlyster.com/l/mMwMjI

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
