### ISSUE TITLE
 How to get your first job as a developer while being a student from another country?

### ISSUE THREAD

**Issue by luizfelipehh** [BrisJS/meetups#417]
I've been worked  as software developer in Brazil. But my Student Visa it's a problem here in Australia to get a job.

**Comment by iamkevinv** [comment]
Hi there! Welcome Luiz!
- Any idea on talk length? Is this a lighting talk? (~10min)
- Can you give some rough talking points you would cover?
- Are you free to talk about it in our virtual event coming up in Dec?
- Do you have any social accounts like a twitter you'd like me to use if i'm advertising our speakers upcoming?

**Comment by iamkevinv** [comment]
@luizfelipehh - Can you provide details? I've been holding on sending out the notice to everyone, but i'm not able to delay longer. I'll update it again to include you if you can make it.

**Comment by luizfelipehh** [comment]
> Hi there! Welcome Luiz!
> 
> * Any idea on talk length? Is this a lighting talk? (~10min)
> * Can you give some rough talking points you would cover?
> * Are you free to talk about it in our virtual event coming up in Dec?
> * Do you have any social accounts like a twitter you'd like me to use if i'm advertising our speakers upcoming?

1 - What is the best way when a person is from other country and has a Student Visa?

2 - I’ve never seen sucess cases when a person just can work part time (Student Visa) 20 hours weekly.

3 - Is it possible get a internship without is studying in University?

**Comment by iamkevinv** [comment]
Thanks @luizfelipehh - But i still need to know:
Can you confirm its lightning talk length of about 10 mins or less?
Are you able to attend the Monday meetup over zoom video?

**Comment by iamkevinv** [comment]
Didn't get the time or confirmation, so i assume you're not available. Hope to see you in Feb!

**Comment by iamkevinv** [comment]
Hi @luizfelipehh - Are you interested in presenting this in the upcoming months?
Can you confirm its lightning talk length of about 10 mins or less?
Are you able to attend the Monday Feb 1st meetup over zoom video... if not, i'll put this into March to organise further.

**Comment by iamkevinv** [comment]
Hi @luizfelipehh - Are you interested in presenting this in the upcoming months?

**Comment by iamkevinv** [comment]
Hi @luizfelipehh - can you present this talk at our upcoming virtual event next week?

**Comment by iamkevinv** [comment]
Hi @luizfelipehh - could this become an upcoming talk?

**Comment by iamkevinv** [comment]
Hi @luizfelipehh - Are you potentially able to present this on 4/July or 1/Aug?

**Comment by iamkevinv** [comment]
@luizfelipehh - Interested in reviving this talk for 2023?

**Comment by iamkevinv** [comment]
Hi @luizfelipehh - Wondering if you're still interested in doing a talk some time soon?
