### ISSUE TITLE
Multiple roles for Mid/Senior/Lead (React/NodeJS) developers @ Swyftx

### ISSUE THREAD

**Issue by jared-fraser** [BrisJS/meetups#418]
Are you ready for your next step? Become an integral part of Australia’s next billion-dollar success story by collaborating within a team of innovators, with a focus on building awesome Crypto Currency trading software. With our focus on putting our people first, you will become a major contributing factor to the company’s growth and technical milestones. For more about what’s on offer check out https://swyftx.com.au/careers/.

Swyftx are hiring for multiple roles:

- Mid/Senior Full-Stack Developers. 
- Mid/Senior React Developers
- Mid/Senior NodeJS Developers

# Your Role:

Swyftx are in search for developers that are passionate about elegant code, design patterns, software architecture, development best practices and up to date with new technologies, frameworks and other languages. You will be working closely with the founders to keep the company ahead of the game. 

# Day to day tasks will include:

- Contribute to the architecture and migration of our trading platform from AngularJS to React
- Bug fixes, writing code (Node and Angular) responsible for millions of dollars in transactions, innovating on new features, optimising systems, collaborating with the team and performing peer reviews. 
- Transforming business requirements and user feedback into product features that involve developing in different languages and technologies in both back and front-end layers.
- Providing complementary skills/expertise to the team and continuously learning from peers and seniors.
- Continually performing code reviews and knowledge transfers to other developers
- Providing, colleagues and customers with technical advice.

# This is you:

-    Degree in Computer Science, IT, or related field.
-    2+ years of full-time experience.
-    Experience with NodeJS and a comprehensive understanding of Async programming.
-    Working knowledge of Angular, HTML and CSS.
-    Possesses initiative and has an adaptive and proactive nature.
-    Ability to prioritise tasks and manage your own workflow.
-    Good analytical skills for solution design, software build and problem resolution.
-    A customer focused mindset in all aspects of your work.

You will experience first-hand what it means to say “I did that” as you watch your ideas and visions become a reality, impacting thousands of people every day.

# On Offer:
Salary: $80,000 - $140,000 gross salary + Super (based on experience)

Location: Milton, Brisbane, QLD - Close to all public transport

Benefits:
All our benefits are listed on our [Careers Page](https://swyftx.com.au/careers/)

- Fortnightly pay
- Learning & Development budget
- Career growth
- Online game tournaments

You will be working amongst a team of innovators, industry disruptors and caffeine consumers (duh!). The open plan office based in Milton creates a relaxed and supportive environment, that is filled with engaging group activities, motivating music, and like minded people.

# Who are we?

Swyftx is rapidly building a name for itself as Australia’s most feature rich and best priced digital currency exchange. The vision is for Swyftx to be the only place crypto traders and investors alike need to go to get anything and everything they need. The company was bootstrapped over 18 months by its two founders and has successfully established itself in the Australian market, with goals set on being the largest crypto currency trading platform in Australia. Check us out! https://swyftx.com.au/

Interested? Send your resume and cover letter to jared@swyftx.com.au.

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
