### ISSUE TITLE
Kotlin.js

### ISSUE THREAD

**Issue by tyc222** [BrisJS/meetups#419]
Kotlin/JS provides the ability to transpile your Kotlin code, the Kotlin standard library, and any compatible dependencies to JavaScript. The current implementation of Kotlin/JS targets ES5.

I can give a quick talk on this if anyone is interested.

**Comment by iamkevinv** [comment]
Hi @tyc222 - Cool! Can you please provide the following?
Talk title: <here>
Talk length: ~10min, 20 min or 40 min
Talk description: Kotlin/JS provides the ability to transpile your Kotlin code, the Kotlin standard library, and any compatible dependencies to JavaScript. The current implementation of Kotlin/JS targets ES5.
Available month(s): <Any month from Feb 2021 here...>
Optional: your Twitter account or such so we can promote your talk

**Comment by tyc222** [comment]
Talk title: Kotlin/js
Talk length: ~20 min
Talk description: Kotlin/JS provides the ability to transpile your Kotlin code, the Kotlin standard library, and any compatible dependencies to JavaScript. The current implementation of Kotlin/JS targets ES5.
Available month(s): March, April, May

**Comment by iamkevinv** [comment]
Hi @tyc222 - Can i confirm you to do this talk for next week's BrisJS March event, to present this in our next Zoom livestream?

**Comment by tyc222** [comment]
HI, unfortunately my plate is a bit full in March. I should be free for April

**Comment by iamkevinv** [comment]
Scheduling you in for next month then and will ping again closer to the date for confirmation

**Comment by iamkevinv** [comment]
Hi @tyc222 - Can i confirm you'll be presenting this at our virtual event, monday 19th April 6:30pm onward? I'd like to send out the event list to all 👍

**Comment by iamkevinv** [comment]
Hi @tyc222 - Just following up... can i confirm?

**Comment by iamkevinv** [comment]
moved to May

**Comment by iamkevinv** [comment]
Hi @tyc222 - can I confirm you for this upcoming virtual meetup?

**Comment by iamkevinv** [comment]
I don't have any replies and confirmations. I'll move this entry to next month. Not enough speakers sadly so I'll cancel the may event.

**Comment by iamkevinv** [comment]
Hi @tyc222 - Are you available to do a talk at BrisJS this year? Please let me know and i'll be happy to add you to an event :)

**Comment by iamkevinv** [comment]
Hi @tyc222 - Are you available to do a talk at an upcoming BrisJS event?

**Comment by iamkevinv** [comment]
Hi @tyc222 - Are you available to do a talk at one of the upcoming months?

**Comment by iamkevinv** [comment]
Closing due to length of time open. Please let me know if it should be re-opened.
