### ISSUE TITLE
Talk volunteer - ansible for a private repo

### ISSUE THREAD

**Issue by shotlom** [BrisJS/meetups#42]
Talk volunteering - I've just figured out how to deploy from a private repo using ansible.

Anyone interested in an ansible noob talk?

**Comment by kevdesign** [comment]
You still happy to cover this tomorrow @shotlom ? Sorry for the late reminder.

**Comment by shotlom** [comment]
holy crap!!! I didn't think anyone was interested in this!!!!



On Sun, Mar 1, 2015 at 9:34 PM, Kevin Vanderbeken <notifications@github.com>
wrote:

> You still happy to cover this tomorrow @shotlom
> <https://github.com/shotlom> ? Sorry for the late reminder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/42#issuecomment-76593040>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by kevdesign** [comment]
Yeah man, why not - something lots of people would do, and always good to get a tip :)
If it's going to be a problem though, just let me know.

**Comment by shotlom** [comment]
Crap. Sorry, I made other plans because no-one looked that interested.

Happy to do a proper presentation at the following meetup.

My apologies.


On Sun, Mar 1, 2015 at 11:21 PM, Kevin Vanderbeken <notifications@github.com
> wrote:

> Yeah man, why not - something lots of people would do, and always good to
> get a tip :)
> If it's going to be a problem though, just let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/42#issuecomment-76596495>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by kevdesign** [comment]
Hi @shotlom - Want to do this for April?
Also you had added comment in #22 regarding the use with systemd - which could also be interesting to mention perhaps?

**Comment by shotlom** [comment]
Hi Kevin,

Yep - I'll see if I can get a little demo going

On Thu, Mar 19, 2015 at 1:59 PM, Kevin Vanderbeken <notifications@github.com
> wrote:

> Hi @shotlom <https://github.com/shotlom> - Want to do this for April?
> Also you had added comment in #22
> <https://github.com/BrisJS/meetups/issues/22> regarding the use with
> systemd - which could also be interesting to mention perhaps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/42#issuecomment-83307170>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by elliotthilaire** [comment]
I'm interesting in hearing about this.

**Comment by shotlom** [comment]
@kevdesign  - is the next meetup Monday 13th? I can prepare somethign over the weekend for it.

**Comment by kevdesign** [comment]
Gah... i just realised i'd left this off the list (so sorry!)... i can still add you in to the April promo if you'd like? Otherwise you'd first off the list for next month if you prefer. Sorry to jerk you around man.

**Comment by shotlom** [comment]
All good - I'm down in Victoria so It'll have to be June! ;)

On Fri, May 1, 2015 at 9:11 PM, Kevin Vanderbeken <notifications@github.com>
wrote:

> Gah... i just realised i'd left this off the list (so sorry!)... i can
> still add you in to the April promo if you'd like? Otherwise you'd first
> off the list for next month if you prefer. Sorry to jerk you around man.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/42#issuecomment-98102011>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by kevdesign** [comment]
1st of June is monday @shotlom ... Would you like a small spot to give us a demo?

**Comment by shotlom** [comment]
Sounds good - I'll get something together over the weekend.

On Thu, May 28, 2015 at 1:07 PM, Kevin Vanderbeken <notifications@github.com
> wrote:

> 1st of June is monday @shotlom <https://github.com/shotlom> ... Would you
> like a small spot to give us a demo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/42#issuecomment-106157162>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by kevdesign** [comment]
Thanks mate I'll add you

**Comment by iamkevinv** [comment]
Thanks again @shotlom - if you have any resources to link - please do so and i'll add the right label

**Comment by shotlom** [comment]
Hi @iamkevinv  - yep apologies for the limited demo,

There is a good resource here:

http://blog.carbonfive.com/2014/06/02/node-js-in-production/
