### ISSUE TITLE
Talk submission - Going with the flow, building nodes with JS for node-red

### ISSUE THREAD

**Issue by developersteve** [BrisJS/meetups#420]
**Talk length**: Could be 10 mins but could easily fill 20 mins 

Keen to come and do a talk about node-red (open sourced low code/no code) and how its really handy for prototyping (particularly at hackathons), also show how easy it is to build and deploy nodes to the community. Taking a look at some of the projects ive used it for previous including some of the TelstraDev joint demos (https://github.com/MichelleHowie/Arduino-MKR-IMU-Fall-Detect) and how it powers my coffee table and even wedding cake (lol true story!)

**Comment by iamkevinv** [comment]
@developersteve - Sorry for being so tied up - that's on me! 
I'm extremely happy to see this submission as mentioned when we last talked. 
**What months would you be available?**
I'm trying to organise the talk for **Feb 1st** right now, but that's really short notice so if push comes to shove and we can't organise it within the next 24/48h i will move it forward by a week to 8 Feb. Are you keen for the Feb date?

**Comment by developersteve** [comment]
Soz just saw the notification, wont be able to make Monday but is it ok if we push it out a month?

**Comment by iamkevinv** [comment]
Not a worry! If i postpone Feb to 8th of Feb instead of 1st of Feb (monday) would that help you?
Just weighing scheduling options. Otherwise March is totally fine!

**Comment by iamkevinv** [comment]
Confirming you for 8th Feb @developersteve :)

**Comment by iamkevinv** [comment]
We'll do the presenting side over Zoom, and it will be automatically streamed to our youtube channel. If we hop on a few mins early we can test audio, video and sharing for everyone.
The link is https://us02web.zoom.us/j/169245706

Topic: BrisJS Meetup
Time: Feb 8, 2021 06:25 PM Brisbane
        Feb 8, 2021 06:25 PM

Join Zoom Meeting
https://us02web.zoom.us/j/169245706

Meeting ID: 169 245 706
One tap mobile audio dial in
+61871501149,,169245706# Australia
+61280156011,,169245706# Australia

Dial in audio by your location
        +61 8 7150 1149 Australia
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
Meeting ID: 169 245 706
Find your local number: https://us02web.zoom.us/u/kcd66mBOf

**Comment by iamkevinv** [comment]
Thanks for the talk, if you've got any resources you'd like to add, please do!

**Comment by developersteve** [comment]
Thanks Kevin, thanks for letting me present last night. 

Heres some links to the things i talked about 

Givebackathon - [https://barayamal.com.au/programs/give-backathon/](https://barayamal.com.au/programs/give-backathon/)
Call for Code - [https://developer.ibm.com/callforcode/](https://developer.ibm.com/callforcode/)
Node-red - [https://node-red.org](https://node-red.org) 
IOT SMS env shield code for node-red - [https://github.com/MichelleHowie/IoTSensorData_OnDemand](https://github.com/MichelleHowie/IoTSensorData_OnDemand)
Node-red chatbot - [https://developer.ibm.com/components/node-red/tutorials/create-a-voice-enabled-covid-19-chatbot-using-node-red/](https://developer.ibm.com/components/node-red/tutorials/create-a-voice-enabled-covid-19-chatbot-using-node-red/)
