### ISSUE TITLE
Building Identity Platforms with Azure ADB2C and MSAL.js 

### ISSUE THREAD

**Issue by cryptoroo** [BrisJS/meetups#421]
Talk title:  Building Identity Platforms with Azure ADB2C and MSAL.js 
Talk length: 20 min
Talk synopsis: How to build an identity platform using ADB2C and MSAL.js. Some common use cases and how to solve them. The concept of an identity broker and how it helps to keep frontend code clean. 
Available month(s): Feb 2020 + 
Optional: your Twitter account so we can promote your talk

**Comment by iamkevinv** [comment]
Wonderful! Thanks for this cool submission @cryptoroo!
I'm trying to organise the talk for Feb 1st _right now_, but I know that's short notice so if push comes to shove and i can't get enough speakers confirmed within the next 24/48h i will move it forward by a week to 8 Feb. Are you keen for the Feb 1st date? No problem booking you in for March too if Feb isn't possible for you.

**Comment by iamkevinv** [comment]
Just pinging again to hopefully get your inbox attention @cryptoroo - any thoughts on the last post?

**Comment by iamkevinv** [comment]
@cryptoroo - any chance you're ready for next week's March event?

**Comment by iamkevinv** [comment]
Hi @cryptoroo - Can i confirm you'll be presenting this at our virtual event, monday 19th April 6:30pm onward? I'd like to send out the event list to all 👍

**Comment by iamkevinv** [comment]
Hi @cryptoroo - Just following up... can i confirm?

**Comment by iamkevinv** [comment]
moved to May

**Comment by iamkevinv** [comment]
Hi @cryptoroo - can I confirm you for this coming meetup?!

**Comment by iamkevinv** [comment]
I don't have any replies and confirmations. I'll move this entry to next month. Not enough speakers sadly so I'll cancel the may event.

**Comment by iamkevinv** [comment]
Hi @cryptoroo / @ahaw021 - is this still a potential talk for upcoming meetups?

**Comment by iamkevinv** [comment]
Hi @cryptoroo / @ahaw021 - Are you potentially able to present this on 4/July or 1/Aug?

**Comment by ahaw021** [comment]
Hi @iamkevinv  we can close this one off. 

I don't have access to Azure ADB2C anymore for a demo :D
