### ISSUE TITLE
Enjoyable Load Testing with K6.io - Load Testing Developers will Love

### ISSUE THREAD

**Issue by cryptoroo** [BrisJS/meetups#422]
Talk title: Enjoyable Load Testing with K6.io - Load Testing Developers will Love
Talk length: 20 min
Talk synopsis: Funny Things happen at scale. This talk is about how we adopted K6.io and reasons why. I will walk through some code samples (written in TypeScript) and why I think its a load testing tools JavaScript developers should love and learn. 
Available month(s): Feb 2020 +
Optional: your Twitter account so we can promote your talk

**Comment by iamkevinv** [comment]
Oh another one! Love this passion @cryptoroo!
Same message... I'm trying to organise the talk for Feb 1st _right now_, Which talk did you want to do first... and are you keen for the Feb 1st date? No problem booking you in for March too if Feb isn't possible for you.

**Comment by cryptoroo** [comment]
Hi @iamkevinv  - should be good for the march meetup for this one

**Comment by iamkevinv** [comment]
Great @cryptoroo - will lock you in for the event over zoom! I'll send the details soon

**Comment by iamkevinv** [comment]
@cryptoroo - sorry to be a bother, but as you may have seen I've had schedule conflicts for other talks, meaning you're the sole presenter, I'm wondering if perhaps we postpone BrisJS one week since it's had a poor lead up this time. Is March 8th still OK for you? Please reply ASAP!

**Comment by iamkevinv** [comment]
@cryptoroo - checking in again that moving the date will be OK? I'm going to make the move today. We've run out of time. Hope you can still present - even if we can't get the other speakers schedules lined up again this should give everyone more time and more notice.

**Comment by iamkevinv** [comment]
@cryptoroo - can you give me your full name for the event description please?

**Comment by iamkevinv** [comment]
https://www.meetup.com/BrisJS/events/fxdfkryccfbcb/

**Comment by cryptoroo** [comment]
Hi @iamkevinv  

I have had a family emergency so won't be able to present tonight. 

Really sorry to put you out on a lurch.

**Comment by iamkevinv** [comment]
@cryptoroo - hi, as I mentioned we've already moved it to next week Monday - hope everyone will be okay mate!

**Comment by iamkevinv** [comment]
Hope you and the family are doing OK mate. When you get a chance, i just need your full name for the meetup page notes for this coming Monday's online event. Thanks.

**Comment by cryptoroo** [comment]
next week works well.

**Comment by iamkevinv** [comment]
OK - adding to the event listing:
> Andrei Hawke - 20m (linkedin: andrei-hawke-b9140a14/)

Details for tomorrow's zoom
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetup
Time: Mar 8, 2021 06:15 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/83905657880

Meeting ID: 839 0565 7880

Dial by your location
Find your local number: https://us02web.zoom.us/u/kdIobpGwWL

**Comment by iamkevinv** [comment]
It says 6:15 for prep time, but the event is from 6:30pm

**Comment by iamkevinv** [comment]
@cryptoroo - if you'd like to share the slides or any links, please feel free to add them here!
