### ISSUE TITLE
Service Workers(PWAs)

### ISSUE THREAD

**Issue by ameenurrahman36** [BrisJS/meetups#423]

**Comment by iamkevinv** [comment]
Hi @ameenurrahman36 - We'd love to have you present something at BrisJS :) 

Can you help me out and fill out the following details?

Presenter Name: You!
Talk title: My Talk
Talk length: 10 min / 20 min / 30 min
Talk description:
Available month(s): Feb, March, April... etc
Optional: your Twitter account or other so we can promote your talk

**Comment by ameenurrahman36** [comment]
Presenter Name: Ameenur Rahman
Talk title: Service Workers(PWAs)
Talk length: 30 min
Talk description: A service worker is a script that your browser runs in the background, separate from a web page, opening the door to features that don't need a web page or user interaction. Today, they already include features like push notifications and background sync. The core feature discussed in this talk is the ability to intercept and handle network requests, including programmatically managing a cache of responses.
Available month(s): Feb/March
Optional: https://www.linkedin.com/in/ameenur-rahman-093a224b/

**Comment by iamkevinv** [comment]
Are you still available to present if I move the online event to the next Monday 8 Feb instead of this Monday 1st Feb?

**Comment by ameenurrahman36** [comment]
Yes am available on Monday 8th Feb, thanks.

**Comment by iamkevinv** [comment]
Fantastic :) I'll add you to the confirmed list and we'll do this Monday 8th Feb.
Is it possible to edit down less than 30min in this session? We have 2 other 20min sessions and i'd like to try and ensure we meet the time length of the event. If it goes over with questions thats fine, but aiming for the body of the talk to be a little closer to 20min would really help 😄  - Sorry if that puts you out a bit! We can always get a follow up talk scheduled in future 👍

**Comment by ameenurrahman36** [comment]
No problem I'll cut short it to 20 mins.

**Comment by iamkevinv** [comment]
We'll do the presenting side over Zoom, and it will be automatically streamed to our youtube channel. If we hop on a few mins early we can test audio, video and sharing for everyone.
The link is https://us02web.zoom.us/j/169245706

Topic: BrisJS Meetup
Time: Feb 8, 2021 06:25 PM Brisbane
        Feb 8, 2021 06:25 PM

Join Zoom Meeting
https://us02web.zoom.us/j/169245706

Meeting ID: 169 245 706
One tap mobile audio dial in
+61871501149,,169245706# Australia
+61280156011,,169245706# Australia

Dial in audio by your location
        +61 8 7150 1149 Australia
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
Meeting ID: 169 245 706
Find your local number: https://us02web.zoom.us/u/kcd66mBOf

**Comment by iamkevinv** [comment]
Thanks for the talk, if you've got any resources you'd like to add, please do!

**Comment by ameenurrahman36** [comment]
Thanks, I have added the ppt I used for presentation.
[ServiceWorkers.pptx](https://github.com/BrisJS/meetups/files/5948492/ServiceWorkers.pptx)
