### ISSUE TITLE
Talk Proposal: Mobile App Development for Noobs using React Native and Expo

### ISSUE THREAD

**Issue by uqsbolla** [BrisJS/meetups#424]
Talk title: Mobile App Development for Noobs using React Native and Expo
Talk length: 20 min
Talk synopsis:
This talk is for those interested in learning more about mobile app development using Javascript and React.  I will be providing a cook's tour of React Native and Expo, and diving into some of my favourite online resources and tutorials that can get you writing and deploying your own quite sophisticated apps in a number of days.
Available month(s): Any

**Comment by iamkevinv** [comment]
Thanks @uqsbolla for your submission!
The next event is next monday 1st Feb, online via Zoom. Let me know if you're available for that one at this short notice... or otherwise if we're swarmed with response today i may shuffle some of the items to March 1st. 
Much appreciate the support.

**Comment by uqsbolla** [comment]
Hi Kevin, Yep can do Monday the 1st. Let me know. Cheers, Scott Sent from Mail for Windows 10 From: Kevin VanderbekenSent: Thursday, 28 January 2021 3:06 PMTo: BrisJS/meetupsCc: uqsbolla; MentionSubject: Re: [BrisJS/meetups] Talk Proposal: Mobile App Development for Noobs using React Native and Expo (#424) Thanks @uqsbolla for your submission!The next event is next monday 1st Feb, online via Zoom. Let me know if you're available for that one at this short notice... or otherwise if we're swarmed with response today i may shuffle some of the items to March 1st.Much appreciate the support.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iamkevinv** [comment]
You're first to reply... so i'll confirm you on the Feb lineup. If we have a change in date this month i'll reply back.

**Comment by iamkevinv** [comment]
We've moved the event to 8th of Feb. Hope this still works for you, and looking forward to hearing you speak!

**Comment by uqsbolla** [comment]
Yep … all good for next monday Sent from Mail for Windows 10 From: Kevin VanderbekenSent: Wednesday, 3 February 2021 7:06 PMTo: BrisJS/meetupsCc: uqsbolla; MentionSubject: Re: [BrisJS/meetups] Talk Proposal: Mobile App Development for Noobs using React Native and Expo (#424) We've moved the event to 8th of Feb. Hope this still works for you, and looking forward to hearing you speak!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iamkevinv** [comment]
We'll do the presenting side over Zoom, and it will be automatically streamed to our youtube channel. If we hop on a few mins early we can test audio, video and sharing for everyone.
The link is https://us02web.zoom.us/j/169245706

Topic: BrisJS Meetup
Time: Feb 8, 2021 06:25 PM Brisbane
        Feb 8, 2021 06:25 PM

Join Zoom Meeting
https://us02web.zoom.us/j/169245706

Meeting ID: 169 245 706
One tap mobile audio dial in
+61871501149,,169245706# Australia
+61280156011,,169245706# Australia

Dial in audio by your location
        +61 8 7150 1149 Australia
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
Meeting ID: 169 245 706
Find your local number: https://us02web.zoom.us/u/kcd66mBOf

**Comment by uqsbolla** [comment]
Hi Kevin, Im online waiting to be let in … Sent from Mail for Windows 10 From: Kevin VanderbekenSent: Wednesday, 3 February 2021 9:00 PMTo: BrisJS/meetupsCc: uqsbolla; MentionSubject: Re: [BrisJS/meetups] Talk Proposal: Mobile App Development for Noobs using React Native and Expo (#424) We'll do the presenting side over Zoom, and it will be automatically streamed to our youtube channel. If we hop on a few mins early we can test audio, video and sharing for everyone.The link is https://us02web.zoom.us/j/169245706Topic: BrisJS MeetupTime: Feb 8, 2021 06:25 PM BrisbaneFeb 8, 2021 06:25 PMJoin Zoom Meetinghttps://us02web.zoom.us/j/169245706Meeting ID: 169 245 706One tap mobile audio dial in+61871501149,,169245706# Australia+61280156011,,169245706# AustraliaDial in audio by your location+61 8 7150 1149 Australia+61 2 8015 6011 Australia+61 3 7018 2005 Australia+61 7 3185 3730 Australia+61 8 6119 3900 AustraliaMeeting ID: 169 245 706Find your local number: https://us02web.zoom.us/u/kcd66mBOf—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iamkevinv** [comment]
Sorry for the delay @uqsbolla - that was on me, not you! :-D Bit of a scramble coming off a work call straight to brisjs :)

**Comment by iamkevinv** [comment]
Thanks again for the talk, if you've got any resources you'd like to add, please do!

**Comment by uqsbolla** [comment]
Hi Kevin, I spoken at the BrisJS meetup at the beginning of the year, talking about React Native. I’m currently looking for some work if you know of anything on offer.  I am a full-stack developer specialising in React / Redux / Node.js / Bootstrap.   CV attached. Let me know if you know of anything. Any ideas greatly appreciated. Cheers, Scott
