### ISSUE TITLE
Long talk: Building microservices with Node.js

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#425]
Talk time: 30-40 minutes

Let's explore how to build microservices with Node.js.

We'll talk about why and when to use microservices and how to build a basic microservice with Node.js. 

I'll be giving away copies of my book Bootstrapping Microservices.

**Comment by iamkevinv** [comment]
@ashleydavis - any chance that having moved the meetup to 8 March now means you can do this talk in March?

**Comment by iamkevinv** [comment]
https://www.meetup.com/BrisJS/events/fxdfkryccfbcb/

**Comment by ashleydavis** [comment]
Sorry mate

**Comment by ashleydavis** [comment]
I can do a short talk next week though!

**Comment by iamkevinv** [comment]
Awesome which would you like for next week!??

**Comment by ashleydavis** [comment]
Ok if I decide tomorrow?

**Comment by ashleydavis** [comment]
I've just logged a new short talk:

https://github.com/BrisJS/meetups/issues/433

Let me know if that's ok for next week?

**Comment by iamkevinv** [comment]
Hi @ashleydavis - Can i confirm you'll be presenting at our virtual event, monday 19th April 6:30pm onward? I'd like to send out the event list to all 👍

**Comment by ashleydavis** [comment]
Yes, I'm good to go.

**Comment by ashleydavis** [comment]
I'm updating the talk abstract to remove some things that would make it too long.

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.
Topic: BrisJS Meetup

Join Zoom Meeting
https://us02web.zoom.us/j/85471587750

Meeting ID: 854 7158 7750
Find your local number: https://us02web.zoom.us/u/kd6FHBQfCa

**Comment by ashleydavis** [comment]
Here are my slides:
https://www.slideshare.net/AshleyDavis33/microservices-with-nodejs-for-brisjs

**Comment by iamkevinv** [comment]
Thanks for the linked resources! Keep in touch and let me know which if your other submissions you'd like to present next!
