### ISSUE TITLE
JavaScript in the Cloud

### ISSUE THREAD

**Issue by melissahoughton** [BrisJS/meetups#428]
**Talk title:** JavaScript in the Cloud
**Talk length:** 20 min
**Talk synopsis:**
A look at all the fun stuff you can do with JavaScript, in the cloud!

Traditionally, JavaScript is the language of the web, and it still is. But today it's so much more. With the advent of server-side JavaScript and JavaScript support in major cloud platforms, JavaScript's power increased dramatically.

From building, maintaining, optimising and deploying, the end to end development and delivery process is possible with JavaScript in the cloud.

Cloud platforms give us the tools, elasticity and scalability to create high performing applications without managing the physical infrastructure.

Take advantage of the cloud while using a language you already know: JavaScript!

**Available month(s):** April 2021 onwards
**Optional:** [@meliss_houghton](https://twitter.com/meliss_houghton)

**Comment by iamkevinv** [comment]
Wonderful :) I'll schedule it in April as per your request

**Comment by melissahoughton** [comment]
Thanks Kevin, can you confirm, are your meetups still virtual? I am located in Melbourne.

**Comment by iamkevinv** [comment]
Yes we're still virtual for now - presenters collaborate over zoom and then that session is streamed to zoom :-)

**Comment by iamkevinv** [comment]
Hi @melissahoughton - Can i confirm you'll be presenting at our virtual event, monday 19th April 6:30pm onward? I'd like to send out the event list to all 👍

**Comment by melissahoughton** [comment]
Yes that will be great, thanks

**Comment by melissahoughton** [comment]
Hi, @iamkevinv , do you have the zoom details for me for tonight?

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.
Topic: BrisJS Meetup

Join Zoom Meeting
https://us02web.zoom.us/j/85471587750

Meeting ID: 854 7158 7750
Find your local number: https://us02web.zoom.us/u/kd6FHBQfCa

**Comment by iamkevinv** [comment]
Thanks again! I hope it was fun! Please feel free to leave any links you like here, and I'm completely open to any further ideas and feedback you may have! Hope to see more great submissions from you!
