### ISSUE TITLE
Long talk: How to build a VSCode extension

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#430]
Talk time: 30-40 mins

Ever had a cool idea for a VSCode extension? 

Creating and publishing VSCode extensions is easier than you might think and they coded in JavaScript or TypeScript!

In this talk we'll look at the structure of Taskboard VSCode extension. We'll learn how to interface with VSCode through its API and all the important pieces of the puzzle that are required for an extension to work.

I'd like to do this talk later in 2021, because I want to do the microservices talk first: #425

**Comment by iamkevinv** [comment]
@ashleydavis - Any chance that this talk could be presented for the next BrisJS Nov 7??

**Comment by ashleydavis** [comment]
Sorry mate, kind of maxed out at the moment. Hope to do a big talk next year, although maybe not this one.

**Comment by iamkevinv** [comment]
Hi @ashleydavis - is this talk something you still want to keep on the roster? Maybe Nov?

**Comment by ashleydavis** [comment]
> Hi @ashleydavis - is this talk something you still want to keep on the roster? Maybe Nov?

I probably won't do this anytime soon. It's been years now since I worked on an extension! If I start working on any of the extensions again I'll put it a new talk. Feel free to close this one.
