### ISSUE TITLE
Desygner is looking for a Senior Frontend Developer

### ISSUE THREAD

**Issue by sayanb** [BrisJS/meetups#431]
**About Us**

Desygner is one of the leading tech companies now in Australia’s top 10 startups to work for (and top 500 in the world). Desygner is focused on building solutions that make design, branding, and marketing better through automation, AI, and adaptive technologies without needing a designer. There is no better opportunity to be part of something big than this and now is the chance to join our small team of under 50 in the Gold Coast before we explode!

We believe that anyone should have a powerful brand and opportunities, regardless of their marketing budget. Our users’ success is our success and we’re on a mission to deliver solutions that make marketing better and easier for them. 

- B2C and B2B solutions
- Global audience with over 15 million users (20,000+ new signups every day)
- 15,000 corporate clients with many more industry leaders coming onboard
- Leading technology in graphic design, on-brand content creation, PDF editing, and intelligent design automation

**Organisation Cultural Fit**

We are looking for professionals who seek constant improvement, and are willing to take responsibility and celebrate the wins.

- Passion for true bootstrapped startups and big-picture development
- Takes ownership and finds solutions with our founders
- Able to think outside of the box and solve problems

**Senior Frontend Developer**

 Do bad interfaces stress you out? Are you a fan of aesthetically pleasing and user-friendly products? Then we’d love to hear from you! Desygner is looking for an exceptional front-end developer to join our growing team.

**The Role**

 As a Front-End Developer at Desygner you will be working closely with Desygner’s directors and particularly the Chief Technology Officer & VP of Engineering to organise, manage and deliver technical solutions. You will play an active role in the development of our product and assist Desygner to develop to its full potential.

**Key Responsibilities:**

- Mockup-to-web duties, working closely with the design and marketing team;
- Maintaining and enhancing the core editor code;
- Constant improvement in the way our users interact with the platform, focusing on UX, redesign, and flow;
- Assist us with internal practices to standardise frontend development.

**Required Skills:**

- HTML (HTML5 and one or more of the following - Twig, Handlebars, Jade);
- CSS (CSS3, Stylus);
- JavaScript (JavaScript 5, JavaScript ES6 + Babel);
- Deep API server-to-client understanding;
- Template engines, node, modern frameworks, ES6, transpilers, building tools;

**Desired Skills:**

- Familiarity with SVG-Edit or other SVG JavaScript Libraries;
- PHP & Java familiarity understanding;
- Basic PHP or MVC backend frameworks experience;
- Basic AWS knowledge.

**Benefits & Perks** 

We nurture a creative, focused & fun environment where people look forward to coming to the office. Our team is diverse in both culture and talent which makes for a superbly unique work environment without politics and hierarchy.

- Work in the Gold Coast with views over the beaches and canals from your desk
- Multicultural small, yet dynamic team with direction and leadership clear
- Work on solutions used by millions of people every day
- Central office location in Gold Coast near best restaurants, beaches, and public transport.
- Opportunity to live a holiday lifestyle overlooking the sun and sea every morning
- Competitive compensation + equity option plans by seniority
- Flexible hours, so you will not be controlled by the clock! 
- Exciting career opportunities as an early team member
- Be respected and heard in a startup that is now smashing numbers
- Continuous learning, development, and support from founders and external training

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
