### ISSUE TITLE
Frontend Engineer @ Megaport

### ISSUE THREAD

**Issue by nathenstreet-megaport** [BrisJS/meetups#432]
**The Role**

Reporting to the Head of Software Development, this role will be a key contributor to our highest value web property - the Megaport Portal. Working with the existing engineering team to build the best user experience and simultaneously producing a high quality codebase and maintaining feature implementation goals.

**About Megaport**

Megaport has transformed the way IT gets connected. We're global leaders in Network as a Service (NaaS), changing the way businesses reach the cloud. We're also a leading partner to Amazon, Microsoft, Google, IBM, Oracle, NYSE, and many other leading technology companies. Megaport is a publicly traded company on the Australian Stock Exchange with a market cap exceeding $2 Billion. We’re a lean, high-achieving team made up of over 230 members globally. While the company is headquartered in Brisbane, Australia, employees are spread out across North America, Europe, and Asia-Pacific. Staff enjoy an environment that is collaborative, supportive, and fun.

**Our Team Culture**

Join a team of globally-positioned industry experts that lead by example. We do not compromise our values for commercial gain; we are all custodians of our culture, and the customer is at the centre of everything we do. Our employees are motivated, adaptable, persistent, hard-working, and dynamic. Our culture permeates everything we do and this, in turn with a global vision, forms a commitment to each other, our customers, and shareholders alike.

**What You'll Be Doing**

- Help build and maintain the Megaport Portal and other tools in Javascript, HTML5 and CSS3
- Work closely with, and incorporate feedback from PMs, designers and other engineers
- Proactively enhance our web platform
- Write client-side code for web-based applications, create fast, easy-to-use applications, and develop prototypes quickly

**What We Are Looking For**

- 2+ years of software development experience in client side web development
- Strong UX and design sensibilities, and a desire to sweat the small stuff
- Experience with Vue.js or other modern frameworks such as AngularJS or React
- Demonstrable experience consuming web services (REST, SOAP, OAuth etc)
- Experience developing responsive web applications that work across multiple devices
- Solid understanding of the full web technology stack (HTTP, WebSockets, cookies, asset loading / caching)
- Knowledge on cross-browser quirks and ways to mitigate them
- Strong written and verbal communication
- Experience using CSS dialects such as Stylus, SASS or LESS
- An agile mindset with the ability to work in a transparent and collaborative manner
- Experience and a working knowledge revision control systems, preferably Git

**What We Offer**

- Flexible working environments with the ability to do your job from anywhere
- Birthday Leave
- Generous study and training allowance + development opportunities
- Creative, fun, and contemporary workspaces
- Motivated team of industry experts and new talent
- Celebrated success with ‘Legend’ and ‘Kudos’ Awards
- Health and wellness program
- Opportunities for career growth and potential for global intra-company transfers for interested candidates

[Apply for this job](https://jobs.lever.co/megaport/c3d1a348-9297-42c3-99a5-e43f518b3909/apply)

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
