### ISSUE TITLE
Short talk: How to start your own open source project

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#433]
Talk time: 10-15 minutes

This a whirlwind tour of how to start your own open-source project.

We'll look at how to:
- Start a Node.js project
- How to get it on GitHub
- How to publish it on npm

We'll look at this through the lens of my latest small open source project: Figit

I've literally just started Figit this week and you'll be able to watch as I make the code open source and publish it on npm.

You'll have to wait for the meetup if you want to learn what Figit does!

**Comment by iamkevinv** [comment]
Works for me :) Have lots of time in the night, so lets make it 15min ;-)

**Comment by ashleydavis** [comment]
Awesome

**Comment by ashleydavis** [comment]
Note that I've updated the name of the library in the description (in case you copied the text already).

**Comment by ashleydavis** [comment]
I can probably stretch this to 20 minutes if you like?

**Comment by iamkevinv** [comment]
> Note that I've updated the name of the library in the description (in case you copied the text already).

Updated the meetup page text.

Yep we have all the time in the world, so 20min is great :) Really appreciate all the support as always

**Comment by ashleydavis** [comment]
I'm writing up the slides and I'm starting to think with slides + demo this could go for 30 mins ;)

**Comment by iamkevinv** [comment]
Haha sounds good

**Comment by iamkevinv** [comment]
Details for tomorrow's zoom
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetup
Time: Mar 8, 2021 06:15 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/83905657880

Meeting ID: 839 0565 7880

Dial by your location
Find your local number: https://us02web.zoom.us/u/kdIobpGwWL

**Comment by iamkevinv** [comment]
It says 6:15 for prep time, but the event is from 6:30pm

**Comment by ashleydavis** [comment]
I've uploaded my slides:

https://www.slideshare.net/AshleyDavis33/how-to-start-your-own-open-source-project-244028940

Here's some links to Figit, the project that I open sourced during the talk:
https://github.com/ashleydavis/figit
https://www.npmjs.com/package/figit

**Comment by iamkevinv** [comment]
Like clockwork! Thanks again @ashleydavis :D
