### ISSUE TITLE
Senior Frontend Developer @ CSIRO

### ISSUE THREAD

**Issue by roger-butler** [BrisJS/meetups#436]
• Are you a cloud software developer who wants to turn science into web products?
• Translate world-class science into software products for economic, environmental and societal impact
• Join CSIRO's Data61 - Australia's premier data innovation organisation

We are currently offering two opportunities for Front End Developers to join our highly motivated, multidisciplinary team at Data61. You will work alongside scientists, engineers, UX designers and product managers who are developing impactful technology in a range of domains. Specifically, you will design, develop, deploy and maintain web applications which are prototypes and products that make economic, environmental and societal impact. Delivering unique opportunities to facilitate the digital delivery of CSIRO’s research and technology, the role will suit highly collaborative individuals who genuinely enjoy the development of web front ends.

As the role is offered across two salary ranges, to be eligible for the higher range, in addition to the requirements outlined below, you must be able to demonstrate:
1. Deep expertise developing and deploying cloud software.
2. Experience mentoring junior software developers.
3. A minimum of 5 years of commercial software development experience.

In this role you will:
· Design, develop, deploy and maintain web applications (typically TypeScript and ReactJS)
· Work collaboratively to ensure that project goals and CSIRO’s goals are achieved.
· Make optimal use of appropriate software development tools and processes.
· Contribute to CSIRO’s engineering discipline by promoting the effective use of software development tools, practices and culture.
· Apply specialist expertise to identify and solve complex problems across a diverse range of projects and disciplines.

Location: Dutton Park (Brisbane) Queensland (Canberra and Sydney may be considered)
Salary: AU$98k to AU$106k per annum, plus up to 15.4% superannuation (Salary level 5)
             AU$113k to AU$132k per annum, plus up to 15.4% superannuation (Salary level 6)
Tenure: Indefinite

Reference: 72824

To be considered you will hold relevant diploma/bachelor’s degree or have equivalent work experience in software engineering. You will also have:
· Expertise developing and deploying cloud software
· Expertise in web front end development, including HTML, CSS, JavaScript and single-page app frameworks.
· Experience with contemporary software development tools and practises: version control, unit testing, automated testing, issue tracking.
· A minimum of 3 years of commercial software development experience.
· Good judgement, strong problem-solving abilities, and sound interpersonal skills.

The successful candidate will enjoy developing web front ends and may also have expertise in these technologies:
1. Varied programming language paradigms, including object oriented and functional
2. Cloud DevOps and container technologies (we deploy mostly to AWS ECS)
3. Design and use of REST APIs
4. Reactive programming
5. Relational, NoSQL, time series and spatial databases
6. Message queues (Kafka, Kinesis, MQTT, RabbitMQ)
7. Databases (SQL and NoSQL, time-series, administration, performance tuning, schema design and modelling, stored procedures, triggers, clustering, query design and evaluation)
8. Continuous integration/continuous deployment (Jenkins, Gitlab, Buildkite)
9. Agile project management

Eligibility
The successful applicant will be required to obtain and provide a National Police Clearance or equivalent.

Flexible Working Arrangements
We work flexibly at CSIRO, offering a range of options for how, when and where you work. Talk to us about how this role could be flexible for you. Balance

CSIRO’s Commitment to Diversity
We’re working hard to recruit diverse people and ensure all our people feel supported to do their best work and empowered to let their ideas flourish. Diversity and Inclusion Strategy

We are committed to the safety and wellbeing of all children and young people.

About CSIRO At CSIRO, Australia’s national science agency, we solve the greatest challenges through innovative science and technology.

Join us and start creating tomorrow today!

How to Apply

To apply online, please provide a CV and cover letter outlining your motivations for applying and your suitability for the role, paying particular attention to the requirements outlined in the Position Details.
https://jobs.csiro.au/job/Brisbane%2C-QLD-Senior-Front-End-Developers-%28two-positions-available%29/724695900/

Applications Close
Thursday 8 April, 2021 (11pm AEST)
We reserve the right to withdraw this ad prior to the closing date.

**Comment by iamkevinv** [comment]
OK to close? Past it's date now. Re-open if it's extended :D thanks!

**Comment by roger-butler** [comment]
Thanks Kevin. We have some good candidates from the ad.
