### ISSUE TITLE
Short talk: Bundling a web page with Parcel!

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#437]
Talk time: 10-15 minutes

So you need to bundle your web page?

What are you going to use?

Probably Webpack right? Except the setup and configuration for Webpack is rather daunting.

Well look no further than Parcel. It's a powerful and flexible bundler, except it requires almost zero-configuration. 

Parcel supports the most common web technology out of the box and when it doesn't, well there's usually a plugin for that.

I recently ported a landing page to Parcel from Jekyll. First I tried Next.js... but it caused some issues, then I considered Webpack which I've used before, but after playing with Parcel for only a few minutes I couldn't turn back. It just was just so seamless and streamlined. 

In this talk I'll show you what Parcel can do and how I used it to bring up the new version of my landing page.

**Comment by ukuhnhardt** [comment]
👍
