### ISSUE TITLE
Experienced react developer @ Widget Works - remote

### ISSUE THREAD

**Issue by mrthan** [BrisJS/meetups#438]
## Experienced frontend developer (Typescript/Node) - remote

**About us**
------------

Widget Works creates and delivers financial calculators for banks, fintechs and broking clients. We started primarily as lead generation tools, but with our advanced mortgage pricing support we perform a growing range of loan servicing and prequalification functions.

We’re remote only (work from home) and give you the flexibility to produce your best work while living life.

Our clients include some of the largest banks in Australia, New Zealand and USA. We value good relationships with our customers so we care deeply about producing high-quality products to meet their needs.

**Tasks and responsibilities**
------------------------------

*   Architect and engineer accessible, performant and resilient front end applications that deliver mortgage & financial product information, education, analytics & lead generation
*   Mid-Senior role allows you freedom to contribute to architectural design
*   Develop and improve our stack, testing and internal devops tools
*   Document and describe your work for technical and end users

You're comfortable architecting and structuring applications, managing data and state transformations. Ideally you have interest or familiarity with:

*   Functional programming and data transformation: io-ts/fp-ts, Immerjs
*   State management (e.g. Redux, Mobx, Vuex)
*   Dependency injection

**Qualifications and experience**
---------------------------------

*   TypeScript and NodeJS
*   Modern front-end framework experience (e.g. React, Vue, Angular)
*   3-5+ years experience delivering, supporting and maintaining software projects
*   Cross-browser and mobile web development experience
*   You can create accessible web interfaces to WCAG AA standard, supporting multiple assistive technologies
*   Automated testing (e.g. Jest, Karma, Browserstack, etc)
*   Comfortable using git and workflow with multiple developers, branches, rebasing & pull requests

**Nice-to-have skills and experience**
--------------------------------------

Even if you don't tick all the boxes above, if you have experience in these areas we'd love to hear from you.

*   AngularJS (yes, the old one)
*   Our current codebase is AngularJS, transitioning to React
*   HTML/CSS experience working with CSS or preprocessors (SASS, LESS, PostCSS)
*   Serverless/functions e.g. AWS Lambda, Azure Functions, Google Cloud Functions, Firebase
*   CI/CD experience (Github Actions/Bitbucket Pipelines/CircleCI, etc)
*   Financial services/financial mathematics exposure or experience (or willingness to learn this life skill!)
*   You like a good spreadsheet and the power of MS Excel

**What we look for**
--------------------

*   Flexibility - you'll be working in lots of different areas of our products
*   Attention to detail - Likes high quality software, hates bugs!
*   UX appreciation - you may not design the experience, but you always put the user first
*   You want to hone and improve your craft (even if you're not a React ninja, you want to use your skills and experience to get there)
*   We always strive to do better - you're willing to improve codebase, not just put up with what's there
*   You can accept and provide clear feedback on people, process and technology
*   You understand customer priorities and tailor your focus accordingly

**Benefits**
------------

* Full time role $100,000 - $139,999 + super
* Friendly, fun and flexible workplace
* Allowance to help set up your home office and workstation

**Remote details**
------------------

Preferred Timezone: +/- 2 hours of (GMT+10:00) Eastern Time - Brisbane

**Interested?**
---------------

* Send us your CV and a 2 page cover letter highlighting 2-3 points from each of the main sections above.
* Given the nature of our clients, the successful applicant must live in Australia and complete a Police background check.
* We will only accept direct applications, no third party or recruiters thanks.
* Contact [Nathaniel](https://www.linkedin.com/in/nathaniel-fitzgerald-hood-2b226311/)

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
