### ISSUE TITLE
Freelance Senior Front-end Engineer @ SecureStack (Gold Coast office + remote friendly within Aus)

### ISSUE THREAD

**Issue by bensullivan** [BrisJS/meetups#439]
### Hello 👋🏻.

[SecureStack](https://securestack.com) is building a new front end for [bloodhound](https://bloodhound.securestack.com) to help developers continuously visualise security risk insights from aggregated vulnerabilities across the entire product offering (public attack surfaces, source code and cloud stacks).

### The Engagement

- Establish the front-end architecture and strategy for implementation
- Greenfield, front-end component development
- 2-3 months, full-time, preferably with immediate start
- 5 days a week, Monday to Friday working at our office on Gold Coast or remotely
- We are open to flexible hours and remote working for the right person (preferred timezone +/- 2 hours of GMT+10:00)

### Type of Engineer We're Looking For

You value understanding the fundamentals of HTML5, CSS3 and JavaScript runtimes over the different frameworks that operate within modern browsers. 

The design principles you subscribe to are based on strong opinions that are weakly held, garnered from real world experience and professional development.  

You have a passion for technology, simplicity, pragmatism, quality, lean code, feedback loops, problem-solving, listening, asking questions and continuous learning.  

Your communication skills aren’t limited to technical discourse – you can write and present your ideas clearly to a cross-functional team and analyse business and technical requirements with ease.  

You believe in the value of a team being greater than the sum of its parts and as such you are willing to be involved in every step of the delivery of software to ensure the success of a product. 

You are:
- An experienced, senior front-end software engineer
- All about customer experience
- Thirsty for interesting problems to solve and fun people to work with
- An advocate of the functional programming paradigm

You know how to use:
- Version control
- HTML5, CSS3
- TypeScript
- Automated testing

You should be familiar with:
- Dynamic, data visualisation components (isometric diagramming and WebGL would be really handy!!)
- UX design principles and best practices ... with a hint of cyberpunk ...
- UX analytics engines
- Browser performance tuning

You should not be:
- A front-end engineering silo
- Disrespectful
- A rambler (the talking variety)

You should also be:
- Assertive
- Organised
- A people person
- Chill, but not too chill

You’re partial to:
- Pair-programming
- Drawing on whiteboards
- Giving and receiving constructive feedback
- Office/IM banter and intermittent, raucous laughter

### Interested?

Contact [Paul](https://www.linkedin.com/in/mccartypaul/) or [Ben](https://www.linkedin.com/in/bensullivandevops/).

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
