### ISSUE TITLE
BangleJS - A watch that runs JavaScript

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#441]
~~Presenter Name: Josh Wulf
Talk title: Google ZX - replace BASH with JS
Talk length: 10 min
Talk description :Lightning talk on Google ZX - write BASH scripts in JavaScript with top-level await. 
Available month(s): May / June
Optional: list any preferred social accounts so we can promote you and your talk: twitter.com/sitapati~~

Presenter Name: Josh Wulf
Talk title: BangleJS - A watch that runs JavaScript
Talk length: 10 min
Talk description :Lightning talk on BangleJS, A watch that runs JavaScript, like all watches should. 
Available month(s): JULY
Optional: list any preferred social accounts so we can promote you and your talk: twitter.com/sitapati

**Comment by iamkevinv** [comment]
Hey mate! Would love to have you present this lightning talk if you're keen for our June event in a few weeks? Can i confirm you?

**Comment by jwulf** [comment]
Not if it is June 7 - it's Queens Birthday weekend here. If it's the week after, then yes. Otherwise, I'll have to do July.

**Comment by iamkevinv** [comment]
July it is mate :) Thanks

**Comment by iamkevinv** [comment]
You confirmed for this coming monday @jwulf ?

**Comment by iamkevinv** [comment]
@jwulf - It's been moved to July 12 - can i count on your talk for that livestream? Thanks!

**Comment by jwulf** [comment]
Yes, but can I talk about something else? I just got a BangleJS - a watch that runs JavaScript, as all good watches should. I'd like to talk about that, if no-one else has.

**Comment by iamkevinv** [comment]
Yes you can talk about BangleJS - any details appreciated so i can update the post

**Comment by iamkevinv** [comment]
Please find the following details for connecting to our zoom for the BrisJS livestream:

Topic: BrisJS Meetup
Time: Jul 12, 2021 06:15 PM (for a 6:30pm Start) - Brisbane AEST Time

Join Zoom Meeting
https://us02web.zoom.us/j/85471587750

Dial by your location
Meeting ID: 854 7158 7750
Find your local number: https://us02web.zoom.us/u/kd6FHBQfCa
