### ISSUE TITLE
Talk Proposal: Reactive Programming in React with Rx.js

### ISSUE THREAD

**Issue by mattvalleycodes** [BrisJS/meetups#442]
**Presenter Name:** Matt Valley
**Talk title:** Reactive Programming in React with Rx.js
**Talk length:** 30 mins
**Talk description:**  I'm the founder of a tech startup called Testfully. To build the customer-facing dashboard for  Testfully, I leveraged the Reactive Programming paradigm and built the app using React & Rx.js. 
While doing the R&D for this project, I noticed a lack of information (case studies, tutorials, sample projects) about using Rx.js with React, so I decided to propose a talk on this topic. In this talk, I will go through Reactive Programming as a paradigm, Observer Pattern, Reactive Extension and Rx.js, followed by how I used them in my project.  There will be some code examples to help the audience see things in action. 
**Available month(s):** June - July 2021
**Optional:** Twitter handle: @mattvalleycodes

**Comment by iamkevinv** [comment]
Can i confirm you for June 7th @mattvalleycodes ?

**Comment by iamkevinv** [comment]
Matt's slides are here: https://speakerdeck.com/mattvalleycodes/reactive-programming-in-react-with-rxjs

**Comment by iamkevinv** [comment]
Thanks again @mattvalleycodes! Hope others can follow your lead and pop in their talk submissions soon!
