### ISSUE TITLE
Short talk: Introduction to Vue.js

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#443]
Duration: 10-15 minutes

Speaker:  Torsten Schmidt, Frontend Lead at Bridj Technology

Abstract: 
Get a short introduction to Vue.js and discover why developers love it so much.

Torsten will convince you of just how awesome is Vue.js or die trying (only kidding, no ones going to die).

**Comment by iamkevinv** [comment]
Thanks @ashleydavis  - does Torsten have a github account we can assign him to this issue?
What months is Torsten avail?

**Comment by ashleydavis** [comment]
Hey @1mak, this is for your vuejs talk. The organiser has some questions above.

**Comment by 1mak** [comment]
Hey guys. I am available throughout the year I believe. There's always a little bit of churn and overtime but I will try to manage my time around that to get more Brisbane folks onto the VueJS train. :)

**Comment by iamkevinv** [comment]
Hi @1mak - How about this coming monday? for the July Talks?

**Comment by iamkevinv** [comment]
@1mak (cc @ashleydavis) - It's been moved to July 12 - can i count on your talk for that livestream? Thanks! Please confirm

**Comment by 1mak** [comment]
Yes, I am looking forward to it! :)

**Comment by iamkevinv** [comment]
Please find the following details for connecting to our zoom for the BrisJS livestream:

Topic: BrisJS Meetup
Time: Jul 12, 2021 06:15 PM (for a 6:30pm Start) - Brisbane AEST Time

Join Zoom Meeting
https://us02web.zoom.us/j/85471587750

Dial by your location
Meeting ID: 854 7158 7750
Find your local number: https://us02web.zoom.us/u/kd6FHBQfCa

**Comment by 1mak** [comment]
Hey @iamkevinv:

I would love to do a (series of) follow-up talks about VueJS. For my next presentation, I would like to present how to scaffold a module/component structure for enterprise-size applications and how to get the most out of reusable/shared components, the pitfalls, and how to overcome them.

**Comment by iamkevinv** [comment]
Hey @1mak - If you're keen to do this follow up... would you like it confirmed for this upcoming 9 Aug?

**Comment by iamkevinv** [comment]
I'll make a new issue, since it looks like this will require more scheduling :)
