### ISSUE TITLE
JavaScript developer job opportunity at Esri Australia.

### ISSUE THREAD

**Issue by LHoBiz** [BrisJS/meetups#444]
Hi JavaScripters. There's a job going at Esri Australia. 

LinkedIn
https://www.linkedin.com/jobs/view/2590923875

Seek
https://www.seek.com.au/job/52560823?type=promoted#searchRequestToken=0ef09732-d5b9-4976-b227-7e5c1f59b5b2

The job title is Consultant Managed Services but JavaScript development is a primary part of this role. So yeh they're chasing someone talented with JS. 

My description of the role isn't official so please refer to the job ad itself. Feel free to mention that I (Luke) hooked you up :-).

**Comment by iamkevinv** [comment]
Much appreciated, lets get the word out :)

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
