### ISSUE TITLE
ABC News - Front-end Developer

### ISSUE THREAD

**Issue by louisstow** [BrisJS/meetups#445]
Bring your skills to a high performing team that powers Australia's number 1 News website – ABC News. News Web is a cross functional team of developers, designers, content and product people, collaborating to build the platform that impacts  **millions of Australians**. 

Each day, Australians rely on ABC News, as an online service to keep informed and updated. We are working with cutting edge technologies such as Node, React, Webpack – ensuring we keep at the forefront of industry trends to deliver quality at scale.

https://www.seek.com.au/job/52657476
https://careers.abc.net.au/caw/en/job/501734/developer

**Comment by iamkevinv** [comment]
Thanks for submitting! Have tagged so it appears on brisjs.org

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
