### ISSUE TITLE
React & Web3 for Blockchain - DeveloperAlly [Alison Haire - IBM Developer Advocate]

### ISSUE THREAD

**Issue by DeveloperAlly** [BrisJS/meetups#446]
Presenter Name: Alison Haire (DeveloperAlly)
Talk title: Blockparty - Using React with Solidity Blockchain Contracts
Talk length: 30 mins
Talk description: I'll walk you through connecting to the blockchain using the Web3 javascript library and React with Next.js
Available month(s): July
Optional: twitter @developerally, linked-in: ally-haire

**Comment by iamkevinv** [comment]
Thanks again @DeveloperAlly - Can i confirm you for the Monday talks? Thanks.

**Comment by iamkevinv** [comment]
Assuming yes! 🎉

**Comment by DeveloperAlly** [comment]
Hi @iamkevinv Yes sorry can confirm!
Do you mind if I change my talk though? I updated the details above!

I've been playing around a lot with solidity contracts and blockchain so thought I might show people how to connect to blockchain solidity contracts from React (or any javascript framework) using the web3 javascript library if thats ok with you?

**Comment by DeveloperAlly** [comment]
Sorry for the late notice!!!!

**Comment by iamkevinv** [comment]
Please find the following details for connecting to our zoom for the BrisJS livestream:

Topic: BrisJS Meetup
Time: Jul 12, 2021 06:15 PM (for a 6:30pm Start) - Brisbane AEST Time

Join Zoom Meeting
https://us02web.zoom.us/j/85471587750

Dial by your location
Meeting ID: 854 7158 7750
Find your local number: https://us02web.zoom.us/u/kd6FHBQfCa

**Comment by DeveloperAlly** [comment]
Github: https://github.com/DeveloperAlly/brisjs

**Comment by iamkevinv** [comment]
Thanks again @DeveloperAlly! If you want to present your other talk idea, please pop an issue here and i'll fast track it in! We're keen for more talks on 9 Aug.
