### ISSUE TITLE
RapidAIM is hiring a new lead software developer/engineer

### ISSUE THREAD

**Issue by ellasapiatzer** [BrisJS/meetups#447]
We are a Brisbane-based Agtech startup with a vision to transform agriculture to a low chemical input system. We’re on a mission to take the guesswork out of pest management for sustainable food production. Our precision pest management solution drives efficient crop protection. The information package delivered to growers on a mobile app is enabled by our unique insect sensing technology integrated into a comprehensive IoT solution. 

We have a small, highly collaborative team and we’re looking for people as passionate as we are to grow our business and make an impact on a global scale. We are one team, and we take pride in our diversity and culture of inclusion. We started commercial sales in January 2020, and our product is in the hands of more than 170 end users with more than 500 sensors deployed from northern QLD to southern VIC. We have a deep understanding of end users, and the pain points associated with insect pest management. We have a high quality and differentiated product that is ready to scale. 

For more information on the role check out the job ad in seek.

Seek link:
https://www.seek.com.au/job/52759786?type=standout#searchRequestToken=2049bf75-cc7c-4bcf-81a6-af067b218dee

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
