### ISSUE TITLE
Medium talk: Sharing code between TypeScript projects

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#448]
Talk length: 15-20 mins

Abstract:
We all know that we can share TypeScript code through npm, but did you know that there's a more direct way to share code between your TypeScript projects?

In this talk we will explore using TypeScript "project references" to created shared code libraries. It's a great approach that works well for both mono-repos and meta-repos

We'll look at some specific examples. How to share a code library into a Node.js application, then sharing code between microservices or Docker images and even how to share code between the frontend and the backend.

@iamkevinv I can do this talk for 9th August if that's ok?

**Comment by iamkevinv** [comment]
Yes please!

**Comment by ashleydavis** [comment]
Some resources:

Example code: https://github.com/ashleydavis/sharing-typescript-code-libraries
TypeScript project references documentation: https://www.typescriptlang.org/docs/handbook/project-references.html
ts-project-bundler (bundles compiled TypeScript code): https://www.npmjs.com/package/ts-project-bundle

**Comment by iamkevinv** [comment]
Thanks mate!
