### ISSUE TITLE
Vue.JS structures for enterprise-scale

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#449]
Pitched by @1mak - Torsten

> I would love to do a (series of) follow-up talks about VueJS. For my next presentation, I would like to present how to scaffold a module/component structure for enterprise-size applications and how to get the most out of reusable/shared components, the pitfalls, and how to overcome them.

These sound like 20 min slots and i've created this issue to handle scheduling.

**Comment by iamkevinv** [comment]
@1mak - i've moved the suggestion here on it's own ticket. Can you let me know when you can be available? I can still squeeze it in during 9 Aug, but that window will close fast as i'm trying to announce by tomorrow if possible.

**Comment by 1mak** [comment]
I am on holidays until mid August. We have to reschedule for September.

**Comment by iamkevinv** [comment]
No worries mate! Was worried you were missing the messages and would miss out! All good - see you in sept!

**Comment by iamkevinv** [comment]
Hi @1mak - can you confirm you're speaking on monday? Thanks

**Comment by iamkevinv** [comment]
@1mak - can't message you on twitter and no reply here so i'm going to push this another month until i can hear back.

**Comment by iamkevinv** [comment]
Hi @1mak - as we haven't been able to line up something at this stage, i'll close this issue until you are available again. Thanks again for your first presentation on Vue JS.
