### ISSUE TITLE
DeveloperSteve - Talking of talks - Meetup/conference speaking

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#450]
> actually how about i come do one on meetup/conference speaking
- @DeveloperSteve

For August 2021 meetup

**Comment by developersteve** [comment]
Ok here’s a blurb….

Talking of talks 

Ever wanted to give a talk on something but didn’t know how to go about it? This meta session is taking a look all the things you need to know about putting together a speaking session. From camera positioning for virtual events, talk story flow and topics. We are even going to look at the scary topic of ……. demo failure *gasp* (that never happens right?).

**Comment by iamkevinv** [comment]
Thanks mate, if you have any resources to share please link them here :)
