### ISSUE TITLE
[DeveloperAlly] Getting Mobile - an intro to react-native

### ISSUE THREAD

**Issue by DeveloperAlly** [BrisJS/meetups#451]
So you've got down some javascript or web language basics - and now you want to move to mobile - well this is the intro for you!
I'll show you the basics of react-native and how you can get up and running with a mobile app in 10(ish) minutes!

**Comment by iamkevinv** [comment]
@DeveloperAlly - Included in the Monday Aug 9 lineup... tonight!

**Comment by iamkevinv** [comment]
Thanks again! If you have any slides or resources to share, feel free to link them here!
