### ISSUE TITLE
[DeveloperAlly] Building DApps on Mobile (future long talk)

### ISSUE THREAD

**Issue by DeveloperAlly** [BrisJS/meetups#452]
More details TBA

**Comment by iamkevinv** [comment]
Thanks :)

**Comment by iamkevinv** [comment]
@DeveloperAlly - are you doing this one monday or are we targeting October?

**Comment by DeveloperAlly** [comment]
Let's target October sorry! Haven't got anything prepared for Monday

**Comment by iamkevinv** [comment]
i think as we're so late and i don't have details, lets actively prep for next month and get everything squared up.
That way we at least have one guaranteed presentation ready for next month too

**Comment by iamkevinv** [comment]
Hi @DeveloperAlly - as we haven't been able to line up something at this stage and get talk details, i'll close this issue until you are available again. Please re-open or submit a new issue when you're available and we can schedule it. Thanks again for your previous presentations 👍
