### ISSUE TITLE
Fully remote part time and senior front-end roles (React/Flutter) @ Maxwell Plus

### ISSUE THREAD

**Issue by lleewwiiss** [BrisJS/meetups#456]
Maxwell plus is hiring:
-  Part-time fully remote front end intern https://www.maxwellplus.com/careers/junior-frontend-developer-flutter-part-time 
- Full-time fully remote Senior front end developer https://www.maxwellplus.com/careers/senior-frontend-engineer

We are a small Brisbane based medical start-up trying to make deaths from prostate cancer a thing of the past. Any questions don't hesitate to reach out. Experience with Flutter is ideal but not an essential requirement.

There are some python back end roles available as well on our career page https://www.maxwellplus.com/careers

**Comment by iamkevinv** [comment]
Hey folks, i'm closing all job ads for the new year. Please re-open or resubmit if you have ongoing hiring to advertise :)
