### ISSUE TITLE
Displaying Data From DataTables J.S In ASP.NET Core 

### ISSUE THREAD

**Issue by LayersOfAbstraction** [BrisJS/meetups#459]
Hi I had an idea I was thinking of implementing for a talk. It would be how to use the open source DataTables.js Editor Server side library in ASP.NET MV5 using an SQL Server Database. I could use my  blog post I made for it that I can follow on my site with. Let me know if you are interested, thanks.

**Comment by iamkevinv** [comment]
Hi @LayersOfAbstraction - I think this could work. Obviously we are probably most keen on the JS part being a JS (but of course we do a wide range of everything web too in the process). I've seen this open and close several times - are you still keen?

**Comment by LayersOfAbstraction** [comment]
Yes @iamkevinv  I am interested. I was just trying to find out how to add labels and couldn't do that. I realize now that's for people who have write access to your repo, lol. So I have an online blog that I can use as a cheat sheet on one side of the screen and open VS Code on the other screen and show the code run from there and demo the talk which should take 30 to 40 minutes. It would be my first talk but I am hungry for the challenge. Let me know if there are any articles I should look at before I do the talk if needed. Thanks, Kev.

**Comment by iamkevinv** [comment]
All good! I'll consolidate into the new GH issue and apply the right labels. Appreciate the info 👍
Normal talk times are about 20min each, and we allow some question answering time at the end.Does that work?

**Comment by LayersOfAbstraction** [comment]
> Normal talk times are about 20min each, and we allow some question-answering time in the end. Does that work?

That should be fine. I will time myself to see how fast I can do it all myself and I am too slow to do it I will put the sample app for the talk partially together at least a week before the talk and back it up locally. Thanks. Yes I can answer a Q&A though some of the questions may be too complex for me to answer but I will do my best, Thanks.
