### ISSUE TITLE
Displaying Data From DataTables J.S In ASP.NET Core 

### ISSUE THREAD

**Issue by LayersOfAbstraction** [BrisJS/meetups#460]
Presenter Name: Jordan Nash
Talk title: Displaying Data From DataTables J.S In ASP.NET 5 MVC
Talk length: 30-40 minutes
Talk description: It would be how to use the open-source DataTables.js Editor Server-side library in ASP.NET MVC 5 with an SQL Server Database. 
Available month(s): Anytime. Just need at least 2 weeks' notice.

LinkedIn: https://www.linkedin.com/in/jordan-nash-87b042173/
Github Pages Website: https://consolecommando.net/

**Comment by iamkevinv** [comment]
Hey @LayersOfAbstraction - still keen on this one potentially for our dec 6 event?

**Comment by LayersOfAbstraction** [comment]
Yes I am excited to do this talk. But I realize to make the presentation more useful I will have to make a git branch for migrating my application to the latest .NET 6 framework as .NET 5 is going out of support early next year. I will also have to migrate the accompanying blog to go with it to the latest framework so as to refer to it for talk. On it now!

Also look I've been taking notes from friends who are in the programming biz who have done tech talks. And watched a few videos of previous BrisJS talks. I would like to ask would me using at least 2 monitors make the presentation run smoother because if so I was going to buy a new 3 monitor stand and perhaps have at least 1 monitor for now. I already use 2 monitors in my current customer service job. I was thinking do your previous speakers find it easier with two monitors for talks?

**Comment by LayersOfAbstraction** [comment]
Also if you have any links you saved for newcomers that they should look at let me know. Already saw tips on your event page, thanks. Podcasts I researched for doing tech conference/meetups were here but they look like they are more suited to pre-COVID talks.
[How To Give An Amazing Conference Talk - Episode 20](https://www.selftaughtornot.com/episodes/how-to-give-an-amazing-conference-talk)
[How to get into Speaking At Conferences](https://dev.to/syntax/how-to-get-into-speaking-at-conferences)

**Comment by iamkevinv** [comment]
Sorry for the lack of comms, it's been so busy!
I think since zoom sharing is either per-monitor or per-window sharing, it's not too tied to the monitor setup. It's mostly what you feel most comfortable with. I think sometimes people with 2 monitors have speaker notes to the side and that helps, but your milage will vary :)

**Comment by iamkevinv** [comment]
Actually it would be good to build up some speaking tips for the newcomers... i'll see what i can dig up over the holidays :) 
Local usergroups and meetups are much more informal than a conference but they provide a good practice ground if you're looking to get into that regularly 👍

**Comment by iamkevinv** [comment]
@LayersOfAbstraction Zoom details for tonight's session:
Time: Dec 6, 2021 06:20 PM Brisbane for a 6:30pm start.
Join Zoom: https://us02web.zoom.us/j/85471587750
Meeting ID: 854 7158 7750

**Comment by LayersOfAbstraction** [comment]
> Actually it would be good to build up some speaking tips for the newcomers... I'll see what I can dig up over the holidays :) Local Usergroups and meetups are much more informal than a conference but they provide a good practice ground if you're looking to get into that regularly 👍

Hi @iamKevin I don't know if I have anything else that is JavaScript-related for the next talk yet. Was thinking rather than you going around the web to find links for this, you could just delegate the responsibility to us. 

i.e we could just fork your repo and add the links to your README file under a heading called:

### Technical talking links 
(Advise our talk is done remotely until COVID-19 rolls away.)
 
If you can advise that is acceptable then I can do a pull request and you can choose if you want to accept.
