### ISSUE TITLE
Medium talk: Live reload - What it is, why you need it and how to do it

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#463]
Talk time: 20 - 30 mins

Title: Live reload - What it is, why you need it and how to do it

Abstract:

Live reloading your code - getting near instant feedback while you are coding - is a fundamental part of maintaining a rapid pace of development.

In this talk we'll look at the best ways to implement automatic live reload across your tech stack for JavaScript, including:

- Live reloading code in the backend and frontend;
- Using "watch mode" for live reload of your automated tests;
- Automatically synchronizing code changes into a running Docker container and reloading it. 

There's simply no part of your development and testing process that can't be improved by automatically reloading so you can easily test your code changes.

Join software craftsman and author Ashley Davis for a tour and demonstration of configuring live reload across your stack.

**Comment by ashleydavis** [comment]
I'm keen to do this talk in March or April if you can fit me in.

**Comment by iamkevinv** [comment]
March or april?! Long time from now but very happy to take the talk :)

**Comment by ashleydavis** [comment]
@iamkevinv since I've prepared this talk I've realised its going to run to about 30 mins.

I can probably cut it back if that's too long.

**Comment by iamkevinv** [comment]
@ashleydavis - Can i confirm you for the 4th March Meetup? I'll get the writeup happening.

**Comment by ashleydavis** [comment]
Do you mean the 7th march? The 4th is a Friday.

**Comment by iamkevinv** [comment]
Whoops! Yes.

**Comment by ashleydavis** [comment]
Cool, I can do the 7th!

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetup March
Time: Mar 7, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by ashleydavis** [comment]
My slides are published: 
https://www.slideshare.net/AshleyDavis33/live-reload-across-the-stack-251303188

The code from my talk is available here: 
https://github.com/ashleydavis/live-reload-examples

**Comment by ashleydavis** [comment]
I've published the blog post related to this talk:
https://www.codecapers.com.au/live-reload-across-the-stack/
