### ISSUE TITLE
Short demo: How to turn any web page into a desktop application in 5 minutes

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#464]
Talk time: 5-10 minutes

Title: How to turn any web page into a desktop application in 5 minutes

Just a real quick demo of a fun tool I found called `nativefier` that can take any web page and package it in just moments into a stand-alone Electron application.

It's great for those important web pages that you sometimes lose among all the tabs/windows of your web browser! Put them in their own application so you can find them more easily.

**Comment by iamkevinv** [comment]
@ashleydavis - Are you interested in presenting this one for Feb 14th, or any of the other 30 topics you have open :) 👍  Thanks friend!

**Comment by ashleydavis** [comment]
I'd like to, but probably not on valentines day.

**Comment by iamkevinv** [comment]
OH FUDGE VALENTINES DAY **eeeeep**. Darn, not sure i can actually even move it again.

**Comment by iamkevinv** [comment]
If you're doing the 30min talk next month, we'll push this one out by one?

**Comment by ashleydavis** [comment]
Sounds good

**Comment by iamkevinv** [comment]
Hi @ashleydavis - Not sure if you're available for this month? i'm trying to get responses from all the other folks still and working out who will make this April lineup monday 11th. Can you let me know if you're keen for this one or if you can otherwise do May? thanks!

**Comment by ashleydavis** [comment]
I can do this talk on Monday night.

**Comment by iamkevinv** [comment]
Hi there! Please find the details to connect via zoom. Zoom does all the streaming to youtube for us. We'll connect 10 mins before and test out our connectivity, before muting and going live :) See you soon!

Topic: BrisJS Meetup
Time: Apr 11, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
Thanks again for jumping in!
