### ISSUE TITLE
lightning talk > Who wants to help contrib and get a free swag t-shirt?

### ISSUE THREAD

**Issue by developersteve** [BrisJS/meetups#467]
Talk title: Who wants to help contrib and get a free swag t-shirt?
Talk length: 10.34 min
Talk synopsis: Just wanted to come and chat a bit about a campaign we are running to help projects get contribs fixing detected vulnerabilities, and get a free shirt doing it > https://snyk.io/events/the-big-fix/
Available month(s): Well any but this ends on the 28th of Feb 
Optional: @developersteve #thebigfix

**Comment by iamkevinv** [comment]
Done! can i confirm for Feb 14?? We pushed it back a week since everyone's still kinda gearing into the year haha

**Comment by developersteve** [comment]
haha understandable, totally keen and will be there :D

**Comment by iamkevinv** [comment]
@developersteve - can i help amplify your 'The Big Fix' marketing through BrisJS socials?

**Comment by developersteve** [comment]
@iamkevinv yes please, that would be ace. Totally need to help keep projects safe and help give out T-Shirts :D 

Also tag @snyksec too so we can RT and fav

**Comment by iamkevinv** [comment]
Do you have a preferred tweet or the like you'd like me to quote-rt?

**Comment by developersteve** [comment]
Ah dont mind, something like this even (also heres a share banner if you want to use it).... 

"Help keep a community project vulnerability free with @snyksec #thebigfix, Scan, fix/patch/upgrade a vulnerability and get a free T-Shirt https://snyk.io/events/the-big-fix/"

<img width="1200" alt="Share Banner" src="https://user-images.githubusercontent.com/1458790/154189107-42312739-b0b3-4390-b622-cd2885180f8a.png">

**Comment by iamkevinv** [comment]
oooh that's really cool lookin - definitely!
