### ISSUE TITLE
High Performance MySQL

### ISSUE THREAD

**Issue by trycatchjames** [BrisJS/meetups#469]
Presenter Name: James Harvey
Talk title: High Performance MySQL
Talk length: Between 20 and 30 minutes with questions
Talk description: I dive into getting the maximum performance out of queries. Explain how indexing works under the hood and provide some tips and anti-patterns along the way.
Available month(s): Anytime
Optional: www.linkedin.com/in/james-harvey-brisbane

**Comment by iamkevinv** [comment]
Hi @trycatchjames - can i confirm you to speak at this months meetup? monday 11th? I'd like to put together the announcement list and hoping we can get everyone's confirmation :) Thanks!

**Comment by trycatchjames** [comment]
Yep, I can do that. So April 11th (next monday?)

**Comment by trycatchjames** [comment]
Hi @iamkevinv, my slides are available here: https://slides.com/jamesharvey/high-performance-mysql

**Comment by iamkevinv** [comment]
@trycatchjames Yes it's monday! last minute announce this time i'm afraid... was working my butt off this week and it got away from me!

**Comment by iamkevinv** [comment]
Hi there! Please find the details to connect via zoom. Zoom does all the streaming to youtube for us. We'll connect 10 mins before and test out our connectivity, before muting and going live :) See you soon!

Topic: BrisJS Meetup
Time: Apr 11, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
Thanks for presenting this talk! Please feel welcome to consider presenting again at brisjs! 🎉
