### ISSUE TITLE
Front-End Web Developer

### ISSUE THREAD

**Issue by csinge** [BrisJS/meetups#47]
Hi All, 

Oniqua is looking for an experienced front end developer. Really interesting product, small company, with great benefits and vibe.

See here for more information
http://oniqua.com/sites/default/files/resources/front-end_web_developer-pd.pdf

If you interested, send you resume through to reception@oniqua.com

Cheers
Cameron

**Comment by ashleygeorgeclarke** [comment]
The pdf link isn't working for me

**Comment by csinge** [comment]
Thanks, I am following up with this now

**Comment by csinge** [comment]
https://drive.google.com/file/d/0B27iXKDhWT9rdGZQdTV5QzhzeDA/view?usp=sharing

**Comment by iamkevinv** [comment]
Hi @csinge - this still current? else can we close it?
