### ISSUE TITLE
Talk on WebOTP

### ISSUE THREAD

**Issue by philnash** [BrisJS/meetups#470]
Talk title: *Web APIs for delightful two factor auth experiences*
Talk length: 20 min/40 min (I can squish it into 20 minutes, but it probably feels more natural somewhere between 25 and 30 minutes)
Talk synopsis: 
> It's a common practice to verify a phone number or implement two factor authentication by sending a one time password over SMS. We can all agree that it's a pretty terrible user experience though.
> 
> This process may increase security, but the friction can decrease conversion and the user experience in general. Android and iOS have APIs to combat this, so why not the web? In this talk we'll take a look at autocomplete and the WebOTP API to see how the web platform can help us build secure flows and a better experience all round.

Available month(s): April
Twitter account: [@philnash](https://twitter.com/philnash)

**Comment by iamkevinv** [comment]
Hi @philnash - can i confirm you to speak at this months meetup? monday 11th? I'd like to put together the announcement list and hoping we can get everyone's confirmation :) Thanks!

**Comment by philnash** [comment]
Confirmed! That's all good with me. :+1:

**Comment by iamkevinv** [comment]
Amazing mate!

**Comment by philnash** [comment]
Hello @iamkevinv! How do I connect to give the talk?

**Comment by iamkevinv** [comment]
Hi there! Please find the details to connect via zoom. Zoom does all the streaming to youtube for us. We'll connect 10 mins before and test out our connectivity, before muting and going live :) See you soon!

Topic: BrisJS Meetup
Time: Apr 11, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
Thanks for presenting this talk! If you have resources to link for folks, please feel free to still attach them here!
