### ISSUE TITLE
Short talk: Creating a multi-package monorepo with pnpm

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#472]
Talk time: 10-15 mins

Title: Creating a multi-package monorepo with pnpm

Abstract:

A short demo of how to create a multi-project or multi-package monorepo using pnpm instead of the more usual npm.

Sorry not available in June, but happy to book in July or after.

**Comment by ashleydavis** [comment]
I'm now available in June, if needed.

**Comment by iamkevinv** [comment]
Hey @ashleydavis are you keen to do this talk monday? If i can line up a 2nd speaker in addition to you we can still go ahead with the night, but otherwise it's shelved again :(

**Comment by ashleydavis** [comment]
Yes I'm good to go! Might be able to extend it a bit if you need me to fill time.

**Comment by iamkevinv** [comment]
Looks like this probably wont go ahead, as we don't seem to have any other speakers, and popping you on there by your lonesome is a bit cruel and unusual. So i fear we may be facing a worsening pattern of lacking submissions. July brisjs will either be pushed back a week or cancelled. Not sure if anyone will come out of the woodwork last min.

**Comment by ashleydavis** [comment]
Ok, thanks for the update.

**Comment by iamkevinv** [comment]
We're looking good to go for August :) We can do this talk or another of your choice

**Comment by ashleydavis** [comment]
Yep, I'm good for 1st August.

**Comment by iamkevinv** [comment]
Hey @ashleydavis, i'm sending out the details to everyone about the monday meetup! Look forward to talking to you then!

**Comment by iamkevinv** [comment]
Lets do this! Announced on meetup and email:
https://www.meetup.com/brisjs/events/287138977/

**The zoom details for the future:**
Topic: BrisJS Meetup
Time: Aug 1, 2022 06:30 PM Brisbane
Join Zoom Meeting: https://us02web.zoom.us/j/85153800585
Meeting ID: 851 5380 0585

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by ashleydavis** [comment]
Thanks

**Comment by aloysb** [comment]
Hi @ashleydavis

Looking forward to hearing your talk, I work with a large legacy codebase and have started moving it to Nx.
I'd be curious to see how you use pnpm to solve the issue.

Cheers.

**Comment by iamkevinv** [comment]
Thanks so much for your talk! If you have resources to share, please feel free to pop them here!

**Comment by ashleydavis** [comment]
Thank you.

Here the resources:
- Blog post: https://www.codecapers.com.au/pnpm-workspaces/
- Example code: https://github.com/ashleydavis/pnpm-workspace-examples
- Pnpm web page: https://pnpm.io/
- My new book Rapid Fullstack Development: https://rapidfullstackdevelopment.com/

**Comment by aloysb** [comment]
We're migrating an old legacy front-end project (plain JS files bundled with Makefile) to a monorepo-like structure.
We settled on Nx to help us to do so.

Nx is 'built' on top of workspaces (yarn workspaces), in a very similar fashion to pnpm workspaces.

@ashleydavis thanks for the talk, it was very interesting! :+1:

**Comment by ashleydavis** [comment]
Thank you
