### ISSUE TITLE
Long talk: Feedback and the REPL

### ISSUE THREAD

**Issue by jamesdiacono** [BrisJS/meetups#473]
Talk title: Feedback and the REPL
Talk length: 40 minutes
Talk synopsis:

James presents a short history of the feedback loops experienced by programmers, beginning with those measured in hours and ending with the instantaneous. He laments that we seem to have lost sight of the holy grail, but then demonstrates how JavaScripters can get it back thru better use of the REPL.

Available month(s): Any time

**Comment by iamkevinv** [comment]
Thanks so much for submitting your talk to brisJS :) 
Our next meetup is virtual on the 1st of August and it would be great to have you presenting then 👍 
As i like to introduce time for questions during the slot, can you aim to present around 30-35min so we can take some questions within the 40min timeframe?

**Comment by jamesdiacono** [comment]
The 1st of August would be great. I should be able to give the talk in 35 minutes. Will we be using Zoom?

**Comment by iamkevinv** [comment]
Indeed it is! I'll send out the details close to the date :)

**Comment by iamkevinv** [comment]
Hey @jamesdiacono, i'm sending out the details to everyone about the monday meetup! Look forward to talking to you then!

**Comment by iamkevinv** [comment]
Lets do this! Announced on meetup and email:
https://www.meetup.com/brisjs/events/287138977/

**The zoom details for the future:**
Topic: BrisJS Meetup
Time: Aug 1, 2022 06:30 PM Brisbane
Join Zoom Meeting: https://us02web.zoom.us/j/85153800585
Meeting ID: 851 5380 0585

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by diachedelic** [comment]
Sounds great! So I just join that Zoom meeting at 6:30 and give my talk straight away? I take it we have a 40 minute Zoom limit.

**Comment by jamesdiacono** [comment]
Sounds great! So I just join that Zoom meeting at 6:30 and give my talk straight away? I take it we have a 40 minute Zoom limit.

**Comment by iamkevinv** [comment]
Hi! Actually you can join me and test out screenshare and audio and such, 10-15min before. At 6:30pm BNE time I'll be doing my welcome and introductions, and then introduce you from there. There are no limits on our zoom account.

**Comment by jamesdiacono** [comment]
OK, see you then.

**Comment by diachedelic** [comment]
I'm waiting in the lobby.

**Comment by iamkevinv** [comment]
Thanks so much for your talk! If you have resources to share, please feel free to pop them here!

**Comment by jamesdiacono** [comment]
Links!
- What makes a REPL? https://lispcast.com/what-makes-a-repl/
- Replete plugins at https://github.com/jamesdiacono/Replete/issues/5
