### ISSUE TITLE
Short Talk Proposition: EOI - Monorepos with Nx

### ISSUE THREAD

**Issue by aloysb** [BrisJS/meetups#474]
Hi all,

Piggy-backing on @ashleydavis talk about pnpm last week, I'd be willing to give a quick, high-level presentation of Nx.

We are transitioning at my day job from a legacy project (plain JS scripts, bundled with Makefiles) - to Nx. 
The migration was mostly painless, which absolutely blew my mind.
Usually, tools come with plenty of promises - but implementing them can be a headache. 

Nx took most of that configuration pain away while allowing you to configure it as much as needed.
Think about Nx as the Create-React-App of monorepos.

Nx is a superset of yarn workspaces and is built with on the same philosophies of pnpm.
Nx feels can feel daunting the first time you look at it, but it couldn't be further from the truth: it is extremely powerful, fast and easy to set up.

I wish to keep the talk quick, 10-15 minutes. Therefore, I want to keep the talk at a high-level overview.

I would like to touch to the following topics:
- What is a monorepo?
- What is Nx?
- A short experience feedback: My experience migrating to Nx from a legacy production environment
- Q/A

Depending on the number of questions, I'd be happy to come back with more precise talks about advanced monorepo / Nx topics.

Anyway, let me know what you think, and if you're interested about this.

**Comment by iamkevinv** [comment]
This sounds great to me! Let's make it happen!

**Comment by aloysb** [comment]
@iamkevinv hey!

Sounds good!
However, I'm pretty flat out right now as I'm in a middle of a move.
When would you like to organise this?

As much as I'd like to jump fresh on the last talk about Workspaces, I believe October might be a better time for me.

**Comment by iamkevinv** [comment]
The next scheduled one is 5th Sept - Are you good with that?

**Comment by aloysb** [comment]
Sure, I can put something together - it's going to be tight but let's make it happen :rocket: 

I might have to change slightly parts of the speech related to my feedback in a production environment, because of NDA/company policies - but there's a lot we can cover regarding Nx so I'm not too worried about content :grin:

**Comment by iamkevinv** [comment]
Wicked! Can't wait!
I'll prep an announcement - can i also get your name for the presenter details as well as any social media handles you might want so we can add it when we ping on something like twitter?

**Comment by iamkevinv** [comment]
Hi @Aloysb - sent out the event details - see you there on the 5th Sept - Can you confirm you're locked in?

**Comment by aloysb** [comment]
@iamkevinv All good on my side! 👍

**Comment by iamkevinv** [comment]
Hi @Aloysb - Here is the zoom link for tonight's live stream - see you in a few mins!

Topic: BrisJS Meetup
Time: Sep 5, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585

**Comment by aloysb** [comment]
Yes I'm trying to join :)

**Comment by aloysb** [comment]
For anyone who survived my long monologue, I'll drop some resources out here to complete the talk.

But the bible remains https://nx.dev/ 📚

**Comment by iamkevinv** [comment]
Thanks so much for this presentation last month :)
