### ISSUE TITLE
SST: Serverless for devs with ADHD (and everyone else) Submission

### ISSUE THREAD

**Issue by DylanLacey** [BrisJS/meetups#475]
# Talk title: SST: Serverless for devs with ADHD (and everyone else)
# Talk length: 20 min
# Talk synopsis: 
Look, Serverless is _great_.  No EC2 setup or fighting with Docker makes me a happy dev.  Unfortunately, as you know, The Internet.  Specifically the speed of light, my personal nemesis.  Why?  Because I have ADHD, and as such, waiting for things (such as Serverless deploys) is not only excruciating, it's a great way for me to get distracted by .... well, literally anything else.  Couple that with the impenetrability of Cloudformation templates and the endless "why are none of my resources showing up oh I'm in the wrong region maybe I don't have permissions what even" two-step and things can get a bit... miserable.

Enter SST!  Make Serverless fun again:

- Nicer Infrastructure-As-Code
- Full local testing of functions (with VS Code breakpoints!)
- Shiny web dashboard _that's actually useful_

I'ma show you a demo!  Because it's fun, and I want y'all to have fun, too.

Available month(s): Most of em.
Optional: https://www.twitter.com/dylanlacey

**Comment by iamkevinv** [comment]
AWESOME! As someone going through adult-diagnosis - this sings to me haha.
Sounds like a great talk and some useful additions to present to everyone!
Keen! Good for next month?

**Comment by iamkevinv** [comment]
Hi @DylanLacey - sent out the event details - see you there on the 5th Sept - Can you confirm you're locked in?

**Comment by iamkevinv** [comment]
Hi @DylanLacey - are you keen to still jump in on the moved date of 2022-10-11

**Comment by iamkevinv** [comment]
Hey @DylanLacey can I confirm your talk for the Dec 5 BrisJS?

**Comment by iamkevinv** [comment]
Also is the 5th too tight? Otherwise, i can try and postpone to make sure everyone can get together for this one. If you're avail on 5th or 12th or both, just let me know with one of those three :) Thanks!

**Comment by iamkevinv** [comment]
We moved to the 12th @DylanLacey - if you're keen to throw yourself into the mix i can still accept your talk. Please let me know asap, otherwise we might see you in Feb?

**Comment by iamkevinv** [comment]
Hello @DylanLacey - When do we re-visit?

**Comment by iamkevinv** [comment]
@DylanLacey Any news on when this may take place?

**Comment by iamkevinv** [comment]
@DylanLacey Any news on whether you can revisit this topic for presentation?

**Comment by iamkevinv** [comment]
One last ping attempt before this one will get cleaned up from our board :) Keen on a September in-person presentation of this talk perhaps @DylanLacey ?

**Comment by iamkevinv** [comment]
Closing due to length of time open. Please let me know if it should be re-opened.
