### ISSUE TITLE
Web components pressure test: What they are, and how different text editors handle them

### ISSUE THREAD

**Issue by RobinJoe** [BrisJS/meetups#476]
Talk title: Web components under a pressure test
Talk length: 20 min
Talk synopsis: Web components – what are they, and what do they do in practice? I tested out how rich text editor components (something that get's reused over and over) to see how they worked, and which rich text editor performed best.

Structure: 

What is a web component?
Web component results summary and comparison
CKEditor
Froala
Slate.js
Quill
TinyMCE
Choosing the right web component integration

Available month(s): September and October
Optional: As this is a talk for Dev Advocate work, the @joinTiny account would be best to add here.

**Comment by iamkevinv** [comment]
Oh yes yes :D 
Thanks very much. I'm keen. lets line you up for Sept!

**Comment by RobinJoe** [comment]
Hi @iamkevinv That sounds good, thanks very much! I'll get onto preparing and practicing. I'll let you know if the talk structure changes, and send through a bio and talk description.

**Comment by RobinJoe** [comment]
@iamkevinv Hi, just confirming my talk is ready for this evening, thanks for the good overview in the meetup event description – I can send through slides if needed.

**Comment by iamkevinv** [comment]
Hi @RobinJoe - Here is the zoom link for tonight's live stream

Topic: BrisJS Meetup
Time: Sep 5, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585

**Comment by iamkevinv** [comment]
Thanks @RobinJoe for your presentation last month... If you have any links or resources you want to share here... please do :)
