### ISSUE TITLE
Long talk: Make your own framework using Web Components

### ISSUE THREAD

**Issue by adam-9001** [BrisJS/meetups#477]
**Talk title**: Make your own React/Vue-style framework using Web Components
**Talk length**: 30-40 mins
**Talk synopsis**:

This talk will introduce Web Components and when they can be practically useful for your applications. 

We then move on to the fun part, a simplified guide on implementing a complete, declarative UI framework (similar to React or Vue) using Web Component APIs and from first principles. This talk will shed some light on how many JS frameworks work behind the scenes and cover many interesting and lesser known JS APIs in the process.

**Available month(s)**: Dec, Jan

**Comment by iamkevinv** [comment]
Thanks @adam-9001 :) I think this would be great 👍

**Comment by iamkevinv** [comment]
Sorry it's taken me a bit to get back to this!

**Comment by adam-9001** [comment]
No worries, looking forward to it!

**Comment by iamkevinv** [comment]
Hi @adam-9001 can I confirm your talk for this Dec 5 BrisJS?

**Comment by iamkevinv** [comment]
Also is the 5th too tight? Otherwise, i can try and postpone to make sure everyone can get together for this one. If you're avail on 5th or 12th or both, just let me know with one of those three :) Thanks!

**Comment by adam-9001** [comment]
Heya, I'm available for both 5th and 12th. If we can get a bigger turnout on the 12th, more than happy to postpone to then.

**Comment by adam-9001** [comment]
Hew mate so are we still on tomorrow or have you postponed it?

**Comment by iamkevinv** [comment]
Postponed till the week after!
I'll use the opportunity to put the call out and advertise. Thanks!!

**Comment by iamkevinv** [comment]
@adam-9001 can i get your name for the announcements and tweets? I just have you here as Adam 9001 :)

**Comment by adam-9001** [comment]
"Adam A" - sent you an email too.

**Comment by iamkevinv** [comment]
True, i was just wondering what the A stands for :)

**Comment by adam-9001** [comment]
Hey Kevin, is there a special link or similar I should use when presenting?

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetup
Time: Dec 12, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
Thanks so much for the presentation - if you have links to share please don't hesitate to drop them here!
