### ISSUE TITLE
Turning your current static portfolio into a blogging website with Gatsby

### ISSUE THREAD

**Issue by LayersOfAbstraction** [BrisJS/meetups#478]
**Talk title:** Turning your current static portfolio into a blogging website with Gatsby
**Talk length:** 30-40 mins
**Talk synopsis:**

The talk will include a repository of a famous Youtuber, Joshua Fluke and identify the differences between regular HTML and JSX and the process for transforming HTML to JSX so we can use React-based frameworks like Gatsby on our site. It will explain some of the pitfalls of conversion and how we can avoid and make use of Transform.io to make the transformation easier.

**Available month(s):** November onwards

**Comment by iamkevinv** [comment]
Thanks @LayersOfAbstraction - Lets get you lined up for the next one if we can - Nov 7. Works for you?

**Comment by LayersOfAbstraction** [comment]
Yes I should be able to make it no problem!

**Comment by iamkevinv** [comment]
Confirming you for the monday brisjs - you're the sole headline speaker!

**Comment by LayersOfAbstraction** [comment]
> Confirming you for the monday brisjs - you're the sole headline speaker!

I will be speaking online during that talk. Thanks!

**Comment by iamkevinv** [comment]
And if by that you're asking if it's a livestream where you're talking with me over Zoom... yes! That's how it's running :)

**Comment by LayersOfAbstraction** [comment]
@iamkevinv Yes I will use the zoom link I will get from you. Sorry, Kev it looks like I can **start only at 7:15pm** but I have rehearsed and can confirm I am 100% sure I am ready for this. I have taken the whole day off work to ensure I don't miss out, thank you!

**Comment by iamkevinv** [comment]
The event is scheduled to start at 6:30pm and I will give an intro which is usually around 15min. So you would typically start at 6:45pm. If you can't make it at the required start time I'll have to send out a notice that we're starting the livestream event 30min later. Please confirm.

**Comment by LayersOfAbstraction** [comment]
I confirm.

**Comment by iamkevinv** [comment]
Join the zoom with this link:
https://us02web.zoom.us/j/85153800585


Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by LayersOfAbstraction** [comment]
Hi Kev,

I want to try for the Livestream again, please. I think it will work this time. It didn't because I didn't trust I would have reliable internet from my home so I tried at the library. We know how that turned out. 

It seems I was wrong. Worked very well in Zoom until my trial version terminated the session after 30 minutes. For MS Teams there was a video dropout but I found a way past that by sharing one of my screens and activating the Windows camera locally on that screen. I've rehearsed at least once with someone for Zoom. This time I think the live stream will go well.

**Comment by LayersOfAbstraction** [comment]
Hi again, sorry for letting you down last time. I finally found out why the internet was so slow that time. I went to the Apple store and they fixed the problem. Turned out it was because I was using Kaspersky Connection (a VPN) even though I switched it off. The configuration got removed by the Apple tech. Now I am confident in been able to present the live demo. I understand your hesitation however and will let you think about things. If you don't let me know by Sunday if you still want to go ahead then I will go to an alternative meetup on Monday, thank you.

**Comment by iamkevinv** [comment]
Hey mate sorry for the delay - would love to have your talk at the next event! I'll confirm you and send out the notice once i have everyone's replies. Thanks!

**Comment by iamkevinv** [comment]
Also is the 5th too tight? Otherwise, i can try and postpone to make sure everyone can get together for this one. If you're avail on 5th or 12th or both, just let me know with one of those three :) Thanks!

**Comment by LayersOfAbstraction** [comment]
The 5th of December at 6:30 pm is fine, thanks. See you then.

**Comment by iamkevinv** [comment]
Hey @LayersOfAbstraction - Can you still make the 12th instead? Based on the feedback I would like to give us the week to help advertise the talks, and give one of our speakers the opportunity to join if they could. Can you please confirm ASAP? I'm updating the meetup page to reflect the new date... If you confirm we'll have two speakers, and i'm hoping before the end of the week we can have the third one in too.

**Comment by LayersOfAbstraction** [comment]
Hi @iamkevinv. That's very reasonable. all good see you on the 12th. If you have to change it again I'm still good. Just happy you're still hosting this.

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetup
Time: Dec 12, 2022 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
+61 2 8015 6011 Australia
+61 3 7018 2005 Australia
+61 7 3185 3730 Australia
+61 8 6119 3900 Australia
+61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
Thanks mate if you have links to share here, please do :)

**Comment by LayersOfAbstraction** [comment]
Yeah if anyone wants to know more. here's a link to the 
[Medium blog I got.](https://medium.com/gitconnected/how-to-turn-your-portfolio-into-a-blogging-website-with-gatsby-1ae8042ef462)
Also here is the sample repository I used that was forked from Joshua Fluke's[Github Pages Portfolio](https://github.com/LayersOfAbstraction/joshuafluke.github.io)

Also hoping to do more talks later but not at all ready yet.
