### ISSUE TITLE
Deep dive into Single Sign On for SPA

### ISSUE THREAD

**Issue by turanofff** [BrisJS/meetups#479]
Talk title: Implementing Single Sign On for Single Page Applications
Talk length: 40 min
Talk synopsis: 
- Overview of the architecture behind SSO
- OpenID (OIDC) vs SAML and how we can use them together
- Security aspects / best practices
- SSO for SPA (Angular) without 3rd party libraries (live coding) 
Available month(s): January, February

**Comment by iamkevinv** [comment]
Awesome submission, we're back in feb - would be great to add you to the upcoming lineup 👍

**Comment by iamkevinv** [comment]
Hello @turanofff - Are you confirmed for monday?

**Comment by turanofff** [comment]
> Hello @turanofff - Are you confirmed for monday?

Hi @iamkevinv, ooops looks like it's a little bit of a short notice for me (sorry I wasn't quite aware of the date). Would you be able to move me to the next one and lemme know the date?

**Comment by iamkevinv** [comment]
Hey @turanofff! Would next Monday after work? I could try and move the date to give both speakers more time…

**Comment by iamkevinv** [comment]
Please let me know if we can delay by 1 week @turanofff - otherwise, it seems we might have to cancel the event for Feb

**Comment by turanofff** [comment]
@iamkevinv I think next Monday (13th of Feb) would do for me. Please also let me know what's the format of the a catch up. Is it gonna be online or in a physical location somewhere?

**Comment by iamkevinv** [comment]
It's online this month with a livestream from our zoom meeting 😀 
So I can confirm you? I'll send out the notice to the world of the changes and announce your talk as the other speaker can also do this date!

**Comment by iamkevinv** [comment]
All lined up https://www.meetup.com/brisjs/events/nvkmpsyfcdbjb/ See you then!

**Comment by iamkevinv** [comment]
I'll set up the zoom link and post it here soon

**Comment by iamkevinv** [comment]
@turanofff - See you tonight on the zoom! https://us02web.zoom.us/j/85153800585 <-- use the link to join from 6:15pm bne time onwards. We'll aim to get started at 6:30 to broadcast the zoom to youtube.

If you run into trouble and can't join and can't hit me up on brisjs twitter account, linkedin or something, I set up a chat channel for speakers on the old existing gitter chat. Sign in with github. https://gitter.im/BrisJS/speakers?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by iamkevinv** [comment]
Thanks again for your talk!

**Comment by iamkevinv** [comment]
@turanofff - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)
