### ISSUE TITLE
The promo builder, or: unidirectional app structure with virtual DOM. 

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#48]
@collypops has been working on a pretty slick tool to let journalists create promo images with quotes for social media. It's pretty neat.

<img src="https://pbs.twimg.com/media/CAdY3iFUUAADnEV.jpg:large" width=400 alt="Part of the problemk with this debate is the use of the wretched term metadata which confuses everybody - Malcolm Turnbull, Communications Minister">

<img src="https://pbs.twimg.com/media/CAdfXR0UUAAR18D.jpg:large" width=400 alt="Right now the onus of safety is on the victim with very little focus on the perpetrators - Rosie Batty, Australian of the Year">

Anyway, I've talked him into talking at the May meetup about it. It's a half show-and-tell, half discussion about one-way-binding. I hope he also talks about some of the rendering too because it's pretty neat. :+1:

**Comment by kevdesign** [comment]
Love it. Saw the seeds at CampJS i believe...

**Comment by kevdesign** [comment]
@collypops Will you still be in bris to be able to run us through the presentation you gave at CampJS? Otherwise we'll have to reschedule for when you're back.

**Comment by colingourlay** [comment]
@kevdesign I can't make it to the meetup (travel prep, etc.) tomorrow, but I'm happy to go through it again once I'm back!

**Comment by kevdesign** [comment]
Nice. Enough time for people to need another reminder! Thanks mate

**Comment by iamkevinv** [comment]
I seem to have a lot of talks for August @colingourlay - but we could still get you in for this gem. I'll have to update this once i see the whole list and ballpark the length.

**Comment by colingourlay** [comment]
Sorry @iamkevinv , can you put me on hold again? I've got a lot of shit to get done in the next couple of weeks (including a work trip), and I'm not gonna have the time to pull this together.

**Comment by iamkevinv** [comment]
I know the feeling dude! 
Also, don't need much more than the Campjs speech again btw. Labels removed!

**Comment by iamkevinv** [comment]
@colingourlay - did you maybe want to show us this magic for the 12th Oct Meetup? Looking for someone to fill in for the Angular 2 talk which is cancelled and Mercury should get it's time to shine :)

**Comment by iamkevinv** [comment]
@colingourlay i believe you're overseas again, so i'll push this back a month

**Comment by iamkevinv** [comment]
Hey @colingourlay - Now that you're back... are you keen?

**Comment by AshKyd** [comment]
Re-ping @colingourlay: wanna run us through some Mercury in Feb? I want to hear about what you've been up to. :D

**Comment by iamkevinv** [comment]
C'mon @colingourlay ... you cannot deny the power of the BrisJS :-P  Want to get this show on the road?

**Comment by iamkevinv** [comment]
Long shot @colingourlay - but i need talks for BrisJS monday... keen to revisit this? Maybe contrast what you did, and what you'd like to do with it now, and if you'd make the same technical choices?
