### ISSUE TITLE
Observability - All the things you wanted to know but were scared to ask

### ISSUE THREAD

**Issue by ahaw023** [BrisJS/meetups#480]
@ashleydavis challenged me to summarise my thoughts on observability 

Talk title: Observability - All the things you wanted to know but were scared to ask

I will draw on some my experiences from DevOps, SRE and Observability Engineering to hopefully summarise a fairly complex field in to 40 minutes

Talk length: 40 min
Talk synopsis:
- Observability vs Monitoring
- TEMPLE - the signals worth capturing
- Break down of a typical observability stack
- What we should offload to cloud 
- Use Case first approach
- Why K6 should be part of your observability stack
- Open Telemetry
- SLI /SLO
- Some good projects for observability
Available month(s): Feb March 2023

**Comment by ashleydavis** [comment]
Oh this will be awesome.

**Comment by iamkevinv** [comment]
Cool lets line it up for feb @ahaw023 ?

**Comment by ahaw023** [comment]
Happy New Years @iamkevinv !!!

That sounds good.

**Comment by iamkevinv** [comment]
Hello @ahaw023! Are you confirmed for monday?

**Comment by ahaw023** [comment]
Yes we are @iamkevinv  :D

**Comment by iamkevinv** [comment]
Thanks @ahaw023 - If we need to move it forward by 1 week to the following monday, would that still work for you? The other speaker needs to reschedule and i'm seeing if i can make that move for them. I'd prefer to have two speakers, rather than one,... but if there's nothing we can do, we'll have you up solo :)

**Comment by ahaw023** [comment]
hi @iamkevinv  - the week after is fine :D

**Comment by iamkevinv** [comment]
Brilliant- that will be the one then! I'll announce the talks and change of date asap then

**Comment by iamkevinv** [comment]
All lined up https://www.meetup.com/brisjs/events/nvkmpsyfcdbjb/ See you then!

**Comment by iamkevinv** [comment]
I'll set up the zoom link and post it here soon

**Comment by iamkevinv** [comment]
@ahaw023 - See you tonight on the zoom! https://us02web.zoom.us/j/85153800585 <-- use the link to join from 6:15pm bne time onwards. We'll aim to get started at 6:30 to broadcast the zoom to youtube.

If you run into trouble and can't join and can't hit me up on brisjs twitter account, linkedin or something, I set up a chat channel for speakers on the old existing gitter chat. Sign in with github. https://gitter.im/BrisJS/speakers?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ukuhnhardt** [comment]
Awesome talk! can we please get the slides here, of if it's somewhere else, the link?

**Comment by ahaw023** [comment]
@ukuhnhardt  - sure :D  https://my.visme.co/view/1j6yn1ym-brisjs-feb-2023-observability

**Comment by iamkevinv** [comment]
Thanks for sharing the resources too! thanks!
