### ISSUE TITLE
Achieving Page Speed with a Data-heavy Visualisation

### ISSUE THREAD

**Issue by mbourne** [BrisJS/meetups#481]
Talk title: Achieving Page Speed with a Data-heavy Visualisation (or, Why I hate Tableau)
Talk length: 40 min
Talk synopsis: Many data visualisations (in fact, many sites for that matter) suffer from slow load times due to bloated scripts and poor optimisation. This talk demonstrates the possibilities for solving these issues using a case study.
Available month(s): Feb, Mar, Apr
Twitter handle: @bourne_2_learn

**Comment by iamkevinv** [comment]
This sounds great @mbourne :) We'd love to have you present. Probably the Mar event, but i'll double check today around scheduling. Does that work for you?

**Comment by mbourne** [comment]
Yep - March will be fine with me.

**Comment by iamkevinv** [comment]
Hi @mbourne - As I've had real issues with my scheduling up to now and BrisJS has fallen a little by the wayside. In order to get two speakers lined up together, would you also be available to present (remote via zoom) on March 13 instead of March 6th? Thanks in advance.

**Comment by mbourne** [comment]
Hi Kevin

Sure, 13th is good for me.

Regards
Murray

**Comment by iamkevinv** [comment]
For tonight, you can connect to my zoom a few mins before and test your audio, video and screen sharing :) 

Topic: BrisJS Meetups 2023
Time: Mar 13, 2023 06:30 PM Brisbane

Join Zoom Meeting: https://us02web.zoom.us/j/85153800585

----------------
Alternate audio connectivity details: 
Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by mbourne** [comment]
Thanks, Kevin

Will do at about 6:15

Regards
Murray

**Comment by iamkevinv** [comment]
slides: https://bourne2learn.com/math/energy/page-speed-data-heavy-visualisation.php
examples: https://bourne2learn.com/math/energy/consumption-totals.php
https://bourne2learn.com/math/energy/consumption-fuels.php

**Comment by iamkevinv** [comment]
Thanks again for your talk!
