### ISSUE TITLE
Lead Full Stack Engineer for high impact and growth startup (brisbane bonus points!) 

### ISSUE THREAD

**Issue by J-at-turnto** [BrisJS/meetups#482]
**About Turnto** 
Getting a serious health condition sucks! Then, trying to find the best cutting-edge treatments is impossible. Then, finding the best providers and leaders to turn to can take an enormous amount of time, and in the end, depends mostly on luck! That’s a lot of “thens!”

Turnto is solving this by building the home for all voices and insights - for every single health condition. We have our first product in-market, serving health consumers with curated search and lists to find more treatments than anywhere else, with expert and consumer reviews about cutting edge treatments.

This is just the beginning. We are out to build the genre-changing health platform that is the future for search, feed, conversation and connection. 

**About the team**
We are passionate, creative, ambitious, yet a flexible team that would make a perfect fit for someone who is self-motivated, driven, likes to solve problems, and wants to make a massive global impact. 

Turnto is a pre-product market fit, early-stage health tech startup, with a team spread across the globe. We have raised our pre-seed from some big name angels and funds, like Lars Rasmussen and founders of unicorn startups.

We work remotely, with a few in-person meet ups each year - with the possibility of hybrid work in Brisbane/Sydney if fate aligns. 

You will be a founding team member at Turnto and as such will have a hand in shaping the future of the company. You will also have the opportunity of a meaningful equity stake; as well as growing your role and influence alongside the company.

**Where do you fit?** 
You will be our technical leader - with your hands on the tools, responsible for building, building, building, with a slice of building on the side.

We have heaps of traction with the early MVP, positioning in the value proposition, engagement with the target audience, acquisition, community building, and generating revenue. Now, we need to supercharge the development of our product offering. 

You will work closely with the founder in designing, executing, and building the platform - moving fast with a bias to action, to bring the next iteration (and the many after that) of this consumer-facing platform to life. You will be working in a small engineer team, leading 1-2 other engineers, and alongside a seasoned and talented PM and designer. Your experience and expertise will also be crucial in our technical strategic decision-making going forward (you may even need to fix a couple of things we have already done with the first platform). 

You will be savvy, experimental, a lover of the entrepreneurial and startup thrills, impact driven, and someone who enjoys a challenge - setting themselves very ambitious timelines and goals - ready to do your life’s best work for the benefit of millions!

From a technical perspective, we’re looking for someone who’s happy working across the full stack.

Since we are building everything from the ground up in this second stage, we’re looking for somebody who has performance and scale top-of-mind. Therefore, to be successful in this role - strong computing fundamentals, first principles, architectural chops, and product acumen are a must!

Experience you’ll bring to the table:

- Software engineering skills - with experience across the front and backend development - this role is 100% hands on
- Familiarity with web programming languages such as React, JavaScript, Node.js, Python, as well as modern database technologies.
- Experience building in the cloud - ideally with AWS - data pipeline development, RDS experience, and deployment systems experience would be handy!
- Mobile app experience and React Native
- 

Bonus points if you have:

- Experience in building consumer-facing products at scale
- Released apps on the iOS and Android App Stores
- Experience with Machine Learning pipelines or generally in the “data science” space
- Mobile app development skills and experience
- 

Being a startup - what’s most important in a founding member is drive and passion to learn, grow, and build a product which helps people. We make hiring decisions based on a blend of your experience, skills and passion. Therefore, if you LOVE what we are doing but feel you don’t tick all the boxes - apply anyway - and let us know in a cover letter why you love what we’re doing. We still want to know who you are, and we can be flexible with gaps in experience if there are strengths in other areas.

**Comment by iamkevinv** [comment]
Closing due to length of time open. Please let me know if it should be re-opened.
