### ISSUE TITLE
Freelance JavaScript/PHP Developer Wanted

### ISSUE THREAD

**Issue by tobybeedell** [BrisJS/meetups#483]
I have an urgent need for an experienced JavaScript developer to assist with the refactoring of an existing e-commerce site to integrate with the Stripe API, and add in some validations around capturing of email addresses and phone numbers. Fairly simple project and would guess that it is less than 15hrs coding required. Please contact me if you have some extra availability this week to come in and save the day.

**Comment by iamkevinv** [comment]
Closing due to length of time open. Please let me know if it should be re-opened.
