### ISSUE TITLE
Medium talk: Implementing Observability in Node.js

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#484]
After the excellent overview on Observability from @ahaw023 in February I'd like to do a follow up talk on adding Observability to a Node.js microservices project.

Talk time: 20-30 min

Title: Implementing Observability in Node.js

Let's implement Observability in a Node.js microservices project using open telemetry and Honeycomb.

Open telemetry can seem really complicated and overwhelming, but once you know what you need (with a bit of help from Honeycomb's SDK) it's actually quite easy to get a lot just from it just by integrating the Node.js automatic instrumentation.

We'll see how to integrate automatic distributed traces into our Node.js code and then how to find those traces in the Honeycomb UI.

We'll then learn the basics of creating spans, adding attributes and recording events and errors.

**Comment by iamkevinv** [comment]
@ashleydavis - trying to arrange for your availability so that this happens on the 13th instead of the 6th. I'll keep you posted.

**Comment by ashleydavis** [comment]
Thanks @iamkevinv, If you can let me know by the 7th that will mean I can find some time to prep for the talk.

**Comment by iamkevinv** [comment]
For tonight, you can connect to my zoom a few mins before and test your audio, video and screen sharing :) 

Topic: BrisJS Meetups 2023
Time: Mar 13, 2023 06:30 PM Brisbane

Join Zoom Meeting: https://us02web.zoom.us/j/85153800585

----------------
Alternate audio connectivity details: 
Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by ashleydavis** [comment]
Ok, see you tonight.

**Comment by ashleydavis** [comment]
Resources from my talk: 

Example code:
https://github.com/ashleydavis/open-telemetry-nodejs-microservices-example

Honeycomb quickstart:
https://docs.honeycomb.io/quickstart/

Honeycomb training videos:
https://www.honeycomb.io/usecase/learn-honeycomb

OpenTelemetry bootcamp:
https://www.aspecto.io/opentelemetry-bootcamp/

OpenTelemetry docs:
https://opentelemetry.io/docs/

**Comment by iamkevinv** [comment]
Thanks again for your talk mate!
