### ISSUE TITLE
Low-Code Software Engineering: What is Low-Code?

### ISSUE THREAD

**Issue by Yonarp** [BrisJS/meetups#485]
Talk title: Low-Code Software Engineering: What is Low-Code?

In this 40-minute talk, I will like to explore the concept of low-code software engineering, what low-code is, how it differs from no-code platforms, and also how it can be beneficial for the future of software engineers.

Talk length: 40 min

Talk synopsis: 

- What is low-code

- highlighting the key differences between low-code and no-code

- understanding low code with a demonstration

Available month(s): April 2023

**Comment by iamkevinv** [comment]
Sounds great :) Thanks for your submission! Lets get it on the schedule!

**Comment by Yonarp** [comment]
Unfortunately, I will be unable to attend on the first Monday of next month, which falls on April 3rd. Would it be possible to reschedule to a different time that is convenient for you?

**Comment by iamkevinv** [comment]
No Guarantees... but is the week after better?

**Comment by Yonarp** [comment]
I think the week after everyone will have an easter holiday on Monday, ill be okay with anything after that. How about the week after that on the 17th?

**Comment by iamkevinv** [comment]
Yeah then it's getting too late in the month. I guess we'll have to cancel after all.

**Comment by iamkevinv** [comment]
HI @Yonarp - Can you still present on monday? I'm going to send out the notice, since it's gotten really late and the event is rushing up to meet us :)

**Comment by Yonarp** [comment]
Hi @iamkevinv - I can present a talk on Monday, we are 2 speakers and a length of 40 mins.

**Comment by iamkevinv** [comment]
Great! I'll get the reminder announcement out - can I get both of your names for the meetup page?

**Comment by iamkevinv** [comment]
I can edit the names later... i've added and sent the announce for:
https://www.meetup.com/brisjs/events/292821975/ 
See you monday! I'll send out another message here @Yonarp - with Zoom details to connect to my stream. Thanks!

**Comment by Yonarp** [comment]
Hi @iamkevinv  the names are Dominik Keller and Pranoy Sarkar

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetups 2023
Time: May 8, 2023 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585
One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

Dial by your location
        +61 2 8015 6011 Australia
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
Meeting ID: 851 5380 0585
Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
See above @Yonarp

**Comment by iamkevinv** [comment]
@Yonarp - Thanks for the presentation folks! If you have any links of resources to share here, please do!

**Comment by iamkevinv** [comment]
@Yonarp - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)

**Comment by Yonarp** [comment]
Hi @iamkevinv, I apologize for the delay. definitely interested in repeating our talk in the near future for SydJS.
