### ISSUE TITLE
Senior Full-Stack Cloud Engineer

### ISSUE THREAD

**Issue by ShaunSpinelli** [BrisJS/meetups#486]
Are you looking for an exciting opportunity to work with cutting-edge technology and shape the future of infrastructure engineering?

Look no further than SiteSee, our powerful AI analysis systems, coupled with real-world infrastructure 3D Digital Twins, are empowering users to design and build their infrastructure assets and make informed decisions, all from the desktop.

As a Senior Full-stack Cloud Engineer at SiteSee, you will design and implement innovative solutions that leverage the power of our cutting-edge AI analysis systems and 3D Digital Twin models. 

https://www.sitesee.io/open-position/senior-full-stack-cloud-engineer

**Comment by iamkevinv** [comment]
Closing due to length of time open. Please let me know if it should be re-opened.
