### ISSUE TITLE
Long talk: JavaScripting from the terminal

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#487]
Talk time: 30-40 mins

Have you ever wished you could take a data file or even some data output by a tool and transform it without having to write a ton of code?

You might have already tried using `jq` (or a similar tool) to do this and  like me you might have been flummoxed by the syntax and struggled to remember later how to use it.

Join Ashley Davis and discover a new technique using JavaScript in the terminal to create rapid fire data transformation, filtering and aggregation while hardly breaking a sweat.

**Comment by iamkevinv** [comment]
Hey @ashleydavis - i'm still trying to wrangle a 2nd speaker for June to pair this with - anyone you know?

**Comment by iamkevinv** [comment]
Sending out the notice for monday brisjs livestream :)

**Comment by ashleydavis** [comment]
I'm good to go.

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetups 2023
Time: Jul 3, 2023 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585

---

One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

---

Dial by your location
• +61 2 8015 6011 Australia
• +61 3 7018 2005 Australia
• +61 7 3185 3730 Australia
• +61 8 6119 3900 Australia
• +61 8 7150 1149 Australia

Meeting ID: 851 5380 0585

Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by ashleydavis** [comment]
Here is a link to Datakit that I demonstrated at tonight's meetup:
https://github.com/ashleydavis/datakit

This is Mongokit which I showed as well:
https://github.com/ashleydavis/mongokit

**Comment by iamkevinv** [comment]
Thanks for the excellent work! Appreciate you sharing the links already too :)

**Comment by iamkevinv** [comment]
@ashleydavis - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)

**Comment by ashleydavis** [comment]
I'm keen! What time?

**Comment by ashleydavis** [comment]
@iamkevinv sorry I just remembered I'm busy on the 20th March, going to a World Science Festival event. I should be able to do it another day though!

**Comment by iamkevinv** [comment]
No sweat mate, thank you for responding anyway 👍
If the date is moved I'll let you know!
