### ISSUE TITLE
Short talk: Adding user-extensibility to your web apps

### ISSUE THREAD

**Issue by adam-pccw** [BrisJS/meetups#488]
Hi Kevin 👋 

This is a a short talk (15-25mins), aiming to cover all the different techniques that allow for creating plugin/add-on systems into web apps, including a short history and security considerations.

Happy to give whenever most convenient and makes most sense in the BrisJS schedule.

**Comment by iamkevinv** [comment]
locked in ... Sending out the notice for monday brisjs livestream :)

**Comment by iamkevinv** [comment]
Kevin Vanderbeken is inviting you to a scheduled Zoom meeting.

Topic: BrisJS Meetups 2023
Time: Jul 3, 2023 06:30 PM Brisbane

Join Zoom Meeting
https://us02web.zoom.us/j/85153800585

Meeting ID: 851 5380 0585

---

One tap mobile
+61280156011,,85153800585# Australia
+61370182005,,85153800585# Australia

---

Dial by your location
• +61 2 8015 6011 Australia
• +61 3 7018 2005 Australia
• +61 7 3185 3730 Australia
• +61 8 6119 3900 Australia
• +61 8 7150 1149 Australia

Meeting ID: 851 5380 0585

Find your local number: https://us02web.zoom.us/u/kcM2vMYniv

**Comment by iamkevinv** [comment]
Thanks for the excellent work! If you have links to your presentation or any resources, please feel free to update the issue!

**Comment by adam-pccw** [comment]
Came across this: https://extism.org/docs/overview

Maybe someone might find it helpful, it's a plugin system that uses wasm behind the scenes, very relevant to what we talked about
