### ISSUE TITLE
Talks Submission: How TypeScript allows us to effectively leverage our development team

### ISSUE THREAD

**Issue by elhedran** [BrisJS/meetups#489]
Presenter Name: Ian Walters (Principal Engineer with Fugro)
Talk title: How TypeScript allows us to effectively leverage our development team
Talk length: 20 min/30 min (can be flexible)
Talk description:

TypeScript is one of the few software languages that allow for development in almost any context. While overall an excellent tool for developers, in particular, this enables us to have one software language across our entire product and as a consequence better use the developer resources in our team by reducing knowledge silos and increasing our ability to shift focus where needed.

In this talk we will discuss the value TypeScript brings to our product across;
* The API Logic - compute handlers (agnostic code wrapped by either AWS lambda or Express)
* The Front end development (web apps)
* Infrastructure as Code (AWS Cloud Development Kit)
* Publishing SDK for client use and development
* System tests
* Performance tests
* Developer tooling

For each area of concern, we will cover how we apply TypeScript and why it is well suited to that area. We will also discuss how we bring this all together as a project and why modern cloud architecture is an ideal target for TypeScript development.
We will also reference some technologies and approaches we don't use but still feel are worth considering for use cases outside our current product requirements.

Available month(s):

The talk isn't written yet, so I need at least a week's notice to fit putting it together around other work.  However, we (as a Team, Fugro itself leans more to C#) use TypeScript in this way in our development and have done so for quite a long time now - so it's more pulling it together in a presentation than anything else.

Optional:
I'll update this one in a bit - LinkedIn is giving me grief today.

**Comment by iamkevinv** [comment]
Thanks so much Ian (@elhedran)!!
Sounds great :) 
We're still trying to work out if this will be possible to do as an in person meetup (we're unfortunately running out of time to get the logistics handled) but we're absolutely going to have our Livestream of course, and we'd love your presentation :)

**Comment by iamkevinv** [comment]
How is the timeline looking for you? Aug 7 is the next event. If you're looking to take more time, let me know so i can help work out the scheduling :) 
We're still needing a few more talks, so if you have folks out there you think are keen to follow in your footsteps, please help us spread the word :D

**Comment by iamkevinv** [comment]
Hi @elhedran - We have only your submission this month, which is yours (thank you!). So to be able to put on the show we're trying to get another one lined up. If we Postpone the next event to be 4 Sept, are you still available to present it? Can you present it in-person in Toowong or only online with a livestream?

**Comment by iamkevinv** [comment]
Hi @elhedran - I haven't had any reply from you :( 
I only have your talk for Aug, and due to comms issues, this means we can't really go ahead with the Aug livestream. Let's push forward for an in person Sept meetup event instead.

**Comment by iamkevinv** [comment]
Hi @elhedran - Still trying to get confirmation from you?
Instead of the next week presentation... given we're aiming to have in-person events again, could you please confirm if you're available to present this at the October BrisJS? Seems like we also had the public holiday clash come up on Oct 2, So we'd be looking at Monday Oct 9th instead.
Why do i ask? Well, getting the sponsorship money organised is taking a little longer, and we'll miss our window by at least week. That week after, I will be unable to MC the events and handle the logistics. So we might end up making the next one a BrisJS social event in the city, and then re-launch in-person BrisJS with an even bigger bang.
Can you let me know asap? Thanks.

**Comment by iamkevinv** [comment]
@elhedran can you please confirm your presentation will be on Monday Oct 9th BrisJS event, held at Auto & General meeting space, in person?

**Comment by iamkevinv** [comment]
@elhedran - Would you be available for Nov 6th? I'd like to give you the opportunity to jump in this time. We're gathering quite a long list of interested folks to speak and i'll need to get speaker confirmation from you in the next few days to arrange to post the details of the event this week if you're up for it.

**Comment by elhedran** [comment]
Just confirming here as well that I'm available for November 6th

**Comment by iamkevinv** [comment]
@elhedran - Would you also be available to present on the 13th?
I have come to learn that CampJS is still wrapping up on the same date of the event Monday 6th. In order to maximise attendance we may want to push the date back by 1 week - Monday the 13th Nov.

**Comment by iamkevinv** [comment]
Never mind, we are somewhat committed now 😉 see you Monday!

**Comment by iamkevinv** [comment]
Thanks for the presentation! If you have any resources you wanted to share, please feel free to add them here!

**Comment by iamkevinv** [comment]
@elhedran - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)
