### ISSUE TITLE
Scrolling through 100,000 items ~ a short demo/discussion

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#49]
##### I will be away for that little bit of May, so this can be in June or beyond

I'm all in favour of the Browser window being like a console that can stream or scroll through lots of information, i have been making an attempt at a page that can scroll thru 100,000 items 

### There have been a couple of recent talks on youtube that cover this:

Scrolling at 60 frames with core-list -- Polycasts #12
https://www.youtube.com/watch?v=2UKPRbrw3Kk&index=2&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN

"Performant UIs Using CSS Magic"
https://www.youtube.com/watch?v=ScXXBvs32Pg

The slickgrid virtual html table widget also does this, but i was unable to glean anything from the source (come to think of it: google maps google docs, cjax/ace/orion/codemirror lots of things probably do this sort of thing). So we'll re-label that "Performant UIs Using JS Magic" and hopefully be able to come up with something that lives up to the title.

By the time the meetup comes around, hopefully i will have had a go at doing it the same way the polymer element does, and can at least demo the thing i made -- which does something like garbage collection for dom elements, plus some attempt at graphing the on page element count and highlighting which blocks are in view onscroll, since i needed to see what was going on, and it's still a bit sketchy.

i was amazed to read on mdn, that when calling:
oldChild = element.removeChild(child);
 
### "The removed child node still exists in memory, 
but is no longer part of the DOM. You may reuse the 
removed node later in your code, via the oldChild object reference." 
https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild

which was not really what i wanted, so how does one fully remove a node? 
node.outerHTML='';node.outerHTML=null; or node.beGone(truely be gone)
i'm still not sure ~ which is why i propose a short demo/discussion

thanks
josh

**Comment by xwipeoutx** [comment]
I can answer your last question :) It gets cleaned up by the garbage collector if there are no references.

First thing to realise is that `child == element.removeChild(child)` is `true`. See http://jsbin.com/hefapoxoha/1/


Calling `element.removeChild(child)` simple detaches the element and returns the same variable. From there, the same garbage collection as any other javascript code takes over. So if you do, say, `window.removedElement = element.remove(child)`, it will stay in memory.  If you do `var removedElement = element.remove(child)`, the variable will get cleaned up when that variable is out of scope (which is at the end of the function or the current script file).

The detaching model is actually very helpful for performance - for example, keeping a pool of DOM elements ready to go is quicker than calling `document.createElement`.  

I believe jQuery and D3 use this to good effect - indeed `divElement.cloneNode()` is faster than `document.createElement('div')` - http://jsperf.com/clonenode-vs-createelement-performance/2

An interesting tidbit is that V8 has a pretty nasty memory leak if you're doing crazy things, like:

    var a = {};
    var b = { value: a };
    var c = { value: b };
    var d = { value: c };
    var e = { value: d };
    var f = { value: e };
    var g = { value: f };
    var h = { value: g };
    var i = { value: h };
    a.value = i;

From memory, it only follows references 7 deep

**Comment by govpack** [comment]
interesting, thanks

I've also been told that the garbage collection holds off while scrolling.

removeChild() returns a reference to the removed element which may be good for swapping things around, i'm not referencing the thing returned there directly, but i don't know if other things are, like do event handlers count? or nested things and closures from how the element arrived there in the first place, short of conducting a few experiments, i don't think it's ever that clear

there's some stuff around running: 
chrome.exe --enable-precise-memory-info --enable-memory-info --enable-memory-benchmarking --js-flags="--expose-gc"

with flags="--expose-gc" set window.gc() may be called explicitly, which of course is useless other than for testing, this page that says it doesn't work is out of date, window.gc() shows up for me: 
https://code.google.com/p/chromium/issues/detail?id=396574

and then use "window.performance.memory" 
or F12 to actually see if the code helps reduce the page load (todo) 

window.performance.memory ~ "Do not use. Proprietary. Chrome only. Gets quantized scripting memory usage numbers." https://docs.webplatform.org/wiki/apis/timing/properties/memory

the "Do not use" (seems like an invite to me) is safely ignored because chrome (or one of it's variants: chromium,canary,torch,nw.js,breach,atom shell,opera,etc) is the only browser i care about for this and it's mainly just for testing.

perhaps the better idea (like the polymer <core-list> tag does) is to restrict how many elements are being added in the first place.

also i've never noticed a problem with having loads of javascript objects/data in memory, but it may be nice to tune in a little bit more to what's happening there.

Also it starts off right then removeChild() but becomes remove() which I would prefer since it saves
typing, but it isn't a thing, which is why jsbin is cool because it will let you know
[1]<b id=bob ><a id=alice>hi</a></b><script>alert(bob.removeChild(alice).outerHTML)</script>

[2]<b id=bob ><a id=alice>hi</a></b><script>alert(bob.remove(alice).outerHTML)</script>
Uncaught TypeError: Cannot read property 'outerHTML' of undefined

or an example like the one at ~ http://jsbin.com/hefapoxoha/1/edit?html,js,output

<h1 id=bob><a id=alice href=# >&#x2693; Anchor</a></h1><script>alert('Pull up the anchor?');bob.innerText=(alice==bob.removeChild(alice))</script>

anything with an id has been added to the global namespace, at window['bob'] or self.alice or
just alice and bob, i've never understood why people use window.document.getElementById(id) or 
$('#alice' ) which started out as an alias for document.getElementById(id), so much when you can just refer to those things directly by name. Also i'd prefer to stay away from names that are confusable with existing dom methods/objects like: parent, parentElement, childNodes, etc since there is a parent.location.href or a parent==self or parent==top etc window object there already. 

i'm a fan of using d1,d2,d3,d4, etc as id's because they're short and you know where you're at, no time lost naming things, then you can use e = document.getElementById('d'+n) to get one of them arbitrarily which i think is a fair use of that method.

**Comment by xwipeoutx** [comment]
Yes, event handlers and closures count - but again, if nothing is holding
on to the event handler, or the function containing the closure, it's no
problem. IE <9 had some major issues with circular references between event
handlers and the DOM, but that was fixed in IE9.

Chrome ships with a memory profiler (see the "Profiles" tab of the dev
tools). Taking a memory snapshot performance garbage collect before
collecting the info.
[image: Inline image 2]

Also the "Timeline" tab of the dev tools has a little bin icon, which does
a garbage collect. No need to start chrome with any arguments at all,
unless you want programmatic access.
[image: Inline image 1]

This stuff very very rarely needs to be used - our particular issues were
having multiple angular applications per page with custom tear down code
and very VERY deep nesting of <ng-include> directives.  Also when rendering
thousands of shapes on a map (heatmap of US zip codes), with tooltips and
heavy interaction.  That's what happens when you try and jam new tech into
old code, I suppose!




God Bless
- Steve

**Comment by govpack** [comment]
what was the solution to that ? angular 2.0
i've been good at adding things to the page, but until now haven't really had to consider
removing them as well, nice thing about the browser is things work well even when coded badly,i need to know more about the dev tools, etc
