### ISSUE TITLE
Handling the logistics of in person meetups.

### ISSUE THREAD

**Issue by LayersOfAbstraction** [BrisJS/meetups#491]
Hi guys,

Just asking if the address you are planning to plan talks at was able to get a 5G signal? Or any form of 4G?

If I knew the address I might search online and see if an ISP supports 5G there. Just because quite a few doesn’t, doesn’t mean they all do.

**Comment by iamkevinv** [comment]
If it's back at the Auto & General venue that we had before, they have a guest wifi they would facilitate for us.
