### ISSUE TITLE
Surfing Midi Streams: Riding the websockets synthwave

### ISSUE THREAD

**Issue by julzelements** [BrisJS/meetups#492]
Presenter Name: Julz
Talk title: Surfing Midi Streams: Riding the websockets synthwave
Talk length: 1hr with audience interaction
Talk description: I've been teaching synth classes in various guises for a couple of years. My chosen education model synth is the Korg Monologue. And now it comes with a realtime classroom! I've built a platform that integrates with the hardware of the synthesizer and guides you through the journey of sound design.

Join me to explore websockets, Midi, and realtime event streams. Get ready to play with 6 (yes, 6!) synthesizers in the audience simultaneously!
Available month(s): August, Sept, Oct
Optional: https://www.linkedin.com/in/jrjscharf/

**Comment by julzelements** [comment]
I can knock this down to 40 mins no problem.

Make it the last talk of the night and then they can keep playing with the hardware afterwards.

**Comment by julzelements** [comment]
Would be good, but not necessary to have 6 tables with chairs around them, in a classroom style. But I'm very adaptable.

```
C C C   C C C
C T C   C T C
C C C   C C C 

C C C   C C C
C T C   C T C
C C C   C C C 

C C C   C C C
C T C   C T C
C C C   C C C 

FRONT STAGE
```

**Comment by iamkevinv** [comment]
Hey @julzelements - Could you please also confirm if you're available to present this at the October BrisJS? Seems like we also had the public holiday clash come up on Oct 2, So we'd be looking at Monday Oct 9th instead.
Why do i ask? Well, getting the sponsorship money organised is taking a little longer, and we'll miss our window by at least week. That week after, i will be unable to MC the events and handle the logistics. So we might end up making the next one a BrisJS social, and then re-launch in-person BrisJS with an even bigger bang.
Can you let me know asap? Thanks.

**Comment by theharold9000** [comment]
Hey @julzelements, we've confirmed that the October 9th meetup will be an in-person one at the Auto & General offices in Toowong - there's a chance we won't be tables available for a classroom style setup but I'll be scoping that out myself this week.

Are you still all good to present in October?

**Comment by julzelements** [comment]
I totally am. I can adapt the presentation to work with different setups, but tables is best.

**Comment by iamkevinv** [comment]
Thanks very much for making this happen mate! If you have links or resources you want to leave here, please feel free to reopen and add. Otherwise thanks again!
