### ISSUE TITLE
CampJS is on again 🏕️ 3rd - 6th Nov 2023

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#493]
Presenter Name: Glen Arrowsmith
Talk title: CampJS is on again
Talk length: 5 minutes
Talk description: CampJS is a 3-night code retreat for anyone who is interested in web technology.

The 2023 camp will be held at Koonjewarre (in Springbrook), on the Gold Coast Hinterland. The official camp schedule includes talks and workshops, but attendees also run other activities like bushwalking, drone flying, and even knitting.

My talk will show some photos of previous camps and promote the 
* CFP https://cfp.campjs.org/campjs-xi/cfp
* Website https://xi.campjs.org/
* Ticket sales https://ti.to/campjs/campjs-xi

Available month(s): August, Sept, Oct

**Comment by iamkevinv** [comment]
@garrows - You're coming right? You spruiking?

**Comment by garrows** [comment]
Yeah! I'll be there.
