### ISSUE TITLE
Talk: Achieving Inner Peace (with Javascript)

### ISSUE THREAD

**Issue by adam-pccw** [BrisJS/meetups#501]
**Presenter Name**: Adam A
**Talk title**: Achieving Inner Peace (with Javascript)
**Talk length**: 20 mins (can be made shorter or longer)
**Talk description**: This talk is a tour of all the ways to write production-ready JS in the most minimalist and stress-free way possible, eliminating many of the frustrations JS developers routinely deal with.

If you ever feel annoyed or tired starting new projects or dealing with the fast-paced JS ecosystem, this talk provides an alternative route that focuses on developer happiness and maximal code longevity. This is especially helpful for those with low working memory or with many personal projects to maintain.

**Available month(s)**:Oct, Nov

**Comment by iamkevinv** [comment]
Hey @adam-pccw :) Would you be available to present in person at the BrisJS event on Nov 6th? Just trying to get everyone's confirmation to post the lineup. Thanks :)

**Comment by adam-pccw** [comment]
Hey Kev, yeah that sounds good!

**Comment by adam-pccw** [comment]
I might have to leave after the first hour by the way, so would be great if I can start earlier :)

**Comment by iamkevinv** [comment]
Hey @adam-pccw - Would you also be available to present on the 13th?
I have come to learn that CampJS is still wrapping up on the same date of the event Monday 6th. In order to maximise attendance we may want to push the date back by 1 week - Monday the 13th Nov. 
Also, yes, we can put you up first on the lineup if you need to leave earlier.

**Comment by iamkevinv** [comment]
Never mind… we are somewhat committed now! See you Monday.

**Comment by adam-pccw** [comment]
Cheers, see you Monday

**Comment by iamkevinv** [comment]
Thanks for the talk mate! You can link your slides here or other resources if you like :)
