### ISSUE TITLE
Talk: What I've been up to (@balupton 2023)

### ISSUE THREAD

**Issue by balupton** [BrisJS/meetups#502]
Presenter Name: Benjamin Lupton @balupton 
Talk title: What I've been up to
Talk length: 30 min
Talk description: Recap of significant work since 2015, demo of Dorothy, demo of Boundation
Available month(s): November 6th, 2023
Optional: https://twitter.com/balupton

---

In 2015 I was fortunate enough to attend BrisJS and give a talk "What I've been up to" — https://www.youtube.com/watch?v=Lt_oKuaFgrg — I'd like to continue that this year at the November 6th meetup (if there is a slot available), as I'll be attending CampJS 2023 then heading down back to Brisbane for the BrisJS meetup.

I'd imagine the talk to be similar in duration at 30 minutes including Q&A, and in theme (covering technology and philosophy, which is where my focus has been the past decade).

WIP structure:

- 15 minutes: brief introduction, recap of significant work and learnings since 2015
- 5 minutes recap of [Dorothy, dotfiles for automated devops](https://cfp.campjs.org/campjs-xi/talk/review/PBAZPBF8FGTTSFWD8KWLXQRHLQ7ZZ33R)
- 5 minutes recap of [Auto-publish JavaScript/TypeScript/Node.js/Deno packages](https://cfp.campjs.org/campjs-xi/talk/review/GQKPPTETANY9M8DJDFKYPFTE3JHBWKVB)
- 5 minutes: q&a

**Comment by iamkevinv** [comment]
Thanks @balupton - Yes it's been a while! - Happy to add you to the lineup for Nov 6th :-) 
Can you confirm this is OK? I'm hoping to get everything announced in the next few days pending everyone's confirmation 👍

**Comment by balupton** [comment]
@iamkevinv let's do it!

**Comment by balupton** [comment]
Here are my notes for the talk:

* brief introduction
    * https://balupton.com/
    * https://github.com/sponsors/balupton
- campjs
    * https://xi.campjs.org/
    * https://cfp.campjs.org/campjs-xi/talk/7ZYUTK/
    * https://cfp.campjs.org/campjs-xi/talk/KF77SY/
* recap of significant work and learnings since 2015
    * https://github.com/BrisJS/meetups/issues/502
    * https://www.youtube.com/results?search_query=brisjs+lupton
    * https://www.youtube.com/watch?v=Lt_oKuaFgrg
    * hitchhike
        * [map](https://www.google.com/maps/dir/Perth+WA/Warburton+WA/Tennant+Creek+NT/Brisbane+QLD/Sydney+NSW/Melbourne+VIC/Adelaide+SA/Perth+WA/@-28.1305425,124.0839586,5z/data=!3m1!4b1!4m50!4m49!1m5!1m1!1s0x2a32966cdb47733d:0x304f0b535df55d0!2m2!1d115.861309!2d-31.9523123!1m5!1m1!1s0x2b0f275e8b53f5a3:0x400f6382479d300!2m2!1d126.5791676!2d-26.1350046!1m5!1m1!1s0x2b4c4c434ebb5449:0x40217a82a248420!2m2!1d134.1909565!2d-19.64591!1m5!1m1!1s0x6b91579aac93d233:0x402a35af3deaf40!2m2!1d153.0260341!2d-27.4704528!1m5!1m1!1s0x6b129838f39a743f:0x3017d681632a850!2m2!1d151.2092955!2d-33.8688197!1m5!1m1!1s0x6ad646b5d2ba4df7:0x4045675218ccd90!2m2!1d144.9630576!2d-37.8136276!1m5!1m1!1s0x6ab735c7c526b33f:0x4033654628ec640!2m2!1d138.6007456!2d-34.9284989!1m5!1m1!1s0x2a32966cdb47733d:0x304f0b535df55d0!2m2!1d115.861309!2d-31.9523123!3e0?entry=ttu)
    * trichotillomania
        * [how i overcame it](https://www.quora.com/How-do-I-overcome-trichotillomania/answer/Benjamin-Lupton?no_redirect=1)
        * deep work book
    * digital nomad in asia
        * 2017 - bali
        * 2018, 2019 - kuala lumpur
        * [the hatchery place](https://www.google.com/maps/place/The+Hatchery+Place/@3.0458535,101.5813945,16.99z/data=!4m6!3m5!1s0x31cc4cdaca0b7021:0xb2409f36cfd8b219!8m2!3d3.0458615!4d101.581378!16s%2Fg%2F11ddwxw53n?entry=ttu)
        * continue the traditions, you'll miss them less
        * [benday](https://www.instagram.com/stories/highlights/18020896111388878/)
    * philosophy study group and community
        * https://discuss.bevry.me/t/welcome-to-bevry/8
        * https://www.youtube.com/channel/UCPkobzBsAIjpItonUT7AU9Q / https://www.youtube.com/@bevry-podcast/streams / https://www.youtube.com/@bevry-podcast/videos
        * podcast
            * [lectures](https://discuss.bevry.me/t/about-the-study-notes-category/991)
                * maps of meaning
                * personality
                * meaning crisis
            * films
                * [social dilemma](https://www.youtube.com/watch?v=g7ip555kCco)
                * [eastern ww2 history](https://www.youtube.com/watch?v=Rsj6tygDoSI)
                * [wisdom in eastern cinema](https://www.youtube.com/watch?v=ZdfatGHRY2s)
            * papers
                * [meaning of meaning](https://www.youtube.com/watch?v=-dxuha3698U)
                * [complexity management theory: motivation for ideological rigidity and social conflict](https://www.youtube.com/watch?v=1Q9Zuwf2UII)
                * [evolutionary neurotheology and jungian psychology](https://www.youtube.com/watch?v=e2Uj83Fv5lc)
                * [kazinsky: the unabomber manifesto: industrial society and its future](https://www.youtube.com/watch?v=jzLaLmqHqV8)
                * [christchurch](https://www.youtube.com/watch?v=uYM42UR0hPU)
            * books
                * [notes](https://discuss.bevry.me/tag/books)
                * [podcast episodes](https://www.youtube.com/playlist?list=PL68A9KvUGBlq-szz3LSLufczHzYntrLR3)
                * [goodreads](https://balupton.com/goodreads) 
                * [beyond good and evil](https://www.youtube.com/watch?v=gqyey3utEcw)
                * [crime and punishment](https://www.youtube.com/watch?v=hdXUc46gx8s)
                    * if we do evil things, are we evil? if we are evil, should we align with our nature?
                * [homer's Iliad and odyssey](https://www.youtube.com/watch?v=NbVeGUrNtZA)
                    * what is a home that is worth sacrificing for
                * how to read a booker — adler
            * interviews
                * [michael toomin](https://www.youtube.com/watch?v=ALTohs4WLjc)
                * [randal rauser](https://www.youtube.com/watch?v=wXxgE0hWIn8)
                * [john vervaeke](https://www.youtube.com/watch?v=otbpbdrbAUU)
            * original research
                * [veganism](https://balupton/vegan) 
                * [are digital nomads traitors](https://www.youtube.com/watch?v=O8NdyHZeTEE)
                * [antinatalism](https://www.youtube.com/watch?v=EzEmocn8yb4)
                * [cultic forces](https://www.youtube.com/watch?v=dY50jVilaxc), [part 2](https://www.youtube.com/watch?v=M6RrNIY-DJQ)
                * [memetic warfare](https://www.youtube.com/watch?v=RGfrEM9ur_E)
                * [internet as a mistake/weapon/church](https://www.youtube.com/watch?v=VGI7ib6kjwk)
            * will be resumed in the coming months-year
        * major learnings re progress
            * mental health
                * prior talk started with first half on mental health of maintainers
                * you may have also noticed my bald spots
                * deep work and agency
            * person-persona divide
                * firmanent: https://kagi.com/images?q=firmanent
                * intrinsic identity vs extrinsic identity
                * acceptance
            * claiming one's future
                * a commitment to reclaim one's agency in the ever present moment
            * [purpose of humanities](https://www.youtube.com/results?search_query=balupton+purpose+of+humanities)
            * practices over goal
    * liberland
        * https://liberland.org/en/
    * fareness
        * https://fareness.dev/
        * https://thanks.dev/home
        * https://www.youtube.com/@thanks_dev/videos
    * coda
        * https://coda.io/@balupton/packs
* recap of [Auto-publish JavaScript/TypeScript/Node.js/Deno packages](https://cfp.campjs.org/campjs-xi/talk/review/GQKPPTETANY9M8DJDFKYPFTE3JHBWKVB)
    * https://github.com/bevry/boundation
* recap of [Dorothy, dotfiles for automated devops](https://cfp.campjs.org/campjs-xi/talk/review/PBAZPBF8FGTTSFWD8KWLXQRHLQ7ZZ33R)
    * https://github.com/bevry/dorothy
* q&a

Latest places to reach out are my twitch and my discords:

- [twitch](https://www.twitch.tv/balupton)
- [bevry software discord](https://discord.gg/nQuXddV7VP)
- [bevry travel discord](https://discord.gg/sCg2BURuS3)
- [bevry philosophy discord](https://discord.gg/x3AtPKHUPW)

**Comment by balupton** [comment]
@iamkevinv any chance of getting a copy of the recording?
