### ISSUE TITLE
Nestjs

### ISSUE THREAD

**Issue by jrwpatterson** [BrisJS/meetups#503]
Presenter Name:Joe Patterson 
Talk title: Nextjs, the app router and deploying without vercel! 
Talk length:30+min?
Talk description: Vercel is the obvious choice to deploy a Nestjs application. But some companies need to be on the same cloud provider. We had to build our app on aws but the app router it doesn't play nicely with amplify or serverless needing a solution that isn't out of the box so how did we do it?!
Available+month(s):November + 1st half of December 
Optional:+list+any+preferred+social+accounts+so+we+can+promote+you+and+your+talk

**Comment by iamkevinv** [comment]
Thanks so much for your submission @jrwpatterson :) 
November is looking pretty full already, but can you let me know just in case if you're available to present for this upcoming Nov 6? Otherwise, we'll definitely have a timeslot for you in the Dec meetup. I'll work out the final lineup and post back here of course. let me know!

**Comment by iamkevinv** [comment]
Hi @jrwpatterson - Can you confirm you will present on Monday 11th Dec? Thanks :)

**Comment by iamkevinv** [comment]
Sorry, i originally said 4th dec, but it was already set to 11th dec for availability reasons. It's Monday 11th.

**Comment by iamkevinv** [comment]
@jrwpatterson - I need your confirmation as the talks list will be out *today* 👍

**Comment by iamkevinv** [comment]
Updated: Joe wont be available monday. Pushed back to Feb schedule

**Comment by iamkevinv** [comment]
Hi @jrwpatterson! Just trying to make sure I can lock in the next event in Feb - Given that I'm late to chase up everyone's confirmations for attendance I may resort to moving the event to 12 Feb instead of 5th Feb (also giving me time to fix up the drinks supply sponsorship). I am however asking everyone if they're available for both dates, so I can make a determination. Please let me know ASAP if you can do a presentation on either 5th Feb or 12th Feb, or March 11th? Thank you!

**Comment by iamkevinv** [comment]
Hi @jrwpatterson - Can i lock you in for presenting on Monday 11th March? Please let me know as soon as possible. I will be overseas on business during 4-8th march so my replies, and time to organise things will be limited :)

**Comment by iamkevinv** [comment]
Hello - should i close this submission? Or would you like to plan it for an upcoming month? Thanks @jrwpatterson

**Comment by jrwpatterson** [comment]
Sorry I have git hub notificants turned off otherwise all my notifications are GitHub! I might make a change and make the talk about Vercel and running hybrid Vercel+Aws so all the benefits of Vercel but where Vercel is too expensive BYO aws which is what we are doing for our latest client leave it open I'll come back before the end of the week and confirm what the exact talk, might be different still I'll ask my team what's interesting them we have done recently!

**Comment by jrwpatterson** [comment]
> Hello - should i close this submission? Or would you like to plan it for an upcoming month? Thanks @jrwpatterson 

Ok I have a few talks I can talk about and happy to shorten them keep them as 4 and bring them in

- Alternatives to vercel for deploying Nextjs
- V0 ai website generation 
- Monolyths vs Microservices finding the best path for your project
- Feature toggles, A/B tests, building code that can be tested in production then measuring success!

**Comment by iamkevinv** [comment]
Would love to have your talks mate! 
Are you still keen on the originally listed one above, or would you prefer to draft up these others?

**Comment by iamkevinv** [comment]
Hey @jrwpatterson - I'd love to have you present something on monday - which talk would you be comfortable bringing to us?

- Nextjs, the app router and deploying without vercel!
- Alternatives to vercel for deploying Nextjs
- V0 ai website generation
- Monolyths vs Microservices finding the best path for your project
- Feature toggles, A/B tests, building code that can be tested in production then measuring success!

Please let me know which, and a bit of a talk description so i can add it to the line up asap please!
THANKS!

**Comment by jrwpatterson** [comment]
wait is it Monday will need to do something the next one, would be ready and very happy to speak at the next one, very happy but I've just got an email to invite me to my citizenship ceremony on Monday! So June 3rd? does that work

**Comment by jrwpatterson** [comment]
@iamkevinv but very keen on that date!

**Comment by iamkevinv** [comment]
June it is 👍

**Comment by jrwpatterson** [comment]
Perfect sorry to do it again! I am ready this week!

**Comment by jrwpatterson** [comment]
but been waiting for 6 months!

**Comment by iamkevinv** [comment]
6 months for the citizenship?

**Comment by jrwpatterson** [comment]
> 6 months for the citizenship?

no 6 months waiting for the ceremony!

**Comment by iamkevinv** [comment]
Hey mate - just confirming you for next Monday? I'm putting the final description up on meetup

**Comment by iamkevinv** [comment]
Oops I forgot to @ mention you - so @jrwpatterson lock you in for Monday June 3rd?

**Comment by jrwpatterson** [comment]
Yup should be good.

Will confirm talk tomorrow.

Has anyone done a run through of react 19/next 15 given all that was announced at Vercel Ship

**Comment by iamkevinv** [comment]
@jrwpatterson No they have not :)
Based on your comments above i'm left a little unsure what i'm telling everyone you're presenting... I'll put down the description you provided at the top of the issue... unless you let me know in time...? I'm working on sending the email now...

**Comment by iamkevinv** [comment]
https://www.meetup.com/brisjs/events/300126612/ this is the current description which i'll send out by morning! Ping me if something needs an edit! Thanks.

**Comment by jrwpatterson** [comment]
Nah make mine about the new next/react stuff I think that's really cool and very on topic

**Comment by jrwpatterson** [comment]
Something like 

React 19 and Nest 15

React 19 and Nest 15 have both been announced! What's new, why is this exciting and how will affect me?

We will take you on a wirlwind tour of the new compiler, the other big upgrades and what it means to your website.

**Comment by iamkevinv** [comment]
OK...updating...

**Comment by jrwpatterson** [comment]
Glad I'm second I should be there on time but I have to pick up kid from Churchie at 5:15 drop him off in Windsor the come to you so!

**Comment by iamkevinv** [comment]
Looking forward to having you present tonight. If you end up a little late, you may need to call Dev Zaveri our contact at Auto & General who facilitates the venue on the night - so you can get up the lift to the venue. His number is 0412 974 666. My phone is usually recording the talks but I'll have my Apple Watch connected as an all-else-fails backup contact point 0438 594 258. Let dev know you're a speaker that needs access up the lifts and you can wait at the Gallery level corporate tower lifts area.

**Comment by iamkevinv** [comment]
Actually it will be Mike Walton - 0400 896 121

**Comment by jrwpatterson** [comment]
Hey thanks again for for having me to speak last night.

If you want me to do any speech's, AI, Adchitecture, Frontend or Backend my colleagues all say I love the sound of my own voice and I'm happy to help out 

Just ping me on 0417347833.

**Comment by iamkevinv** [comment]
Thanks so much for your presentation mate! Much appreciated! 
I would love to schedule in your upcoming talks. Let's add them as separate entries in GitHub issues and we can work out where to add them into the upcoming months.
Sorry for all the logistics issues last night - we're working with A&G to make things smoother in future too.

**Comment by jrwpatterson** [comment]
Done I think you have my linked in other wise ping me a text on 0417347833 or ping me a email!

**Comment by iamkevinv** [comment]
Thanks mate, if you want to link any additional resources here for this one feel free! I'll close for now.
