### ISSUE TITLE
Element: HTML For The Next Generation Web (talk submission)

### ISSUE THREAD

**Issue by drpitman76** [BrisJS/meetups#505]
Talk title: Element: HTML For The Next Generation Web

Talk length: 40 min

Talk synopsis:
Element is an open source web development framework built to unlock the full potential of the modern web + web3. This session will demonstrate how Element enables lightning-fast development of complex, modular web applications through inheritable web components, declarative routing and data binding, and a streamlined HTML-first architecture.

First exploring Element's history and design goals, including write-once-use-anywhere code reuse, granular DOM updates, and simplified tooling. Live coding will showcase building a dynamic app in Element complete with reusable components, routing, data binding, optional pre-rendering for production optimization and through to deployment.

Element provides a solid foundation for the next generation of web applications (and web3 dapps). Attendees will learn how to leverage Element's capabilities for their own projects and contribute to a coming ecosystem of components and tools. The future of web development starts with Element.

(Note: I am the author of Element, so I am introducing my own product here, it is currently in late alpha and is on track to be a solid beta release by November/December 2023. More details can be found at [elementhtml.dev](https://elementhtml.dev)  ).

Available month(s): December preferably, otherwise as soon after that as you like...

**Comment by iamkevinv** [comment]
Hi @drpitman76 - You're also welcome to do this one if you prefer? Otherwise Feb is another option for you. Please let me know which you're presenting on Monday 11th. Thanks!

**Comment by iamkevinv** [comment]
Sorry, i originally said 4th dec, but it was already set to 11th dec for availability reasons. It's Monday 11th.

**Comment by drpitman76** [comment]
I would prefer to do this one if possible!

**Comment by iamkevinv** [comment]
Thanks for the talk! Any links to presentation materials or resources would be appreciated :)

**Comment by drpitman76** [comment]
This is the link to the Slides I used on the night: https://docs.google.com/presentation/d/1O5MrXlaGormMeO25ddtEvXwWgPe6cHzjINmya_HEzdU/edit?usp=sharing

Otherwise the website for the framework itself: https://elementhtml.dev/

**Comment by iamkevinv** [comment]
@drpitman76 - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)

**Comment by drpitman76** [comment]
Sure, I would happy to do that - feel free to pass on my details or let me know how to follow up...
