### ISSUE TITLE
Talk: (Don’t) Stay Hydrated – A Look at Server Components, Astro and Qwik and Why We Need Them

### ISSUE THREAD

**Issue by julianburr** [BrisJS/meetups#506]
Talk title: (Don’t) Stay Hydrated – A Look at Server Components, Astro and Qwik and Why We Need Them

Talk length: can do either 20 min or 30 min

Talk description:
What is "hydration" and why is it a problem? Let's have a look at how modern server side rendering works with frameworks like React, what the hydration bottleneck is, and how Server Components as well as some new frameworks like Astro and Qwik try to address this through "partial" or even "zero hydration".

Available month(s): Dec 2023 forward

Twitter: https://twitter.com/jburr90

**Comment by iamkevinv** [comment]
Awesome! Looking forward to this!

**Comment by iamkevinv** [comment]
Hi @julianburr - Can you confirm you will present on this Monday 11th Dec? Thanks :)

**Comment by iamkevinv** [comment]
Sorry, i originally said 4th dec, but it was already set to 11th dec for availability reasons. It's Monday 11th.

**Comment by iamkevinv** [comment]
@julianburr - Hi Julian - just really need your confirmation that you're presenting this monday at BrisJS? I'm putting the lineup emails out today as i'm already quite late trying to get everyone's confirmations :) Thanks!

**Comment by julianburr** [comment]
@iamkevinv Sorry, didn't see the notifications. I'm in Sydney next week, unfortunately, so won't be able to present. Sorry, should have updated the availability in the original message 😞

**Comment by iamkevinv** [comment]
Hi @julianburr! Just trying to make sure I can lock in the next event in Feb - Given that I'm late to chase up everyone's confirmations for attendance I may resort to moving the event to 12 Feb instead of 5th Feb (also giving me time to fix up the drinks supply sponsorship). I am however asking everyone if they're available for both dates, so I can make a determination. Please let me know ASAP if you can do a presentation on either 5th Feb or 12th Feb, or March 11th? Thank you!

**Comment by julianburr** [comment]
@iamkevinv yes, I'm good for both Feb 5th and Feb 12th 👍😊 

how much time should I plan for? 20min or 30min?

**Comment by iamkevinv** [comment]
At least 20, up to 25 if you're struggling to contain it, and i always assume there's 5min on top or so for questions. :) Does that help?

**Comment by iamkevinv** [comment]
The timeline is too tight to handle logistics and get everyone properly notified to get a good turn out, so i'm going to push it back to 12 Feb. I'll update meetup.com and start adding everyone's talk details there for the announcement :) I'll confirm you for the 12th Feb - locked in!

**Comment by iamkevinv** [comment]
Thanks again for your presentation for Feb! If you have any resources you want to share here that would be great :)

**Comment by iamkevinv** [comment]
@julianburr - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)

**Comment by julianburr** [comment]
Hey @iamkevinv , sorry I really need to monitor my github notifications better 😕

Generally always open to redo this and other talks if it helps, just did a refined version of this talk at React Connection 😊

**Comment by julianburr** [comment]
Also here the slides from the original talk, cause I forgot to post them as well: https://www.canva.com/design/DAF7t5BbuU8/Gv-1KCn5dctl9OKp7vFFsw/edit?utm_content=DAF7t5BbuU8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by iamkevinv** [comment]
Thanks mate!
