### ISSUE TITLE
Medium talk: How to cheat at testing in JavaScript (and still have great tests)

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#507]
Making the most of my CampJS talk, if you want it for BrisJS early in 2024 ;)

**Talk time:** 30 mins

**Title:**  How to cheat at testing JavaScript (and still have great tests)

**Abstract:**

Testing is hard.

When we do it well everything just works and it kinda feels like testing was a waste of time.

When we do it badly, things are usually broken and we wished we had done more testing.

What if told you there was a better middle ground. A place somewhere in the middle where testing doesn't cost as much and can deliver a lot more bang for your buck.

In this talk we'll cover various testing techniques that will make you more effective with much less effort. 

Join software craftsman and author Ashley Davis and learn how to be more effective at testing in JavaScript.

**Comment by iamkevinv** [comment]
@ashleydavis - any possibility you can fill in with a talk for Monday BrisJS? I just happen to have lost two speakers at the last minute.

**Comment by ashleydavis** [comment]
Hey @iamkevinv I'd probably need a short talk, but I can't think of anything right now. If something comes to mind I'll let you know.

**Comment by ashleydavis** [comment]
Hey @iamkevinv, I just thought that if you still need a short talk for Monday night I could give a demonstration of DFN v2?

**Comment by iamkevinv** [comment]
More than happy to do that :)

**Comment by ashleydavis** [comment]
Ok cool, put me down for it. Just 10 minutes or so.

**Comment by iamkevinv** [comment]
As discussed, moving your talk to March due to availability.

**Comment by ashleydavis** [comment]
Thanks @iamkevinv

**Comment by iamkevinv** [comment]
Hi @ashleydavis - Can i lock you in for presenting on Monday 11th March? Please let me know as soon as possible. I will be overseas on business during 4-8th march so my replies, and time to organise things will be limited :)

**Comment by ashleydavis** [comment]
Yeah I'm in for the 11th.

**Comment by iamkevinv** [comment]
Awesome thanks for being quick!, if we get any replies on the other two speakers, we can confirm!.... if not, we need to skip this upcoming month.

**Comment by iamkevinv** [comment]
Hi @ashleydavis - A customary confirmation that you are still OK to do for this Monday the 8th? Looks like we have one additional speaker and we could potentially pull it off. :)
