### ISSUE TITLE
Introduction to Canvas & Multiplayer Web Game Development

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#509]
Talk title: Introduction to Canvas & Multiplayer Web Game Development
Talk length: 40 min
Talk synopsis: This talk starts with the canvas element and teaches how to draw on it. We then add some basic gravity to start building a game. Keyboard input is added. Then we dive really deep by adding realtime multiplayer using WebSockets.
Available month(s): Feb, Mar.
Optional: https://x.com/garrows

**Comment by iamkevinv** [comment]
Thank you sir! Any links to presentation materials are appreciated!

**Comment by iamkevinv** [comment]
@garrows - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)

**Comment by garrows** [comment]
Apologies for the slow response @iamkevinv . 

Here's the slides & code https://github.com/garrows/canvas-intro-and-game-dev

You can pass my email along to SydJS folks if they're still after people. glen.arrowsmith@gmail.com
