### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by marklawlor** [BrisJS/meetups#51]
Hey guys,

Like we previously discussed in #45 I'm happy to do a couple of talks on unit testing. After giving it some thought, I'm going to split it into two talks. 

The first will be to the merits of unit testing and test-driven development. 

The second talk will compare libraries and showcase different workflows.

If you have an existing workflow that you think its awesome or some fancy testing library, let me know as I've love to include real world examples.

**Comment by garrows** [comment]
Sounds like a great talk.
I would like to hear your thoughts on functional tests vs unit tests.

For example to test user registration my tests would:
* drop the db
* start the web server
* use request to register a user
* test expected response

Cheers
Glen

**Comment by csinge** [comment]
Hi Glen,

I have a fairly good example of how I do that with grunt and protractor, I
would be happy to walk people through it

Cheers
Cameron

On Wed, Apr 15, 2015 at 12:29 PM, Glen Arrowsmith <notifications@github.com>
wrote:

> Sounds like a great talk.
> I would like to hear your thoughts on functional tests vs unit tests.
>
> For example to test user registration my tests would:
> * drop the db
> * start the web server
> * use request to register a user
> * test expected response
>
> Cheers
> Glen
> On 15/04/2015 11:45 am, "marklawlor" <notifications@github.com> wrote:
>
> > Hey guys,
> >
> > Like we previously discussed in #45
> > <https://github.com/BrisJS/meetups/issues/45> I'm happy to do a couple
> of
> > talks on unit testing. After giving it some thought, I'm going to split
> it
> > into two talks.
> >
> > The first will be to the merits of unit testing and test-driven
> > development.
> >
> > The second talk will compare libraries and showcase different workflows.
> >
> > If you have an existing workflow that you think its awesome or some fancy
> > testing library, let me know as I've love to include real world examples.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/BrisJS/meetups/issues/51>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/51#issuecomment-93156667>.
>



-- 
Cameron Singe
Mobile : 0468 336 808

**Comment by marklawlor** [comment]
@garrows Thats mostly what I'd like to cover in the first talk, explaining what is unit testing how its different from the other testing methodologies (Integration/E2E, Functional, Regression, etc).

@csinge Protractor is for E2E testing, which has larger scope than unit testing and probably won't be covered in my talk. Still I'd see like to see examples on what the community is doing for testing. If you could post a gist it would be very helpful.

**Comment by xwipeoutx** [comment]
I wrote a browser based Javascript test runner, because the ones out there didn't cut it for me (I know, I know...)

It's called Basil, you can see some info on my [blog](http://stevesspace.com/projects/basil.html) or there's some [samples](http://stevesspace.com/projects/basil/samples/sample-test.html) available, the main advantage being it's infinitely hierarchical, and there's no annoying 'setup' and 'teardown' functions to call to do that - increasing the readability pretty dramatically.

We use it at work, where it runs about 8500 unit tests (Maybe 20 or so are more like integration/smoke tests) in under 2 minutes (with embarrassingly parallel speedup).

Not exactly sure what my point is here, but if we want a quick demo of a locally developed test runner, and good ways of handling complicated set up

As for workflow, `gulp-watch` and `gulp-livereload` are amazing.

**Comment by csinge** [comment]
Hi Mark,

I do also have similar examples at the integration layer

Cheers
Cameron

On Wed, Apr 15, 2015 at 4:03 PM, Steve Leigh <notifications@github.com>
wrote:

> I wrote a browser based Javascript test runner, because the ones out there
> didn't cut it for me (I know, I know...)
>
> It's called Basil, you can see some info on my blog
> <http://stevesspace.com/projects/basil.html> or there's some samples
> <http://stevesspace.com/projects/basil/samples/sample-test.html>
> available, the main advantage being it's infinitely hierarchical, and
> there's no annoying 'setup' and 'teardown' functions to call to do that -
> increasing the readability pretty dramatically.
>
> We use it at work, where it runs about 8500 unit tests (Maybe 20 or so are
> more like integration/smoke tests) in under 2 minutes (with embarrassingly
> parallel speedup).
>
> Not exactly sure what my point is here, but if we want a quick demo of a
> locally developed test runner, and good ways of handling complicated set up
>
> As for workflow, gulp-watch and gulp-livereload are amazing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/51#issuecomment-93208335>.
>



-- 
Cameron Singe
Mobile : 0468 336 808

**Comment by ashleygeorgeclarke** [comment]
Thanks for the talk @marklawlor, really enjoyed it

**Comment by kevdesign** [comment]
Awesome. Thanks! Can you link slides and things here too? I'll add the label then.
