### ISSUE TITLE
Presentation: Building GitHub Actions with TypeScript

### ISSUE THREAD

**Issue by jbristowe** [BrisJS/meetups#510]
**Building GitHub Actions with TypeScript**
This presentation dives into the world of [GitHub Actions](https://github.com/features/actions), showing you how to build them with TypeScript. It provides a clear overview of GitHub Actions and explains their significance and mechanics within GitHub. The presentation then shifts to a practical guide, describing how to create GitHub Actions using TypeScript. You'll learn how to use the GitHub ToolKit for building GitHub Actions. This presentation will feature real-world examples and hands-on demos. It will use everything from scripting custom actions to utilizing the GitHub API.

This presentation is suitable for developers at any level.

Length: 20-30 minutes (flexible)

**Comment by iamkevinv** [comment]
Excellent :) Thanks for the submission!
When were you thinking? Feb we start back up... but might have everyone wanting to go at once :) I'll add you to the Feb milestone and we'll sort out scheduling.

**Comment by jbristowe** [comment]
February is fine! Or, March.

**Comment by iamkevinv** [comment]
Hi @jbristowe! Just trying to make sure I can lock in the next event in Feb - Given that I'm late to chase up everyone's confirmations for attendance I may resort to moving the event to 12 Feb instead of 5th Feb (also giving me time to fix up the drinks supply sponsorship). I am however asking everyone if they're available for both dates, so i can make a determination. Please let me know asap if you can do a presentation on either 5th Feb or 12th Feb, or March 11th? Thank you!

**Comment by jbristowe** [comment]
I'm available for all three dates.

**Comment by iamkevinv** [comment]
The timeline is too tight to handle logistics and get everyone properly notified to get a good turn out, so i'm going to push it back to 12 Feb. I'll update meetup.com and start adding everyone's talk details there for the announcement :) I'll confirm you for the 12th Feb - locked in!

**Comment by iamkevinv** [comment]
Thanks again for your presentation for Feb! If you have any resources you want to share here that would be great :)

**Comment by jbristowe** [comment]
![image](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjJyeGpiMjRrNW82dnZvNHlpNnliOXo2Zmxyc2ZwYmdwazJjNG1hNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/7bumBQjZX8BgaE2zjv/giphy.gif)

**Comment by iamkevinv** [comment]
@jbristowe - SydJS is looking for some folks who could provide some presentations (remotely via livestream) and have asked if some of our previous presentations might be keen to repeat their talks? Their initial target was March 20th which is quite soon. Let me know if this might be of interest to you? (or if not possible perhaps a future date?)

**Comment by jbristowe** [comment]
I’ll be at KubeCon in Paris next week.

**Comment by iamkevinv** [comment]
Not a problem mate, thanks for the super speedy comms as usual.
