### ISSUE TITLE
Boosting Static Web Application Performance: Client-Side Techniques for Optimal User Experience

### ISSUE THREAD

**Issue by drpitman76** [BrisJS/meetups#511]
**Talk length**: 20 mins or so

**Synopsis**: 
In this talk, I will explore a range of client-side techniques that can significantly enhance the performance of static web applications. Leverage the power of vanilla HTML, CSS, and JavaScript, to optimize web performance without relying on specific frameworks or server-side techniques. Gain insights into best practices and practical strategies to improve loading times, minimize resource consumption, and deliver a seamless user experience across devices.

Available for April 2024 or beyond...

**Comment by iamkevinv** [comment]
Hi @drpitman76 - Thank you for stepping up to help us continue BrisJS on the upcoming Monday - can you confirm that this would be OK to do for this Monday the 8th?

**Comment by drpitman76** [comment]
Yep, that's fine with me! I'll be happy to do this talk on Monday 8th...

**Comment by drpitman76** [comment]
Here is the link to the slides used in the talk: https://docs.google.com/presentation/d/1PrUEpmorVyutXJvsAk48uSYl2_4PQXKZivqD1Z3AwGc/edit?usp=sharing

**Comment by ankitbtanna** [comment]
This was an excellent talk @drpitman76 Thank you so much :)
