### ISSUE TITLE
API First

### ISSUE THREAD

**Issue by dallasclark** [BrisJS/meetups#512]
Talk Length: 40 minutes

I'd like to talk about API First (>= June) and why Magentus Practice Management is focusing on this initiative with a couple of foundation steps.

The talk will cover why API First, what issues we've identified, and our plans to roll out this initiative.

Most of us know what API First is but what it entails and its impact are often not considered.

This is a leadership and strategy-based talk.

**Comment by iamkevinv** [comment]
Thank you sir :) 
Pop a few more talk details on when you get the chance and I'll include it in the upcoming line up soon

**Comment by iamkevinv** [comment]
Hey @dallasclark are you still locked in for monday? Did you want to include any other details you want me to use for the meetup page?

**Comment by dallasclark** [comment]
Hey Kevin,

I won't be able to do it until Monday, 3rd June sorry.

**Comment by iamkevinv** [comment]
Ah yeah you did say that in your first description. That's my bad. I've updated the Milestone to June. Thanks.

**Comment by iamkevinv** [comment]
Hello @dallasclark! Can I confirm your talk for Monday 3 June 😀

I'm putting the final description up on meetup

**Comment by dallasclark** [comment]
> Hello @dallasclark! Can I confirm your talk for Monday 3 June 😀
> 
> I'm putting the final description up on meetup

Yep, good to go!

**Comment by dallasclark** [comment]
The description is updated, feel free to edit.

**Comment by iamkevinv** [comment]
We only have the two speakers this month, so if you'd like a 30min slot too, you got it :)

**Comment by dallasclark** [comment]
As in 2 talks?

**Comment by iamkevinv** [comment]
Yes there are two speakers, one talk each, instead of the usual 3 speakers formula for the night. Given it's a talk before pizza and a talk after pizza we can allow both to be the full 30min blocks as we're not pushed for time in the 2nd half.

**Comment by dallasclark** [comment]
My talk may take 40 minutes, I’ve cut a bit out already but can cut more to fit it in within 30 minutes.

**Comment by iamkevinv** [comment]
Thanks again mate! If you want to link any additional resources here please feel free.
