### ISSUE TITLE
Whole Modules

### ISSUE THREAD

**Issue by jamesdiacono** [BrisJS/meetups#513]
https://james.diacono.com.au/whole_modules.html

**Comment by iamkevinv** [comment]
Thanks so much @jamesdiacono - sorry i didn't get my reply through earlier but we'd be thrilled to check this out further... are you available to present on monday?

**Comment by jamesdiacono** [comment]
Sorry, I can't do monday. What dates will BrisJS meet in June and July?

**Comment by iamkevinv** [comment]
Should be June 3, July 1... don't think there's any more public holidays to get in the way. Hows that work for you @jamesdiacono ?

**Comment by jamesdiacono** [comment]
I think the 1st of July works best for me.

**Comment by jamesdiacono** [comment]
I noticed you applied the "Regular talk (20 mins)" tag. Can I go for longer? I am thinking my minimum time will be about 40 mins.

**Comment by iamkevinv** [comment]
Sure! I can bump you to the 30min slot 👍 and then I factor in additional time for questions after so it ends up at around 40 - how does that sound?

**Comment by jamesdiacono** [comment]
That sounds fine, thanks.

**Comment by jamesdiacono** [comment]
If it's not too late, I'd like to change the name of my talk to "Whole Modules".

**Comment by jamesdiacono** [comment]
Uh oh, has the date changed to the 8th of July?

**Comment by iamkevinv** [comment]
Hello - yes it had to be changed as I'm not able to host in the coming week. Earliest is the week after. Can you still make it?

**Comment by jamesdiacono** [comment]
I think I'll just explain my situation and then maybe we can find a solution.

I live near Sydney. After locking in the 1st of July, I planned a weekend up in Brisbane and booked accomodation, etc. My partner is flying in to Brisbane tomorrow morning, and I'm halfway to Brisbane in my car right now. So I'm definitely in Brisbane this weekend (which will be lovely) but I have to drive back Tuesday morning. I just don't know if I can justify another trip up to Brisbane next Monday. I won't have time to drive, and it's a bit late to book cheap flights.

Do we have any other options?

**Comment by iamkevinv** [comment]
Ah I had no idea of course, so sorry about that mate. Yeah unfortunately a week long event has gotten in the way which means we either have to move it or skip a whole month. 
Is there another month which you’d like? Or should we attempt streaming you in on the night? (Never before attempted)
- Kev

**Comment by jamesdiacono** [comment]
I'd really like to meet you all in person, perhaps we could push it back to September?

**Comment by iamkevinv** [comment]
Hey mate, of course! If you want to aim for Sept let's do that, and try to keep in touch and make sure the date is set in stone before anything is booked on your end. Very sorry about all of the hassle!

**Comment by jamesdiacono** [comment]
No worries, sounds good!

**Comment by jamesdiacono** [comment]
It's sounding like I can be in Brisbane for the 2nd of September, if you have a free slot?

**Comment by iamkevinv** [comment]
Of course! You were scheduled, in anticipation ☺️👌 Looking forward to it.

**Comment by jamesdiacono** [comment]
Sorry to do this to you, but some of my plans have changed and it doesn't look like I'll be in Brisbane in September after all. I'm still keen but it will have to wait until something brings me to Brisbane again.

**Comment by iamkevinv** [comment]
Thanks for letting me know :) We will bump this entry by a month and keep checking in :)

**Comment by iamkevinv** [comment]
Hi @jamesdiacono - The next event schedule is 14th Oct, Is this something you can target for presenting? Or would you prefer something like Nov?

**Comment by jamesdiacono** [comment]
I'm away all October, but November could probably work.

**Comment by jamesdiacono** [comment]
Any idea what date the November meetup would be?

**Comment by jamesdiacono** [comment]
The 4th?

**Comment by iamkevinv** [comment]
Hey there @jamesdiacono - Yes, Nov 4th :) - Will you be joining us?

**Comment by jamesdiacono** [comment]
Yep, lock it in.

**Comment by jamesdiacono** [comment]
Here is the updated blurb:

> Experienced programmers know instinctively that modularity is very important. Even so, many of our popular practices and tools promote poor modularity, condemning us to needless toil and suffering.
> 
> In this talk, I share a personal story of a software project gone wrong: the mistakes, the diagnosis, and how it eventually got turned around.
> 
> I discuss some principles of good modularity, and how they let us detect problems in a codebase earlier rather than later.
> 
> Lastly I present Whole Modules, a new technique for JavaScript that takes modularity to the extreme. I demonstrate Whole Modules in both frontend and backend environments, arguing that it can help us write better software, faster and with less pain.

**Comment by iamkevinv** [comment]
See you tonight at the in-person meetup @jamesdiacono :)

**Comment by iamkevinv** [comment]
Thanks very much for your talk! We finally got you there haha. Appreciate all the travel that you've gone through to visit us. Hope to see you back for another one! If you have any links for the audience or resources, please add them here :)

**Comment by jamesdiacono** [comment]
Thanks for having me! I enjoyed meeting you all, with any luck I will bring another talk someday.

Replete on GitHub: https://github.com/jamesdiacono/Replete
Replete Playground (with tutorial): https://repletejs.org/play/
Whole Modules explained: https://james.diacono.com.au/whole_modules.html
