### ISSUE TITLE
Build Chrome extensions to super power your SaaS

### ISSUE THREAD

**Issue by dkarzon** [BrisJS/meetups#514]
**Talk Volunteered** 
Talk title: Building a Chrome extension
Talk length: 20 min
Talk synopsis: At Pinch we recently launched a Chrome Extension for our customers to give them contextual payment information while they are in other connected systems. Let's take a look at what it took to build this Chrome extension and what kind functionality a Chrome extension might open up for you.
Available month(s): Anytime

*Summary:*
At Pinch we recently launched a Chrome Extension for our customers to give them contextual payment information while they are in other connected systems. Let's take a look at how to go about building a chrome extension with react, making use of the Chrome Runtime and Side Panel APIs, understanding extension permissions (What you can get access to without asking and what you can ask for) and tying it all together into a seamless user experience.

**My Info**
Damian Karzon

BIO: Damian currently manages the developer program at Pinch Payments, building, maintaining and talking about products such as an API payment gateway and an accounting system integrated invoice automatic payment solution. In the past has worked for many other start ups and has experience across a wide range of technologies from frontend and backend web frameworks, to mobile apps and games to TV and console apps.

LinkedIn: https://www.linkedin.com/in/dkarzon/
Video showing our extension in action: https://www.loom.com/share/0c15f2459f364216ba31a0eedcf20409

**Comment by iamkevinv** [comment]
Hi @dkarzon - Would you be available to present this at monday's BrisJS? 8th July.

**Comment by dkarzon** [comment]
@iamkevinv That is a bit too soon, I'm not ready for it just yet 😕

**Comment by iamkevinv** [comment]
All good - let's aim for Aug then!
No worries, sorry to attempt to jump onto it - just in some desperate need to add more folks to the lineup 🙏

**Comment by dkarzon** [comment]
That I can work with 👍
I am giving the same talk at ReactBris in August as well, hopefully that isn't a problem?

**Comment by iamkevinv** [comment]
I added more buffer time since we have it... 30mins for each speaker now instead of the 20. See you monday.
https://www.meetup.com/brisjs/events/301577326/

**Comment by iamkevinv** [comment]
Thanks mate!
