### ISSUE TITLE
Nestjs Monorepos

### ISSUE THREAD

**Issue by jrwpatterson** [BrisJS/meetups#515]
Why Monolyths rule! And if you must go building microservices build them in a Monorepo!

Big teams can build big projects! But for most of us not working for google or Netflix we are used to working with small teams.

Try by to break up projects causes systematic failures where teams end up spending more time maintaining the complexity than trying to actually build code! 

@samjmarshall may want to do a follow up about simpler APIs to go with this!

**Comment by iamkevinv** [comment]
Hi @jrwpatterson - are you available to present this talk at our 8th July Monday meetup? This or #516?

**Comment by iamkevinv** [comment]
Hi @jrwpatterson - are you still keen to do this talk at the Sept meetup next week?

**Comment by jrwpatterson** [comment]
Yup I can talk!

**Comment by iamkevinv** [comment]
brilliant! I will lock you in and see you monday 2nd @jrwpatterson :)

**Comment by iamkevinv** [comment]
See you tonight at BrisJS @jrwpatterson :)

**Comment by iamkevinv** [comment]
Thanks for the talk and support mate :) Cleaning up the closed events now :) If you have links of resources to share, please feel free to add.
