### ISSUE TITLE
Vercel not just a platform

### ISSUE THREAD

**Issue by jrwpatterson** [BrisJS/meetups#516]
Vercel is a PAAS. Well that's what everyone thinks!

In reality it's so much more, from why it's an awesome PAAS to AI and more. This talk wants to walk you all through the features and guide when to use it and when not!

**Comment by iamkevinv** [comment]
Hi @jrwpatterson - are you available to present this talk at our 8th July Monday meetup? This or #515?

**Comment by iamkevinv** [comment]
Thanks again for last months talk! If you know someone who could fill in for a Monday talk that would still be great!
