### ISSUE TITLE
Long Talk: The Big Crypto Talk

### ISSUE THREAD

**Issue by adam-pccw** [BrisJS/meetups#518]
**Presenter Name**: Adam A
**Talk title**: The Big Crypto Talk
**Talk length**: 30mins
**Talk description**: 

This is a big picture talk walking through many facets of JS and crypto, aimed at beginners and experts alike. We'll start with some basics and gradually move onto the current start-of-the-art.

The name is total clickbait, crypto here does not refer to cryptocurrency! (though it is all related).

**Available month(s)**: All the months

**Comment by iamkevinv** [comment]
Love it. I'll send out the notice this morning!

**Comment by iamkevinv** [comment]
Thanks again!
