### ISSUE TITLE
Medium talk: Streamlining contract testing

### ISSUE THREAD

**Issue by ashleydavis** [BrisJS/meetups#519]
Duration: 20-30 mins

Are you looking for a simpler form of contract testing? 

Do you want good test coverage for much less effort?

In this talk Ashley shows a drastically simplified approach to contract testing, get many of the benefits of contract testing for much less work and provide a platform from which to convince your team of just how much contract testing can help in preventing problems going out to production.

**Comment by iamkevinv** [comment]
Hey @ashleydavis - we're good to go to present this at the upcoming brisjs! thanks for volunteering it!

**Comment by iamkevinv** [comment]
Now i just need to confirm our 2nd speaker

**Comment by ashleydavis** [comment]
Good news @iamkevinv, thanks so much.

**Comment by iamkevinv** [comment]
We're on! I'll announce it now :)

**Comment by iamkevinv** [comment]
See you tonight at BrisJS @ashleydavis  :)

**Comment by iamkevinv** [comment]
Thanks for presenting mate! Closing and cleaning up issues now.
