### ISSUE TITLE
Brisbane NodeJS Jobs

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#52]
Hi javascripters,

There are 3 NodeJS developer jobs going at IIX in Brisbane. 
https://boards.greenhouse.io/iix/jobs/58125

IIX is expanding and has a bunch of other jobs available. Here is the full list https://boards.greenhouse.io/iix#.VS7PoxOUeQw 

These are some that you or your friends might be interested in:

* Senior Software Engineer - Backend
* Senior Middleware Developer - Web Platform
* Systems Engineer - Web Platform
* GUI Designer
* Technical Writer
* Quality Engineer (Middleware)
* Quality Engineer - Web Platform
* Senior Software Development Engineer in Test

Note that there is a bunch of overseas jobs but if you're the right person, you could probably work from the Brisbane office or even from home.

If you want to know more about IIX than what the job descriptions mention then maybe read about them a little in the news https://www.google.com.au/search?q=iix&tbm=nws 

I apologise for all the spam. To make up for it, IIX is going to be sponsoring the next BrisJS.

If you have any questions that you want kept private you can email me directly at garrowsmith@iix.net

**Comment by garrows** [comment]
Hi all,
just an update on this. We have filled most of the positions but we are still really looking for some full stack web devs with nodejs experience. Please apply to me garrowsmith@iix.net. I'll be at the drinks on Thursday so if you have any questions, I'm the tall one with the big ginger beard. Here is the job description: 

### The Company
IIX Inc., the global software-defined interconnection company, is
headquartered in Silicon Valley, California. The company’s SDI™ platform
enables programmable interconnection between networks that allows customers to
gain more control, improve security, reduce costs associated with IP transit
delivery, optimize network performance and extend network reach across the
globe. IIX customers include content providers, data center providers,
Internet Service Providers (ISPs), carriers and other enterprises globally.
We are building an extraordinary team here at IIX with a goal of delivering
fast, simple and secure interconnection solutions globally to benefit both our
customers and their end users.


### The Role
We hire those who display our values, have deep expertise in serving clients
and are passionate about advances in the internet backbone and IT space. We
look for self-motivated professionals who have a commitment to excellence,
offer a personal approach to service, enjoy a challenge and are dedicated to
pursuing growth and learning. The entrepreneurial spirit is a must in this fast
paced, growing organization.

In this role, you will be responsible for the initial development effort turning user interface designs into mobile and browser based web applications. You will have the opportunity to be exposed to the entire product stack and work with our globally distributed team, through integration testing from our web platform products. In addition, this position will fully engage (hands on) in the day to day product development activities, gaining the opportunity to work on cutting-edge technologies. This position is an excellent opportunity for professional growth, allowing you to develop your technical skills in web frameworks, security, and networking. 

### Primary job responsibilities
Technical
+ Take ownership of product components and features. Analyze and decompose the features. Turning wireframes and sketches into working prototypes. Translating prototypes into launch ready code
+ Build and maintain front-end libraries and frameworks
+ Develop robust web-client user interfaces which integrate with various server-side components and back-end systems
+ Deliver implementation that is as simple as it gets, with 100% automated unit and user acceptance tests that enable continuous integration and delivery
+ Participates in code peer reviews (includes product code and test automation code)
+ Participates in product usability, security, architecture, and documentation reviews

Agile/Scrum
+ Participate in Agile SCRUM activities such as daily standup, sprint planning and retrospective meetings
+ Working closely with our Interactive Designer to develop creative solutions and rapid prototypes that take into consideration the technical, organizational, schedule, and business requirements.
+ Working closely with our Backend Developers to ensure the integrity of the UI throughout the development process
+ Working closely with our Quality Engineers to conduct usability and accessibility review for products and define usability requirements
+ Actively look for opportunities to enhance standards and improve process efficiency

### Required skills
+ Bachelor's degree in computer science or a related field
+ Good understanding of modern web technologies: HTML5, CSS3, responsive design, client-side + Javascript frameworks (Javascript (CJS/Browserify), Angular, Node.js, HTML5, LESS) and modern build systems (Gulp.js, Grunt, Webpack)
+ Production knowledge of ES6 would be highly regarded
+ 3+ years of experience in developing the frontend of web application with a focus on performance and scalability, preferably in the open source model
+ Demonstrated ability to accurately estimate and scope the design & development work
+ Demonstrated success in accomplishing goals working with a team
+ Professional skill level in the following technologies:
  + Solid understanding of web and mobile application technologies
  + Familiarity with all aspects of MVC/MVVM web applications
  + Awareness of cross-browser compatibility issues
  + Experience with full stack development
  + Keen interest and knowledge of latest trends in mobile and web app interfaces and development
+ Proactive developer involved in the wider developer community, open source projects, etc would be highly regarded
+ Ability to work in a fast-paced environment with team members dispersed across multiple countries and time zones
+ Familiarity with different project management methodologies, tools, and defect tracking systems
+ Experience working in a cross-functional, multi-cultural collaborative environment
+ Effective communication skills, both verbal and written

**Comment by iamkevinv** [comment]
These are still happening. We have FE and BE mean stack applications which require specialised talents to join us. If you're interested, please do drop myself or @garrows a line.
