### ISSUE TITLE
Talk: Avoiding javascript soup to improve UX

### ISSUE THREAD

**Issue by mbourne** [BrisJS/meetups#520]
Talk title: Avoiding javascript soup to improve UX
Talk length: 30 min
Talk synopsis: 
Too many sites give users a poor experience because pages are slow, clunky and error-prone. This talk will use a case study to demonstrate how we improve things by avoiding common javascript pitfalls.
Available month(s): Oct, Nov
X: @bourne_2_learn

(Kevin: Yes, this is similar to the talk I gave last year, but the case study is different and the message has a different emphasis. If you think it's too soon or too similar, no problems!)

**Comment by iamkevinv** [comment]
My apologies @mbourne for the delay, i've been on work travel for a few weeks... If you can confirm that you're ready and able to present for the 14th Oct event, i will add you the schedule. However i am having difficulty lining up the minimum 2 speakers at this stage with one volunteer dropping out earlier, so i'll let you know if Oct is cancelled and we move to Nov. Please let me know? Thanks :)

**Comment by iamkevinv** [comment]
My apologies - it was scheduled for 14th of october, as there's a QLD public holiday. I have more confidence then that we can line up a 2nd speaker.

**Comment by mbourne** [comment]
Hi Kevin. No probs. I'm good on 14th Oct and will be ok if it's 4 Nov.

**Comment by iamkevinv** [comment]
Lets try and put 14 Oct on :) I'll send out the notice today :)
