### ISSUE TITLE
Web3: Not Just Crypto

### ISSUE THREAD

**Issue by drpitman76** [BrisJS/meetups#521]
**Talk title**: Web3: Not Just Crypto
**Talk length**: 20 min
**Talk synopsis**: A deep dive into the burgeoning web3 wild west arena full of decentralization, autonomous services and unstoppable apps ... and lots of JavaScript! While the most recognizable application of web3 technologies is cryptocurrencies, this space has a lot more to offer: from distributed databases, to permanent storage, to autonomous AI. This talk will attempt to give an overview of the current state of the space, what's likely on the horizon and how it can be integrated into your "web2" development toolset.
**Available month(s)**: October 2024

**Comment by drpitman76** [comment]
I've put down this as a 20 min talk, but it could easily go for much longer if there is time on the night. Let me know what might work best for everyone and I'll adapt accordingly.

**Comment by iamkevinv** [comment]
Sounds great! Can I confirm you for Monday then? @drpitman76

**Comment by drpitman76** [comment]
Absolutely!

**Comment by drpitman76** [comment]
Here is the link to the slides from last night for future reference: https://docs.google.com/presentation/d/1pxyWo4bwCg7baW59soyjVqlqu__GutbOz96dVrWrEAA/edit?usp=sharing

**Comment by iamkevinv** [comment]
Thanks again for sharing the talk and resources! Cheers!
