### ISSUE TITLE
A talk about using browser crypto api to replace authentication providers

### ISSUE THREAD

**Issue by utilitydelta** [BrisJS/meetups#522]
Presenter Name: Tyson Brown
Talk title: Building a Transparent, Zero Friction User Auth System: JavaScript Meets Asymmetric Cryptography
Talk length: 20 min
Talk description:
In this talk we'll explore a fresh take on authentication that keeps things simple and seamless for users. Imagine accessing a service without the need for a password, hardware token, or even a signup process—just a secure, automatic way to verify identity. This approach helps solve a common problem: losing users at the signup stage because they don't want to go through the hassle. We'll discuss how this method can enhance security while making the user experience frictionless. Plus, we'll touch on how this concept relates to WebAuthn and where it fits into the broader landscape of authentication options. If you're interested in reducing barriers for users without compromising security, this talk is for you!

Available month(s): Any
Linkedin: https://www.linkedin.com/in/tyson-brown-208b88b6/

**Comment by iamkevinv** [comment]
Thanks for your talk submission @utilitydelta! I'm assuming this is best presented in our following event for November - and tentatively set it there for you :) If we get desperate for this monday i might ping you soon ;-)

**Comment by utilitydelta** [comment]
Thanks Kevin, I might need a day or so notice to get some slides created so let me know as early as you can if you want me for Monday.

**Comment by iamkevinv** [comment]
Hey @utilitydelta - are you still ready for this Monday 4 Nov event? :D

**Comment by utilitydelta** [comment]
Yup, can do!

**Comment by iamkevinv** [comment]
Great! I'll organise the announcement ASAP :)

**Comment by iamkevinv** [comment]
See you tonight at the in-person meetup @cacothi :)

**Comment by iamkevinv** [comment]
See you tonight at the in-person meetup @utilitydelta!

**Comment by iamkevinv** [comment]
Thanks very much for your talk! It was honestly awesome. Hope to see you back for another one! If you have any links for the audience or resources, please add them here :)
