### ISSUE TITLE
MongoDB + JS 

### ISSUE THREAD

**Issue by cacothi** [BrisJS/meetups#523]
### Context:
MongoDB is a noSQL database based on BSON (Binary JSON)
Due to its familiarity with JavaScript, and robust query and data management, it’s a great database for modern applications 

### Benefit of MongDB for Devs
- Great tool for BackEnd Devs, and also for FullStack developers
- Increase of efficiency on development. 
- reduce the database migration management
- Great Learning transition for FE Js  and NodeJs Dev. 

### The Talk
- Basic: we can share the basic CRUD and some commands to share how easy is to kick off with MongoDB
- Advanced: Aggregation queries and some database modeling. 

### About me
- I have been working in Tech for 24 years
- First 15 years with great experience with SQL, and last 9 years working with MongoDB
- Wide experience FrontEnd, BackEnd, Cloud, DevOps, Marketing, UI/UX,CX. 
- Recent past experience: Part of the Leadership Innovation team at Suncorp
- Currently working as DM at Auto & General

**Comment by iamkevinv** [comment]
This would be great @cacothi :) Are you available for the Nov 4 meetup, or are you aiming for Dec 2?
If you are ready for Nov 4 there's a better chance we can move ahead with that one and send out the info tomorrow :) 
20 mins plus Q&A or 30 mins plus Q&A?

**Comment by cacothi** [comment]
Hi Kevin,

I’m happy with 4th November. Let’s do it!

It’s a live code session, where I will show in real time some commands
using js and MongoDB

**Comment by iamkevinv** [comment]
Great! I'll organise the announcement ASAP :)

**Comment by iamkevinv** [comment]
See you tonight at the in-person meetup @cacothi :)

**Comment by iamkevinv** [comment]
Thanks for your presentation mate! I think the audience got a lot out of it. If you have any links for the audience or resources, please add them here :)
