### ISSUE TITLE
Lighting Talk: Service Worker API

### ISSUE THREAD

**Issue by chrsr** [BrisJS/meetups#54]
I've been to a few BrisJS meetups and have been keen to volunteer a talk for a while. Recently I've begun exploring the Service Worker API as part of a push to improve front-end performance and experience for our users here at Expedia Brisbane (née Wotif) and I'm happy to put some of these thoughts and demos in a brief slide deck.

Looking to explore in the presentation:
- Current state
- Progressively enhancing the network
- Service Worker
- Cache control ability
- Examples of the internal push here at Expedia
- Brief demo

**Comment by AshKyd** [comment]
That sounds awesome, it's something I've been meaning to look into so it'd be a good one to have an intro. Is the May meetup (4 days) enough time?

**Comment by chrsr** [comment]
Thanks Ash, Monday should be fine.

**Comment by kevdesign** [comment]
Oh i didn't realise this was up here... obviously you already got in after you emailed me @chrsr :)

**Comment by kevdesign** [comment]
Thanks for this! If you could add the resources / slides here perhaps... that would be great, and i'll add the right label so that closed issues with resources can still be found.

**Comment by chrsr** [comment]
Thanks @kevdesign.

Link to my slides from my BrisJS talk here for anyone interested: http://chrsr.com/presentations/service-worker-brisjs0515/#/
