### ISSUE TITLE
Front End Developer Nightlife Music 

### ISSUE THREAD

**Issue by ljowen** [BrisJS/meetups#59]
Hi all!

We're seeking an experienced front end developer at Nightlife Music here in Brisbane.

For more details see: http://www.nightlife.com.au/pdf/Positions%20Available/Web%20Developer%20120515.pdf

Cheers,
Lawrence

**Comment by iamkevinv** [comment]
Hi @ljowen - the link is now broken so i'll take that as a sign that the position is filled. Cheers.

**Comment by ljowen** [comment]
Thats correct, thanks kevin
