### ISSUE TITLE
Run all of npm. JS 4 Astral Unicodes. Srcoll 1e5 dom elements. JS 4 Units of Measure, et al 

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#61]
Here's an offer to present a short talk in 5 swatch beats [a strict 7 minutes 12 seconds] 

About How one might:
  
(1) Run/examine all (of an old snapshot) of npm
(2) Handle Unicode from the astral planes in JS 
without the newser ES5 methods "string".codePointAt(position) && String.fromCodePoint(codePoint)
(3) Scrolling 100,000 items on a page (better but still a work in progress)
(4) Handle Units Of Measure (mass/length/time/dates/forex/css) Some current work to try and do a practical unification of: currency exchange, SI units, data flow, screen+css dimensions and positions,  etc, SI units, with some help/data/notation from ucum.js, = The Unified Code for Units of Measure, at http://unitsofmeasure.org/ucum.html, and other sources, for use in JS and stored as json.
(5) Other modules or JS things of interest of late...

...like how to lookup unicode characters (via unicode-search.net) automatically with a little local webservice and converts html tables into json (with tabletojson)
http://unicode-search.net/unicode-namesearch.pl?verbose=1&print=1&term=wave

I got interested in point number (2) after i noticed that font-family:Segoe UI Emoji; for codepoints around 127,891 (aka Emoji, etc) showed up in colour!!! even in textareas!!! even in my oldish WebBrowser control, which was a bit of a surprise. 

best summarized in this talk: Mathias Bynens from Opera - Awwwards Conference 2015 on Vimeo
https://vimeo.com/126112284

So I updated the main place i use String.fromCharCode(x) and  "x".charCodeAt(0)  to better use/read/return the surrogate pairs (or the 16 other astral planes, above the BMP). for characters above \uFFFF since my context lacks the newer ES6 methods 
"string".codePointAt(pos) && String.fromCodePoint(codePoint) 

it wasn't too hard to do, 

my existing function...

```javascript
function(x){/*CharCode2String+ String2CharCode*/if(typeof x=='number'){return String.fromCharCode(x)}return x.toString().charCodeAt(0)}
```

half a day later, with some code re-use, became...

```javascript
function(x){/*http://norbertlindenberg.com/2012/05/ecmascript-supplementary-characters/#String*/ 
var ty=typeof x;if(ty=='string'){/*return x.toString().charCodeAt(0)|now|"String".codePointAt(pos)*/ 
var a=x.charCodeAt(0);if(a>=0xD800&&a<=0xDBFF&&x.length>1){var b=x.charCodeAt(1); 
if(b>=0xDC00 && b <= 0xDFFF){return ((a-0xD800)<<10)+(b-0xDC00)+0x10000}} return a} 
var a=[x]/*String.fromCharCode(x)|now|String.fromCodePoint(codePoint)*/ 
if(arguments.length!=1){a=[].slice.call(arguments)}else if(ty=='object'){a=x} 
var C=[]; for(var i=0;i<a.length;i++){var c=Number(a[i]); 
if(!isFinite(c)||c<0||c>0x10FFFF||Math.floor(c)!==c){throw new RangeError ('Invalid code point '+c)} 
if(c< 0x10000) {C.push(c)}else{c-=0x10000;C.push((c>>10)+0xD800);C.push((c%0x400)+0xDC00)}} 
return String.fromCharCode.apply(undefined,C)}
```

i also added Mathias Bynens's "jsesc" which is worth a look at:
https://mothereff.in/js-escapes#1🍉

**Comment by govpack** [comment]
![](http://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Grey_Catbird.jpg/330px-Grey_Catbird.jpg)

**Comment by kevdesign** [comment]
The monday slot has an open floor section (at your request) so we can absolutely see you presenting if you have any of the above ready. :)
