### ISSUE TITLE
Front-end components 2: applying generic(ish) components to create complex interfaces.

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#63]
I'd like to do the second part to my last talk, which was a while ago, to show people how we use small components to build complex applications.

**Comment by kevdesign** [comment]
When would you be ready @KoryNunn ? :)

**Comment by KoryNunn** [comment]
For the next one, will be mostly live coding.

**Comment by iamkevinv** [comment]
Hey @KoryNunn if you have any resources, please add them and i'll put the right label here

**Comment by KoryNunn** [comment]
The  component made in the first talk: https://www.npmjs.com/package/predicty

Fastn: https://github.com/KoryNunn/fastn

The code we spammed together during the talk: https://gist.github.com/KoryNunn/6fe046323a1077908c5e

What you get when you use a framework/nothing/tools: https://gist.github.com/KoryNunn/e906f362546a71497bc2

**Comment by iamkevinv** [comment]
Thanks!
