### ISSUE TITLE
Talk: Private NPM Modules. What you need to know and how to fully use them.

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#64]
I would like to volunteer a talk on private NPM modules. When I moved our codebase over I discovered a fair few traps that I would like to share. I also want to share how to use them to break up your mammoth app into something manageable. 

I can be ready for June 1st too.

**Comment by kevdesign** [comment]
Sounds good. Lets get you in

**Comment by MauriceButler** [comment]
Is this the new scoped modules or the enterprise stuff? 

I would love to see some examples of how the enterprise stuff evens.

**Comment by garrows** [comment]
Scoped.

**Comment by garrows** [comment]
Here are the slides
http://slides.com/glenarrowsmith/npm-private-modules#/
Hope you enjoyed it.
