### ISSUE TITLE
Could I invite @streetkid and his good friend(s) from sportsmed to give a talk...

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#66]
## Talk Requested: "Performance enhancers FROM professional athletes FOR regular people"

I've always though of coding as being a bit of an endurance sport, and that, paradoxically, sitting down for a long time can be one of the most tiring things a person can do.

Performance and image enhancing drugs (PIEDs) were the topic of a recent article in the MX paper, which said that Queensland was a hotspot for that sort of thing.

Regarding professional athletes etc, I've heard if something will give them an edge or a boost -- THEY WILL DO IT -- which means pretty much they have tried everything!! So there are a lot of supplements and performance enhancing drugs which will be illegal in sport but would be okay else where -- like for extra performance in the office -- or as a programmer.

### Could I invite @streetkid and his good friend(s) from sportsmed to give a talk about HOW:
* state of the art techniques, 
* supplements and drugs, new diets, exercise regimes, 
* and the use of personal biometric and exercise data

### FROM THE TOOLKIT OF THE PROFESSIONAL ATHLETE 

....could be used to get more general fitness for the day and to get more programming done. 

Perhaps they could show off their software for some of the visuals (http://sportsmedglobal.com/) if it does something unique and magic and the advertising/presentation is entertaining -- then it is 1000x times better that it is delivered from a commercial base!!! Programmers should be all in favour of software that can be sold for money, because it validates and sustains their careers.

Commercial operations can do a lot more deep research, and may have ironed out a lot more unique wrinkles [that value add is their competitive advantage -- as with the rest of IT -- if it boosts some valuable metric -- then it's WORTH some money!!] and cutting a whole bunch of paychecks is actually a lot better than what Richard Stallman has done (eating his toe nails, and pimping everyone out and getting them to work for free). Open Source is a great way for a coder to work, but buying into that vision wholesale, is actually a huge scam -- because the people doing it aren't really paid, respected or looked after.

Personally I'm thinking: I need to change things up a bit to get a few more energized coding hours in each day. Re: exercise, etc ~ why can't they just put motivation in a bottle? huh? or maybe they have? How do we improve things naturally and sustainably with a bit of extra help? apparently sportsmed has the data.

thanks

**Comment by streetkid** [comment]
Hi

I can ask them if they'd like to give a talk about their work, their technology and such. Not sure if this requires them to be sponsors of such? If yes let me know, Kevin.

However I don't think they will talk about the drugs you mentioned. The app is used not for programmers, but for athletes



Cheers

**Comment by govpack** [comment]
@streetkid and @kevdesign 

there's a definitely a growing variety of health apps that use js+html to display and interact with personal medical data and biometrics in a variety of useful ways, it would be worth getting an over view or some perspectives on that. [SMART on FHIR](https://github.com/smart-on-fhir) [gallery](https://gallery.smarthealthit.org/) etc, as well as lots of new devices like the [Microsoft Band](http://www.techradar.com/reviews/wearables/microsoft-band-1283262/review/3) with "a  whopping ten sensors: an optical heart rate sensor, 3-axis accelerometer, gyrometer, GPS, ambient light sensor, skin temperature sensor, UV sensor, capacitive sensor, microphone and a galvanic skin response sensor."

"According to Dr. Richard Veech, an NIH researcher and expert on ketones, both the brain and heart work more efficiently on ketones than glucose." which means that the stuff that sports doctors had been saying for 30 years (carb loading etc) was kind bad advice (re diabetes etc) and he sports doctor in charge of the Australian cricket team agreed (in a recent ABC documentary) and said that he was having better results with high fat/protien diets (avoiding carbs almost entirely). 

I thought sportsmed might have some helpful things to say for anyone with a body,  just a quick and easy, 10 minutes: "here's what we're up to, here's some useful stuff we've found" re health and fitness + technology hopefully with no extra preparation required, surely sponsorship wouldn't be required.

**Comment by krisrogers** [comment]
As an anecdotal aside, after switching to a high carb, whole food plant-based diet I am able to keep energised and focused throughout the day without relying on stimulants (coffee, chocolate).

I find it interesting that many low carb proponents in the fitness industry also endorse heavy stimulant usage.

**Comment by kevdesign** [comment]
I think the technology background at work which supports athletes is an interesting thing that might be relevant presentation. Might also be interesting to show how things relate to web approaches, etc. Certainly doesn't require sponsorship @streetkid, as we're trying to show people how in the real world we are solving problems. Anyone can present for free as long as it's relevant to the group :)

**Comment by iamkevinv** [comment]
Have been talking with Scott from Sports Med and will create/wait for a talk to be volunteered - until then will close this issue.
