### ISSUE TITLE
Why not just say "Anyone who's new to the group will have to talk, anyone else who wants to talk can do so"?

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#67]
@kevdesign @MauriceButler @nigelr 

So i went thru the talks on offer/requested for June 1st. This is a chore and should never have to be done again. Why not just say "Anyone who's new to the group will have to talk, anyone else who wants to talk can do so"? 

@anyone who's hiring should make themselves visible and say a few words

@anyone with a technical question should present it as a challenge to the group
  
@AshKyd The promo builder, or: unidirectional app structure with virtual DOM.
https://github.com/BrisJS/meetups/issues/48

@marklawlor Testing workflows for prototyping/small libraries
https://github.com/BrisJS/meetups/issues/51

@ArtemGovorov The wallaby.js testing product and what it can do for you
http://wallabyjs.com ~  "wallaby.js runs your code as you write it"
 
@BrisJS Group talk for @xwipeoutx about how people are "Managing large js applications"
https://github.com/BrisJS/meetups/issues/55

@garrows Private NPM Modules. What you need to know and how to fully use them.  
https://github.com/BrisJS/meetups/issues/64

@KoryNunn Front-end components 2: applying generic(ish) components to create complex interfaces. 
https://github.com/BrisJS/meetups/issues/63

@govpack Run all of npm. JS 4 Astral Unicodes. Srcoll 1e5 dom elements. JS 4 Units of Measure
https://github.com/BrisJS/meetups/issues/61

I have offered a talk but it has not been confirmed [so i haven't had any certainty on which to base any preparations, nor any feedback to indicate that it's valued/wanted at all]. Why allow that to be an excuse? Or to miss out on interesting things closer to the time the person wants to present something. Why have the tastes of one person limit the variety of what gets heard? In the list above, 120 minutes would allow plenty of time for everyone to speak for 5m, 10m, 15m, 20 minutes, whatever they wanted. If ten people wanted to speak for the maximum time then they could all speak for 12 minutes -- plenty of time to show how/why, and what you like about something. 

Personally I'm sick of the introductory tech talks, at least on youtube one can fast forward 20 minutes into a one hour presentation -- to where they actually start saying something useful!! In any given talk there's usually not that many actionable items, or units of value that can be re-applied. Shorter talks are going to condense that, so they're probably going to be more useful. Hopefully soon we can move to "game mode" where everyone is coding/doing/talking at the same time, to better utilize the group IQ.

Hopefully the talks on Unit Testing are ongoing so i will get to hear how Mark Lawlor show how he is able to get further/faster/happier/better using unit testing, since I missed the first one.

https://github.com/BrisJS/meetups/issues/45
Week 2 - Testing workflows for prototyping/small libraries:
Using tape
Using nodemon for console
Using beefy for browser
Using smokestack for automated testing (Shoutout to @timoxley, if he could provide some info it would be awesome)
Moving from local testing to continuous integration (smokestack -> Saucelabs)

Right on topic with that would be having ArtemGovorov show the group his wallaby.js testing product. he offered earlier when he said "I could present my tool wallaby.js for JavaScript continuous testing (both node and browser). The tool is commercial, however..."  it's only the cost of a cab ride from the airport or a night out (ie practically free) and it may do something magic to improve how you work (better/faster/quicker/etc). -- and i'm not sure if it got a showing

I think software developers are one of the stingiest/hardest markets to sell to (because we got so used to free). But I'm happy for him to try his best sales pitch/demo. The way i see it is "wallaby.js" is free software (after you've paid for it it's free) [and Windows is free software -- it comes free with the hardware] after that it's the results and the time spent that have got to be important. 

Having said that, lots of people have offered some great stuff to present, so thanks to all of them for that.

**Comment by kevdesign** [comment]
You've done a really good job collating here @govpack -very appreciated. I'm updating the meetup page at the moment - I'll grab our few confirmed speakers and make the rest of the space free for all. It's always intended to be an open approach. Apologies on not confirming your slot for the things you wanted to present- this meetup has just suffered from the postCampjs effect. You are more than welcome to present.

**Comment by timoxley** [comment]
> Personally I'm sick of the introductory tech talks,

+1.

**Comment by govpack** [comment]
@timoxley people deal with it by multitasking with their iphones and laptops, i like how that divided attention is now a totally acceptable behaviour, "i'll just wander off into cyberspace and tune back in when i hear something interesting" lol

@kevdesign No worries, i don't have any issues personally, or face to face, it's just the artifacts of the medium and delays. Having an open YES to speakers , would not only encourage such, it would also be good for travelers who show up on an impromptu basis, (even hearing a foreign accent, i think is a bit like going on a holiday) it's always fun. and they won't be here next month, so it has to be done on the night.

If you did a fortnightly meetup (the browser/node split) people could just start running thru the nodeschool courseware for content and structure -- with the web there's no shortage of subject matter. Monthly is fine too, I'm just saying it doesn't really matter if no one wants to speak either. Fewer chores for the organiser has to be better for everyone. "Want to" is fine but "have to" for a voluntary thing is a bit much.
