### ISSUE TITLE
Wanted - Full Stack Developer

### ISSUE THREAD

**Issue by chriswilsoon** [BrisJS/meetups#68]
Hi
Are you interested in doing something in the IoT/IIoT space. I need a fullstack developer for a few months to build a webapp to be served off an embedded ARM SBC. 

Need to be able to design a clean good looking UI, be proficient in Javascript, node.js, angular.js, mongoDB, interfacing with 3rd party libraries. App will involve dashboards / charts / widgets, previous experience with designing these a plus.

Please contact Chris Wilson 
chriswilsoon@gmail.com
0432808664

**Comment by iamkevinv** [comment]
Sounds like a lot of fun @chriswilsoon - hope someone rises to the challenge

**Comment by iamkevinv** [comment]
How did you go with this @chriswilsoon ?

**Comment by chriswilsoon** [comment]
Some interest, I ended up doing it myself. You can close this. Thanks 

Chris
