### ISSUE TITLE
Web workers

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#69]
We've had the intro to Service Worker recently, I propose taking a step back to talk about Web Workers; the less glamorous and slightly plainer cousin.

I've been thinking for a while, and recently actually doing a bit of work with web workers, and I think I can impart some knowledge around:

* What they are (dedicated, shared, and service workers) and how they all fit together.
* Demo the code behind a multi-process app.
* How best to structure your app to make the most of this paradigm (because this is a big hurdle to adoption, in my experience).

I'll also cover some practical stuff like browserify (workerify is really cool, but you may not want to use it), performance and when you might want to do stuff like this, and I don't know. Anything else you might want to know?

**Comment by KoryNunn** [comment]
Interested. also would be cool to see some interesting ways people have used them

**Comment by iamkevinv** [comment]
Sounds cool @AshKyd - If you can be ready, i'd love this at the next BrisJS :)

**Comment by AshKyd** [comment]
Yup, count me in.

**Comment by Samreay** [comment]
If you're looking for some current applications of web workers, I've got a web application used for scientific purposes over at http://samreay.github.io/Marz. I send data chunks to a web worker queue to get processed and returned to the user.

**Comment by AshKyd** [comment]
Hey thanks, I've been looking around for stuff like that.

**Comment by davidmason** [comment]
@AshKyd I am considering web workers for running validations on string inputs. The inputs are often paragraph-sized and a there are a lot of things to check are valid. Not sure if I will be able to work on that in the next month though.

**Comment by KoryNunn** [comment]
FYI: http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#transferable-objects

This is something I'm really interested in you covering if possible...

**Comment by AshKyd** [comment]
Ah, I misunderstood you the other night, thought you were talking about [structured clone](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/The_structured_clone_algorithm). I haven't used it, but I'll skill up and add it to my slides. :)

**Comment by iamkevinv** [comment]
@AshKyd If you could post any of your resources here that would be rather grand - i'll pre-emptively add the label.

**Comment by AshKyd** [comment]
Sure, we've got:

* [Interactive Slides](https://ashkyd.github.io/web-workers-brisjs-2015)
* [Blog post overview](https://ash.ms/blog/2015-07-08/web-workers-an-overview)
