### ISSUE TITLE
PouchDB

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#70]
[PouchDB](http://pouchdb.com) is pretty neat. I heard about it when @drzax shared their recent "[we have a problem with promises](http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html)" post and @annagerber mentioned it in passing at CampJS too, so it seems to be so hot right now.

From the homepage: "it enables applications to store data locally while offline, then synchronize it with CouchDB and compatible servers when the application is back online, keeping the user's data in sync no matter where they next login."

It might be a fun one if someone has any experience, especially with the syncing stuff.

**Comment by iamkevinv** [comment]
Do you think we could drum something up for the next BrisJS? - Perhaps we ask around? @drzax @annagerber @AshKyd

**Comment by geoffreyd** [comment]
I've done some projects with CouchDB in the past, and have a need todo some digging into PouchDB soon, so I could talk about it, maybe August Meetup? (I'm already doing EmberJS 2, and JSON API 1 in Jul)

**Comment by iamkevinv** [comment]
Would be good @geoffreyd if you don't feel overcommitted with all that... I'll put the right labels here.

**Comment by iamkevinv** [comment]
@geoffreyd - Are you doing this talk in Aug? Trying to lock down the talks which are Y state.

**Comment by iamkevinv** [comment]
Switched in for Sept instead

**Comment by iamkevinv** [comment]
@geoffreyd are you still interested in doing this? Your option is still to look at this in Oct

**Comment by geoffreyd** [comment]
@iamkevinv Yeah, I think I should be good for Sept.

**Comment by iamkevinv** [comment]
Sept might be too full @geoffreyd - i'm waiting on confirmation of some of the others, but it's possible we'll have no choice but to have this one in Oct. You can be first choice for filling a spot on standby - i'll do my very best to keep on top of this since @AshKyd is super keen to hear you talk about this.

**Comment by AshKyd** [comment]
:+1::+1::+1:

**Comment by geoffreyd** [comment]
@iamkevinv Cool, well I'm happy to be Stand by, I've only just started to dig into this at work, so if it's pushed back, it just means I'll have more time to awesomify it.

**Comment by iamkevinv** [comment]
Hello @geoffreyd ;-) How goes all that awesomification? I think it would be really nice to get this out to the people :)

**Comment by geoffreyd** [comment]
@iamkevinv Yup, put me down, I've been sitting on the Couch all last week, and feeling good about it.

**Comment by iamkevinv** [comment]
Thanks again for the talk... if you could share some resources here (links) that would be great.

**Comment by geoffreyd** [comment]
You can find PouchDB at http://pouchdb.com

A good intro to CouchDB, many of the concepts are shared by Pouch: http://guide.couchdb.org/draft/
And more detailed Docs: http://docs.couchdb.org/en/1.6.1/intro/

PouchDB plugins: http://pouchdb.com/external.html
