### ISSUE TITLE
Latest from jsonapi.org & emberjs

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#71]
@geoffreyd has offered to talk about:

* jsonapi.org hitting 1.0
* and/or EmberJS hitting 2.0

**Comment by iamkevinv** [comment]
This is grand :) Pushing it forward

**Comment by govpack** [comment]
+100000 to both jsonapi.org and the latest from emberjs

preferably show us something that EmberJS 2.0 can do, that the other MVCs cannot!! 

~ i mean less code is one thing, plus it's good that they did the rejig/refactors etc [good for themselves and those that use it] but i don't use any anglularz, or honey i'm back home, or emburs/bars, etc -- so it's hard to get less code than zero lines. And v2 makes v1 look bad, therefore v2 is just the swill waiting for v3 etc. If you put the code out front it's not even a horse & pony show -- it's just horrible. It's like i'm standing in the future and saying `none of this has even arrived` not even close. 

It's in the tagline for Emberjs: "A framework for creating ambitious web applications." exactly!!! an amphibious (ambitious/transcendent/outstanding) web application now that would be good to see!!!

**Comment by iamkevinv** [comment]
@geoffreyd could you please add any links to your talk resources here?

**Comment by iamkevinv** [comment]
Got a link to the slides @geoffreyd ?

**Comment by geoffreyd** [comment]
Sorry @iamkevinv for the slow response. Here are my slides: https://www.icloud.com/keynote/AwBuCAESEPw5RH6G5I60JMVZxa5ofFMaPKTr7F1gp0KfmrLLttxv0VpZ77BReNr2xwJUaAmiFbbMi99zJxj55wvR1B_eXIuauwg9XCbRO1vni4UakwMCUCAQEEIDAGySWd-jbMPrkcR534kt2lrHCU7zDUOKkvz42gVgMQ#New_in_Ember_2 

I really wish iCloud url's weren't so nasty!
