### ISSUE TITLE
ES6 WeakMaps WeakSets and cool stuff you can use them for

### ISSUE THREAD

**Issue by KoryNunn** [BrisJS/meetups#73]
I absolutely love WeakMaps. Best thing in ES6. I'd like to do a talk on how awesome they are and how they can be used.

**Comment by iamkevinv** [comment]
Sure :) When? 6th July?

**Comment by iamkevinv** [comment]
That date is locked in.

**Comment by iamkevinv** [comment]
@KoryNunn please attach a link with the things... if there are things.

**Comment by KoryNunn** [comment]
Some of the stuff I used to demo is in this repo: https://github.com/KoryNunn/maps-n-sets/

But as usual, live coding is kinda hard to link to :)

**Comment by iamkevinv** [comment]
Cheers!
