### ISSUE TITLE
Circle work

### ISSUE THREAD

**Issue by govpack** [BrisJS/meetups#74]
[Circle Work](http://unicode-search.net/unicode-namesearch.pl?verbose=1&print=1&term=CIRCLED)
(Q) How many “CIRCLED” characters can we find?… 
(A) 370
# ⊕|⊖|⊗|⊘|⊙|⊚|⊛|⊜|⊝|⎉|⎊|①|②|③|④|⑤|⑥|⑦|⑧|⑨|⑩|⑪|⑫|⑬|⑭|⑮|⑯|⑰|⑱|⑲|⑳|Ⓐ|Ⓑ|Ⓒ|Ⓓ|Ⓔ|Ⓕ|Ⓖ|Ⓗ|Ⓘ|Ⓙ|Ⓚ|Ⓛ|Ⓜ|Ⓝ|Ⓞ|Ⓟ|Ⓠ|Ⓡ|Ⓢ|Ⓣ|Ⓤ|Ⓥ|Ⓦ|Ⓧ|Ⓨ|Ⓩ|ⓐ|ⓑ|ⓒ|ⓓ|ⓔ|ⓕ|ⓖ|ⓗ|ⓘ|ⓙ|ⓚ|ⓛ|ⓜ|ⓝ|ⓞ|ⓟ|ⓠ|ⓡ|ⓢ|ⓣ|ⓤ|ⓥ|ⓦ|ⓧ|ⓨ|ⓩ|⓪|⓫|⓬|⓭|⓮|⓯|⓰|⓱|⓲|⓳|⓴|⓵|⓶|⓷|⓸|⓹|⓺|⓻|⓼|⓽|⓾|⓿|⛒|✪|❂|❶|❷|❸|❹|❺|❻|❼|❽|❾|❿|➀|➁|➂|➃|➄|➅|➆|➇|➈|➉|➊|➋|➌|➍|➎|➏|➐|➑|➒|➓|➲|⟴|⦶|⦷|⦸|⦹|⦼|⦾|⦿|⧀|⧁|⨀|⨁|⨂|⨶|⨸|⬲|⭙|⮈|⮉|⮊|⮋|⮾|⮿|〶|㉄|㉅|㉆|㉇|㉈|㉉|㉊|㉋|㉌|㉍|㉎|㉏|㉑|㉒|㉓|㉔|㉕|㉖|㉗|㉘|㉙|㉚|㉛|㉜|㉝|㉞|㉟|㉠|㉡|㉢|㉣|㉤|㉥|㉦|㉧|㉨|㉩|㉪|㉫|㉬|㉭|㉮|㉯|㉰|㉱|㉲|㉳|㉴|㉵|㉶|㉷|㉸|㉹|㉺|㉻|㉼|㉽|㉾|㊀|㊁|㊂|㊃|㊄|㊅|㊆|㊇|㊈|㊉|㊊|㊋|㊌|㊍|㊎|㊏|㊐|㊑|㊒|㊓|㊔|㊕|㊖|㊗|㊘|㊙|㊚|㊛|㊜|㊝|㊞|㊟|㊠|㊡|㊢|㊣|㊤|㊥|㊦|㊧|㊨|㊩|㊪|㊫|㊬|㊭|㊮|㊯|㊰|㊱|㊲|㊳|㊴|㊵|㊶|㊷|㊸|㊹|㊺|㊻|㊼|㊽|㊾|㊿|㋐|㋑|㋒|㋓|㋔|㋕|㋖|㋗|㋘|㋙|㋚|㋛|㋜|㋝|㋞|㋟|㋠|㋡|㋢|㋣|㋤|㋥|㋦|㋧|㋨|㋩|㋪|㋫|㋬|㋭|㋮|㋯|㋰|㋱|㋲|㋳|㋴|㋵|㋶|㋷|㋸|㋹|㋺|㋻|㋼|㋽|㋾|🄋|🄌|🄫|🄬|🄭|🄮|🅐|🅑|🅒|🅓|🅔|🅕|🅖|🅗|🅘|🅙|🅚|🅛|🅜|🅝|🅞|🅟|🅠|🅡|🅢|🅣|🅤|🅥|🅦|🅧|🅨|🅩|🉐|🉑|🔂|🕀|🗟|🛈

❶❷❸❹❺❻❼❽❾❿
⓫⓬⓭⓮⓯⓰⓱⓲⓳⓴ 
➊➋➌➍➎➏➐➑➒➓ 

note: the non contiguous ranges between ❶-❿ and ⓫-⓴
❿=10111=DINGBAT NEGATIVE CIRCLED NUMBER TEN (10111)    
⓫=9451=NEGATIVE CIRCLED NUMBER ELEVEN  

...and then the smaller set [your fonts may vary] of black circled "dingbats" from ➊-➓

➊=10122=DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ONE 
➓=10131=DINGBAT NEGATIVE CIRCLED SANS-SERIF NUMBER TEN
..and zero at 
⓿=9471=NEGATIVE CIRCLED DIGIT ZERO
🄋=127243=astral, dingbat circled sans-serif digit zero (U+1F10B)
from the "Enclosed Alphanumeric Supplement"  http://graphemica.com/%F0%9F%84%8B
says js '\u1F10B' , which is not quite right  till ES6? in which case it would be `\u{1F10B}` or
`\uD83C\uDD0B` before hand

The reason for looking is that i'm thinking of using 🅐🅑🅒🅓🅔🅕🅖🅗🅘🅙🅚🅛🅜🅝🅞🅟🅠🅡🅢🅣🅤🅥🅦🅧🅨🅩
for named and +/-relative LIST item references, ie ❶-⓴ for the negative ones and  ①-⑳ for the positive relative references to get a sort of 1D excel thing going, and ❂ or some such for zero or self. The reason for posting is just sharing something JS related. of the above 370 circles only:  
ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ
ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ
are valid js variable names :-(

╠════════9472-9599 Box Drawing════════╗
 ⓫[ &#9451; \u24EB] ⓬[ &#9452; \u24EC] ⓭[ &#9453; \u24ED] ⓮[ &#9454; \u24EE] ⓯[ &#9455; \u24EF] ⓰[ &#9456; \u24F0] ⓱[ &#9457; \u24F1] ⓲[ &#9458; \u24F2] ⓳[ &#9459; \u24F3] ⓴[ &#9460; \u24F4] 
╠════════12352-12447 Hiragana Japanese════════╗(ranges are out)
 ❶[ &#10102; \u2776] ❷[ &#10103; \u2777] ❸[ &#10104; \u2778] ❹[ &#10105; \u2779] ❺[ &#10106; \u277A] ❻[ &#10107; \u277B] ❼[ &#10108; \u277C] ❽[ &#10109; \u277D] ❾[ &#10110; \u277E] ❿[ &#10111; \u277F] ➊[ &#10122; \u278A] ➋[ &#10123; \u278B] ➌[ &#10124; \u278C] ➍[ &#10125; \u278D] ➎[ &#10126; \u278E] ➏[ &#10127; \u278F] ➐[ &#10128; \u2790] ➑[ &#10129; \u2791] ➒[ &#10130; \u2792] ➓[ &#10131; \u2793]

define:contiguous= sharing a common border; touching:

'❶❷❸❹❺❻❼❽❾❿'=='➊➋➌➍➎➏➐➑➒➓' //true
'❶❷❸❹❺❻❼❽❾❿'=='➊➋➌➍➎➏➐➑➒➓' //false 
different characters, 4th string is smaller in another font

to test if somename "x" is a valid variable name, do 

```javascript
try{eval('var '+x+'=99');return true}catch(er){return false}
```

**Comment by garrows** [comment]
Those aren't valid variable names. 
`var Ⓓⓤⓒⓚ = '🅣🅐🅢🅣🅨';`
Gives a SyntaxError.

**Comment by MauriceButler** [comment]
Your friend https://mothereff.in/js-variables

**Comment by govpack** [comment]
yes, i see that 
ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ=5
VM196:2 Uncaught SyntaxError: Unexpected token ILLEGAL
in Chrome, but F12 in IE is fine = interesting difference in context, f'kin jscript etc
anyway 
# Ⓓⓤⓒⓚ 

is a typo, lol

anyway, try pasting the 
# ⒻⓇⓄⒼ
into the address bar

 re Your friend https://mothereff.in/js-variables
yes, i love @mathias 's unicode work, i must use the function there and see which unicodes line up green in IE and red in Chrome as variable names

where *must* probably =could/won't,  but still interesting

**Comment by garrows** [comment]
What's IE? Is it a new experimental browser? 

`var ⒻⓇⓄⒼ = 'not tasty';` Doesn't work either.

**Comment by AshKyd** [comment]
It's right on the _edge_ man. ⓔ

**Comment by govpack** [comment]
i mean in the address bar where Ⓓⓤⓒⓚ will become Duck

yup, IE is so many things, it's not funny, (see below) i would respect programmers more if they were "conscientious objectors" to things they really don't like, like Muhammad Ali was regarding war in Vietnam (yes, it's really that bad), if they were then there wouldn't be so many problems, so the IE thing, they/we deserve it for participating in it, so sucked in, rather than just saying i don't/won't do that (they did that when buying Macs and just said, "i don't do that other thing...) so yeah it's best to go into a state of amnesia/ignorance is bliss on some things


* Internet Explorer (Microsoft)	
* In Effect	
* Information Element (ATMF)	
* Ireland (top level domain name)	
* Information Exchange	
* Industrial Engineering	
* Instituto de Empresa (Madrid, Spain business school)	
* Information Engineering	
* International Education	
* Institute of Education (UK)	
* Import/Export	
* Interactive Entertainment (International Conference)	
* Information Environment	
* In Essence	
* Inclusive Education	
* Information Extraction	
* Intelligent Enterprise	
* Inland Empire (southern California)	
* Inland Empire (California)	
* Industrial Engineer	
* Indo-European	
* International Exchange	
* Ion Exchange	
* Industrial Ethernet (extreme operating environments)	
* Individual Events	
* Id Est (Latin: That Is)	
* Inference Engine	
* Inside Edition (TV show)	
* Industrial Ecology	
* Initial Evaluation	
* Iarnród Éireann (Irish Rail)	
* Ionization Energy	
* In Exception	
* Infective Endocarditis	
* Improv Everywhere (comedy group)	
* Iced Earth (band)	
* Industry Executive	
* Institute of Energy	
* Information Expert	
* Infrared Emission	
* Initiating Event	
* Individual Equipment	
* Solomon Airlines (airline code)	
* Internal Examination	
* Input Enable	
* Interrupt Enable Register (Intel 8051 Microcontroller register)	
* Inhale Exhale	
* Intellectual Elites	
* Instrumental Enrichment	
* Independent Engineer (job title)	
* Investment Entity (IRS Form 5500)	
* Interior Elements (furniture industry)	
* Interactive Encyclopedia	
* Investment Efficiency	
* Institute of Export	
* Integration Engineering	
* International eCommerce	
* Idle End	
* Improvement Era (LDS Church)	
* Iniezione Elettronica (Italian: electronic injection)	
* Inspiration Expiration (ratio)	
* Irradiation Effect	
* Iridescent Effect	
* Income Endowment (life insurance)	
* Internationale Enheder (Danish: International Units; medicine)	
* Indemnité d'Expatriation (French: Expatriation Allowance)	
* Inhibition-Excitation	
* Ignition Electrode	
* Instrumental Engineering	
* Inspector Examiner (US FAA)	
* Instrument Earth	
* Instrument Examiner	
* Industry and Environment Office of UNEP	
* Inverted Elevation	
* Insurer's Examination (Canada)	
* Independent Evaluation/Evaluator	
* Immediate Export (logistics)	
* Instrument Engineer	
* Initial Elevation (line)	
* Initial Equipment

**Comment by govpack** [comment]
@garrows 

![b7lguuyiaaig2t8](https://cloud.githubusercontent.com/assets/8147200/8471713/7005a5e0-20de-11e5-8d4c-9d966ac81a0d.jpg)

**Comment by govpack** [comment]
IE also responsible for [Toyota Unintended Acceleration death and the Big Bowl of “Spaghetti” Code](http://www.safetyresearch.net/blog/articles/toyota-unintended-acceleration-and-big-bowl-%E2%80%9Cspaghetti%E2%80%9D-code)

**Comment by govpack** [comment]
![pad](https://cloud.githubusercontent.com/assets/8147200/8471845/7268537c-20df-11e5-8c19-322301fe8953.png)

no I didn't

**Comment by govpack** [comment]
Unfortunately, we don't support that file type.  Try again with a PNG, GIF, JPG.

**Comment by govpack** [comment]
Unfortunately, we don't support that file type.  Try again with a PNG, GIF, JPG.
