### ISSUE TITLE
NodeBots day roundup

### ISSUE THREAD

**Issue by AnnaGerber** [BrisJS/meetups#75]
I'd like to volunteer a short talk for the August BrisJS to talk about what we did at International NodeBots Day (to be held July 25th)

Should fit in well with Steve's talk on ESP8266 if that ends up happening then

**Comment by iamkevinv** [comment]
Good call! Sounds like an option.

**Comment by AshKyd** [comment]
:+1:

**Comment by iamkevinv** [comment]
If you have any links or a shareable link to the slides / notes - please add them here if you could. I'll close it with the Resources Shared label so it wont get lost.

**Comment by AnnaGerber** [comment]
Slides are here: 
http://www.slideshare.net/annagerber/international-nodebots-day-brisbane-roundup-brisjs

Code and files for the robot I demoed are here: 
https://github.com/AnnaGerber/NodeRover

**Comment by iamkevinv** [comment]
Thanks!
