### ISSUE TITLE
Talk Volunteer: How we are using reactJS at everydayhero.com

### ISSUE THREAD

**Issue by davidherse** [BrisJS/meetups#79]
If there is interest, I'd be happy to present a talk on how we are using ReactJS to unify our UI at everydayhero.com. I can demo the UI and widget libraries we are developing. Also, I can discuss the applications we have created using reactJS and the architectural approaches we have tried including our first isomorphic application.

**Comment by garrows** [comment]
+1

**Comment by govpack** [comment]
+Number.MAX_VALUE -- since mvc will never be done, i'm interested to see any newer/better things there as they come up, and how people have been making new widgets for them, and the benefits they see, good one.

**Comment by davidmason** [comment]
+1

**Comment by demsey2** [comment]
+1

**Comment by iamkevinv** [comment]
I'll lock you in

**Comment by iamkevinv** [comment]
@davidherse If you have any links or a shareable link to the slides / notes - please add them here if you could. I'll close it with the Resources Shared label so it wont get lost.

**Comment by davidherse** [comment]
@iamkevinv Here are the slides from my presentation. http://www.slideshare.net/DavidHerse/react-everydayherocom-brisjs-meetup

**Comment by davidmason** [comment]
@davidherse thanks for a great talk. We're using React in more and more places lately, and I'm converting our main Angular app to React. It helps to see how others are structuring things while I am working on the build tooling to keep things consistent.

**Comment by davidherse** [comment]
Thanks @davidmason. Keep in touch. It would be good to hear how you go.

**Comment by davidmason** [comment]
@davidherse I might have something worth talking about in a couple of months, depending how I go with the build tools. Some of it is pretty ambitious, but even just the simpler stuff will be useful. I have a bit of a different team skillset to deal with - most of the team are primarily Java developers so the JavaScript level is ok, but not fantastic. I'm hopeful that I can get enough static analysis in the watch task to ensure that decent JS is written and all our pattern and style conventions are followed without them having to sit down and read style documents or have suggested fixes on every other line of a code review.

**Comment by davidherse** [comment]
We use eslint with babel-eslint and gulp-eslint. Best lint setup we've had so far. Very configurable to your style guide. We have it setup in our HUI library. https://github.com/everydayhero/hui
