### ISSUE TITLE
Focusing on front-end performance

### ISSUE THREAD

**Issue by Vheissu** [BrisJS/meetups#8]
Last night was my first BrisJS meetup event and I noticed there was a lack of front-end related Javascript discussion. Server-side Javascript like Node.js is nice, but perhaps a nice thorough talk about front-end best practices would be beneficial.

I wouldn't mind putting something together and presenting it. Maybe not the next event, but perhaps the one after, so that would be about June or so (unless someone discusses it in the May meetup).

I think covering topics like:

* Webworkers
* DocumentFragments
* jQuery vs Native methods and how sometimes native methods are faster
* Memory management
* Reflows and redraws
* Etc...

Would this be something ;people would be interested in hearing discussed?

**Comment by Vheissu** [comment]
Hey mate,

I am so sorry, I've been working over in the US for a few months for a
content platform company building a Javascript intensive Netflix like
application, it was pretty awesome.

But I just got back and in Brisbane for good and I would still love to do a
talk. I've been doing some exciting stuff using AngularJS and React.js on a
commercial scale. Perhaps I can do a talk about using those two in
combination with an awesome way to create large-scale modular Angular
applications using Gulp.

Kind regards,

Dwayne Charrington

**Comment by kevdesign** [comment]
If that's what you'd like to do instead, maybe give some info in a new github issue and we can get it moving :)

**Comment by kevdesign** [comment]
Ping

**Comment by kevdesign** [comment]
Closed due to inactivity.
