### ISSUE TITLE
Talk Volunteer:  CBS, a new idea in frontend, and how to build MVVM framework from scratch

### ISSUE THREAD

**Issue by alexzhaosheng** [BrisJS/meetups#82]
Hi, I created an open source MVVM framework "knot.js" which introduces a brand new idea named "CBS" (Cascading Binding Sheets) to increase the experience of front-end development.
If there's interest, I'd like to show you how CBS works, talk about the pros/cons and collect your feedback to help me make it better. 
And I'd also be happy to share the implementation details of knot.js if you are interesting.

Here is the website of knot.js: http://www.knotjs.com

**Comment by iamkevinv** [comment]
Sounds interesting - Would you be able to present at the 08/03/2015?

**Comment by alexzhaosheng** [comment]
Hi Kevin,

No problem.  Will there be a projector?

**Comment by AshKyd** [comment]
There is a projector, I think we have HDMI and Mini DisplayPort/Thunderbolt connectors. I'll leave Kev to get back to you on scheduling. :)

**Comment by govpack** [comment]
@alexzhaosheng i'd like to hear about that, there's some magic where 
javascript meets the dom (or keeps track of which parts need updating) 
and then updates it, i had a go at making something like that, making it was
a bit tricky and twisted (and afterwards i'm not clear on how it works), so i'm 
VERY interested in other peoples take on how databinding can be done, maybe 
you could use a picture/diagram to explain how knotjs works 

I would prefer you talked sooner rather than later

thanks

**Comment by iamkevinv** [comment]
It's late notice but yes we could get you added - 20 minutes is a usual slot. There's very large TV screens which everyone can hook their laptops into. Check out the recent photos on our meetup page.

**Comment by iamkevinv** [comment]
Please let me know before Monday if you are confirmed. Otherwise there is always next month.

**Comment by alexzhaosheng** [comment]
Hi Kevin,

Just noticed your response, it would be a little bit rush for me, I think I'd better do it next month.
Thank you very much.

**Comment by alexzhaosheng** [comment]
Hi @govpack ,

I'm glad that you are interesting. Hope we could get a chance talk about it next month.

**Comment by iamkevinv** [comment]
No problem, i'll update to indicate next month. Thanks

**Comment by iamkevinv** [comment]
@alexzhaosheng - Are you still keen to present in a few weeks time? The sept brisJS meetup? I'll tentatively add the confirmation label.

**Comment by iamkevinv** [comment]
Thanks @alexzhaosheng - great concept to introduce - appreciate your time to show us. If you have resources to share... please link them here for everyone's reference. :)

**Comment by alexzhaosheng** [comment]
Hi @iamkevinv,
It was my pleasure to talk about my ideas with others.
At current stage, I only have knot.js website to share. I'm currently very busy with another project, I'll come back to knot.js once I get a break. 
I'd be very glad if anyone is interesting with contributing to knot.js :)

**Comment by iamkevinv** [comment]
Thanks!
