### ISSUE TITLE
Emscripten

### ISSUE THREAD

**Issue by AshKyd** [BrisJS/meetups#87]
@louisstow has been doing amazing things with [emscripten](https://github.com/kripken/emscripten).

I think he should tell us about what he's been up to and how to harness emscripten for good (not evil).

**Comment by govpack** [comment]
+ 1septendecillion+ 1novemdecillion +1octodecillion

In related news: this thing https://github.com/jsmess/jsmess as mentioned in portland during  (https://youtu.be/tJqZGRIwtxk?t=36m)[Open Source Bridge 2012 Keynote - Jason Scott] , the jsmess multiplatform game emulator, has fallen out of repair, the demo page http://jsmess.textfiles.com/demos.html isn't there mentioned at 
http://www.archiveteam.org/index.php?title=Javascript_Mess as "The main JSMESS site has some classic software demos guaranteed to work." (lol)

in which case one would try to build the project, 
https://github.com/jsmess/jsmess/wiki/How-to-build-and-test-JSMESS-0.153 
which i imagine would be a massive hassle, however building stuff with emscripten should be part of every javascript programmers toolchain -- so i would like to see/hear more about that!!!

so cheers to @louisstow @AshKyd for offering or being able to show how that is done

thanks

**Comment by iamkevinv** [comment]
Are you keen @louisstow?

**Comment by louisstow** [comment]
Yeah I can do a talk.

**Comment by louisstow** [comment]
@iamkevinv I've been porting an old school 3D game with emscripten so I was thinking my angle could be the journey and the multitude of issues.

**Comment by iamkevinv** [comment]
@louisstow Since we're having a bit of a games making thread this next meetup, the porting you've done and the otherwise general interest in emscripten would be cool - happy to have this confirmed for this upcoming sept meetup?

**Comment by louisstow** [comment]
@iamkevinv sounds good

**Comment by iamkevinv** [comment]
Thanks @louisstow - really appreciate the presentation. If you have resources to share... a few links here would be great. :)

**Comment by iamkevinv** [comment]
Ping @louisstow
