### ISSUE TITLE
Talk Volunteered: 2D Canvas Basics & JS13K Game Comp

### ISSUE THREAD

**Issue by garrows** [BrisJS/meetups#88]
Would anyone be interested in learning the basics of drawing on a 2D canvas with a games focus? No libraries just the raw API. 

The JS13K game comp (js13Kgames.com) is starting tomorrow too so I thought I might drum up some interest. @AshKyd might want to share his experiences too.

**Comment by xwipeoutx** [comment]
+1. Will this include WebGL at all?

**Comment by AshKyd** [comment]
Don't see why not, though IMO WebGL is kinda complex and impractical without a layer in between, such as Three.

I did present an intro to 2d canvas drawing after js13k last year. That said it's a huge space with lots of angles to cover and plenty of techniques to tackle.

I'll be happy to briefly show what I come up with. Games seems like a fun theme for an evening if there's enough content.

**Comment by govpack** [comment]
➕① they'd be enough content, maybe around 500 games, for everyone in the group to do a code review of a few games, and report with general and specific details of how people are making them

http://js13kgames.com/entries/2012
http://js13kgames.com/entries/2013
http://js13kgames.com/entries/2014
http://js13kgames.com/entries/2015 


![polar](https://cloud.githubusercontent.com/assets/8147200/9240226/20e5c9ce-41a7-11e5-8f5f-b4b0ca351588.png)

i played @AshKyd 's http://js13kgames.com/games/polar-defender/ which is great too
http://2012.js13kgames.com/ -->Michal Budzynski --> http://antarcticjs.com/ SOON!
which is when the 2015 games are being made

**Comment by fariazz** [comment]
+1!
I'm actually one of the judges of the compo

**Comment by davidmason** [comment]
:+1: I love playing with 2D canvas games.

*Aside:* I messed around with [crtrdg](http://crtrdg.com/) a few years ago - it is just a set of basic modules to get a game loop and entities going. It was fun to build up a game engine around that simple core, does take a long time to get anything really working though.

**Comment by garrows** [comment]
I was hoping to experiment with a workshop style talk where people can code as I'm presenting. Might be hard to keep under 20mins while keeping everyone in sync but I'm keen to try. 

It might be a good idea to have a games themed night so if you (especially @AshKyd ) have something to show or a talk to do please offer it in a new thread for @iamkevinv.

**Comment by garrows** [comment]
Just saw https://github.com/BrisJS/meetups/issues/90#issuecomment-132827612  :)

**Comment by iamkevinv** [comment]
If you're happy to have this for sept @garrows - i've tentatively added the confirmation label.

**Comment by garrows** [comment]
Yup. I'm happy to ☺

**Comment by garrows** [comment]
I converted my material into a basic (and ugly) tutorial site at http://canvas.garrows.com

Hope you found it interesting. I'm pretty convinced that live coding isn't a good idea now though.

**Comment by iamkevinv** [comment]
Thanks for sharing the resources mate. I've added the right label.
