### ISSUE TITLE
Making games with Phaser - talk proposal

### ISSUE THREAD

**Issue by fariazz** [BrisJS/meetups#90]
Hey everyone,

I'd be happy to give a talk on the Phaser JavaScript library if people are keen. I'm the author of an [online course where we build 15 games](https://academy.zenva.com/product/the-complete-mobile-game-development-course-platinum-edition/?zva_src=brisjs) using JavaScript and Phaser and have authored several tutorials on the subject. I'm also one of the judges of the [js13kgames](http://js13kgames.com/) competition.

The talk would show some examples and explain the basics of the framework like sprites, states, arcade physics and collision detection, and also talk about how to build them as hybrid apps using the Intel XDK.

**Comment by loklaan** [comment]
Absolutely keen.

**Comment by davidmason** [comment]
:+1:

**Comment by govpack** [comment]
+ ALOT

![](http://media.tumblr.com/tumblr_m57r9lsMHm1qbolbn.jpg)

@fariazz  i'd also be interested to hear about the testing practices you and other game makers use. Like how/if testing practices differ much from other javascript out there, for instance i found that the majority of npm (51% plus) had some sort of test command, and i know game makers write A LOT of code, but i wondered if playing the game substituted somewhat for writing more code/tests.

**Comment by fariazz** [comment]
hey @govpack I would be just as interested as you are in learning about this topic. Automating testing for games (other than testing that a method returns what they should and things like that) is a challenging thing as you would have to make your test "play" the game.

**Comment by iamkevinv** [comment]
I'd like to confirm this for the upcoming sept brisJS... okay @fariazz ?

**Comment by fariazz** [comment]
@iamkevinv yes if it's on the 7th of Sept! I'm going overseas on the 10th, so the 7th is perfect.

**Comment by iamkevinv** [comment]
Thanks again @fariazz - if you have resources you can share... could you link them to this issue please?

**Comment by fariazz** [comment]
@iamkevinv sorry for the delay.

-Phaser:  http://phaser.io

-Our written tutorials on Phaser:  http://gamedevacademy.org/category/tutorials/html5-gamedev-phaser/

-The source code and examples shown are part of our online course on JavaScript and Phaser:  https://academy.zenva.com/product/the-complete-mobile-game-development-course-platinum-edition/?zva_src=brisjs

**Comment by iamkevinv** [comment]
Awesome! thanks!
