### ISSUE TITLE
NativeScript

### ISSUE THREAD

**Issue by iamkevinv** [BrisJS/meetups#91]
@jbristowe has offered to tell us about NativeScript (https://www.nativescript.org/). Could you give us an idea of what that entails John?

**Comment by jbristowe** [comment]
Play "Magical Mystery Tour" by The Beatles in the background while staring at a shell window with the iOS and Android emulators sitting to the side and you'll start to get an idea. ;)

But seriously, I'd like to provide a lap around NativeScript. The who, what, where, when, and why of this technology. No slides, just a hands-on, demo-heavy tour of our latest bits.

**Comment by iamkevinv** [comment]
Nice! Oct meetup?

**Comment by jbristowe** [comment]
Let's do it.

**Comment by iamkevinv** [comment]
Thanks again for the talk... if you could share some resources here (links) that would be great.

**Comment by iamkevinv** [comment]
Ping again @jbristowe if you have links for people to share?

**Comment by jbristowe** [comment]
We put everything here: https://www.nativescript.org/resources

<img src="https://www.nativescript.org/images/default-source/Blogs/sneakers-console-output.gif" />

**Comment by iamkevinv** [comment]
Thanks man
