### ISSUE TITLE
How to do Angular JS 2.0

### ISSUE THREAD

**Issue by andrewling89** [BrisJS/meetups#93]
Hello
I'd like to do a talk on Angular JS 2.0, both creating a new application and migrating an existing application.

**Comment by tomtomau** [comment]
That sounds awesome! I know I would find interest in it

**Comment by xwipeoutx** [comment]
+1

Will this be typescript or vanilla JS?

**Comment by iamkevinv** [comment]
Sounds good - i'll queue this up.

**Comment by andrewling89** [comment]
Just to advise that I cannot do this talk until November as I'm on holidays this coming Monday.

**Comment by iamkevinv** [comment]
As discussed by email... we'll do this some other time. I'll issue a cancellation for your talk.

**Comment by iamkevinv** [comment]
@andrewling89 Next BrisJS is nov 2 :) which is soon. Please confirm you're all good to go with this so i can send out the email. Thanks :)

**Comment by iamkevinv** [comment]
Ping @andrewling89 - Yes? I need to announce it. Thanks.

**Comment by andrewling89** [comment]
Should be fine.

**Comment by iamkevinv** [comment]
Perfect. I'll add you as a confirmed speaker

**Comment by iamkevinv** [comment]
You'll probably have at least half an hour to 40 minutes on this topic - as you have the first speaker slot.

**Comment by andrewling89** [comment]
I'm expecting my talk to be around the 10 - 15 minute mark. I'm planning to
give an overview of my experiences with creating a basic Angular2
application and what's different compared to Angular1.

**Comment by iamkevinv** [comment]
Okay fair enough. lets solve this with https://github.com/BrisJS/meetups/issues/99 :-) I'll switch up the running order.

**Comment by iamkevinv** [comment]
It's now a shared 45 minute block to take us from 6:15ish to 7:00pm where we can eat pizza, @garrows and @andrewling89 :-)

**Comment by iamkevinv** [comment]
Any helpful resources you can share @andrewling89 ?

**Comment by iamkevinv** [comment]
Stale. Closing.
