### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by xwipeoutx** [BrisJS/meetups#94]
Anyone interested in Typescript? I'm happy to do a talk on it.

I saw https://github.com/BrisJS/meetups/issues/93, and since Angular 2 is being done in Typescript, people may want to know about it...

**Comment by iamkevinv** [comment]
Hey mate - happy to have you give us a demo, knowing that you're such a proponent of it's benefits :)
Okay for the next brisJS if the angular 2.0 one is there as well?

**Comment by xwipeoutx** [comment]
Depends on popularity - no point doing it if noone wants to hear it ;) But yes, That'll be fine.

**Comment by iamkevinv** [comment]
https://github.com/BrisJS/meetups/issues/91 is also on the bill, not sure if it's overkill to do both, or an opportunity to contrast them?

**Comment by xwipeoutx** [comment]
Good point. Let's hold off for now - perhaps November.

**Comment by iamkevinv** [comment]
Okay mate - still could do it, as i said - contrast and comparison could be cool, but i'll go by your lead! Lets see who else confirms also.

**Comment by iamkevinv** [comment]
Next BrisJS is nov 2 :) which is soon. Please confirm you're all good to go with this please so i can send out the email.

**Comment by iamkevinv** [comment]
Ping @xwipeoutx :)

**Comment by xwipeoutx** [comment]
Egads, sorry. I Wrote a reply and musn't have hit the comment button.  And you want me to present something.

Can do, all good, no worries.  If anyone has an idea for a little sample app they'd like to see (either node or browser), I can take that on board.  It'll probably end up being a Todo list in angular 1.4 or something otherwise ;)

**Comment by iamkevinv** [comment]
Sounds good, i'll add you as a speaker.

**Comment by iamkevinv** [comment]
You'll have quite a bit speaking slot, 30-45 mins easily.

**Comment by xwipeoutx** [comment]
Woo, that may or may not be useful ^_^. I'm ending with live-coding that... let's just say it isn't a finely polished stone.

**Comment by xwipeoutx** [comment]
Slides are here: https://slides.com/xwipeoutx/bris-ts/
GitHub repo here: https://github.com/xwipeoutx/BrisJS-TypeScript

**Comment by iamkevinv** [comment]
Thanks!
