### ISSUE TITLE
Lightweight Javascript framework for responsive web design

### ISSUE THREAD

**Issue by BlackMagic** [BrisJS/meetups#95]
I have developed a lightweight pure Javascript framework for implementing responsive web design.

The framework is less than 2k characters and consists of half a dozen small functions that interact with HTML and CSS to provide web page resizing at various pixel widths selected under user control. The framework eliminates a lot of the code bloat normally associated with responsive web design. It doesn't use JQuery or CSS3 media queries. The framework simulates media queries with event listeners.

You can see the framework working and inspect the source code at ieee-ac.org. WARNING: There is a bug in iOS9 that conflicts with the website hosting the framework. iOS8 is OK. Apple is aware of the problem and it will be resolved in the near future.

**Comment by iamkevinv** [comment]
Were you keen to get in the next meetup? First monday of Oct.

**Comment by BlackMagic** [comment]
Whenever you're ready. I might need to borrow a laptop from someone. Mine is an el cheapo that doesn't have a video port to attach to a projector.

**Comment by govpack** [comment]
@BlackMagic 
Magic Mike, this sounds excellent. drawing and scaling our own geometries IS something we need to do more of (ever since htm5 dropped the framestet etc) --xxo

**Comment by BlackMagic** [comment]
@govpack 
I lied about the size of the framework. It's less than 800 characters. However, in a working environment it usually expands to around 2k characters.

I'm working on a Github home for it, and an article in A List Apart.

**Comment by BlackMagic** [comment]
The iOS9 bug mentioned above has been reported to Apple. It appears that Apple has left flexbox support out of iOS9. Safari and Chrome 45 on iOS9 don't render flexbox sites properly. 

The framework doesn't use flexbox, but the code at ieee-ac.org uses flexbox to control layout. Thought I'd clear that up.

**Comment by iamkevinv** [comment]
If you know about the bug filed with Apple - i'd love to see the details on that!
Regardless - We can have you demo next meetup, and i can put your presentation resources on my laptop for you.

**Comment by BlackMagic** [comment]
Open ieee-ac.org <http://ieee-ac.org/> with an iOS9 device and you'll 
see that flexbox isn't working properly. I use flexbox a lot to simplify 
layout issues.

Flexbox demo sites 
<https://css-tricks.com/snippets/css/a-guide-to-flexbox/> screw up on 
iOS9 too.

**Comment by xwipeoutx** [comment]
We had issues with flexbox on our app, we had success on iOS9 with using `-webkit-box` and `-webkit-flex` prefixes in that order, with their associated `flex-direction`, `flex-align`. fallbacks as well.  Using LESS or SASS mixins makes this fairly easy.  Something like this (LESS)
```
.display(flex) 
{
     display: -webkit-box;
     display: -webkit-flex;
     display: -ms-flexbox;
}
.display(inline-flex) 
{
    display: -webkit-inline-box;
    display: -webkit-inline-flex;
    display: -ms-inline-flexbox; 
}
.display(@display) { display: @display; }
```

Means we can `.display(flex)` or `.display(inline-flex)` and have it work everywhere pretty reliably.

**Comment by BlackMagic** [comment]
Thanks Steve.

I'm using:
.box{flex:1 1 0%;margin:1% 0 1% 1%;box-shadow:0 0 10px 
#888888;padding:10px 10px;font-size:1em;}
and
.flex{display:flex;flex-direction:row;margin-left:.3cm;margin-right:.5cm;}

That works fine on iOS8 and OSx. I'll try using the prefixes to see if 
it fixes the iOS9 problem.

Can you help me test it please as I don't have an iPhone?

**Comment by xwipeoutx** [comment]
I don't have one either ^_^ Someone else figured this out at work, not me...

**Comment by BlackMagic** [comment]
I used the webkit prefixes but my friend who has an iPhone 6 tells me 
the problem is still there.

Now that I know what the problem is I'll keep trying to fix it.

I'm astonished that iOS8 doesn't have this problem but iOS9 does.
