### ISSUE TITLE
JAWS - The Monstrously Scalable Serverless Framework

### ISSUE THREAD

**Issue by jwulf** [BrisJS/meetups#96]
I'm a contributor to JAWS, a framework that scaffolds and deploys applications on AWS Lambda. 

I'd love to give a talk on it.

**Comment by garrows** [comment]
Yes! This!

**Comment by demsey2** [comment]
+1

**Comment by marklawlor** [comment]
+1 

I've been lurking in the JAWS gitter for a while now, didn't realise you were from Brisbane.  I'm trying to get time at work to prototype a new project.

**Comment by govpack** [comment]
![](http://www.rollonfriday.com/Images/JamieH/Images/060417-jaws2.jpg)

**Comment by iamkevinv** [comment]
Thanks for volunteering! Happy to have this presented - should be great.

**Comment by iamkevinv** [comment]
@jwulf - Can you replace Andrew Ling for the October 12th meetup?

**Comment by iamkevinv** [comment]
Ping @jwulf ?

**Comment by jwulf** [comment]
https://vimeo.com/141138561

**Comment by jwulf** [comment]
October 12, let me check my calendar....

**Comment by jwulf** [comment]
I'm a yes.

**Comment by iamkevinv** [comment]
Thanks again for the talk... if you could share some resources here (links) that would be great.

**Comment by fud** [comment]
Just thought i'd say that I noticed that jaws has been renamed, it's now called 'serverless'. https://github.com/serverless/serverless

**Comment by iamkevinv** [comment]
Yeah that's pretty interesting for them to do - you'd think the marketing of Jaws is awesome.

**Comment by marklawlor** [comment]
@iamkevinv @fud The scope of the project changed, hence the name. JAWS is just about getting lambda/API-gateway working together. Serverless is aiming to solve other issues (eg front-end applications) with a similar philosophy/workflow (no backend dev-ops, multiple stages, quick versioned deployments).  A lot of people were trying to use JAWS to deploy angular applications...

Also they wanted to remove 'AWS' from the name, as other cloud providers may start offering similar architecture.

**Comment by iamkevinv** [comment]
If we have more resources from @jwulf please add them - otherwise it's tagged and closed
