### ISSUE TITLE
An Adaptive Design approach to create cross-platform Universal apps with Sencha Ext JS 6

### ISSUE THREAD

**Issue by shikhirsingh** [BrisJS/meetups#98]
‎Responsive Design is great for creating websites. To create apps, the best approach is to use Adaptive Design techniques which creates the best user experience for users. During this session, we will explore how to create apps using an Adaptive Design approach using Ext JS. Ext JS is an HTML5 framework which can be used to create cross-platform web and hybrid apps.

December 1st week slot is available for myself

**Comment by iamkevinv** [comment]
Thanks for coming up and volunteering :) I've added you as a candidate talk for Dec.

**Comment by iamkevinv** [comment]
Hi @shikhirsingh - looking forward to having you present next monday. Still confirmed i take it?

**Comment by shikhirsingh** [comment]
My apologies, I will not make it. I didn't realize that being marked candidate means it's confirmed. I need at least 30 days confirmed to attend a talk internationally.

**Comment by iamkevinv** [comment]
Oh. That's disappointing news. I guess i didn't explicitly say it was confirmed back in Oct, but it was definitely. We don't have a complex selection criteria, we welcome all presenters who volunteer.
Usually the Candidate label just means they need to be slotted in the next meetup or we're waiting for them to confirm closer to the date that they will attend. 
Dec is the last meetup for 2015. Feb 2016 is the next one.

**Comment by iamkevinv** [comment]
Ping - if you're happy for it, you'd be confirmed for the Feb meetup. I wont be there as i'll be on holidays but the venerable @AshKyd will be a replacement fearless leader :)

**Comment by shikhirsingh** [comment]
Can we do in March? I'll be Australia then

On Wednesday, January 6, 2016, Kevin Vanderbeken <notifications@github.com>
wrote:

> Ping - if you're happy for it, you'd be confirmed for the Feb meetup. I
> wont be there as i'll be on holidays but the venerable @AshKyd
> <https://github.com/AshKyd> will be a replacement fearless leader :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/98#issuecomment-169531586>.
>


--

**Comment by AshKyd** [comment]
No problems, sounds great. Can we confirm you for March 7th? :)

**Comment by shikhirsingh** [comment]
The day works for me, but I want to see if my colleague will attend as
well. Give me a day to confirm.

On Thursday, January 14, 2016, Ash Kyd <notifications@github.com> wrote:

> No problems, sounds great. Can we confirm you for March 7th? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrisJS/meetups/issues/98#issuecomment-171852775>.
>


--

**Comment by shikhirsingh** [comment]
Is it possible to move it to the Thursday or Friday the week earlier (March
3rd or March 4th). This will make it possible for my colleague to attend
too.

Also, what is the period of time expectations for the talk?

On Thursday, January 14, 2016, Shikhir Singh <shikhir@gmail.com> wrote:

> The day works for me, but I want to see if my colleague will attend as
> well. Give me a day to confirm.
>
> On Thursday, January 14, 2016, Ash Kyd <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> No problems, sounds great. Can we confirm you for March 7th? :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BrisJS/meetups/issues/98#issuecomment-171852775>.
>>
>
>
> --
>
>

--

**Comment by iamkevinv** [comment]
Unless there’s a public holiday meaning we need to move the date back, we don’t customise the day of the event. We stick to the first available Monday of each calendar month for consistency for our members, in this case - 7th if you're targeting March.

Talk time averages around 20 minutes normally, but we are happy to accomodate longer talks and do so regularly, up to about 45 minutes. Those talks are usually first of the night, and we break for Pizza after.

**Comment by shikhirsingh** [comment]
That's fine. I can go 45 mins.

On Sun, Jan 17, 2016 at 8:25 PM, Kevin Vanderbeken <notifications@github.com

**Comment by shikhirsingh** [comment]
Just writing to confirm before I book my flight to Brisbane, that this
event has been scheduled and I'm speak for the 45 min time slot. Can you
please re-validate?

**Comment by AshKyd** [comment]
Yup, that's correct.

* Date: March 7
* Timeslot: 45 min

Are there any other details you need? Otherwise, that sounds great. See you there!

**Comment by AshKyd** [comment]
@shikhirsingh Thanks a bunch for coming, really enjoyed your talk. Have to say, the adaptive approach is definitely the way to go for mobile apps.

Do you have any slides resources you would like to share for this one?
